"""
Mesh analysis: topology (manifoldness, orientation, boundary, components, genus), quality statistics, QEM decimation, discrete curvatures, and geodesic distances.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.spatial.bvh import Bvh
from numeria.graph.core import Graph

class MeshStats:
    """
Summary statistics of a mesh.

Rust: `mesh::analyze::MeshStats`
    """
    def __init__(self, vertices: int, edges: int, faces: int, euler: int, genus: Optional[int], boundary_loops: int, is_manifold: bool, is_closed: bool, is_oriented: bool, min_angle_deg: float, max_angle_deg: float, min_edge: float, max_edge: float) -> None: ...
    @property
    def vertices(self) -> int: ...
    @property
    def edges(self) -> int: ...
    @property
    def faces(self) -> int: ...
    @property
    def euler(self) -> int: ...
    @property
    def genus(self) -> Optional[int]: ...
    @property
    def boundary_loops(self) -> int: ...
    @property
    def is_manifold(self) -> bool: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def is_oriented(self) -> bool: ...
    @property
    def min_angle_deg(self) -> float: ...
    @property
    def max_angle_deg(self) -> float: ...
    @property
    def min_edge(self) -> float: ...
    @property
    def max_edge(self) -> float: ...

def stats(m: Mesh) -> MeshStats:
    """
Computes all `MeshStats` in one pass over the mesh.

Rust: `mesh::analyze::stats`
    """
    ...

def euler_characteristic(m: Mesh) -> int:
    """
Euler characteristic χ = V − E + F.

Rust: `mesh::analyze::euler_characteristic`
    """
    ...

def is_manifold(m: Mesh) -> bool:
    """
True when every edge belongs to one or two faces and the faces
around every vertex form a single fan (connected through shared
edges at that vertex).

Rust: `mesh::analyze::is_manifold`
    """
    ...

def is_closed(m: Mesh) -> bool:
    """
True when every edge belongs to exactly two faces.

Rust: `mesh::analyze::is_closed`
    """
    ...

def is_consistently_oriented(m: Mesh) -> bool:
    """
True when every shared edge is traversed once in each direction
(faces agree on winding).

Rust: `mesh::analyze::is_consistently_oriented`
    """
    ...

def fix_orientation(m: Mesh) -> bool:
    """
Makes the orientation consistent per connected component by BFS
flipping. Returns false (leaving a best-effort result) when the
mesh is non-orientable (e.g. a Möbius band) or an edge has more
than two faces. A closed, consistently oriented component with
negative volume is flipped outward.

Rust: `mesh::analyze::fix_orientation`
    """
    ...

def boundary_loops(m: Mesh) -> list[list[int]]:
    """
Boundary loops as ordered vertex index cycles (each loop closed
implicitly; first vertex not repeated).

Rust: `mesh::analyze::boundary_loops`
    """
    ...

def connected_components(m: Mesh) -> list[Mesh]:
    """
Splits into connected components (each with its own compacted
vertex list), ordered by smallest original vertex index.

Rust: `mesh::analyze::connected_components`
    """
    ...

def non_manifold_edges(m: Mesh) -> list[tuple[int, int]]:
    """
Edges belonging to more than two faces.

Rust: `mesh::analyze::non_manifold_edges`
    """
    ...

def duplicate_faces(m: Mesh) -> list[tuple[int, int]]:
    """
Pairs of faces with identical vertex sets (regardless of winding),
each pair reported once as `(earlier, later)`.

Rust: `mesh::analyze::duplicate_faces`
    """
    ...

def self_intersections(m: Mesh, bvh: Optional[Bvh] = None) -> list[tuple[int, int]]:
    """
Face pairs that intersect without sharing a vertex index. Pass the
mesh's BVH (`Mesh::build_bvh`) to prune candidate pairs.

Rust: `mesh::analyze::self_intersections`
    """
    ...

def decimate_edge_collapse(m: Mesh, target_faces: int) -> Mesh:
    """
Garland-Heckbert quadric error metric decimation ("Surface
Simplification Using Quadric Error Metrics", SIGGRAPH 1997):
greedily collapses the cheapest edge whose collapse keeps the mesh
manifold (link condition) and does not flip surviving faces, until
at most `target_faces` faces remain or no valid collapse exists.

Rust: `mesh::analyze::decimate_edge_collapse`
    """
    ...

def vertex_valence(m: Mesh) -> list[int]:
    """
Number of distinct neighbors of each vertex.

Rust: `mesh::analyze::vertex_valence`
    """
    ...

def dihedral_angles(m: Mesh) -> list[float]:
    """
Angle between the normals of the two faces at each interior edge
(0 for coplanar faces), aligned with `Mesh::edges` order;
boundary and non-manifold edges get 0.

Rust: `mesh::analyze::dihedral_angles`
    """
    ...

def sharp_edges(m: Mesh, angle_threshold_rad: float) -> list[tuple[int, int]]:
    """
Interior edges whose faces' normals differ by more than the
threshold angle (radians).

Rust: `mesh::analyze::sharp_edges`
    """
    ...

def discrete_gaussian_curvature(m: Mesh) -> list[float]:
    """
Integrated Gaussian curvature per vertex as the angle deficit:
2π − Σ incident angles (π − Σ on the boundary). Summing over a
closed mesh gives exactly 2πχ (discrete Gauss-Bonnet).

Rust: `mesh::analyze::discrete_gaussian_curvature`
    """
    ...

def discrete_mean_curvature(m: Mesh) -> list[float]:
    """
Discrete (unsigned) mean curvature per vertex via the cotangent
Laplacian: H = |Σ (cot α + cot β)(vᵢ − vⱼ)| / (4 A) with A the
mixed Voronoi vertex area (Meyer et al. 2003). Zero on boundary
vertices.

Rust: `mesh::analyze::discrete_mean_curvature`
    """
    ...

def geodesic_distance_dijkstra(m: Mesh, source: int) -> list[float]:
    """
Graph-shortest-path distance along mesh edges from `source` to
every vertex (an upper bound on true geodesic distance).

Panics:
Panics when `source` is out of range.

Rust: `mesh::analyze::geodesic_distance_dijkstra`
    """
    ...

def geodesic_distance_fast_marching(m: Mesh, source: int) -> list[float]:
    """
First-order fast marching on the triangle mesh (Kimmel & Sethian
1998): distances propagate as planar wavefronts across triangles,
converging to the true geodesic distance under refinement (unlike
edge-graph Dijkstra).

Panics:
Panics when `source` is out of range.

Rust: `mesh::analyze::geodesic_distance_fast_marching`
    """
    ...

def geodesic_path(m: Mesh, from_: int, to: int) -> list[int]:
    """
Shortest edge path between two vertices (inclusive); empty when
unreachable.

Panics:
Panics when either endpoint is out of range.

Rust: `mesh::analyze::geodesic_path`
    """
    ...
