"""
Procedural mesh generators. Closed shapes are watertight (shared seam vertices, no duplicates) with outward-facing counterclockwise winding.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.spatial.primitives import Capsule
from numeria.spatial.primitives import Cylinder
from numeria.spatial.primitives import Polygon2
from numeria.spatial.primitives import Polyline
from numeria.math import Vec2
from numeria.math import Vec3

def uv_sphere(radius: float, segments: int, rings: int) -> Mesh:
    """
Latitude/longitude sphere: `rings` latitude bands, `segments`
meridians, poles as single vertices. Closed manifold (Euler
characteristic 2).

Panics:
Panics unless `radius > 0`, `segments >= 3`, and `rings >= 2`.

Rust: `mesh::generate::uv_sphere`
    """
    ...

def icosphere(radius: float, subdivisions: int) -> Mesh:
    """
Geodesic sphere: an icosahedron subdivided `subdivisions` times,
vertices projected to the sphere. Closed manifold.

Panics:
Panics unless `radius > 0`.

Rust: `mesh::generate::icosphere`
    """
    ...

def box_mesh(half: Vec3 | Sequence[float]) -> Mesh:
    """
Axis-aligned box with the given half extents: 8 shared vertices, 12
triangles. Closed manifold.

Panics:
Panics unless every half extent is positive.

Rust: `mesh::generate::box_mesh`
    """
    ...

def cylinder(radius: float, height: float, segments: int, capped: bool) -> Mesh:
    """
Cylinder along the y axis, centered at the origin, spanning
`[-height/2, height/2]`. With `capped`, both ends are closed by
fans sharing the rim vertices (closed manifold).

Panics:
Panics unless `radius > 0`, `height > 0`, `segments >= 3`.

Rust: `mesh::generate::cylinder`
    """
    ...

def cone(radius: float, height: float, segments: int) -> Mesh:
    """
Cone with its base disk in the y = 0 plane (centered at the origin)
and apex at `(0, height, 0)`. Closed manifold.

Panics:
Panics unless `radius > 0`, `height > 0`, `segments >= 3`.

Rust: `mesh::generate::cone`
    """
    ...

def torus(major: float, minor: float, major_segs: int, minor_segs: int) -> Mesh:
    """
Torus around the y axis: tube of radius `minor` swept along a
circle of radius `major` in the xz plane. Closed manifold (Euler
characteristic 0).

Panics:
Panics unless `0 < minor < major` and both segment counts are >= 3.

Rust: `mesh::generate::torus`
    """
    ...

def plane_grid(width: float, depth: float, nx: int, nz: int) -> Mesh:
    """
Flat grid in the xz plane centered at the origin, normals facing
+y, `nx` by `nz` cells. Open (has a boundary).

Panics:
Panics unless `width > 0`, `depth > 0`, `nx >= 1`, `nz >= 1`.

Rust: `mesh::generate::plane_grid`
    """
    ...

def capsule(radius: float, height: float, segments: int, rings: int) -> Mesh:
    """
Capsule along the y axis: a cylinder of length `height` between two
hemispherical caps of the given radius (`rings` latitude bands per
hemisphere). Closed manifold.

Panics:
Panics unless `radius > 0`, `height >= 0`, `segments >= 3`,
`rings >= 1`.

Rust: `mesh::generate::capsule`
    """
    ...

def disk(radius: float, segments: int) -> Mesh:
    """
Flat disk in the y = 0 plane centered at the origin, normal +y.
Open (has a boundary).

Panics:
Panics unless `radius > 0` and `segments >= 3`.

Rust: `mesh::generate::disk`
    """
    ...

def tube_along_polyline(path: Polyline, radius: float, segments: int) -> Mesh:
    """
Tube of the given radius swept along a polyline using parallel
transport frames (rotation-minimizing, so the tube does not twist).
A closed path joins the last ring back to the first; an open path
leaves the ends uncapped.

Panics:
Panics unless `radius > 0`, `segments >= 3`, and the path has at
least two points with nonzero consecutive tangents.

Rust: `mesh::generate::tube_along_polyline`
    """
    ...

def extrude_polygon(poly: Polygon2, height: float) -> Mesh:
    """
Extrudes a simple polygon (in the xy plane) along +z from z = 0 to
z = `height`, with ear-clipped caps. Closed manifold for a simple
polygon. Clockwise input is treated as its counterclockwise
reversal.

Panics:
Panics unless the polygon has at least 3 vertices and
`height > 0`.

Rust: `mesh::generate::extrude_polygon`
    """
    ...

def revolve_profile(profile: list[Vec2 | Sequence[float]], segments: int) -> Mesh:
    """
Revolves a profile polyline around the y axis. Each profile point
`(x, y)` gives radius `x` at height `y`; points with `x == 0`
become poles. The profile should ascend in y for outward normals;
a profile that starts and ends on the axis yields a closed
manifold.

Panics:
Panics unless the profile has >= 2 points, `segments >= 3`, and no
profile radius is negative.

Rust: `mesh::generate::revolve_profile`
    """
    ...

def heightfield(heights: list[float], nx: int, nz: int, dx: float, dz: float) -> Mesh:
    """
Height field surface: vertex `(i, j)` sits at
`(i * dx, heights[j * nx + i], j * dz)`, triangles facing +y for
positive `dx`, `dz`. Open.

Panics:
Panics unless `nx >= 2`, `nz >= 2`,
`heights.len() == nx * nz`, and `dx, dz > 0`.

Rust: `mesh::generate::heightfield`
    """
    ...

def from_parametric(f: Callable[[float, float], Vec3 | Sequence[float]], u_range: tuple[float, float], v_range: tuple[float, float], nu: int, nv: int, close_u: bool, close_v: bool) -> Mesh:
    """
Samples a parametric surface on an `nu` by `nv` cell grid.
`close_u`/`close_v` wrap the respective direction (the last row of
samples is omitted and faces reference the first, so periodic
surfaces come out watertight). Triangles are wound so normals
follow `∂f/∂u × ∂f/∂v`.

Panics:
Panics unless `nu >= 1`, `nv >= 1` (>= 3 for a closed direction)
and each range is nonempty.

Rust: `mesh::generate::from_parametric`
    """
    ...
