"""
Mesh parameterization: closed-form spherical/planar/cylindrical projections, harmonic (cotangent-Laplace) disk parameterization with fixed boundaries, least-squares conformal maps (Lévy, Petitjean, Ray & Maillot 2002), and per-triangle conformal and area distortion measures.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.math import Vec2
from numeria.math import Vec3

class BoundaryShape:
    """
Target shape for the fixed boundary of a harmonic
parameterization.

Rust: `mesh::parameterize::BoundaryShape`
    """
    ...

def spherical_uv(m: Mesh) -> None:
    """
Spherical texture coordinates for a (genus-0) mesh: each vertex
direction from the centroid maps to
u = ½ + atan2(d_y, d_x)/2π, v = acos(d_z)/π. Writes `m.uvs`.

Panics:
Panics on an empty mesh.

Rust: `mesh::parameterize::spherical_uv`
    """
    ...

def planar_uv(m: Mesh, normal: Vec3 | Sequence[float]) -> None:
    """
Planar projection along `normal`, normalized so the projected
bounding box spans [0, 1]². Writes `m.uvs`.

Panics:
Panics on an empty mesh or a zero normal.

Rust: `mesh::parameterize::planar_uv`
    """
    ...

def cylindrical_uv(m: Mesh, axis: Vec3 | Sequence[float]) -> None:
    """
Cylindrical projection about `axis` through the centroid:
u = angle/2π around the axis, v = normalized height along it.
Writes `m.uvs`.

Panics:
Panics on an empty mesh or a zero axis.

Rust: `mesh::parameterize::cylindrical_uv`
    """
    ...

def harmonic_parameterization(m: Mesh, boundary_shape: BoundaryShape) -> list[Vec2]:
    """
Harmonic (cotangent-weight) parameterization of a disk-topology
mesh: the boundary loop is pinned to the target shape and the
interior solves the discrete Laplace equation, giving the unique
harmonic extension (identity up to similarity on flat meshes;
convexity of the target keeps the map injective for meshes with
non-negative weights). Returns one UV per vertex.

Panics:
Panics unless the mesh has disk topology and the linear solve
converges.

Rust: `mesh::parameterize::harmonic_parameterization`
    """
    ...

def lscm(m: Mesh, pinned: list[tuple[int, Vec2 | Sequence[float]]]) -> list[Vec2]:
    """
Least-squares conformal map: minimizes the conformal energy
Σ_T A_T |∇u rotated 90° − ∇v|² with two pinned vertices removing
the similarity ambiguity. Solved through the normal equations by
conjugate gradients. Returns one UV per vertex.

Panics:
Panics unless the two pins are distinct valid vertices and the
solve converges.

Rust: `mesh::parameterize::lscm`
    """
    ...

def conformal_distortion(m: Mesh, uv: list[Vec2 | Sequence[float]]) -> list[float]:
    """
Per-triangle conformal distortion σ₁/σ₂ of the parameterization
(1 = angle-preserving; degenerate triangles report 1).

Panics:
Panics unless `uv` has one entry per vertex.

Rust: `mesh::parameterize::conformal_distortion`
    """
    ...

def area_distortion(m: Mesh, uv: list[Vec2 | Sequence[float]]) -> list[float]:
    """
Per-triangle area distortion: the UV/3-D area ratio normalized by
the global ratio, so a globally scaled isometry reports 1
everywhere.

Panics:
Panics unless `uv` has one entry per vertex.

Rust: `mesh::parameterize::area_distortion`
    """
    ...
