"""
Hypothesis tests and confidence intervals.  p-values come from the crate's own distribution CDFs (Student t, chi-squared, F) and the asymptotic Kolmogorov distribution Q_KS(λ) = 2·Σ (−1)^{j−1} e^{−2j²λ²} (NR §14.3). All t-type tests report two-sided p-values.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.linalg.matrix import Matrix

class TestResult:
    """
Outcome of a hypothesis test. For tests with two df parameters
(ANOVA, independence tables) `df` is the numerator / primary df;
the p-value always accounts for the full parameterization.

Rust: `statistics::inference::TestResult`
    """
    def __init__(self, statistic: float, p_value: float, df: float) -> None: ...
    @property
    def statistic(self) -> float: ...
    @property
    def p_value(self) -> float: ...
    @property
    def df(self) -> float: ...

def t_test_one_sample(x: list[float], mu0: float) -> TestResult:
    """
One-sample t test of H₀: μ = mu0.

R cross-check: `t.test(c(1,2,3,4,5), mu=2)` gives
t = 1.4142, df = 4, p-value = 0.2302.

Panics:
Panics unless x has at least 2 elements.

Rust: `statistics::inference::t_test_one_sample`
    """
    ...

def t_test_two_sample(x: list[float], y: list[float], equal_var: bool) -> TestResult:
    """
Two-sample t test of H₀: μₓ = μᵧ. `equal_var` selects the pooled
test; otherwise Welch's test with Welch-Satterthwaite df.

Analytic cross-check: x = 1..5 vs y = 2,4,…,10 with equal variances
gives t = −3/√2.5 = −1.897367 on 8 df (p ≈ 0.094); Welch df is
exactly 6.25/1.0625 = 5.882353.

Panics:
Panics unless both samples have at least 2 elements.

Rust: `statistics::inference::t_test_two_sample`
    """
    ...

def t_test_paired(x: list[float], y: list[float]) -> TestResult:
    """
Paired t test: one-sample test on the pairwise differences.

Panics:
Panics unless the samples are the same length with n ≥ 2.

Rust: `statistics::inference::t_test_paired`
    """
    ...

def chi_squared_gof(observed: list[float], expected: list[float]) -> TestResult:
    """
Chi-squared goodness-of-fit test: Σ (O − E)²/E with k − 1 df.

R cross-check: `chisq.test(c(10,20,30,40), p=rep(0.25,4))` gives
X-squared = 20, df = 3, p-value = 0.0001697.

Panics:
Panics unless the slices match in length (≥ 2) and all expected
counts are positive.

Rust: `statistics::inference::chi_squared_gof`
    """
    ...

def chi_squared_independence(table: Matrix | Sequence[Sequence[float]]) -> TestResult:
    """
Chi-squared test of independence on an r×c contingency table;
expected counts from the margins, (r−1)(c−1) df (reported as `df`).

Panics:
Panics unless the table is at least 2×2 with non-negative entries
and positive margins.

Rust: `statistics::inference::chi_squared_independence`
    """
    ...

def ks_test_one_sample(x: list[float], cdf: Callable[[float], float]) -> TestResult:
    """
One-sample Kolmogorov-Smirnov test of x against a continuous CDF.
`statistic` is Dₙ; `df` reports the sample size; p uses the NR
asymptotic correction λ = (√n + 0.12 + 0.11/√n)·D.

Panics:
Panics if x is empty.

Rust: `statistics::inference::ks_test_one_sample`
    """
    ...

def ks_test_two_sample(x: list[float], y: list[float]) -> TestResult:
    """
Two-sample Kolmogorov-Smirnov test. `df` reports the effective
sample size n₁n₂/(n₁+n₂).

Panics:
Panics if either sample is empty.

Rust: `statistics::inference::ks_test_two_sample`
    """
    ...

def anova_one_way(groups: list[list[float]]) -> TestResult:
    """
One-way ANOVA. `statistic` is F; `df` reports the between-groups
(numerator) df k − 1; the p-value uses F(k − 1, N − k).

Analytic cross-check: groups (1,2,3), (2,3,4), (5,6,7) give
SS_between = 26, SS_within = 6, F = 13 on (2, 6) df.

Panics:
Panics unless there are ≥ 2 groups, each non-empty, with more total
observations than groups.

Rust: `statistics::inference::anova_one_way`
    """
    ...

def confidence_interval_mean(x: list[float], level: float) -> tuple[float, float]:
    """
Two-sided confidence interval for the mean at the given level
(e.g. 0.95): x̄ ± t·s/√n.

Panics:
Panics unless n ≥ 2 and level ∈ (0, 1).

Rust: `statistics::inference::confidence_interval_mean`
    """
    ...

def pearson_test(x: list[float], y: list[float]) -> TestResult:
    """
Test of H₀: ρ = 0 from the Pearson correlation:
t = r·√((n−2)/(1−r²)) with n − 2 df.

R cross-check: `cor.test(c(1,2,3,4,5), c(2,1,4,3,5))` gives
r = 0.8, t = 2.3094, df = 3, p-value = 0.1041.

Panics:
Panics unless both slices have equal length n ≥ 3.

Rust: `statistics::inference::pearson_test`
    """
    ...
