"""
Clustering, mixture models and nearest neighbours.  # Clustering has no ground truth, so the tests need invariants  Nothing here has a right answer to compare against. What it has instead is a supply of exact statements, and those are what the tests use:  *Lloyd's algorithm cannot go uphill.* Each half of a k-means iteration -- reassigning points to their nearest centre, then moving each centre to its cluster's mean -- minimises the same objective over one of its two arguments, so the inertia is non-increasing and the algorithm terminates in finitely many steps. There are finitely many assignments and none repeats.  *Expectation-maximisation cannot go downhill.* The same argument in the other direction: each step maximises a lower bound that touches the log-likelihood at the current parameters, so the likelihood climbs monotonically. Both are asserted step by step rather than end to end, because a monotone sequence is a much sharper claim than an improved endpoint.  *A label is not a name.* Cluster indices are arbitrary, so every comparison between two clusterings has to be invariant under relabelling either of them. `adjusted_rand_index` is, exactly, and it is corrected for chance so that two independent random partitions score about zero rather than about a half.  # Where the guarantees stop, and why that is worth saying  Single and complete linkage produce merge heights that never decrease, so their dendrograms can be drawn without crossings. *Centroid linkage does not.* Merging two clusters moves their centre to somewhere between them, which can be closer to a third cluster than either original was, and the dendrogram then contains an inversion. That is a property of the method, not a bug in it, and `Linkage::Centroid` is documented and tested as inverting rather than quietly producing dendrograms nobody should draw.  DBSCAN's core points are determined by the data alone and do not depend on the order it arrives in. Its *border* points can: a point within reach of two clusters joins whichever claimed it first. That asymmetry is in the algorithm as Ester and colleagues defined it, and pretending otherwise would mean inventing a tie-break and calling it DBSCAN.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.linalg.matrix import Matrix
from rust_physics_engine.monte_carlo import Rng

class Gmm:
    """
A fitted Gaussian mixture.

Rust: `learn::cluster::Gmm`
    """
    def __init__(self, weights: list[float], means: list[list[float]], covariances: list[Matrix | Sequence[Sequence[float]]], log_likelihood_history: list[float]) -> None: ...
    def log_likelihood(self) -> float: ...
    @property
    def weights(self) -> list[float]: ...
    @property
    def means(self) -> list[list[float]]: ...
    @property
    def covariances(self) -> list[Matrix]: ...
    @property
    def log_likelihood_history(self) -> list[float]: ...

class KMeans:
    """
The outcome of a k-means run.

Rust: `learn::cluster::KMeans`
    """
    def __init__(self, centroids: list[list[float]], labels: list[int], inertia_history: list[float], iterations: int) -> None: ...
    def inertia(self) -> float: ...
    @property
    def centroids(self) -> list[list[float]]: ...
    @property
    def labels(self) -> list[int]: ...
    @property
    def inertia_history(self) -> list[float]: ...
    @property
    def iterations(self) -> int: ...

class Linkage:
    """
How the distance between two merged clusters is defined.

Rust: `learn::cluster::Linkage`
    """
    ...

def kmeans_pp_init(data: list[list[float]], k: int, rng: Rng) -> list[list[float]]:
    """
Chooses `k` starting centres by the k-means++ rule: the first
uniformly at random, each subsequent one with probability
proportional to its squared distance from the nearest centre already
chosen.

The rule matters. Uniform initialisation regularly puts two centres
in the same dense region and leaves another region unclaimed, and
Lloyd's algorithm cannot repair that -- it is a local method and the
bad split is a local optimum. The `D^2` weighting makes the expected
final inertia within a logarithmic factor of the best possible,
which is the only approximation guarantee k-means has.

Errors:

`SolveError::InvalidArgument` for an invalid dataset, `k == 0`, or
more centres than points.

Rust: `learn::cluster::kmeans_pp_init`
    """
    ...

def kmeans(data: list[list[float]], k: int, iters: int, rng: Rng) -> KMeans:
    """
Lloyd's algorithm, restarted `RESTARTS` (10) times from independent
k-means++ starts, keeping the run with the lowest inertia.

The result carries the winning run's inertia history, which is
non-increasing within that run -- see the module note. Use
`kmeans_once` to observe a single trajectory.

Errors:

`SolveError::InvalidArgument` for an invalid dataset, `k == 0`,
more clusters than points, or zero iterations.

Rust: `learn::cluster::kmeans`
    """
    ...

def kmeans_once(data: list[list[float]], k: int, iters: int, rng: Rng) -> KMeans:
    """
A single run of Lloyd's algorithm from one k-means++ start.

Runs until the assignment stops changing or `iters` iterations have
passed. The inertia after each iteration is recorded, and it is
non-increasing by construction.

An empty cluster is refilled with the point currently furthest from
its own centre. Leaving it empty would silently return fewer clusters
than were asked for, and the mean of no points is not a number.

Errors:

As `kmeans`.

Rust: `learn::cluster::kmeans_once`
    """
    ...

def elbow_data(data: list[list[float]], k_range: list[int], iters: int, rng: Rng) -> list[tuple[int, float]]:
    """
The final inertia for each cluster count in `k_range`, for plotting
an elbow.

Inertia falls monotonically with `k` in expectation and reaches zero
when every point is its own cluster, so the number alone says
nothing -- the elbow is where the fall stops being worth the extra
cluster, and that is a judgement rather than a computation. The
function returns the curve and declines to pick a point on it.

Errors:

As `kmeans`, or `SolveError::InvalidArgument` for an empty range.

Rust: `learn::cluster::elbow_data`
    """
    ...

def dbscan(data: list[list[float]], eps: float, min_pts: int) -> list[int]:
    """
Density-based clustering. Returns a label per point, with `-1` for
noise.

A point is a *core* point if at least `min_pts` points (itself
included) lie within `eps`. Clusters are the connected components of
the core points, plus the non-core points within `eps` of one.

Core points are determined by the data alone. Border points are not:
one within reach of two clusters joins whichever reaches it first,
which depends on the order the points arrive in. That is in the
algorithm as defined, not an artefact here -- see the module note.

Errors:

`SolveError::InvalidArgument` for an invalid dataset, a
non-positive `eps`, or `min_pts == 0`.

Rust: `learn::cluster::dbscan`
    """
    ...

def hierarchical_agglomerative(data: list[list[float]], linkage: Linkage) -> list[tuple[int, int, float]]:
    """
Agglomerative clustering, returning the merges in order as
`(left, right, height)`.

Cluster indices below `n` are the original points; the merge at step
`t` creates cluster `n + t`. Heights are Euclidean distances under
the chosen linkage.

Errors:

`SolveError::InvalidArgument` for an invalid dataset or fewer than
two points.

Rust: `learn::cluster::hierarchical_agglomerative`
    """
    ...

def dendrogram_cut(merges: list[tuple[int, int, float]], n: int, k: int) -> list[int]:
    """
Cuts a dendrogram into `k` clusters, returning a label per original
point.

Errors:

`SolveError::InvalidArgument` if `k` is zero or exceeds the point
count, or if the merge list is not `n - 1` long.

Rust: `learn::cluster::dendrogram_cut`
    """
    ...

def gaussian_mixture_em(data: list[list[float]], k: int, iters: int, rng: Rng) -> Gmm:
    """
Fits a Gaussian mixture by expectation-maximisation.

Each step increases the log-likelihood, which is recorded so that the
monotonicity can be checked rather than assumed.

Errors:

`SolveError::InvalidArgument` for an invalid dataset, `k == 0`,
more components than points, or zero iterations;
`SolveError::NotPositiveDefinite` if a covariance cannot be
factored even with the floor applied.

Rust: `learn::cluster::gaussian_mixture_em`
    """
    ...

def silhouette_score(data: list[list[float]], labels: list[int]) -> float:
    """
The mean silhouette over all points, in `[-1, 1]`.

A point's silhouette compares the mean distance to its own cluster
against the mean distance to the nearest other cluster. One means
the clusters are tight and far apart; zero means the point sits on a
boundary; negative means it is closer to another cluster than its
own. A point alone in its cluster scores zero by convention -- there
is no within-cluster distance to compute, and calling it a perfect
one would reward splitting every point off.

Errors:

`SolveError::InvalidArgument` for an invalid dataset or fewer than
two distinct labels; `SolveError::DimensionMismatch` on a length
mismatch.

Rust: `learn::cluster::silhouette_score`
    """
    ...

def adjusted_rand_index(a: list[int], b: list[int]) -> float:
    """
The adjusted Rand index between two partitions.

Counts the pairs of points the two partitions agree about, then
subtracts what agreement would be expected by chance from partitions
with the same cluster sizes. Identical partitions score exactly one;
independent random ones score about zero, and may score below it.

The correction is what makes the number usable. The unadjusted Rand
index of two random partitions of many points into a few clusters is
close to one, because most pairs are in different clusters under both
and that counts as agreement.

Invariant under relabelling either partition, which is the minimum a
comparison between clusterings has to satisfy: a cluster index is not
a name.

Errors:

`SolveError::DimensionMismatch` if the two have different lengths;
`SolveError::InvalidArgument` if they are empty.

Rust: `learn::cluster::adjusted_rand_index`
    """
    ...

def davies_bouldin(data: list[list[float]], labels: list[int]) -> float:
    """
The Davies-Bouldin index: the mean over clusters of the worst ratio
of within-cluster spread to between-cluster separation.

Lower is better, and zero is unattainable. Unlike the silhouette it
is unbounded above, and unlike the silhouette it uses only the
centroids, so it is cheap and it is blind to cluster shape.

Errors:

As `silhouette_score`.

Rust: `learn::cluster::davies_bouldin`
    """
    ...

def knn_classify(train: list[list[float]], labels: list[int], x: list[float], k: int) -> int:
    """
Classifies `x` by a majority vote of its `k` nearest neighbours.

Ties are broken towards the smaller label, which is arbitrary but
deterministic; an even `k` on a two-class problem can produce them,
which is the usual reason to prefer an odd one.

Errors:

`SolveError::InvalidArgument` for an invalid or empty training set,
`k == 0`, or more neighbours than points;
`SolveError::DimensionMismatch` on a label count or query
dimension mismatch.

Rust: `learn::cluster::knn_classify`
    """
    ...

def knn_regress(train: list[list[float]], targets: list[float], x: list[float], k: int) -> float:
    """
Predicts a value for `x` as the mean of its `k` nearest neighbours'
targets.

Errors:

As `knn_classify`.

Rust: `learn::cluster::knn_regress`
    """
    ...
