"""
Feed-forward networks, trained by backpropagation.  # Backpropagation is the chain rule with the products reassociated  The derivative of the loss with respect to an early weight is a product of Jacobians, one per layer. Multiplying them left to right costs a matrix-matrix product per layer; multiplying right to left, starting from the scalar loss, costs a matrix-*vector* product per layer. Backpropagation is the second association, and that is the whole of it. It is not an approximation and it is not specific to neural networks -- it is reverse-mode differentiation, and the cost of one gradient is a small multiple of the cost of one forward pass however many parameters there are.  Which is why `Mlp::numerical_grad_check` is the test that matters. Descent will reduce a loss using wrong gradients, just more slowly and towards somewhere else, so a falling training curve is no evidence at all. A central difference agreeing with the analytic gradient to eight digits is.  # Softmax and cross-entropy belong together  Taken separately, softmax has a Jacobian and cross-entropy has a gradient, and composing them involves a matrix. Taken together the product collapses: the gradient of cross-entropy with respect to the *logits* is exactly `p - y`, the predicted distribution minus the target. That cancellation is worth having for accuracy as well as speed -- computing the two separately loses precision exactly where the network is confident and the softmax output is near zero or one. The two are therefore fused here, and `Loss::CrossEntropy` requires `Act::Softmax` on the output layer.  # Initialisation is not cosmetic  Weights start from a scaled normal draw -- the He scaling `sqrt(2/fan_in)` for rectifiers, the Xavier scaling `sqrt(1/fan_in)` otherwise. Initialising everything to zero makes every hidden unit in a layer compute the same thing and receive the same gradient forever, so the layer has one effective unit no matter how wide it is; initialising too large saturates the sigmoid and tanh, whose derivative is then near zero and whose gradient therefore vanishes.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.linalg.matrix import Matrix
from rust_physics_engine.monte_carlo import Rng

class Act:
    """
The activation applied after a layer's affine map.

Rust: `learn::nn::Act`
    """
    ...

class Gradients:
    """
The gradient of the loss with respect to every parameter, shaped
like the network itself.

Rust: `learn::nn::Gradients`
    """
    def __init__(self, layers: list[tuple[Matrix | Sequence[Sequence[float]], list[float]]]) -> None: ...
    def norm(self) -> float: ...
    @property
    def layers(self) -> list[tuple[Matrix, list[float]]]: ...

class Loss:
    """
What the network is asked to minimise.

Rust: `learn::nn::Loss`
    """
    ...

class Mlp:
    """
A fully connected feed-forward network.

Rust: `learn::nn::Mlp`
    """
    def __init__(self, sizes: list[int], activation: Act, output_activation: Act, rng: Rng) -> None: ...
    def input_size(self) -> int: ...
    def output_size(self) -> int: ...
    def parameter_count(self) -> int: ...
    def preactivations(self, x: list[float]) -> list[list[float]]: ...
    def forward(self, x: list[float]) -> list[float]: ...
    def predict(self, x: list[float]) -> int: ...
    def example_loss(self, x: list[float], y: list[float], loss: Loss) -> float: ...
    def loss(self, data: list[tuple[list[float], list[float]]], loss: Loss) -> float: ...
    def backward(self, x: list[float], y: list[float], loss: Loss) -> Gradients: ...
    def numerical_grad_check(self, x: list[float], y: list[float], loss: Loss) -> float: ...
    def train_sgd(self, data: list[tuple[list[float], list[float]]], loss: Loss, epochs: int, lr: float, batch: int, rng: Rng) -> list[float]: ...
    def train_adam(self, data: list[tuple[list[float], list[float]]], loss: Loss, epochs: int, lr: float, batch: int, rng: Rng) -> list[float]: ...
    @property
    def layers(self) -> list[tuple[Matrix, list[float]]]: ...
    @property
    def activation(self) -> Act: ...
    @property
    def output_activation(self) -> Act: ...

def conv2d_forward(input: list[float], w: int, h: int, kernels: list[tuple[list[float], int, int]], stride: int, pad: int) -> tuple[list[list[float]], int, int]:
    """
One convolution layer's forward pass: `kernels` applied to a single
channel image, with the given stride and zero padding.

Returns one output plane per kernel, each row-major, along with the
output width and height. The convolution here is the cross-correlation
that every machine learning library calls a convolution -- the kernel
is *not* flipped. Against a symmetric kernel the two agree and the
distinction never shows; against an asymmetric one they differ by a
reflection, so a signal-processing convolution needs the kernel
reversed on the way in.

Errors:

`SolveError::InvalidArgument` for a zero stride, an empty kernel
set, a kernel larger than the padded image, or mismatched sizes;
`SolveError::DimensionMismatch` if the image is not `w * h`.

Rust: `learn::nn::conv2d_forward`
    """
    ...

def linear_regression_gd_check(x: Matrix | Sequence[Sequence[float]], y: list[float], iterations: int) -> float:
    """
Fits `y = X b` by gradient descent and reports how far the answer is
from the closed-form least-squares solution, relative to its size.

The point is the comparison. Least squares has an exact answer
through the normal equations, so an iterative method solving the same
problem has somewhere to be checked against -- and that check is
worth more than any amount of watching a loss go down, because a
descent with the wrong gradient also produces a loss that goes down.

The step size is taken as `1 / L` with `L` the largest eigenvalue of
`X^T X`, estimated by a few power iterations. That is the largest
step for which gradient descent on a quadratic is guaranteed to
converge, and going past it diverges rather than converging slowly.

Errors:

`SolveError::InvalidArgument` for an empty or ill-shaped problem;
whatever the least-squares solver reports otherwise.

Rust: `learn::nn::linear_regression_gd_check`
    """
    ...
