"""
Decision trees, random forests and gradient boosting.  # What a tree does that a linear model cannot  A decision tree asks a sequence of threshold questions about single features. Three consequences follow, and they are what the method is for rather than incidental to it.  *Scale does not matter.* A threshold on a feature is decided by the order of its values, not their magnitudes, so multiplying a column by a thousand changes the thresholds and nothing else -- the tree computes the same function and the predictions are identical. Nothing that measures a distance can say that: k-nearest-neighbours, k-means and a Gaussian process all change their answers entirely under the same rescaling. This is asserted directly.  *Interactions come free.* A split below a split conditions on the first, so a tree represents `x > a AND y > b` without anyone writing the product term.  *Nothing is extrapolated.* Every prediction is a leaf's summary of the training points that reached it, so a tree's output outside the training range is flat. That is honest and it is also useless for trend extrapolation, which is the usual reason to reach for something else.  # The impurity decrease is never negative  A split is chosen to minimise the weighted impurity of its two children, and refusing to split is always available, so the decrease recorded at every node is at least zero. Feature importances are sums of those decreases, weighted by how many samples passed through, so they are nonnegative and they sum to exactly the total impurity the tree removed. Both are checked rather than assumed.  # A single tree overfits by construction  Grown without limit, a tree separates every training point that can be separated, and its training error reaches zero. That number is therefore worthless as evidence of anything, in the same way a 1-nearest-neighbour training error is. What the ensembles do about it differs:  - a **random forest** grows many deep trees on bootstrap samples with a random subset of features considered at each split, and averages them. The trees are individually overfitted and their errors are decorrelated, so averaging cancels the variance without adding bias. - **gradient boosting** grows shallow trees in sequence, each fitted to what the previous ones got wrong. The trees are individually underfitted and the bias comes down step by step, which is why the learning rate matters and why the round count is what has to be stopped early.  The two are opposite strategies and neither is a variant of the other.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.monte_carlo import Rng

class Forest:
    """
An ensemble of trees grown on bootstrap samples.

Rust: `learn::tree::Forest`
    """
    def __init__(self, trees: list[Tree], out_of_bag: list[list[int]]) -> None: ...
    @property
    def trees(self) -> list[Tree]: ...
    @property
    def out_of_bag(self) -> list[list[int]]: ...

class Gbm:
    """
A gradient boosted regressor: a constant plus a sequence of shallow
trees.

Rust: `learn::tree::Gbm`
    """
    def __init__(self, base: float, trees: list[Tree], learning_rate: float, loss_history: list[float]) -> None: ...
    @property
    def base(self) -> float: ...
    @property
    def trees(self) -> list[Tree]: ...
    @property
    def learning_rate(self) -> float: ...
    @property
    def loss_history(self) -> list[float]: ...

class Tree:
    """
A fitted decision tree. Node zero is the root.

Rust: `learn::tree::Tree`
    """
    def __init__(self, nodes: list[TreeNode], n_features: int) -> None: ...
    @property
    def nodes(self) -> list[TreeNode]: ...
    @property
    def n_features(self) -> int: ...

class TreeNode:
    """
A node of a fitted tree.

Rust: `learn::tree::TreeNode`
    """
    ...

def gini(counts: list[int]) -> float:
    """
The Gini impurity of a set of class counts, `1 - sum p^2`.

Exactly zero for a pure node and exactly `1 - 1/k` for `k` classes in
equal proportion, which is its maximum. Both are identities rather
than limits.

Compared with `entropy` it is cheaper -- no logarithm -- and the
two rank splits almost identically, which is why the choice between
them is very nearly arbitrary.

Rust: `learn::tree::gini`
    """
    ...

def entropy(counts: list[int]) -> float:
    """
The Shannon entropy of a set of class counts, in nats.

Zero for a pure node and `ln k` for `k` classes in equal proportion.
A count of zero contributes nothing, which is the continuous
extension of `p ln p` at the origin rather than a special case.

Rust: `learn::tree::entropy`
    """
    ...

def decision_tree_fit(x: list[list[float]], y: list[int], max_depth: int, min_leaf: int) -> Tree:
    """
Fits a classification tree by greedy Gini reduction.

Errors:

`SolveError::InvalidArgument` for an invalid dataset or a zero
`min_leaf`; `SolveError::DimensionMismatch` on a label count
mismatch.

Rust: `learn::tree::decision_tree_fit`
    """
    ...

def regression_tree_fit(x: list[list[float]], y: list[float], max_depth: int, min_leaf: int) -> Tree:
    """
Fits a regression tree by greedy variance reduction.

Errors:

As `decision_tree_fit`, and additionally for non-finite targets.

Rust: `learn::tree::regression_tree_fit`
    """
    ...

def tree_predict(tree: Tree, x: list[float]) -> int:
    """
The class a tree predicts for a point.

Errors:

`SolveError::DimensionMismatch` if the point has the wrong width.

Rust: `learn::tree::tree_predict`
    """
    ...

def tree_predict_value(tree: Tree, x: list[float]) -> float:
    """
The value a regression tree predicts for a point.

Errors:

As `tree_predict`.

Rust: `learn::tree::tree_predict_value`
    """
    ...

def feature_importance(tree: Tree) -> list[float]:
    """
How much impurity each feature removed, summed over the splits that
used it and weighted by the samples that reached them.

Nonnegative, because no split with a negative decrease is ever taken,
and summing to exactly the tree's total weighted impurity decrease.
Unnormalised on purpose: the total is a meaningful quantity, and
dividing by it throws away how much the tree explained in favour of
how it divided the credit.

Rust: `learn::tree::feature_importance`
    """
    ...

def random_forest_fit(x: list[list[float]], y: list[int], n_trees: int, max_depth: int, min_leaf: int, features_per_split: int, rng: Rng) -> Forest:
    """
Grows a random forest: `n_trees` classification trees, each on a
bootstrap resample, each split choosing among a random subset of
features.

Both sources of randomness are needed. Bagging alone leaves the trees
too much alike, because whichever feature is most informative is
chosen at the root of nearly all of them; restricting the features
considered at each split is what decorrelates the errors, and
averaging only cancels errors that are not shared.

`features_per_split` defaults to the square root of the feature
count when given as zero, which is the usual choice for
classification.

Errors:

As `decision_tree_fit`, plus `SolveError::InvalidArgument` for
zero trees.

Rust: `learn::tree::random_forest_fit`
    """
    ...

def forest_predict(forest: Forest, x: list[float]) -> int:
    """
The forest's majority vote.

Errors:

As `tree_predict`.

Rust: `learn::tree::forest_predict`
    """
    ...

def gradient_boosting_lite(x: list[list[float]], y: list[float], n_rounds: int, learning_rate: float, depth: int) -> Gbm:
    """
Fits a gradient boosted regressor under squared loss.

Starts at the mean and adds `learning_rate` times a shallow tree
fitted to the current residual, `n_rounds` times. Under squared loss
the negative gradient *is* the residual, which is why this simplest
case looks like nothing more than fitting the errors -- for other
losses the tree is fitted to the gradient and the leaf values are
then corrected, which is where the name comes from.

The loss falls monotonically for a learning rate at or below one,
because each tree reduces the squared residual it was fitted to and
shrinking a descent step cannot turn it into an ascent.

Errors:

As `regression_tree_fit`, plus `SolveError::InvalidArgument` for
a learning rate outside `(0, 1]`.

Rust: `learn::tree::gradient_boosting_lite`
    """
    ...

def gbm_predict(model: Gbm, x: list[float]) -> float:
    """
The boosted model's prediction.

Errors:

As `tree_predict_value`.

Rust: `learn::tree::gbm_predict`
    """
    ...
