"""
Network flow: maximum flow, minimum cut, and the problems that reduce to them.  A flow network is a `Graph` whose weights are capacities. An undirected edge is treated as a pair of arcs, each with the full capacity, which is the usual convention: flow may run either way but not both at once.  Capacities must be finite and non-negative. The residual graph is built internally as an arc list with paired indices, so the reverse arc of arc `i` is arc `i ^ 1`.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.graph.core import Graph

def max_flow_dinic(g: Graph, s: int, t: int) -> tuple[float, list[list[float]]]:
    """
The maximum flow from `s` to `t` by Dinic's algorithm, and the flow on each
arc as a matrix.

Dinic repeatedly builds a level graph by breadth-first search and pushes
blocking flow through it, which bounds the number of phases by the vertex
count rather than by the flow value -- the difference between terminating
and not on a network with large capacities.

The returned matrix holds the net flow: entry `(u, v)` is what crosses from
`u` to `v`, and is zero where nothing does.

Panics:
Panics if `s` or `t` is out of range, if they are equal, or if any capacity
is negative or not finite.

Rust: `graph::flow::max_flow_dinic`
    """
    ...

def max_flow_push_relabel(g: Graph, s: int, t: int) -> float:
    """
The maximum flow value by the push-relabel method with the highest-label
rule.

A different algorithm from `max_flow_dinic` rather than a variation on
it: push-relabel never maintains a valid flow until it finishes, working
instead with a preflow that it gradually returns to feasibility. The two
agreeing is therefore evidence, not a tautology.

Panics:
Panics under the same conditions as `max_flow_dinic`.

Rust: `graph::flow::max_flow_push_relabel`
    """
    ...

def min_cut(g: Graph, s: int, t: int) -> tuple[float, list[bool]]:
    """
The minimum `s`-`t` cut: its capacity and the source side.

By the max-flow min-cut theorem the capacity equals the maximum flow, and
the source side is exactly what remains reachable from `s` in the residual
network once the flow is maximum.

Panics:
Panics under the same conditions as `max_flow_dinic`.

Rust: `graph::flow::min_cut`
    """
    ...

def global_min_cut_stoer_wagner(g: Graph) -> tuple[float, list[int]]:
    """
The global minimum cut, by the Stoer-Wagner algorithm.

Finds the cheapest way to split the graph in two without naming the two
sides, which no single `s`-`t` computation does. Each phase grows a set by
always adding the most tightly connected vertex, which makes the last two
added a valid `s`-`t` pair for free; merging them and repeating gives the
global optimum in `n - 1` phases.

Returns the cut capacity and one side of it.

Panics:
Panics if the graph is directed, or has fewer than two vertices.

Rust: `graph::flow::global_min_cut_stoer_wagner`
    """
    ...

def min_cost_max_flow(g: Graph, costs: list[float], s: int, t: int) -> tuple[float, float]:
    """
The minimum-cost maximum flow from `s` to `t`.

`costs` gives the cost per unit on each arc, in the same order as
`g.edges()`. Returns the flow value and its total cost.

Augments along a shortest path by cost each round, found with Bellman-Ford
so negative costs are allowed. Sending flow along a shortest path keeps the
residual network free of negative cycles, which is what makes the greedy
choice optimal rather than merely feasible.

Panics:
Panics if `costs` does not have one entry per edge, or under the same
conditions as `max_flow_dinic`.

Rust: `graph::flow::min_cost_max_flow`
    """
    ...

def circulation_with_demands(g: Graph, demand: list[float], lower: list[float]) -> Optional[list[float]]:
    """
A feasible circulation meeting the given vertex demands, or `None` if none
exists.

`demand[v]` is positive when `v` must receive that much and negative when
it must send it. `lower` gives the minimum flow on each edge, in the order
of `g.edges()`. Solved by the standard reduction: subtract the lower bounds
into the demands, then look for a saturating flow from a super-source to a
super-sink.

Returns the flow on each edge in the order of `g.edges()`.

Panics:
Panics unless `demand` has one entry per vertex, `lower` one per edge, the
demands sum to zero, and every lower bound is within its capacity.

Rust: `graph::flow::circulation_with_demands`
    """
    ...

def max_bipartite_matching_via_flow(g: Graph, left: list[int]) -> list[Optional[int]]:
    """
A maximum matching of a bipartite graph, found by maximum flow.

`left` names the vertices on one side; the rest are the other side. Returns
the partner of each vertex, or `None` for the unmatched.

Slower than `graph::matching::hopcroft_karp` but built from a
different primitive, so the two agreeing is evidence about both.

Panics:
Panics if `left` names a vertex twice or out of range, or if an edge joins
two vertices on the same side.

Rust: `graph::flow::max_bipartite_matching_via_flow`
    """
    ...

def edge_disjoint_paths(g: Graph, s: int, t: int) -> int:
    """
The number of pairwise edge-disjoint paths from `s` to `t`.

Menger's theorem says this equals the minimum number of edges whose removal
separates them, which is the maximum flow with every capacity one.

Panics:
Panics if `s` or `t` is out of range, or they are equal.

Rust: `graph::flow::edge_disjoint_paths`
    """
    ...

def vertex_disjoint_paths(g: Graph, s: int, t: int) -> int:
    """
The number of pairwise internally vertex-disjoint paths from `s` to `t`.

The vertex form of Menger's theorem. Each vertex other than `s` and `t` is
split into an in-copy and an out-copy joined by a unit arc, which caps how
many paths can use it; the answer is then the edge-disjoint count on the
split graph.

Panics:
Panics if `s` or `t` is out of range, or they are equal.

Rust: `graph::flow::vertex_disjoint_paths`
    """
    ...

def gomory_hu_tree(g: Graph) -> Graph:
    """
A Gomory-Hu tree: an `n`-vertex tree in which the minimum cut between any
two vertices equals the lightest edge on the tree path between them.

Built by Gusfield's simplification, which needs only `n - 1` maximum-flow
computations and no vertex contraction. The result encodes all `C(n, 2)`
pairwise minimum cuts in `n - 1` numbers.

Panics:
Panics if the graph is directed.

Rust: `graph::flow::gomory_hu_tree`
    """
    ...

def closure_problem(g: Graph, weights: list[float]) -> tuple[float, list[bool]]:
    """
The maximum-weight closed subset of a directed graph.

A closure is a vertex set containing every successor of every member. The
maximum-weight closure reduces to a minimum cut: positive vertices are
joined to a source with their weight, negative ones to a sink with its
magnitude, and each original arc is given infinite capacity so no cut can
break it, which is exactly the closure condition.

Returns the weight and the membership flags.

Panics:
Panics unless `weights` has one entry per vertex.

Rust: `graph::flow::closure_problem`
    """
    ...

def project_selection(project_revenue: list[float], machine_cost: list[float], requires: list[list[int]]) -> float:
    """
The maximum profit of a project selection problem.

Projects have revenues and require machines that cost money; a project may
only be taken if every machine it needs is bought. `project_revenue[i]` is
the revenue of project `i`, `machine_cost[j]` the cost of machine `j`, and
`requires[i]` the machines project `i` needs.

This is `closure_problem` on the bipartite graph of projects and
machines, with revenues positive and costs negative.

Panics:
Panics if `requires` does not have one entry per project, or names a
machine out of range.

Rust: `graph::flow::project_selection`
    """
    ...

def max_flow(g: Graph, s: int, t: int) -> float:
    """
The maximum flow value as a plain number, for callers that do not want the
arc-by-arc matrix.

Panics:
Panics under the same conditions as `max_flow_dinic`.

Rust: `graph::flow::max_flow`
    """
    ...

def cut_capacity(g: Graph, side: list[bool]) -> float:
    """
The capacity of the cut defined by `side`: the total weight of the edges
leaving the `true` set.

A directed graph counts only arcs from the `true` side to the `false` one,
which is the `s`-`t` cut convention; an undirected graph counts every edge
crossing.

Panics:
Panics unless `side` has one flag per vertex.

Rust: `graph::flow::cut_capacity`
    """
    ...
