"""
Shortest paths, spanning trees, and tours.  Distances are `f64` and an unreachable vertex is `f64::INFINITY`, so the results compose without an `Option` at every step. Predecessor arrays use `None` for the source and for unreachable vertices alike; the distance distinguishes the two.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.graph.core import Graph
from numeria.linalg.matrix import Matrix
from numeria.cfd.riemann import Prim

def dijkstra(g: Graph, s: int) -> tuple[list[float], list[Optional[int]]]:
    """
Single-source shortest paths with non-negative weights, by Dijkstra.

Returns the distances and the predecessor array. Unreached vertices have
distance `f64::INFINITY` and no predecessor.

Panics:
Panics if any weight is negative, where the algorithm is simply wrong
rather than merely slow -- use `bellman_ford` instead.

Rust: `graph::paths::dijkstra`
    """
    ...

def dijkstra_target(g: Graph, s: int, t: int) -> Optional[tuple[float, list[int]]]:
    """
The shortest path from `s` to `t` and its length, or `None` if `t` is
unreachable.

Rust: `graph::paths::dijkstra_target`
    """
    ...

def bellman_ford(g: Graph, s: int) -> tuple[list[float], list[Optional[int]]]:
    """
Single-source shortest paths allowing negative weights, by Bellman-Ford.

Errors:
Returns `NegativeCycle` when a cycle of negative total weight is
reachable from `s`, which is detected by one relaxation pass beyond the
`n - 1` that suffice when none exists.

Rust: `graph::paths::bellman_ford`
    """
    ...

def floyd_warshall(g: Graph) -> Matrix:
    """
All-pairs shortest paths by Floyd-Warshall, `O(n^3)`.

Entry `(i, j)` is the distance, `f64::INFINITY` when unreachable. Negative
cycles are not detected here; a negative diagonal entry in the result is
the sign of one.

Rust: `graph::paths::floyd_warshall`
    """
    ...

def johnson(g: Graph) -> Matrix:
    """
All-pairs shortest paths by Johnson's algorithm: a Bellman-Ford pass from a
virtual source supplies potentials that make every weight non-negative,
then one Dijkstra per vertex.

Faster than Floyd-Warshall on sparse graphs, and unlike plain Dijkstra it
tolerates negative weights.

Errors:
Returns `NegativeCycle` if the graph contains one.

Rust: `graph::paths::johnson`
    """
    ...

def a_star(g: Graph, s: int, t: int, h: Callable[[int], float]) -> Optional[tuple[float, list[int]]]:
    """
A* search with the heuristic `h`.

Returns the path and its true length, or `None` if `t` is unreachable. The
result is optimal exactly when `h` is admissible -- never overestimating
the remaining distance -- and the search is efficient when `h` is also
consistent. An inadmissible heuristic still terminates but may return a
suboptimal path, which is the caller's trade to make.

Panics:
Panics if any weight is negative.

Rust: `graph::paths::a_star`
    """
    ...

def bidirectional_dijkstra(g: Graph, s: int, t: int) -> Optional[tuple[float, list[int]]]:
    """
Dijkstra from both ends at once, alternating between them.

Both searches settle vertices; the answer is the best path through any
vertex either has reached, and the search stops once the two settled
radii sum to at least the best path found. On a graph where the reachable
set grows with the radius, this settles roughly the square root of the
vertices a one-sided search would.

Panics:
Panics if any weight is negative.

Rust: `graph::paths::bidirectional_dijkstra`
    """
    ...

def k_shortest_paths_yen(g: Graph, s: int, t: int, k: int) -> list[tuple[float, list[int]]]:
    """
The `k` shortest loopless paths from `s` to `t`, by Yen's algorithm.

Returns them in increasing length, and may return fewer than `k` when
fewer exist. Each candidate is found by forcing a shared prefix with an
already-accepted path and forbidding the arc it took next, which is what
keeps the results distinct and loopless.

Rust: `graph::paths::k_shortest_paths_yen`
    """
    ...

def widest_path(g: Graph, s: int, t: int) -> Optional[tuple[float, list[int]]]:
    """
The widest path: the one whose narrowest edge is as wide as possible.

Also called the bottleneck shortest path or the maximum capacity path.
Dijkstra with `min` in place of `+` and `max` in place of `min`, which is
valid because `min` is monotone in the same way `+` is.

Rust: `graph::paths::widest_path`
    """
    ...

def minimax_path(g: Graph, s: int, t: int) -> Optional[tuple[float, list[int]]]:
    """
The minimax path: the one whose widest edge is as narrow as possible.

The dual of `widest_path`, and the path a minimum spanning tree gives
between any two vertices.

Rust: `graph::paths::minimax_path`
    """
    ...

def dag_shortest(g: Graph, s: int) -> list[float]:
    """
Shortest distances from `s` in a DAG, by relaxing in topological order.

Linear time and correct with negative weights, neither of which Dijkstra
manages.

Panics:
Panics if the graph is not a DAG.

Rust: `graph::paths::dag_shortest`
    """
    ...

def dag_longest(g: Graph, s: int) -> list[float]:
    """
Longest distances from `s` in a DAG.

Longest path is NP-hard in general but linear on a DAG, since the
topological order removes any need to revisit.

Panics:
Panics if the graph is not a DAG.

Rust: `graph::paths::dag_longest`
    """
    ...

def count_paths_dag(g: Graph, s: int, t: int) -> int:
    """
The number of distinct directed paths from `s` to `t` in a DAG.

Exact, because the count grows exponentially: a grid DAG of side `n` has
`C(2n, n)` paths, past `u64` before `n = 34`.

Panics:
Panics if the graph is not a DAG.

Rust: `graph::paths::count_paths_dag`
    """
    ...

def transitive_closure(g: Graph) -> list[list[bool]]:
    """
The reachability matrix: `[i][j]` is true when `j` is reachable from `i`.

Every vertex reaches itself.

Rust: `graph::paths::transitive_closure`
    """
    ...

def minimum_spanning_tree_kruskal(g: Graph) -> tuple[float, list[tuple[int, int]]]:
    """
A minimum spanning forest by Kruskal's algorithm: sort the edges, accept
each one that joins two different components.

Returns the total weight and the edges, each with `u < v`. On a
disconnected graph this is a spanning forest, and the edge count is
`n - components` rather than `n - 1`.

Rust: `graph::paths::minimum_spanning_tree_kruskal`
    """
    ...

def minimum_spanning_tree_prim(g: Graph) -> tuple[float, list[tuple[int, int]]]:
    """
A minimum spanning forest by Prim's algorithm: grow a tree from each
unvisited vertex, always taking the cheapest edge leaving it.

Returns the same weight as Kruskal on any graph, though possibly a
different tree when weights tie.

Rust: `graph::paths::minimum_spanning_tree_prim`
    """
    ...

def minimum_spanning_tree_boruvka(g: Graph) -> tuple[float, list[tuple[int, int]]]:
    """
A minimum spanning forest by Boruvka's algorithm: every component picks its
own cheapest outgoing edge, and all of them are added at once.

Halves the component count per round, so `O(log n)` rounds suffice. Ties
are broken by edge index, which is what stops two components from each
picking the other's edge and forming a cycle.

Rust: `graph::paths::minimum_spanning_tree_boruvka`
    """
    ...

def second_best_mst(g: Graph) -> Optional[tuple[float, list[tuple[int, int]]]]:
    """
The second-best spanning tree: the cheapest spanning tree that differs from
the minimum one in at least one edge.

Found by swapping: for each non-tree edge, adding it creates one cycle, and
removing the heaviest tree edge on that cycle gives the cheapest tree
containing it. The best such swap is the answer.

Returns `None` when the graph is disconnected or has no non-tree edge, so
no second tree exists.

Rust: `graph::paths::second_best_mst`
    """
    ...

def steiner_tree_small(g: Graph, terminals: list[int]) -> tuple[float, list[tuple[int, int]]]:
    """
A minimum Steiner tree spanning the given terminals, by Dreyfus-Wagner.

Returns the weight and the edges. The tree may use non-terminal vertices,
which is what separates the problem from a spanning tree. Costs
`O(3^t n + 2^t n^2)` for `t` terminals, so the terminal count is what has
to stay small, not the graph.

Panics:
Panics if there are more than 12 terminals, or a terminal is out of range.

Rust: `graph::paths::steiner_tree_small`
    """
    ...

def traveling_salesman_exact(dist: Matrix | Sequence[Sequence[float]]) -> tuple[float, list[int]]:
    """
The exact optimal travelling salesman tour, by Held-Karp.

Returns the tour length and the tour as a vertex sequence starting and
ending at 0, with the final return implied rather than repeated. Costs
`O(2^n n^2)` time and `O(2^n n)` memory.

Panics:
Panics if `dist` is not square, or has more than 20 rows.

Rust: `graph::paths::traveling_salesman_exact`
    """
    ...

def tsp_nearest_neighbor(dist: Matrix | Sequence[Sequence[float]]) -> tuple[float, list[int]]:
    """
A nearest-neighbour tour: repeatedly walk to the closest unvisited city.

Fast and usually poor: on a metric instance it can be a logarithmic factor
worse than optimal, so it is a starting point for `tsp_2opt` rather than
an answer.

Panics:
Panics if `dist` is not square.

Rust: `graph::paths::tsp_nearest_neighbor`
    """
    ...

def tour_length(dist: Matrix | Sequence[Sequence[float]], tour: list[int]) -> float:
    """
The length of a closed tour under `dist`.

Rust: `graph::paths::tour_length`
    """
    ...

def tsp_2opt(dist: Matrix | Sequence[Sequence[float]], tour: list[int]) -> tuple[float, list[int]]:
    """
2-opt local search: repeatedly reverse a tour segment when that shortens
the tour, until no single reversal helps.

The result is 2-optimal, not optimal. On a symmetric instance a reversal
changes only the two edges at its ends, which is what makes each move an
`O(1)` decision.

Panics:
Panics if `dist` is not square, or `tour` is not a permutation of its rows.

Rust: `graph::paths::tsp_2opt`
    """
    ...

def tsp_or_opt(dist: Matrix | Sequence[Sequence[float]], tour: list[int]) -> tuple[float, list[int]]:
    """
Or-opt local search: relocate a run of one, two or three consecutive cities
elsewhere in the tour, in either orientation, while that shortens it.

Complements 2-opt, which can only reverse: a run that belongs elsewhere
entirely is a move 2-opt cannot make in one step.

Panics:
Panics if `dist` is not square, or `tour` is not a permutation of its rows.

Rust: `graph::paths::tsp_or_opt`
    """
    ...

def tsp_christofides(dist: Matrix | Sequence[Sequence[float]]) -> Optional[tuple[float, list[int]]]:
    """
Christofides' tour, which is within a factor of 1.5 of optimal on a metric
instance.

Takes a minimum spanning tree, adds a minimum-weight perfect matching on
the odd-degree vertices to make every degree even, walks the resulting
Eulerian circuit, and shortcuts repeats. The matching here is exact by
brute force over pairings, which is affordable because a tree has few
odd-degree vertices on the instances this is used for, and is refused
beyond sixteen of them rather than silently degrading to a greedy one.

Returns `None` when the odd set is too large for the exact matching.

Panics:
Panics if `dist` is not square or is not symmetric, since the guarantee
needs a metric.

Rust: `graph::paths::tsp_christofides`
    """
    ...

def chinese_postman(g: Graph) -> Optional[tuple[float, list[int]]]:
    """
A shortest closed walk crossing every edge at least once: the Chinese
postman problem.

Returns the walk's total weight and the vertex sequence. When every degree
is already even the answer is an Eulerian circuit and costs exactly the
total edge weight; otherwise the odd-degree vertices are paired up by a
minimum-weight perfect matching over shortest paths, and those paths are
duplicated. Returns `None` when the edges span more than one component, so
that no single closed walk can cross them all, or when the odd set is too
large for the exact matching. An edgeless graph has nothing to cross, so it
returns the empty route rather than failing on being disconnected.

Panics:
Panics if the graph is directed, where the construction differs.

Rust: `graph::paths::chinese_postman`
    """
    ...
