"""
Primes: sieves, primality testing, factorization, and prime counting.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.monte_carlo import Rng

def sieve_eratosthenes(n: int) -> list[int]:
    """
All primes up to and including `n`, by the sieve of Eratosthenes.

Rust: `discrete::primes::sieve_eratosthenes`
    """
    ...

def sieve_segmented(lo: int, hi: int) -> list[int]:
    """
Primes in `[lo, hi)`, sieving only that window.

The window is marked using the primes up to `sqrt(hi)`, so memory scales
with the window rather than with `hi`.

Rust: `discrete::primes::sieve_segmented`
    """
    ...

def sieve_linear(n: int) -> tuple[list[int], list[int]]:
    """
Primes up to `n` together with the smallest prime factor of every
integer up to `n`, by the linear (Gries-Misra) sieve.

Each composite is struck exactly once, by its smallest prime factor.

Rust: `discrete::primes::sieve_linear`
    """
    ...

def mod_pow_u64(base: int, exp: int, m: int) -> int:
    """
Modular exponentiation on `u64`.

Rust: `discrete::primes::mod_pow_u64`
    """
    ...

def is_prime_u64(n: int) -> bool:
    """
Deterministic primality for every `u64`.

Miller-Rabin over the first twelve prime bases is proven correct for
all 64-bit inputs, so this is a decision procedure rather than a
probabilistic test.

Rust: `discrete::primes::is_prime_u64`
    """
    ...

def is_prime_bigint(n: int, rounds: int, rng: Rng) -> bool:
    """
Probabilistic primality for a `BigInt`: `rounds` Miller-Rabin bases
followed by a strong Lucas test, which together form BPSW.

No composite is known to pass BPSW, though none is proven not to; a
composite passing `rounds` independent Miller-Rabin bases alone has
probability at most `4^-rounds`.

Panics:
Panics if `n` is negative.

Rust: `discrete::primes::is_prime_bigint`
    """
    ...

def next_prime(n: int) -> int:
    """
The smallest prime strictly greater than `n`.

Panics:
Panics if the search would overflow `u64`.

Rust: `discrete::primes::next_prime`
    """
    ...

def prev_prime(n: int) -> Optional[int]:
    """
The largest prime strictly less than `n`, or `None` below 3.

Rust: `discrete::primes::prev_prime`
    """
    ...

def random_prime(bits: int, rng: Rng) -> int:
    """
A random prime with exactly `bits` bits.

Panics:
Panics if `bits` is below 2.

Rust: `discrete::primes::random_prime`
    """
    ...

def pollard_rho(n: int) -> Optional[int]:
    """
A non-trivial factor of a composite `n` by Pollard's rho with
Brent's cycle detection, or `None` if the attempt fails.

Rust: `discrete::primes::pollard_rho`
    """
    ...

def pollard_rho_bigint(n: int, rng: Rng) -> Optional[int]:
    """
Pollard's rho over `BigInt`, for factors beyond `u64`.

Rust: `discrete::primes::pollard_rho_bigint`
    """
    ...

def pollard_p_minus_1(n: int, bound: int) -> Optional[int]:
    """
Pollard's p-1 method: finds a factor `p` of `n` when `p - 1` is
`bound`-smooth. Returns `None` when no such factor separates.

Rust: `discrete::primes::pollard_p_minus_1`
    """
    ...

def trial_division(n: int, limit: int) -> tuple[list[tuple[int, int]], int]:
    """
Trial division up to `limit`: the factors found and the unfactored
remainder.

Rust: `discrete::primes::trial_division`
    """
    ...

def fermat_factor(n: int) -> Optional[tuple[int, int]]:
    """
Fermat's method: write an odd `n` as a difference of squares.

Effective only when `n` has two factors close to its square root;
returns `None` once the search passes a generous bound.

Rust: `discrete::primes::fermat_factor`
    """
    ...

def factorize(n: int) -> list[tuple[int, int]]:
    """
The complete prime factorization of `n`, ascending by prime.

Small factors go by trial division, the rest by Pollard's rho.

Rust: `discrete::primes::factorize`
    """
    ...

def factorize_bigint(n: int, rng: Rng) -> list[tuple[int, int]]:
    """
The factorization of a `BigInt` into primes.

Complete in every case that terminates, which is every case observed.
Unlike `factorize` this cannot promise it: splitting a large composite
has no guaranteed-terminating fallback the way trial division is one below
`2^64`, so a cofactor that survives Pollard rho and Pollard p-1 is returned
as a single entry even though it is known composite. A caller that needs
certainty should test each returned base with `is_prime_bigint`. Rho is
tried three times and each call draws sixteen fresh random polynomials, so
reaching that state means forty-eight independent attempts all failed.

Panics:
Panics if `n` is not positive.

Rust: `discrete::primes::factorize_bigint`
    """
    ...

def prime_count_meissel(n: int) -> int:
    """
The exact count of primes up to `n`, without sieving to `n`.

Uses the Lucy_Hedgehog recurrence over the distinct values of
`n / i`: starting from a count of all integers, each prime up to
`sqrt(n)` sieves its multiples out of every partial count at once. The
state has `O(sqrt n)` entries and the whole computation is
`O(n^(3/4))`, so `pi(10^9)` is reachable without a `10^9`-bit sieve.

Rust: `discrete::primes::prime_count_meissel`
    """
    ...

def prime_count_li_approx(x: float) -> float:
    """
The logarithmic integral estimate of `pi(x)`, by series.

Rust: `discrete::primes::prime_count_li_approx`
    """
    ...

def riemann_r(x: float) -> float:
    """
Riemann's refinement `R(x) = sum_{k>=1} mu(k)/k * li(x^(1/k))`.

Rust: `discrete::primes::riemann_r`
    """
    ...

def nth_prime(n: int) -> int:
    """
The `n`th prime, one-based: `nth_prime(1) == 2`.

Panics:
Panics if `n` is zero.

Rust: `discrete::primes::nth_prime`
    """
    ...

def prime_gaps(n: int) -> list[int]:
    """
The gaps between consecutive primes up to `n`.

Rust: `discrete::primes::prime_gaps`
    """
    ...

def twin_primes(n: int) -> list[tuple[int, int]]:
    """
Twin prime pairs `(p, p+2)` with `p + 2 <= n`.

Rust: `discrete::primes::twin_primes`
    """
    ...

def goldbach_partitions(n: int) -> list[tuple[int, int]]:
    """
Every way to write an even `n` as an ordered sum of two primes with
`p <= q`.

Rust: `discrete::primes::goldbach_partitions`
    """
    ...

def primes_in_arithmetic_progression(a: int, d: int, count: int) -> list[int]:
    """
The first `count` primes in the arithmetic progression `a, a+d, ...`.

Panics:
Panics if `d` is zero.

Rust: `discrete::primes::primes_in_arithmetic_progression`
    """
    ...

def mersenne_lucas_lehmer(p: int) -> bool:
    """
The Lucas-Lehmer test: is the Mersenne number `2^p - 1` prime?

`p` must itself be prime for the test to be meaningful; composite `p`
gives a composite Mersenne number and the function returns false.

Rust: `discrete::primes::mersenne_lucas_lehmer`
    """
    ...

def wilson_check(p: int) -> bool:
    """
Wilson's theorem: `p` is prime exactly when `(p-1)! = -1 (mod p)`.

Correct but exponentially slower than `is_prime_u64`; included for
the identity rather than for use.

Rust: `discrete::primes::wilson_check`
    """
    ...
