"""
Integer sequences, linear recurrences, and generating functions.  Two halves. The first recovers a sequence from an analytic or algebraic description: Taylor coefficients from a function by Cauchy's integral, and the minimal linear recurrence from a prefix by Berlekamp-Massey. The second is the named sequences themselves.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def ogf_coefficients(f: Callable[[complex], complex], n: int, radius: float) -> list[float]:
    """
The first `n` Taylor coefficients of `f` about the origin, by Cauchy's
integral evaluated on a circle of the given radius.

`a_k = (1 / 2 pi i) * contour integral of f(z) / z^(k+1)`. Sampling the
circle at `N` equally spaced points turns that into a discrete Fourier
transform, so all `N` coefficients come out of one FFT rather than `n`
separate quadratures.

The radius is the accuracy knob and the caller owns it: it must be inside
the disc of convergence, and the error in `a_k` scales like
`(radius / R)^N` for the true radius of convergence `R`. A radius near `R`
resolves high-order coefficients but amplifies the low-order ones by
`radius^-k`; a small radius does the reverse.

Returns the real parts, so this is for series with real coefficients.

Panics:
Panics if `n` is zero or `radius` is not positive.

Rust: `discrete::sequences::ogf_coefficients`
    """
    ...

def egf_to_ogf(coeffs: list[float]) -> list[float]:
    """
Converts exponential generating function coefficients to ordinary ones by
multiplying term `k` by `k!`.

The factorial overflows `f64` past `k = 170`, so the tail beyond that is
infinite rather than silently wrong.

Rust: `discrete::sequences::egf_to_ogf`
    """
    ...

def linear_recurrence(init: list[int], coeffs: list[int], n: int) -> int:
    """
The `n`-th term of the linear recurrence
`a_k = coeffs[0] a_{k-1} + coeffs[1] a_{k-2} + ...`, with `init` giving
`a_0 .. a_{order-1}`.

Panics:
Panics unless `init` and `coeffs` have the same non-zero length.

Rust: `discrete::sequences::linear_recurrence`
    """
    ...

def linear_recurrence_mod(init: list[int], coeffs: list[int], n: int, m: int) -> int:
    """
The `n`-th term of the same recurrence, modulo `m`, by matrix
exponentiation.

Costs `O(order^3 log n)` rather than `O(order * n)`, which is what makes an
index like `10^18` reachable.

Panics:
Panics unless `init` and `coeffs` have the same non-zero length, or if `m`
is zero.

Rust: `discrete::sequences::linear_recurrence_mod`
    """
    ...

def find_linear_recurrence(seq: list[Fraction]) -> Optional[list[Fraction]]:
    """
The shortest linear recurrence generating `seq`, by Berlekamp-Massey over
the rationals.

Returns `c` with `a_n = c[0] a_{n-1} + c[1] a_{n-2} + ...`, or `None` when
the sequence is too short to determine one. A recurrence of order `L` is
only pinned down by `2L` terms, so a candidate found from fewer is a guess;
this reports `None` in that case rather than returning it. The empty vector
is returned for the all-zero sequence, whose recurrence has order zero.

Rust: `discrete::sequences::find_linear_recurrence`
    """
    ...

def berlekamp_massey_gf2(seq: list[bool]) -> list[bool]:
    """
The connection polynomial of the shortest linear feedback shift register
generating `seq` over GF(2), returned as taps `t` with
`a_n = t[0] a_{n-1} XOR t[1] a_{n-2} XOR ...`.

Same algorithm as `find_linear_recurrence` with the field replaced by
GF(2), where every non-zero discrepancy is one and subtraction is XOR, so
there is no division to do.

Rust: `discrete::sequences::berlekamp_massey_gf2`
    """
    ...

def fibonacci_mod(n: int, m: int) -> int:
    """
`F(n) mod m`, by fast doubling.

The identities `F(2k) = F(k) (2 F(k+1) - F(k))` and
`F(2k+1) = F(k)^2 + F(k+1)^2` halve the index each step, so this is
`O(log n)` multiplications rather than `O(n)` additions.

Panics:
Panics if `m` is zero.

Rust: `discrete::sequences::fibonacci_mod`
    """
    ...

def pisano_period(m: int) -> int:
    """
The Pisano period: the period of the Fibonacci sequence modulo `m`.

Found by advancing until the pair `(0, 1)` recurs, which is the state that
starts the sequence, so the first recurrence is the full period.

Panics:
Panics if `m` is zero.

Rust: `discrete::sequences::pisano_period`
    """
    ...

def lucas(n: int) -> int:
    """
The `n`-th Lucas number: `L(0) = 2`, `L(1) = 1`, `L(n) = L(n-1) + L(n-2)`.

Rust: `discrete::sequences::lucas`
    """
    ...

def pell_number(n: int) -> int:
    """
The `n`-th Pell number: `P(0) = 0`, `P(1) = 1`, `P(n) = 2 P(n-1) + P(n-2)`.

Rust: `discrete::sequences::pell_number`
    """
    ...

def jacobsthal(n: int) -> int:
    """
The `n`-th Jacobsthal number: `J(0) = 0`, `J(1) = 1`,
`J(n) = J(n-1) + 2 J(n-2)`.

Rust: `discrete::sequences::jacobsthal`
    """
    ...

def tribonacci(n: int) -> int:
    """
The `n`-th tribonacci number: `0, 0, 1, 1, 2, 4, 7, 13, ...`.

Rust: `discrete::sequences::tribonacci`
    """
    ...

def look_and_say(seed: str, iterations: int) -> str:
    """
The look-and-say sequence: each step reads the previous term aloud.

`"1"` becomes `"11"` (one 1), which becomes `"21"` (two 1s), and so on.

Panics:
Panics if `seed` is empty or contains a non-digit.

Rust: `discrete::sequences::look_and_say`
    """
    ...

def conway_constant_estimate(iters: int) -> float:
    """
Conway's constant, estimated from the growth of look-and-say lengths.

The true value 1.303577... is the unique real root above one of Conway's
degree-71 polynomial. Lengths grow at that rate asymptotically, but the
single-step ratio does not settle onto it smoothly: it is still swinging
between 1.3137 and 1.3510 at twenty iterations, so reading off one ratio
would be worse at twenty steps than at sixteen. The swing has period four,
so this takes the geometric mean across a four-step window instead, which
cancels most of it and reaches four digits by thirty iterations.

Fewer than four iterations are run as four, since the window needs them.

Rust: `discrete::sequences::conway_constant_estimate`
    """
    ...

def thue_morse(n: int) -> bool:
    """
The `n`-th Thue-Morse bit: the parity of the number of ones in `n`.

Rust: `discrete::sequences::thue_morse`
    """
    ...

def thue_morse_sequence(n: int) -> list[bool]:
    """
The first `n` bits of the Thue-Morse sequence.

Rust: `discrete::sequences::thue_morse_sequence`
    """
    ...

def kolakoski(n: int) -> list[int]:
    """
The first `n` terms of the Kolakoski sequence over `{1, 2}`.

The sequence is its own run-length encoding: it starts `1, 2, 2, 1, 1, 2`,
whose run lengths are `1, 2, 2, 1, 1, 2` again. Generated by reading the
sequence back as it is written -- term `k` says how long run `k` is.

Rust: `discrete::sequences::kolakoski`
    """
    ...

def recaman(n: int) -> list[int]:
    """
The first `n` terms of Recaman's sequence.

`a(0) = 0`; each step subtracts the index if the result is positive and
has not appeared before, and otherwise adds it.

Rust: `discrete::sequences::recaman`
    """
    ...

def ulam_sequence(a: int, b: int, n: int) -> list[int]:
    """
The first `n` terms of the Ulam sequence starting `a, b`.

After the seeds, each term is the smallest integer larger than the last
that is the sum of two distinct earlier terms in exactly one way.

Panics:
Panics unless `0 < a < b`.

Rust: `discrete::sequences::ulam_sequence`
    """
    ...

def aliquot_sequence(n: int, max_steps: int) -> list[int]:
    """
The aliquot sequence from `n`: repeatedly replace a number by the sum of
its proper divisors.

Stops early at zero, which is terminal, and at a repeat, which means the
sequence has entered a cycle (a perfect number, an amicable pair, or a
longer sociable chain). The returned vector includes `n` itself and the
repeated value, so a cycle is visible in the output.

Rust: `discrete::sequences::aliquot_sequence`
    """
    ...

def ackermann_small(m: int, n: int) -> Optional[int]:
    """
The Ackermann function, for arguments whose value is representable.

`A(m, n)` is computed by the closed forms rather than the recursion, which
would not terminate in practice: `A(0,n) = n+1`, `A(1,n) = n+2`,
`A(2,n) = 2n+3`, `A(3,n) = 2^(n+3) - 3`, and `A(4,n)` is a tower of twos.
Returns `None` when the value cannot be built -- `A(4, 2)` already has
19729 digits and `A(5, 0) = A(4, 1)` is the largest value below it that
this returns.

Rust: `discrete::sequences::ackermann_small`
    """
    ...

def sequence_identify(terms: list[int]) -> list[str]:
    """
Names of the known sequences whose opening terms match `terms`.

Every candidate family is generated and compared term by term, so a name is
returned only on an exact match of the whole input. A linear recurrence
found by `find_linear_recurrence` is reported as well, which covers the
families not listed by name.

The result is a list because short prefixes are genuinely ambiguous:
`1, 1, 2` opens the Fibonacci numbers, the Catalan numbers, and the
partition counts alike.

Rust: `discrete::sequences::sequence_identify`
    """
    ...
