"""
Convex optimisation: gradient methods, quasi-Newton methods, proximal splitting, and constrained solvers.  Convexity buys one thing, and it is decisive: every local minimum is global. That removes the question the methods in `optimization::metaheuristics` spend all their effort on -- where else to look -- and replaces it with a purely local question, how fast to get downhill. Everything here is an answer to that.  The answers differ in what they know about curvature. Gradient descent knows nothing and pays for it: on a quadratic its error contracts by `(k-1)/(k+1)` per step, so a condition number of a thousand costs a thousand-fold more iterations than a condition number of one. Conjugate gradients build a set of mutually conjugate directions and finish an `n`-dimensional quadratic in at most `n` steps exactly. Newton's method uses the Hessian outright and lands on a quadratic's minimum in a single step. Quasi-Newton methods sit in between, accumulating an approximation to the Hessian from the gradients they have already paid for.  Those are not asymptotic claims but exact ones, and the tests check them as such: Newton in one step, conjugate gradients in `n`, and every method against the closed-form minimiser `-Q^-1 c` of the quadratic it was given.  The proximal half of the module handles objectives that are convex but not differentiable -- an L1 penalty, a constraint set -- by splitting them into a smooth part, handled by a gradient step, and a simple part, handled by its proximal operator. The reason that works is that the awkward part is usually simple in isolation: the proximal operator of an L1 penalty is soft thresholding, of a box is clamping, and of a simplex is a sorted shift. Each is a projection or near-projection with a closed form, so the non-smoothness costs almost nothing.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.core.dual import Dual
from numeria.linalg.matrix import Matrix
from numeria.monte_carlo import Rng

def backtracking(f: Callable[[list[float]], float], x: list[float], direction: list[float], gradient: list[float], c: float, max_halvings: int) -> float:
    """
Backtracking line search satisfying the Armijo sufficient-decrease
condition.

Halves the step until `f(x + t d) <= f(x) + c t g . d`. The condition is
what stops a long step that reduces the objective by less than the
gradient promised, which is how a descent method diverges on a curved
function despite every step going downhill.

Panics:
Panics unless the direction is a descent direction and `c` lies in
`(0, 1)`.

Rust: `optimization::convex::backtracking`
    """
    ...

def line_search_wolfe(f: Callable[[list[float]], float], grad: Callable[[list[float]], list[float]], x: list[float], direction: list[float], c1: float, c2: float) -> float:
    """
A line search satisfying the strong Wolfe conditions.

Armijo alone allows arbitrarily *short* steps, which stalls a quasi-Newton
method: the curvature information it accumulates comes from the difference
between successive gradients, and a step too short to change the gradient
carries none. The second Wolfe condition,
`|g(x + t d) . d| <= c2 |g(x) . d|`, rules that out by demanding the slope
actually flatten. Together they are what makes the BFGS update
well defined.

Panics:
Panics unless `0 < c1 < c2 < 1` and the direction descends.

Rust: `optimization::convex::line_search_wolfe`
    """
    ...

def exact_line_search(grad: Callable[[list[float]], list[float]], x: list[float], direction: list[float]) -> Optional[float]:
    """
An exact line search, by root-finding on the directional derivative.

The minimiser of `phi(t) = f(x + t d)` is where `phi'(t) = g(x + t d) . d`
vanishes. Since `phi'(0) < 0` for a descent direction, all that is needed
is a `t` where the slope has turned non-negative; bisection then locates
the root to machine precision. On a quadratic `phi'` is affine, so the
answer is exact to rounding.

Returns `None` when no such bracket exists within a doubling cap, which
means the function is unbounded below along the direction -- there is no
minimiser to find, and the caller should use an inexact search instead.

Panics:
Panics unless the direction descends.

Rust: `optimization::convex::exact_line_search`
    """
    ...

def nesterov(grad: Callable[[list[float]], list[float]], x0: list[float], learning_rate: float, momentum: float, iterations: int) -> list[float]:
    """
Nesterov's accelerated gradient method.

Evaluates the gradient at an extrapolated point rather than the current
one, which is the whole difference from heavy-ball momentum: the method
gets to see where the momentum is taking it before committing. That
changes the convergence rate on a smooth convex function from `O(1/k)` to
`O(1/k^2)`, which is optimal for a method that only ever sees gradients.

Panics:
Panics if the learning rate is not positive.

Rust: `optimization::convex::nesterov`
    """
    ...

def adagrad(grad: Callable[[list[float]], list[float]], x0: list[float], learning_rate: float, iterations: int) -> list[float]:
    """
Adagrad: scale each coordinate's step by the inverse root of its
accumulated squared gradient.

Coordinates with consistently large gradients get short steps and rare
coordinates get long ones, which is what makes it suit sparse problems.
The accumulator only grows, so the effective learning rate decays
monotonically to zero -- helpful for convergence, fatal if the problem
needs to keep moving, which is what `rmsprop` fixes.

Panics:
Panics if the learning rate is not positive.

Rust: `optimization::convex::adagrad`
    """
    ...

def rmsprop(grad: Callable[[list[float]], list[float]], x0: list[float], learning_rate: float, decay: float, iterations: int) -> list[float]:
    """
RMSProp: Adagrad with an exponentially weighted accumulator.

Forgetting old gradients keeps the effective learning rate from decaying
to zero, so the method can keep making progress indefinitely.

Panics:
Panics unless the learning rate is positive and `decay` lies in `[0, 1)`.

Rust: `optimization::convex::rmsprop`
    """
    ...

def adamw(grad: Callable[[list[float]], list[float]], x0: list[float], learning_rate: float, weight_decay: float, iterations: int) -> list[float]:
    """
AdamW: Adam with the weight decay applied to the parameters directly
rather than folded into the gradient.

The distinction matters because Adam divides the gradient by its own
running scale. A decay term added to the gradient gets divided too, so its
strength ends up depending on how large the other gradients happen to be;
applied to the parameters it does not. That is the entire content of the
change, and it is why the two behave differently at the same nominal decay.

Panics:
Panics unless the learning rate is positive and both moment decays lie in
`[0, 1)`.

Rust: `optimization::convex::adamw`
    """
    ...

def subgradient_method(f: Callable[[list[float]], float], subgradient: Callable[[list[float]], list[float]], x0: list[float], initial_step: float, iterations: int) -> tuple[list[float], float]:
    """
Subgradient descent for a convex objective that is not differentiable.

A subgradient is not a descent direction -- moving along it can increase
the objective, which is why the best value seen has to be tracked
separately rather than read off the last iterate. With a step size going
to zero but summing to infinity the method converges, at `O(1/sqrt(k))`:
far worse than the smooth case, and the price of giving up
differentiability.

Returns the best point found.

Panics:
Panics if the initial step is not positive.

Rust: `optimization::convex::subgradient_method`
    """
    ...

def bfgs(f: Callable[[list[float]], float], grad: Callable[[list[float]], list[float]], x0: list[float], tol: float, max_iter: int) -> tuple[list[float], float]:
    """
BFGS with a Wolfe line search.

Maintains an approximation to the *inverse* Hessian, updated from the
change in gradient across each step, so a Newton-like direction costs one
matrix-vector product and no solve. The update preserves positive
definiteness whenever the curvature condition `y . s > 0` holds, which the
Wolfe line search guarantees -- the two are designed together, and pairing
BFGS with a plain Armijo search is a classic way to make it fail.

Errors:
Returns an error if the starting point is empty.

Rust: `optimization::convex::bfgs`
    """
    ...

def lbfgs(f: Callable[[list[float]], float], grad: Callable[[list[float]], list[float]], x0: list[float], m: int, tol: float, max_iter: int) -> tuple[list[float], float]:
    """
Limited-memory BFGS.

Stores the last `m` pairs of step and gradient change instead of a full
matrix, and reconstructs the search direction by a two-loop recursion.
Memory drops from `n^2` to `mn`, which is what makes the method usable
where `n` runs to millions and a dense inverse Hessian could not be stored
at all, let alone factored.

Errors:
Returns an error if the starting point is empty or `m` is zero.

Rust: `optimization::convex::lbfgs`
    """
    ...

def conjugate_gradient_nonlinear(f: Callable[[list[float]], float], grad: Callable[[list[float]], list[float]], x0: list[float], tol: float, max_iter: int) -> tuple[list[float], float]:
    """
Nonlinear conjugate gradients with the Polak-Ribiere update.

On a quadratic the directions produced are mutually conjugate, so the
method reaches the exact minimum in at most `n` steps -- an exact finite
termination, not a rate. Away from a quadratic that guarantee lapses,
and the restart when `beta` goes negative is what keeps the directions
descending regardless.

Errors:
Returns an error if the starting point is empty.

Rust: `optimization::convex::conjugate_gradient_nonlinear`
    """
    ...

def prox_l1(v: list[float], t: float) -> list[float]:
    """
The proximal operator of `t ||x||_1`: soft thresholding.

`prox(v) = sign(v) max(|v| - t, 0)`, which is the exact minimiser of
`||x - v||^2 / 2 + t ||x||_1`. It is what makes L1 penalties produce
genuinely zero coefficients rather than merely small ones -- the operator
maps a whole interval to exactly zero, which no smooth penalty does.

Rust: `optimization::convex::prox_l1`
    """
    ...

def prox_l2(v: list[float], t: float) -> list[float]:
    """
The proximal operator of `t ||x||_2` (the norm, not its square): block
soft thresholding.

Shrinks the whole vector toward zero and sets it to exactly zero once its
norm falls below `t`. Unlike `prox_l1` it acts on the vector as a unit,
which is what group-sparse penalties need.

Rust: `optimization::convex::prox_l2`
    """
    ...

def prox_box(v: list[float], lo: float, hi: float) -> list[float]:
    """
The proximal operator of a box constraint: clamping.

The proximal operator of an indicator function is the projection onto the
set, and for a box that is coordinatewise clamping.

Rust: `optimization::convex::prox_box`
    """
    ...

def prox_simplex(v: list[float]) -> list[float]:
    """
Euclidean projection onto the probability simplex.

Sort, find the threshold at which the shifted positive parts sum to one,
and subtract it. The result is the closest point of the simplex, which is
not simply the clamped-and-renormalised vector -- that is a common
substitute and it is a different point.

Panics:
Panics if the vector is empty.

Rust: `optimization::convex::prox_simplex`
    """
    ...

def proximal_gradient(smooth_grad: Callable[[list[float]], list[float]], prox: Callable[[list[float], float], list[float]], x0: list[float], step: float, iterations: int) -> list[float]:
    """
Proximal gradient descent, also called ISTA: a gradient step on the smooth
part followed by the proximal operator of the rest.

The whole point is that the non-smooth part never needs a gradient. It
only has to have a proximal operator that can be evaluated, and for the
penalties that matter -- L1, group norms, indicator functions -- that
operator is a closed form.

Converges at `O(1/k)`.

Panics:
Panics if the step size is not positive.

Rust: `optimization::convex::proximal_gradient`
    """
    ...

def fista(smooth_grad: Callable[[list[float]], list[float]], prox: Callable[[list[float], float], list[float]], x0: list[float], step: float, iterations: int) -> list[float]:
    """
FISTA: proximal gradient descent with Nesterov's extrapolation.

The same two operations per iteration as `proximal_gradient`, applied at
an extrapolated point, which improves the rate from `O(1/k)` to `O(1/k^2)`
for no extra cost per step. The momentum sequence
`t_{k+1} = (1 + sqrt(1 + 4 t_k^2)) / 2` is what makes the accelerated
bound come out; an arbitrary momentum does not.

Panics:
Panics if the step size is not positive.

Rust: `optimization::convex::fista`
    """
    ...

def projected_gradient(grad: Callable[[list[float]], list[float]], project: Callable[[list[float]], list[float]], x0: list[float], step: float, iterations: int) -> list[float]:
    """
Projected gradient descent for a constrained smooth problem.

Take a gradient step, then project back onto the feasible set. Correct
whenever the set is convex and the projection is available; the projection
is what makes or breaks it, since for most sets it is itself an
optimisation problem.

Panics:
Panics if the step size is not positive.

Rust: `optimization::convex::projected_gradient`
    """
    ...

def frank_wolfe(grad: Callable[[list[float]], list[float]], linear_oracle: Callable[[list[float]], list[float]], x0: list[float], iterations: int) -> list[float]:
    """
The Frank-Wolfe method, also called conditional gradient.

Instead of projecting, it minimises a linear approximation over the
feasible set and moves toward that vertex. The iterate stays feasible
automatically as a convex combination of feasible points, so no projection
is ever needed -- which is the reason to use it when a linear minimisation
over the set is cheap and a projection is not.

`linear_oracle` returns the minimiser of a linear function over the set.

Panics:
Panics if the starting point is empty.

Rust: `optimization::convex::frank_wolfe`
    """
    ...

def mirror_descent_simplex(grad: Callable[[list[float]], list[float]], x0: list[float], step: float, iterations: int) -> list[float]:
    """
Mirror descent on the probability simplex, with the entropy mirror map.

The multiplicative update `x_i <- x_i exp(-t g_i)` followed by
renormalisation. Because the geometry matches the constraint set, the
dependence on dimension is `sqrt(log n)` rather than the `sqrt(n)` a
Euclidean projected gradient pays -- a large difference when the simplex
is over thousands of outcomes.

Panics:
Panics if the starting point is empty or the step is not positive.

Rust: `optimization::convex::mirror_descent_simplex`
    """
    ...

def ridge_closed_form(a: Matrix | Sequence[Sequence[float]], b: list[float], lambda_: float) -> list[float]:
    """
Ridge regression in closed form: solve `(A'A + lambda I) x = A'b`.

The one regularised regression with an exact answer, because the penalty
is smooth and quadratic like the loss. The added `lambda I` is also what
makes the system solvable when `A'A` is singular -- ridge regression
regularises the numerics as much as the statistics.

Errors:
Returns an error on a shape mismatch, a negative penalty, or a system that
is singular even after regularisation.

Rust: `optimization::convex::ridge_closed_form`
    """
    ...

def lasso_coordinate_descent(a: Matrix | Sequence[Sequence[float]], b: list[float], lambda_: float, iterations: int) -> list[float]:
    """
Lasso by cyclic coordinate descent.

Each coordinate is minimised exactly with the others held fixed, and that
one-dimensional problem has the soft-threshold closed form. Coordinate
descent works here precisely because the non-smooth part is *separable*:
the L1 penalty splits across coordinates, so a coordinatewise minimum is a
genuine minimum. On a non-separable penalty the same loop can stall at a
point that is optimal in every single direction and not optimal at all.

Minimises `||A x - b||^2 / (2 n) + lambda ||x||_1`.

Errors:
Returns an error on a shape mismatch or a negative penalty.

Rust: `optimization::convex::lasso_coordinate_descent`
    """
    ...

def admm_lasso(a: Matrix | Sequence[Sequence[float]], b: list[float], lambda_: float, rho: float, iterations: int) -> list[float]:
    """
The lasso by the alternating direction method of multipliers.

Splits the objective into the smooth least-squares part and the L1 part
with a copy of the variable, then alternates: a ridge solve, a soft
threshold, and a dual update. The factorisation of the ridge system does
not change between iterations, so it can be computed once -- which is what
makes ADMM cheap here despite doing a linear solve every step.

Solves the same problem as `lasso_coordinate_descent` and must agree
with it.

Errors:
Returns an error on a shape mismatch, a non-positive penalty parameter, or
a singular system.

Rust: `optimization::convex::admm_lasso`
    """
    ...

def admm_generic(prox_f: Callable[[list[float], float], list[float]], prox_g: Callable[[list[float], float], list[float]], x0: list[float], rho: float, iterations: int) -> list[float]:
    """
A generic two-block ADMM.

Minimises `f(x) + g(z)` subject to `x = z`, given only the proximal
operator of each part. The two halves never need to be handled together,
which is the point: a problem that is hard as a whole is often two easy
problems joined by a constraint.

Panics:
Panics if `rho` is not positive or the starting point is empty.

Rust: `optimization::convex::admm_generic`
    """
    ...

def elastic_net(a: Matrix | Sequence[Sequence[float]], b: list[float], l1: float, l2: float, iterations: int) -> list[float]:
    """
Elastic net regression: an L1 and an L2 penalty together.

The L1 part selects variables and the L2 part keeps correlated ones
together. Pure lasso picks arbitrarily among a group of correlated
predictors and zeroes the rest, which is unstable under resampling; the
ridge term removes that arbitrariness. At `l1 = 0` it is ridge and at
`l2 = 0` it is the lasso, and the tests check both limits.

Errors:
Returns an error on a shape mismatch or a negative penalty.

Rust: `optimization::convex::elastic_net`
    """
    ...

def logistic_regression_fit(x: Matrix | Sequence[Sequence[float]], y: list[float], lambda_: float, iterations: int) -> list[float]:
    """
L2-penalised logistic regression, fitted by Newton's method.

The penalised log-likelihood is strictly concave for any positive penalty,
so the maximum is unique and Newton's method converges quadratically to
it. Without the penalty, perfectly separable data has no finite maximiser
at all -- the coefficients run to infinity as the fitted probabilities
approach zero and one -- which is a property of the data rather than a
failure of the solver, and the penalty is what makes the problem
well posed.

`y` holds zeros and ones. Returns the coefficients.

Errors:
Returns an error on a shape mismatch, a label outside `{0, 1}`, or a
non-positive penalty.

Rust: `optimization::convex::logistic_regression_fit`
    """
    ...

def quadratic_program_active_set(q: Matrix | Sequence[Sequence[float]], c: list[float], a: Matrix | Sequence[Sequence[float]], b: list[float]) -> tuple[list[float], list[float]]:
    """
A convex quadratic program with equality constraints, by the active-set
idea applied to the equalities alone.

Minimises `x'Qx/2 + c'x` subject to `Ax = b`. With only equalities the
active set is fixed, so the whole problem is one KKT linear system:
stationarity and feasibility stacked together. The solution satisfies
`Qx + c + A'y = 0` exactly, which is what the tests check rather than
merely that the objective looks small.

Errors:
Returns an error on a shape mismatch or a singular KKT system.

Rust: `optimization::convex::quadratic_program_active_set`
    """
    ...

def kkt_residual(objective_gradient: list[float], constraint_values: list[float], constraint_gradients: list[list[float]], multipliers: list[float]) -> float:
    """
The norm of the Karush-Kuhn-Tucker residual at a candidate point.

Stacks the stationarity condition `grad f + sum y_i grad c_i` and the
feasibility conditions `c_i(x) = 0`. Zero exactly at a constrained
stationary point, which makes it the natural way to check a constrained
solver: it tests the conditions the answer must satisfy rather than
comparing against another solver that could share the same mistake.

Rust: `optimization::convex::kkt_residual`
    """
    ...

def dual_ascent(minimise_lagrangian: Callable[[list[float]], list[float]], constraints: Callable[[list[float]], list[float]], multipliers0: list[float], step: float, iterations: int) -> tuple[list[float], list[float]]:
    """
Dual ascent for an equality-constrained problem.

Alternates minimising the Lagrangian over `x` with a gradient step on the
multipliers, whose gradient is the constraint violation itself. It
converges only under strong assumptions -- strict convexity of the
objective, chiefly -- which is precisely the gap that the augmented
Lagrangian and ADMM close by adding a penalty term.

`minimise_lagrangian` returns the minimiser of `f(x) + y . c(x)` for the
given multipliers.

Panics:
Panics if the step is not positive.

Rust: `optimization::convex::dual_ascent`
    """
    ...

def convexity_check_numeric(f: Callable[[list[float]], float], bounds: list[tuple[float, float]], trials: int, rng: Rng) -> bool:
    """
Tests convexity numerically by sampling the midpoint inequality.

A convex function satisfies `f((a+b)/2) <= (f(a) + f(b)) / 2` for every
pair. Sampling can only ever *refute* convexity, never establish it: a
single violating pair is a proof of non-convexity, while a million
satisfying pairs prove nothing about the pairs not tried. The return value
should be read accordingly -- `false` is a fact and `true` is an absence
of evidence.

Panics:
Panics if the bounds are empty or `trials` is zero.

Rust: `optimization::convex::convexity_check_numeric`
    """
    ...

def condition_number_effect_demo(kappa: float) -> tuple[int, int]:
    """
Iterations that gradient descent and conjugate gradients need on a
two-dimensional quadratic of the given condition number.

Returns `(gradient descent, conjugate gradients)`. The contrast is the
whole point: gradient descent's error contracts by `(k-1)/(k+1)` per
step, so its count grows linearly in the condition number, while
conjugate gradients terminate in at most `n` steps whatever the
conditioning. At a condition number of a thousand that is hundreds of
iterations against two.

Panics:
Panics if the condition number is below one.

Rust: `optimization::convex::condition_number_effect_demo`
    """
    ...
