"""
Linear programming: the simplex method, interior point methods, duality, and the classical models that reduce to a linear program.  This module sits alongside the continuous optimisers in the parent module rather than replacing them. Those search a smooth objective by following gradients or shrinking a simplex, and stop at a local optimum. A linear program has no local optima to stop at: the objective is linear and the feasible region is a convex polyhedron, so any local optimum is global and at least one optimum sits at a vertex. That is the whole reason the subject exists as a separate discipline, and why an exact answer is available where a nonlinear problem admits only an approximation.  Two solvers are provided because they fail in different ways. The simplex method walks vertex to vertex along the boundary, and terminates in an exactly optimal basis, but its worst case is exponential and it can cycle in the presence of degeneracy -- handled here by Bland's rule, which guarantees termination at the cost of speed. The interior point method approaches the optimum through the middle of the region, takes a number of iterations that barely grows with problem size, and never lands exactly on a vertex. Running both on the same problem and comparing is the cheapest real check available on either.  Duality is the organising idea. Every linear program has a dual whose optimal value equals its own, and whose optimal solution is the vector of rates at which the primal objective responds to relaxing each constraint. Those rates -- shadow prices -- are usually worth more than the solution itself, since they say which constraint to attack. The convention used here is stated once and adhered to throughout:  > `duals[i]` is the derivative of the reported objective with respect to > `b[i]`.  That definition is what makes the sensitivity ranges mean something, and it is what the tests check: perturbing a right-hand side within its range changes the objective by exactly `duals[i]` times the perturbation.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.linalg.matrix import Matrix

class Cmp:
    """
The sense of a constraint row.

Rust: `optimization::lp::Cmp`
    """
    ...

class LpProblem:
    """
A linear program.

Minimises (or maximises) `c . x` subject to the rows of `a` compared
against `b` by `constraint_types`, with each variable confined to its
entry of `bounds`. A bound of `(0.0, f64::INFINITY)` is the default
non-negative variable; `(f64::NEG_INFINITY, f64::INFINITY)` makes a
variable free.

Rust: `optimization::lp::LpProblem`
    """
    def __init__(self, c: list[float], a: Matrix | Sequence[Sequence[float]], b: list[float], maximize: bool) -> None: ...
    def n(self) -> int: ...
    def m(self) -> int: ...
    def validate(self) -> None: ...
    def objective_at(self, x: list[float]) -> float: ...
    def is_feasible(self, x: list[float], tol: float) -> bool: ...
    @property
    def c(self) -> list[float]: ...
    @property
    def a(self) -> Matrix: ...
    @property
    def b(self) -> list[float]: ...
    @property
    def constraint_types(self) -> list[Cmp]: ...
    @property
    def bounds(self) -> list[tuple[float, float]]: ...
    @property
    def maximize(self) -> bool: ...

class LpResult:
    """
What a solver concluded.

Rust: `optimization::lp::LpResult`
    """
    def objective(self) -> Optional[float]: ...
    def solution(self) -> Optional[list[float]]: ...

def simplex(p: LpProblem) -> LpResult:
    """
Solves a linear program by the two-phase simplex method.

Phase one minimises the total artificial infeasibility from an
artificial-variable basis; a positive optimum there proves the problem
infeasible, since that value is the least total violation achievable.
Phase two then optimises the real objective from the feasible basis phase
one produced.

Bland's rule is used throughout, so the method terminates on any problem,
including degenerate ones where a faster pivoting rule would cycle.

Errors:
Returns an error if the problem's parts disagree in shape.

Rust: `optimization::lp::simplex`
    """
    ...

def lp_dual(p: LpProblem) -> LpProblem:
    """
The dual linear program.

For a minimisation `min c'x` subject to rows compared against `b` with
`x >= 0`, the dual is `max b'y` subject to `A'y <= c`, with each `y_i`
signed by the sense of its row: non-positive for a `<=` row, non-negative
for a `>=` row, free for an equality. Maximisation mirrors it.

Solving the dual gives the same optimal value as the primal and its
solution is the primal's vector of shadow prices, which is the practical
content of duality: the answer to "what is this constraint costing me" is
a solution to a different linear program of the same size.

Errors:
Returns an error unless every primal variable carries the default bounds
`(0, inf)`. A bounded variable contributes an extra dual row, which would
change the problem's shape rather than transpose it.

Rust: `optimization::lp::lp_dual`
    """
    ...

def sensitivity_ranges(p: LpProblem) -> tuple[list[tuple[float, float]], list[tuple[float, float]]]:
    """
Ranges over which the optimal basis survives, as
`(objective coefficient ranges, right-hand side ranges)`.

Inside a right-hand side's range the shadow price is constant, so the
objective moves by exactly `duals[i]` per unit of `b[i]`. That linearity
is the point of the exercise and is what the tests check; outside the
range the basis changes and the rate does too.

Inside an objective coefficient's range the optimal *point* does not move
at all, only the value.

Errors:
Returns an error if the problem is not solved to an optimum, or if any
variable carries non-default bounds -- a finite upper bound becomes an
extra row during standardisation, and the ranges would then be reported
against rows the caller never wrote.

Rust: `optimization::lp::sensitivity_ranges`
    """
    ...

def dual_simplex(p: LpProblem, basis: list[int]) -> LpResult:
    """
The dual simplex method, started from a given basis.

Where the primal simplex keeps every basic variable non-negative and works
toward optimality, the dual simplex keeps the reduced costs optimal and
works toward feasibility. That is the right way round after a right-hand
side changes -- the old basis stays dual-feasible while becoming primal
infeasible, so re-solving costs a few pivots instead of a fresh start.

`basis` names one standard-form column per constraint row. Column indices
run over the structural variables first, then the slack and surplus
columns in row order.

Errors:
Returns an error if the basis has the wrong length, names a column out of
range, or is singular. A basis that is not dual-feasible is reported as
`GeomError::Degenerate` rather than silently repaired.

Rust: `optimization::lp::dual_simplex`
    """
    ...

def interior_point(p: LpProblem, tol: float) -> LpResult:
    """
Solves a linear program by a primal-dual path-following interior point
method.

The method keeps `x > 0` and `s > 0` strictly, and drives the duality
measure `x's/n` toward zero along the central path. Each iteration solves
one Newton system, reduced to the normal equations `A D A' dy = r` with
`D = diag(x_i / s_i)` and factored by Cholesky. Unlike the simplex method
it never lands exactly on a vertex, and unlike the simplex method its
iteration count barely grows with the size of the problem.

The starting point is deliberately infeasible -- all ones -- and the primal
and dual residuals are driven to zero alongside the duality gap. That
avoids needing a phase one, but means infeasibility shows up as a failure
to converge rather than as a proof, so an unconverged run is reported as
`LpResult::Infeasible` only when the residuals are still large while the
gap has closed.

Errors:
Returns an error if the problem's parts disagree in shape or `tol` is not
positive.

Rust: `optimization::lp::interior_point`
    """
    ...

def lp_from_str(text: str) -> LpProblem:
    """
Parses a linear program from text.

The grammar is deliberately tiny:


The first line gives the sense and the objective. Everything after
`subject to` (or `st`, or `s.t.`) is a constraint row until an optional
`bounds` section, where single-variable lines set bounds rather than adding
rows and `free x` removes a variable's lower bound. Blank lines and `#`
comments are ignored, coefficients may be omitted, and variables are
numbered in order of first appearance.

Errors:
Returns `GeomError::InvalidArgument` naming the first thing that could
not be read.

Rust: `optimization::lp::lp_from_str`
    """
    ...

def diet_problem(costs: list[float], nutrients: Matrix | Sequence[Sequence[float]], requirements: list[float]) -> LpProblem:
    """
Stigler's diet problem: the cheapest combination of foods meeting every
nutritional minimum.

`costs` gives the price per unit of each food, `nutrients` holds the amount
of nutrient `k` in one unit of food `j` at `(k, j)`, and `requirements`
the minimum of each nutrient.

Errors:
Returns an error if the shapes disagree.

Rust: `optimization::lp::diet_problem`
    """
    ...

def production_planning(profits: list[float], usage: Matrix | Sequence[Sequence[float]], available: list[float]) -> LpProblem:
    """
A production plan: how much of each product to make to maximise profit
under resource limits.

`usage` holds the amount of resource `k` consumed per unit of product `j`
at `(k, j)`, and `available` the stock of each resource.

Errors:
Returns an error if the shapes disagree.

Rust: `optimization::lp::production_planning`
    """
    ...

def transportation_problem(supply: list[float], demand: list[float], costs: Matrix | Sequence[Sequence[float]]) -> LpResult:
    """
The transportation problem: ship from sources to sinks at least cost.

`costs` holds the unit cost from source `i` to sink `j` at `(i, j)`.
Supply is an upper limit and demand a lower one, so unbalanced instances
are handled without inventing a dummy row.

The constraint matrix is totally unimodular, so with integer supplies and
demands the simplex optimum is automatically integral -- no branch and
bound is needed, which is why the problem is solved as a linear program at
all.

Errors:
Returns an error if the shapes disagree or total demand exceeds total
supply, which is infeasible by inspection.

Rust: `optimization::lp::transportation_problem`
    """
    ...

def two_player_zero_sum_lp(payoff: Matrix | Sequence[Sequence[float]]) -> tuple[list[float], list[float], float]:
    """
Solves a two-player zero-sum game, returning
`(row strategy, column strategy, value)`.

`payoff` holds the row player's gain at `(i, j)`. The row player maximises
the worst case and the column player minimises the best case, and von
Neumann's minimax theorem says the two coincide -- which here is not an
extra assumption but a consequence of LP duality, since the two players'
programs are duals of each other. The column strategy is read directly off
the row program's shadow prices.

The payoff is shifted to be strictly positive before solving, since the
standard formulation divides by the value; the shift is undone on the way
out.

Errors:
Returns an error if the resulting program has no optimum, which cannot
happen for a finite game and would indicate a numerical failure.

Rust: `optimization::lp::two_player_zero_sum_lp`
    """
    ...

def chebyshev_center(a: Matrix | Sequence[Sequence[float]], b: list[float]) -> tuple[list[float], float]:
    """
The Chebyshev centre of the polyhedron `{x : a_i . x <= b_i}`: the point
furthest from every face, and that distance.

Maximises `r` subject to `a_i . x + r ||a_i|| <= b_i`. The norm term is
what turns "satisfy the constraint" into "stay `r` away from it", and it is
why the problem is linear at all -- the distance from a point to a
hyperplane is linear in the point.

Returns `(centre, radius)`. The radius is always unique, but the centre
need not be: in a box four wide and six tall the largest inscribed circle
has radius two and can sit anywhere along a vertical segment. Only the
coordinates that the touching faces pin down are determined, and the
returned point is one vertex of that optimal face.

An unbounded polyhedron gives an infinite radius; an empty one is an error.

Errors:
Returns an error for a shape mismatch, a zero row, or an infeasible system.

Rust: `optimization::lp::chebyshev_center`
    """
    ...

def l1_regression_lp(x: Matrix | Sequence[Sequence[float]], y: list[float]) -> list[float]:
    """
Least-absolute-deviations regression, solved as a linear program.

Minimises `sum |y_i - x_i . beta|` by splitting each residual into a
positive and a negative part. The result is far less sensitive to an
outlier than a least-squares fit, because the cost of a large residual
grows linearly rather than quadratically -- an outlier at ten standard
deviations pulls a hundred times harder on a least-squares fit than on
this one.

`x` holds one row per observation. Add a column of ones for an intercept.

Errors:
Returns an error on a shape mismatch or if the program has no optimum.

Rust: `optimization::lp::l1_regression_lp`
    """
    ...

def linf_regression_lp(x: Matrix | Sequence[Sequence[float]], y: list[float]) -> list[float]:
    """
Chebyshev (minimax) regression, solved as a linear program.

Minimises the largest absolute residual rather than their sum. Where the
L1 fit ignores an outlier, this one is dominated by it -- the fit is
pinned by the extreme points and by nothing else, which is exactly what is
wanted when the residuals are bounded errors rather than noise.

Errors:
Returns an error on a shape mismatch or if the program has no optimum.

Rust: `optimization::lp::linf_regression_lp`
    """
    ...
