"""
Derivative-free and population-based optimisation, and the benchmark landscapes used to tell one method from another.  Every method here treats the objective as a black box: it may be discontinuous, noisy, or defined only by a simulation, and no gradient is available even in principle. That rules out every gradient-based method and leaves search. What distinguishes the methods here is what they do with the evaluations they have spent.  Pattern search and Nelder-Mead keep a small geometric structure and move it downhill; they are cheap and get stuck in the first basin they find. Differential evolution and particle swarms keep a population, and their mutation steps are built from *differences between members*, so the search scale adapts to the spread of the population without anyone tuning it. CMA-ES goes furthest: it estimates the covariance of the successful steps and samples from that, which amounts to learning the local metric of the landscape, and is why it handles badly scaled and rotated problems that defeat the others.  None of them is guaranteed to find a global optimum in finite time, and any claim otherwise is a claim about the objective rather than the method. What the tests here check is therefore not "finds the optimum" in general, but the properties that must hold regardless: bounds are respected, the best-so-far never worsens, a Pareto front contains nothing dominated, and on landscapes whose optima are known analytically the methods get there.  The benchmark table exists so those claims can be made against something. Its stated optima are checked by dense sampling in the tests rather than taken on trust -- a benchmark whose recorded optimum is wrong silently invalidates every comparison made with it.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.graph.coloring import Order
from numeria.sim.cloth_sim import Particle
from numeria.monte_carlo import Rng
from numeria.spatial.primitives import Sphere

class Benchmark:
    """
A benchmark landscape: name, function, per-coordinate bounds, and the
known global minimum value.

Rust: `optimization::metaheuristics::Benchmark`
    """
    @property
    def name(self) -> str: ...
    @property
    def bounds(self) -> list[tuple[float, float]]: ...
    @property
    def optimum(self) -> float: ...

class GaConfig:
    """
Settings for the real-valued genetic algorithm.

Rust: `optimization::metaheuristics::GaConfig`
    """
    def __init__(self, population: int, generations: int, mutation_rate: float, mutation_scale: float, elite: int) -> None: ...
    @property
    def population(self) -> int: ...
    @property
    def generations(self) -> int: ...
    @property
    def mutation_rate(self) -> float: ...
    @property
    def mutation_scale(self) -> float: ...
    @property
    def elite(self) -> int: ...

def pattern_search(f: Callable[[list[float]], float], x0: list[float], step: float, tol: float, max_iter: int) -> tuple[list[float], float]:
    """
Compass pattern search: probe one coordinate step in each direction, move
to any improvement, and halve the step when none is found.

The simplest direct search that still has a convergence proof: on a
smooth function the step only shrinks when the current point beats all
`2n` neighbours, which forces the gradient toward zero as the step does.
Slower than Nelder-Mead in practice and far more robust, since it never
deforms its search pattern and so cannot collapse into a degenerate
simplex.

Panics:
Panics unless the starting point is non-empty and the step and tolerance
are positive.

Rust: `optimization::metaheuristics::pattern_search`
    """
    ...

def basin_hopping(f: Callable[[list[float]], float], x0: list[float], step: float, temperature: float, hops: int, rng: Rng) -> tuple[list[float], float]:
    """
Basin hopping: repeated local descent from perturbed starting points,
keeping the perturbation only when it leads somewhere better.

The Metropolis acceptance is applied to the *local minima*, not to the raw
function, which is what makes it a search over basins rather than over
points. On a landscape of many narrow wells separated by high barriers --
the case that defeats plain annealing -- collapsing each well to its floor
first turns the problem into a much smoother one.

Panics:
Panics unless the temperature and step are positive.

Rust: `optimization::metaheuristics::basin_hopping`
    """
    ...

def multistart_local(f: Callable[[list[float]], float], bounds: list[tuple[float, float]], starts: int, rng: Rng) -> tuple[list[float], float]:
    """
Repeated local search from random starting points inside a box.

The cheapest defence against a multimodal landscape, and a fair baseline:
any population method that cannot beat enough random restarts to match its
evaluation budget is not earning its complexity.

Panics:
Panics if `bounds` is empty or `starts` is zero.

Rust: `optimization::metaheuristics::multistart_local`
    """
    ...

def differential_evolution(f: Callable[[list[float]], float], bounds: list[tuple[float, float]], population: int, cr: float, weight: float, generations: int, rng: Rng) -> tuple[list[float], float]:
    """
Differential evolution: mutate by adding a scaled difference of two
population members to a third, then cross over with the target.

The difference vector is the whole idea. Early on the population is spread
out and the differences are large, so the search is global; as it
converges the differences shrink with it and the search becomes local.
Nobody has to schedule that -- the step size is read off the population's
own spread, which is why the method has so few parameters and why they
transfer between problems.

`cr` is the crossover rate in `[0, 1]` and `weight` the differential
scaling, conventionally near `0.8`.

Panics:
Panics unless the population is at least four, `cr` lies in `[0, 1]`, and
the bounds are non-empty.

Rust: `optimization::metaheuristics::differential_evolution`
    """
    ...

def particle_swarm(f: Callable[[list[float]], float], bounds: list[tuple[float, float]], particles: int, inertia: float, cognitive: float, social: float, iterations: int, rng: Rng) -> tuple[list[float], float]:
    """
Particle swarm optimisation: each particle carries a velocity pulled
toward its own best and the swarm's best.

`inertia` retains the previous velocity, `cognitive` weights the pull
toward the particle's own history and `social` the pull toward the
swarm's. The classic failure is setting inertia too high, where the swarm
never settles, or too low, where it collapses onto the first decent point
found and stops exploring.

Panics:
Panics unless the swarm is non-empty and the bounds are non-empty.

Rust: `optimization::metaheuristics::particle_swarm`
    """
    ...

def cma_es(f: Callable[[list[float]], float], x0: list[float], sigma0: float, generations: int, rng: Rng) -> tuple[list[float], float]:
    """
The covariance matrix adaptation evolution strategy.

Samples a population from a multivariate normal, keeps the better half,
and updates the mean, the step size and the full covariance from them. The
covariance is what sets it apart: after enough generations it approximates
the inverse Hessian up to scale, so the sampling distribution stretches
along the valley floor of a badly conditioned problem instead of
stumbling across it. That is the same information Newton's method uses,
obtained without a single derivative.

The step size is adapted separately, by comparing the length of the path
the mean has actually travelled against the length a random walk would
have covered; a mean that keeps moving in one direction is taking steps
that are too small.

Panics:
Panics unless the starting point is non-empty and `sigma0` is positive.

Rust: `optimization::metaheuristics::cma_es`
    """
    ...

def genetic_algorithm(f: Callable[[list[float]], float], bounds: list[tuple[float, float]], config: GaConfig, rng: Rng) -> tuple[list[float], float]:
    """
A real-valued genetic algorithm with tournament selection, blend
crossover and Gaussian mutation.

Elitism is what makes the best-so-far monotone: without carrying the best
members over untouched, a generation can be strictly worse than the last,
and the algorithm has no memory to recover it from.

Minimises `f`.

Panics:
Panics unless the population exceeds the elite count and the bounds are
non-empty.

Rust: `optimization::metaheuristics::genetic_algorithm`
    """
    ...

def genetic_algorithm_permutation(cost: Callable[[list[int]], float], n: int, config: GaConfig, rng: Rng) -> tuple[list[int], float]:
    """
A genetic algorithm over permutations, with order crossover and swap
mutation.

Blend crossover is meaningless on a permutation -- averaging two orderings
does not give an ordering. Order crossover instead copies a slice from one
parent and fills the rest in the order the other parent visits them, which
preserves relative order from both and always produces a valid
permutation. That closure property is the whole difficulty of the
permutation case.

Minimises `cost`.

Panics:
Panics unless `n >= 2` and the population exceeds the elite count.

Rust: `optimization::metaheuristics::genetic_algorithm_permutation`
    """
    ...

def pareto_front(points: list[list[float]]) -> list[int]:
    """
Indices of the non-dominated points: those no other point beats on every
objective while beating it on at least one.

Minimisation in every coordinate. The result is the Pareto front, and the
point of computing it is that without further information there is no
reason to prefer any member of it to any other -- a single "best" answer
only exists once the objectives are weighted, which is a decision the
optimiser cannot make.

Rust: `optimization::metaheuristics::pareto_front`
    """
    ...

def hypervolume_2d(front: list[list[float]], reference: tuple[float, float]) -> float:
    """
The area dominated by a two-objective front, bounded by a reference point.

The standard scalar summary of a front's quality, and the only common one
that is strictly monotone: adding a point that is not already dominated
can only increase it, so it cannot reward a front for losing coverage.
Points not dominating the reference contribute nothing.

Panics:
Panics if a front point is not two-dimensional.

Rust: `optimization::metaheuristics::hypervolume_2d`
    """
    ...

def benchmark_functions() -> list[Benchmark]:
    """
The standard test landscapes, in two dimensions.

They are chosen to fail different methods. Sphere is convex and separable
and everything solves it. Rosenbrock's optimum sits at the end of a curved
valley whose floor is nearly flat, which punishes anything that treats the
coordinates independently. Rastrigin and Ackley add a regular lattice of
local minima on top of a global structure, so a purely local method stops
at the first one. Griewank's local minima vanish as the dimension grows,
which makes it *easier* in higher dimensions and is a standing warning
about extrapolating benchmark results. Schwefel puts its optimum near a
corner, far from the centre where most methods are initialised.

The recorded optima are verified by dense sampling in this module's tests
rather than taken on trust.

Rust: `optimization::metaheuristics::benchmark_functions`
    """
    ...

def convergence_curve(history: list[float]) -> list[float]:
    """
The running best of a sequence of objective values.

Monotone non-increasing by construction, which is what makes two runs
comparable: the raw values of a stochastic search jump around and say
nothing about progress.

Rust: `optimization::metaheuristics::convergence_curve`
    """
    ...
