"""
Network models and scheduling: project planning, flows on networks, and the sequencing rules that provably optimise a stated objective.  Two threads run through this module. The first is that several graph problems are linear programs in disguise, and their constraint matrices are totally unimodular, so the linear relaxation is automatically integral. Shortest path and maximum flow both have this property, which is why they can be solved by combinatorial algorithms *and* by a general linear programming solver with the same answer. Having both is worth the duplication: the graph module's algorithms are far faster, and the linear programs are an independent check on them.  The second is that scheduling is a subject of exact greedy rules rather than heuristics. Sorting by processing time minimises mean flow time; sorting by due date minimises maximum lateness; Moore and Hodgson's rule minimises the *number* of late jobs; Johnson's rule minimises makespan on two machines. Each is provably optimal for its own objective and provably not for the others -- shortest-processing-time can make a job catastrophically late while minimising the average -- so the objective must be chosen before the rule. The tests check each rule against exhaustive enumeration of every permutation, on the objective it claims and on nothing else.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.graph.core import Graph
from numeria.optimization.lp import LpResult
from numeria.linalg.matrix import Matrix

class TaskTimes:
    """
The four schedule times of one task: earliest start, earliest finish,
latest start, latest finish.

Rust: `optimization::network::TaskTimes`
    """
    def __init__(self, early_start: float, early_finish: float, late_start: float, late_finish: float) -> None: ...
    def slack(self) -> float: ...
    @property
    def early_start(self) -> float: ...
    @property
    def early_finish(self) -> float: ...
    @property
    def late_start(self) -> float: ...
    @property
    def late_finish(self) -> float: ...

def transshipment(supply: list[float], arcs: list[tuple[int, int, float, float]]) -> LpResult:
    """
The transshipment problem: ship from sources to sinks through intermediate
nodes at least cost.

`supply[i]` is positive at a source, negative at a sink, and zero at a pure
transshipment node; the entries must sum to zero. `arcs` lists
`(from, to, unit cost, capacity)`.

Generalises the transportation problem by allowing goods to pass through a
node rather than only from a source directly to a sink, which is what makes
it a network rather than a bipartite matching.

Errors:
Returns an error if an arc names a node out of range or the supplies do not
balance.

Rust: `optimization::network::transshipment`
    """
    ...

def shortest_path_lp_check(g: Graph, s: int, t: int) -> Optional[float]:
    """
The length of a shortest path, computed as a linear program.

The dual of the shortest path problem asks for node potentials that
maximise the gap between source and target while no arc rises by more than
its length -- so the answer comes out of a linear program whose constraint
matrix is a node-arc incidence matrix, which is totally unimodular.

Its purpose is to check the graph module's Dijkstra against a completely
different method. Slower by a wide margin, and worth it only as
verification.

Errors:
Returns an error if the endpoints are out of range, or the graph has a
negative-length arc, where the linear program is unbounded rather than
merely wrong.

Rust: `optimization::network::shortest_path_lp_check`
    """
    ...

def max_flow_lp_check(g: Graph, s: int, t: int) -> Optional[float]:
    """
The value of a maximum flow, computed as a linear program.

Maximises the net outflow from the source subject to conservation at every
other node and each arc's capacity. Like the shortest path formulation this
exists to check the graph module's combinatorial algorithms rather than to
replace them.

Errors:
Returns an error if the endpoints are out of range or coincide.

Rust: `optimization::network::max_flow_lp_check`
    """
    ...

def network_simplex_lite(balance: list[float], arcs: list[tuple[int, int, float, float]]) -> LpResult:
    """
A minimum-cost flow by the network simplex, expressed through the general
simplex method.

`arcs` are `(from, to, unit cost, capacity)` and `balance[i]` the net
supply at node `i`, summing to zero. The genuine network simplex maintains
a spanning tree basis and pivots in `O(m)` per step rather than solving a
linear system; this routes the same problem through the general solver,
which is correct and slower, and is named "lite" for that reason.

Errors:
Returns an error under the same conditions as `transshipment`.

Rust: `optimization::network::network_simplex_lite`
    """
    ...

def critical_path_method(tasks: list[tuple[float, list[int]]]) -> tuple[float, list[int], list[TaskTimes]]:
    """
The critical path method: the shortest possible project duration, which
tasks cannot slip, and every task's four schedule times.

`tasks[i]` is `(duration, predecessors)`. Returns
`(duration, critical task indices, times)`.

The critical path is the longest path through the precedence graph, and the
project cannot finish sooner than that however many resources are thrown at
it -- which is the point of computing it. A task is critical exactly when
its slack is zero, so shortening a non-critical task buys nothing at all.

Errors:
Returns an error if a predecessor is out of range or the precedences
contain a cycle, which makes the project unschedulable.

Rust: `optimization::network::critical_path_method`
    """
    ...

def pert(tasks: list[tuple[float, float, float, list[int]]]) -> tuple[float, float]:
    """
PERT: the mean and variance of the project duration under three-point
estimates.

`tasks[i]` is `(optimistic, most likely, pessimistic, predecessors)`. Each
task's duration is taken as a beta distribution with mean
`(a + 4m + b) / 6` and standard deviation `(b - a) / 6`, and the project
duration as the sum along the critical path.

The variance is the sum of the *critical path's* variances only, which is
the method's known weakness: a near-critical path with high variance can
overtake the critical one and PERT will not see it, so the figure
understates the true spread. It is reported because it is what PERT means,
not because it is the whole answer.

Errors:
Returns an error if an estimate is out of order or the precedences are
unschedulable.

Rust: `optimization::network::pert`
    """
    ...

def vehicle_routing_savings(distance: Matrix | Sequence[Sequence[float]], demand: list[float], capacity: float) -> list[list[int]]:
    """
Clarke-Wright savings for the capacitated vehicle routing problem.

Every customer starts on its own out-and-back route. Merging the routes
ending at `i` and beginning at `j` saves `d(0,i) + d(0,j) - d(i,j)` -- the
two depot legs replaced by one direct leg -- so merges are tried in
decreasing order of that saving, subject to capacity.

Returns the routes as customer sequences, excluding the depot at each end.

Errors:
Returns an error if the distance matrix is the wrong shape, or a customer's
demand exceeds a vehicle's capacity, which makes routing impossible.

Rust: `optimization::network::vehicle_routing_savings`
    """
    ...

def job_shop_shifting_bottleneck_lite(jobs: list[list[tuple[int, float]]], machines: int) -> float:
    """
A lower bound on a job shop makespan by the shifting bottleneck idea,
simplified.

`jobs[j]` lists `(machine, duration)` in the order job `j` must visit them.
Returns the larger of the busiest machine's total load and the longest
job's total work -- both of which any schedule must exceed, since a machine
cannot process two operations at once and a job cannot be in two places.

The full shifting bottleneck procedure solves a one-machine sequencing
problem per machine and iterates; this reports the elementary bound those
iterations start from.

Errors:
Returns an error if a machine index exceeds the machine count.

Rust: `optimization::network::job_shop_shifting_bottleneck_lite`
    """
    ...

def scheduling_spt(jobs: list[float]) -> list[int]:
    """
Shortest processing time first: the order minimising mean flow time on one
machine.

Optimal by an exchange argument -- swapping an adjacent out-of-order pair
always improves the total -- and optimal for nothing else. It can make one
long job arbitrarily late while the average looks excellent, which is why
the objective has to be chosen before the rule.

`jobs[i]` is a processing time. Returns the job order.

Rust: `optimization::network::scheduling_spt`
    """
    ...

def scheduling_edd(jobs: list[tuple[float, float]]) -> list[int]:
    """
Earliest due date first: the order minimising maximum lateness on one
machine.

Jackson's rule. Also by an exchange argument, and again optimal only for
its own objective: it makes no attempt to reduce the *number* of late jobs,
which is what `moore_hodgson` is for.

`jobs[i]` is `(processing time, due date)`. Returns the job order.

Rust: `optimization::network::scheduling_edd`
    """
    ...

def moore_hodgson(jobs: list[tuple[float, float]]) -> list[int]:
    """
The Moore-Hodgson rule: the order minimising the *number* of late jobs on
one machine.

Work through the jobs by due date; whenever the schedule falls behind,
throw out the longest job accepted so far. That one removal buys the most
time back, and the jobs thrown out are exactly the late ones, which is what
makes the rule optimal rather than merely sensible.

Returns the order: the on-time jobs first in due-date order, then the late
ones.

`jobs[i]` is `(processing time, due date)`.

Rust: `optimization::network::moore_hodgson`
    """
    ...

def johnson_two_machine(jobs: list[tuple[float, float]]) -> list[int]:
    """
Johnson's rule: the order minimising makespan through two machines in
series.

Every job visits machine one then machine two. Jobs whose first operation
is the shorter go first, in increasing order of that operation; the rest go
last, in decreasing order of their second. The first group fills machine
two's queue quickly and the second keeps it busy at the end, which is what
the exchange argument formalises.

`jobs[i]` is `(time on machine one, time on machine two)`.

Rust: `optimization::network::johnson_two_machine`
    """
    ...

def two_machine_makespan(jobs: list[tuple[float, float]], order: list[int]) -> float:
    """
The makespan of a two-machine flow shop under a given order.

Machine two cannot start a job before machine one finishes it, nor before
it finishes the previous job, which is the whole recursion.

Rust: `optimization::network::two_machine_makespan`
    """
    ...

def lpt_makespan(jobs: list[float], machines: int) -> tuple[float, list[int]]:
    """
Longest processing time first onto identical parallel machines.

Returns the makespan and which machine each job went to. The rule finishes
within `4/3 - 1/(3m)` of the optimum, and that bound is tight -- so it is a
guarantee rather than an observation, and the tests check it against an
exact answer.

Panics:
Panics if `machines` is zero.

Rust: `optimization::network::lpt_makespan`
    """
    ...

def interval_scheduling_max(intervals: list[tuple[float, float]]) -> list[int]:
    """
The largest set of pairwise disjoint intervals, by earliest finish time.

The greedy choice is optimal, and the proof is the reason: whatever the
optimal set, replacing its first interval by the one that finishes earliest
leaves it still valid and no smaller, so an optimal solution containing the
greedy choice always exists.

`intervals[i]` is `(start, end)`. Returns the chosen indices.

Rust: `optimization::network::interval_scheduling_max`
    """
    ...

def weighted_interval_scheduling(intervals: list[tuple[float, float, float]]) -> tuple[float, list[int]]:
    """
The most valuable set of pairwise disjoint intervals.

Weights break the greedy argument completely -- one long valuable interval
can be worth more than any number of short ones -- so this is a table:
sort by finish time and, for each interval, either take it and jump to the
last compatible one or skip it.

`intervals[i]` is `(start, end, weight)`. Returns the total and the chosen
indices.

Rust: `optimization::network::weighted_interval_scheduling`
    """
    ...

def gantt_data(processing: list[float], order: list[int]) -> list[tuple[int, float, float]]:
    """
Turns a single-machine job order into `(job, start, finish)` bars.

Jobs run back to back in the given order from time zero, which is what a
single-machine sequencing rule assumes.

Rust: `optimization::network::gantt_data`
    """
    ...
