"""
Exact rational arithmetic over `BigInt`.  Every `Rational` is kept in lowest terms with a strictly positive denominator, so equality is structural and there is exactly one representation of each value. Zero is `0/1`.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.linalg.matrix import Matrix

def farey_sequence(n: int) -> list[Fraction]:
    """
The Farey sequence F_n: every reduced fraction in `[0, 1]` with
denominator at most `n`, in ascending order.

Panics:
Panics if `n` is zero.

Rust: `exact::rational::farey_sequence`
    """
    ...

def stern_brocot_path(r: Fraction) -> list[bool]:
    """
The path from the Stern-Brocot root `1/1` down to `r`, as a sequence of
branch choices: `true` for the right (larger) child, `false` for the
left.

The root itself has an empty path. Only positive rationals have one.

Panics:
Panics unless `r` is strictly positive.

Rust: `exact::rational::stern_brocot_path`
    """
    ...

def best_rational_approximations(x: float, max_den: int) -> list[Fraction]:
    """
Every continued-fraction convergent of `x` with denominator at most
`max_den`, in increasing order of denominator.

The last element is the best rational approximation to `x` under that
bound, in the strong sense that no fraction with a smaller denominator
is closer.

Panics:
Panics if `max_den` is zero or `x` is not finite.

Rust: `exact::rational::best_rational_approximations`
    """
    ...

def solve_exact_rational(a: list[list[Fraction]], b: list[Fraction]) -> Optional[list[Fraction]]:
    """
Solve `A x = b` exactly for rational data, by clearing denominators and
running Bareiss fraction-free elimination.

Returns `None` if the matrix is not square, the shapes disagree, or the
system is singular.

Rust: `exact::rational::solve_exact_rational`
    """
    ...

def solve_exact(a: Matrix | Sequence[Sequence[float]], b: list[float]) -> Optional[list[Fraction]]:
    """
Solve `A x = b` exactly for an `f64` system.

Each coefficient is converted to the rational it exactly equals — every
finite `f64` is dyadic — so the result is the exact solution of the
system as stored. Where the `f64` inputs are themselves roundings of
intended values, use `solve_exact_rational` to keep those values
exact instead.

Returns `None` for a non-square or singular system, mismatched shapes,
or any non-finite entry.

Rust: `exact::rational::solve_exact`
    """
    ...

def determinant_exact(a: list[list[Fraction]]) -> Fraction:
    """
The exact determinant of a rational matrix, via Bareiss on the
denominator-cleared integer matrix.

Panics:
Panics if the matrix is not square.

Rust: `exact::rational::determinant_exact`
    """
    ...

def hilbert_matrix_inverse_exact(n: int) -> list[list[Fraction]]:
    """
The exact inverse of the `n x n` Hilbert matrix `H_ij = 1/(i+j+1)`.

Uses the closed form
`(-1)^(i+j) (i+j+1) C(n+i, n-j-1) C(n+j, n-i-1) C(i+j, i)^2`,
whose entries are all integers.

Panics:
Panics if `n` is zero.

Rust: `exact::rational::hilbert_matrix_inverse_exact`
    """
    ...

def hilbert_matrix_exact(n: int) -> list[list[Fraction]]:
    """
The `n x n` Hilbert matrix as exact rationals.

Panics:
Panics if `n` is zero.

Rust: `exact::rational::hilbert_matrix_exact`
    """
    ...

def new(n: int, d: int) -> Optional[Fraction]:
    """
The rational `n/d`, or `None` when `d` is zero.

Rust: `exact::rational::Rational::new`
    """
    ...

def from_i64(n: int, d: int) -> Fraction:
    """
The rational `n/d` from machine integers.

Panics:
Panics if `d` is zero.

Rust: `exact::rational::Rational::from_i64`
    """
    ...

def from_int(n: int) -> Fraction:
    """
The integer `n` as a rational.

Rust: `exact::rational::Rational::from_int`
    """
    ...

def zero() -> Fraction:
    """

Rust: `exact::rational::Rational::zero`
    """
    ...

def one() -> Fraction:
    """

Rust: `exact::rational::Rational::one`
    """
    ...

def from_f64_exact(x: float) -> Optional[Fraction]:
    """
The exact value of an IEEE-754 double, or `None` for NaN and the
infinities.

Every finite `f64` is a dyadic rational `m * 2^e`, so the reduced
denominator is always a power of two.

Rust: `exact::rational::Rational::from_f64_exact`
    """
    ...

def from_f64_approx(x: float, max_den: int) -> Fraction:
    """
The best rational approximation to `x` with denominator at most
`max_den`, found by walking the continued fraction (equivalently,
descending the Stern-Brocot tree).

Panics:
Panics if `max_den` is zero or `x` is not finite.

Rust: `exact::rational::Rational::from_f64_approx`
    """
    ...

def is_zero(q: Fraction) -> bool:
    """

Rust: `exact::rational::Rational::is_zero`
    """
    ...

def is_negative(q: Fraction) -> bool:
    """

Rust: `exact::rational::Rational::is_negative`
    """
    ...

def is_integer(q: Fraction) -> bool:
    """

Rust: `exact::rational::Rational::is_integer`
    """
    ...

def abs(q: Fraction) -> Fraction:
    """

Rust: `exact::rational::Rational::abs`
    """
    ...

def neg(q: Fraction) -> Fraction:
    """

Rust: `exact::rational::Rational::neg`
    """
    ...

def recip(q: Fraction) -> Optional[Fraction]:
    """
The reciprocal, or `None` for zero.

Rust: `exact::rational::Rational::recip`
    """
    ...

def add(q: Fraction, other: Fraction) -> Fraction:
    """

Rust: `exact::rational::Rational::add`
    """
    ...

def sub(q: Fraction, other: Fraction) -> Fraction:
    """

Rust: `exact::rational::Rational::sub`
    """
    ...

def mul(q: Fraction, other: Fraction) -> Fraction:
    """

Rust: `exact::rational::Rational::mul`
    """
    ...

def div(q: Fraction, other: Fraction) -> Optional[Fraction]:
    """
Quotient, or `None` when `other` is zero.

Rust: `exact::rational::Rational::div`
    """
    ...

def pow(q: Fraction, e: int) -> Fraction:
    """
`self` raised to a signed integer power.

Panics:
Panics when raising zero to a negative power.

Rust: `exact::rational::Rational::pow`
    """
    ...

def to_f64(q: Fraction) -> float:
    """
Nearest `f64`.

When both parts are individually representable the quotient is a
single correctly-rounded division. Otherwise -- a tiny value like
`1e-300` has a denominator of about `2^1049`, far past the `f64`
range even though the quotient is fine -- the numerator is scaled
by a power of two first so the quotient itself lands in range, and
the scale is undone afterwards.

Rust: `exact::rational::Rational::to_f64`
    """
    ...

def floor(q: Fraction) -> int:
    """
Greatest integer not exceeding the value.

Rust: `exact::rational::Rational::floor`
    """
    ...

def ceil(q: Fraction) -> int:
    """
Least integer not below the value.

Rust: `exact::rational::Rational::ceil`
    """
    ...

def round(q: Fraction) -> int:
    """
Nearest integer, with halves rounded away from zero.

Rust: `exact::rational::Rational::round`
    """
    ...

def fract(q: Fraction) -> Fraction:
    """
The fractional part `self - floor(self)`, always in `[0, 1)`.

Rust: `exact::rational::Rational::fract`
    """
    ...

def to_continued_fraction(q: Fraction) -> list[int]:
    """
The continued-fraction expansion `[a0; a1, a2, ...]`.

The expansion is finite for every rational and, apart from the
integer case, never ends in a 1, which makes it canonical.

Rust: `exact::rational::Rational::to_continued_fraction`
    """
    ...

def from_continued_fraction(cf: list[int]) -> Fraction:
    """
Rebuild a rational from a continued fraction.

Errors:
Returns `GeomError::Empty` for an empty expansion, and
`GeomError::InvalidArgument` if a non-leading term is not
positive, which cannot arise from `Self::to_continued_fraction`.

Rust: `exact::rational::Rational::from_continued_fraction`
    """
    ...

def mediant(a: Fraction, b: Fraction) -> Fraction:
    """
The mediant `(a.num + b.num) / (a.den + b.den)`.

The mediant of two fractions always lies strictly between them, the
property the Stern-Brocot tree and Farey sequences are built on.

Rust: `exact::rational::Rational::mediant`
    """
    ...
