"""
Reaction kinetics, chemical thermodynamics and electrochemistry.  Rate laws for first- and second-order decay and the Arrhenius temperature dependence `k = A exp(−Eₐ/RT)`; the Gibbs free energy and its relation to the equilibrium constant, `ΔG° = −RT ln K`, with the van 't Hoff equation for how K moves with temperature; and Hess's law.  Electrochemistry covers the Nernst equation, cell potentials and Faraday electrolysis. Solution chemistry covers pH and pOH, molarity, dilution and osmotic pressure.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def arrhenius_rate(pre_exponential: float, activation_energy: float, temperature: float) -> float:
    """
Arrhenius equation: k = A × exp(-Ea / (RT))

Rust: `chemistry::arrhenius_rate`
    """
    ...

def half_life_first_order(rate_constant: float) -> float:
    """
First-order half-life: t½ = ln(2) / k

Rust: `chemistry::half_life_first_order`
    """
    ...

def concentration_first_order(c0: float, rate_constant: float, time: float) -> float:
    """
First-order concentration decay: `[A] = [A]₀ × e^(-kt)`

Rust: `chemistry::concentration_first_order`
    """
    ...

def concentration_second_order(c0: float, rate_constant: float, time: float) -> float:
    """
Second-order integrated rate law: `1/[A] = 1/[A]₀ + kt`, returns `[A]`

Rust: `chemistry::concentration_second_order`
    """
    ...

def reaction_rate(k: float, concentrations: list[float], orders: list[float]) -> float:
    """
General rate law: `r = k × Π([Ci]^ni)`

Rust: `chemistry::reaction_rate`
    """
    ...

def gibbs_free_energy(enthalpy: float, temperature: float, entropy: float) -> float:
    """
Gibbs free energy: ΔG = ΔH - TΔS

Rust: `chemistry::gibbs_free_energy`
    """
    ...

def equilibrium_constant_from_gibbs(delta_g: float, temperature: float) -> float:
    """
Equilibrium constant from Gibbs energy: K = exp(-ΔG / (RT))

Rust: `chemistry::equilibrium_constant_from_gibbs`
    """
    ...

def vant_hoff(k1: float, delta_h: float, t1: float, t2: float) -> float:
    """
Van't Hoff equation: ln(K2/K1) = -ΔH/R × (1/T2 - 1/T1), returns K2

Rust: `chemistry::vant_hoff`
    """
    ...

def hess_law(enthalpies: list[float], coefficients: list[float]) -> float:
    """
Hess's law: ΔH_rxn = Σ(ci × ΔHi)

Rust: `chemistry::hess_law`
    """
    ...

def nernst_potential(e_standard: float, temperature: float, n_electrons: float, reaction_quotient: float) -> float:
    """
Nernst equation: E = E° - (RT / (nF)) × ln(Q)

Rust: `chemistry::nernst_potential`
    """
    ...

def cell_potential(e_cathode: float, e_anode: float) -> float:
    """
Cell potential: E_cell = E_cathode - E_anode

Rust: `chemistry::cell_potential`
    """
    ...

def faraday_electrolysis(current: float, time: float, molar_mass: float, n_electrons: float) -> float:
    """
Faraday's law of electrolysis: m = (I × t × M) / (n × F)

Rust: `chemistry::faraday_electrolysis`
    """
    ...

def ph(h_concentration: float) -> float:
    """
pH = -log₁₀([H⁺])

Rust: `chemistry::ph`
    """
    ...

def poh(oh_concentration: float) -> float:
    """
pOH = -log₁₀([OH⁻])

Rust: `chemistry::poh`
    """
    ...

def h_from_ph(ph: float) -> float:
    """
[H⁺] = 10^(-pH)

Rust: `chemistry::h_from_ph`
    """
    ...

def osmotic_pressure(molarity: float, temperature: float, i_factor: float) -> float:
    """
Osmotic pressure: Π = iMRT

Rust: `chemistry::osmotic_pressure`
    """
    ...

def molarity(moles: float, volume_liters: float) -> float:
    """
Molarity: M = n / V

Rust: `chemistry::molarity`
    """
    ...

def dilution(c1: float, v1: float, v2: float) -> float:
    """
Dilution: C2 = C1 × V1 / V2

Rust: `chemistry::dilution`
    """
    ...

FARADAY: float
