"""
Newtonian mechanics: kinematics, dynamics, and the harmonic oscillator.  Linear and rotational motion under constant acceleration, forces and momentum, work, energy and power, collisions in one dimension from perfectly elastic to perfectly inelastic, moments of inertia for the standard bodies, and circular motion.  The oscillator section runs from the undamped period through the damped response -- damping ratio, logarithmic decrement, quality factor -- to the driven steady state and its resonance, and ends with the normal frequencies of two coupled oscillators. For the same problem solved numerically, or with more than two masses, see `resonance`.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.resonance.oscillator import Damping
from numeria.statistics.distributions import Normal
from numeria.math import Vec3

def displacement(initial_velocity: float, acceleration: float, time: float) -> float:
    """
Position after uniform acceleration: x = x0 + v0*t + 0.5*a*t^2

Rust: `classical::displacement`
    """
    ...

def velocity(initial_velocity: float, acceleration: float, time: float) -> float:
    """
Velocity after uniform acceleration: v = v0 + a*t

Rust: `classical::velocity`
    """
    ...

def velocity_squared(initial_velocity: float, acceleration: float, displacement: float) -> float:
    """
Velocity squared: v^2 = v0^2 + 2*a*d

Rust: `classical::velocity_squared`
    """
    ...

def position_3d(pos: Vec3 | Sequence[float], vel: Vec3 | Sequence[float], acc: Vec3 | Sequence[float], t: float) -> Vec3:
    """
3D position under constant acceleration.

Rust: `classical::position_3d`
    """
    ...

def velocity_3d(vel: Vec3 | Sequence[float], acc: Vec3 | Sequence[float], t: float) -> Vec3:
    """
3D velocity under constant acceleration.

Rust: `classical::velocity_3d`
    """
    ...

def projectile_range(speed: float, angle_rad: float, g: float) -> float:
    """
Range of a projectile on flat ground: R = v^2 * sin(2θ) / g

Rust: `classical::projectile_range`
    """
    ...

def projectile_max_height(speed: float, angle_rad: float, g: float) -> float:
    """
Maximum height of a projectile: H = v^2 * sin^2(θ) / (2g)

Rust: `classical::projectile_max_height`
    """
    ...

def projectile_time_of_flight(speed: float, angle_rad: float, g: float) -> float:
    """
Time of flight for a projectile on flat ground: T = 2v*sin(θ) / g

Rust: `classical::projectile_time_of_flight`
    """
    ...

def force(mass: float, acceleration: float) -> float:
    """
Force = mass * acceleration (Newton's second law)

Rust: `classical::force`
    """
    ...

def force_3d(mass: float, acceleration: Vec3 | Sequence[float]) -> Vec3:
    """
F = ma as vectors

Rust: `classical::force_3d`
    """
    ...

def acceleration(force: float, mass: float) -> float:
    """
Acceleration from force: a = F / m

Rust: `classical::acceleration`
    """
    ...

def weight(mass: float, g: float) -> float:
    """
Weight: W = m * g

Rust: `classical::weight`
    """
    ...

def momentum(mass: float, velocity: float) -> float:
    """
Linear momentum: p = m * v

Rust: `classical::momentum`
    """
    ...

def momentum_3d(mass: float, velocity: Vec3 | Sequence[float]) -> Vec3:
    """
3D momentum.

Rust: `classical::momentum_3d`
    """
    ...

def impulse(force: float, delta_t: float) -> float:
    """
Impulse: J = F * Δt

Rust: `classical::impulse`
    """
    ...

def elastic_collision_1d(m1: float, v1: float, m2: float, v2: float) -> tuple[float, float]:
    """
Final velocities after a 1D elastic collision between two masses.
Returns (v1_final, v2_final).

Rust: `classical::elastic_collision_1d`
    """
    ...

def inelastic_collision_1d(m1: float, v1: float, m2: float, v2: float) -> float:
    """
Final velocity after a perfectly inelastic collision (objects stick together).

Rust: `classical::inelastic_collision_1d`
    """
    ...

def coefficient_of_restitution(v1i: float, v2i: float, v1f: float, v2f: float) -> float:
    """
Coefficient of restitution: e = -(v1f - v2f) / (v1i - v2i)

Rust: `classical::coefficient_of_restitution`
    """
    ...

def kinetic_energy(mass: float, speed: float) -> float:
    """
Kinetic energy: KE = 0.5 * m * v^2

Rust: `classical::kinetic_energy`
    """
    ...

def potential_energy_gravity(mass: float, g: float, height: float) -> float:
    """
Gravitational potential energy: PE = m * g * h

Rust: `classical::potential_energy_gravity`
    """
    ...

def potential_energy_spring(spring_constant: float, displacement: float) -> float:
    """
Elastic potential energy: PE = 0.5 * k * x^2

Rust: `classical::potential_energy_spring`
    """
    ...

def work(force: float, displacement: float, angle_rad: float) -> float:
    """
Work: W = F * d * cos(θ)

Rust: `classical::work`
    """
    ...

def power(work: float, time: float) -> float:
    """
Power: P = W / t

Rust: `classical::power`
    """
    ...

def power_instantaneous(force: float, velocity: float) -> float:
    """
Power (instantaneous): P = F * v

Rust: `classical::power_instantaneous`
    """
    ...

def angular_velocity(delta_theta: float, delta_t: float) -> float:
    """
Angular velocity: ω = Δθ / Δt

Rust: `classical::angular_velocity`
    """
    ...

def angular_acceleration(delta_omega: float, delta_t: float) -> float:
    """
Angular acceleration: α = Δω / Δt

Rust: `classical::angular_acceleration`
    """
    ...

def torque(radius: float, force: float, angle_rad: float) -> float:
    """
Torque: τ = r * F * sin(θ)

Rust: `classical::torque`
    """
    ...

def torque_3d(r: Vec3 | Sequence[float], f: Vec3 | Sequence[float]) -> Vec3:
    """
Torque as cross product: τ = r × F

Rust: `classical::torque_3d`
    """
    ...

def moment_of_inertia_point(mass: float, radius: float) -> float:
    """
Moment of inertia of a point mass: I = m * r^2

Rust: `classical::moment_of_inertia_point`
    """
    ...

def moment_of_inertia_solid_sphere(mass: float, radius: float) -> float:
    """
Moment of inertia of a solid sphere: I = (2/5) * m * r^2

Rust: `classical::moment_of_inertia_solid_sphere`
    """
    ...

def moment_of_inertia_solid_cylinder(mass: float, radius: float) -> float:
    """
Moment of inertia of a solid cylinder about its axis: I = (1/2) * m * r^2

Rust: `classical::moment_of_inertia_solid_cylinder`
    """
    ...

def rotational_kinetic_energy(moment_of_inertia: float, angular_velocity: float) -> float:
    """
Rotational kinetic energy: KE = 0.5 * I * ω^2

Rust: `classical::rotational_kinetic_energy`
    """
    ...

def angular_momentum(moment_of_inertia: float, angular_velocity: float) -> float:
    """
Angular momentum: L = I * ω

Rust: `classical::angular_momentum`
    """
    ...

def centripetal_acceleration(speed: float, radius: float) -> float:
    """
Centripetal acceleration: a = v^2 / r

Rust: `classical::centripetal_acceleration`
    """
    ...

def centripetal_force(mass: float, speed: float, radius: float) -> float:
    """
Centripetal force: F = m * v^2 / r

Rust: `classical::centripetal_force`
    """
    ...

def friction_force(coefficient: float, normal_force: float) -> float:
    """
Friction force: f = μ * N

Rust: `classical::friction_force`
    """
    ...

def shm_period_spring(mass: float, spring_constant: float) -> float:
    """
Period of a mass-spring system: T = 2π * sqrt(m / k)

Rust: `classical::shm_period_spring`
    """
    ...

def shm_period_pendulum(length: float, g: float) -> float:
    """
Period of a simple pendulum: T = 2π * sqrt(L / g)

Rust: `classical::shm_period_pendulum`
    """
    ...

def shm_position(amplitude: float, angular_freq: float, time: float, phase: float) -> float:
    """
Position of SHM: x(t) = A * cos(ωt + φ)

Rust: `classical::shm_position`
    """
    ...

def shm_velocity(amplitude: float, angular_freq: float, time: float, phase: float) -> float:
    """
Velocity of SHM: v(t) = -A * ω * sin(ωt + φ)

Rust: `classical::shm_velocity`
    """
    ...

def damped_frequency(natural_freq: float, damping_ratio: float) -> float:
    """
Damped angular frequency: ωd = ω₀√(1 - ζ²), returns 0 if overdamped (ζ ≥ 1)

Rust: `classical::damped_frequency`
    """
    ...

def damped_amplitude(initial_amplitude: float, damping_coeff: float, time: float) -> float:
    """
Damped amplitude: A(t) = A₀ × e^(-γt)

Rust: `classical::damped_amplitude`
    """
    ...

def damped_position(amplitude: float, damping_coeff: float, angular_freq: float, time: float, phase: float) -> float:
    """
Damped oscillation position: x(t) = A₀e^(-γt)cos(ωdt + φ)

Rust: `classical::damped_position`
    """
    ...

def damping_ratio(damping_coeff: float, mass: float, spring_constant: float) -> float:
    """
Damping ratio: ζ = c / (2√(mk))

Rust: `classical::damping_ratio`
    """
    ...

def critical_damping(mass: float, spring_constant: float) -> float:
    """
Critical damping coefficient: c_crit = 2√(mk)

Rust: `classical::critical_damping`
    """
    ...

def logarithmic_decrement(damping_ratio: float) -> float:
    """
Logarithmic decrement: δ = 2πζ / √(1 - ζ²)

Rust: `classical::logarithmic_decrement`
    """
    ...

def quality_factor(damping_ratio: float) -> float:
    """
Quality factor: Q = 1 / (2ζ)

Rust: `classical::quality_factor`
    """
    ...

def decay_time(damping_coeff: float) -> float:
    """
Decay time constant: τ = 1/γ (time for amplitude to drop to 1/e)

Rust: `classical::decay_time`
    """
    ...

def driven_amplitude(f0: float, omega: float, omega0: float, gamma: float) -> float:
    """
Driven oscillation amplitude: A = f₀ / √((ω₀²-ω²)² + (2γω)²)
where f₀ = F₀/m (driving force per unit mass)

Rust: `classical::driven_amplitude`
    """
    ...

def driven_phase(omega: float, omega0: float, gamma: float) -> float:
    """
Phase lag of driven oscillation: φ = atan2(2γω, ω₀²-ω²)

Rust: `classical::driven_phase`
    """
    ...

def resonance_frequency(natural_freq: float, damping_coeff: float) -> float:
    """
Resonance frequency: ωr = √(ω₀² - 2γ²), returns 0 if overdamped

Rust: `classical::resonance_frequency`
    """
    ...

def resonance_amplitude(f0: float, omega0: float, gamma: float) -> float:
    """
Peak amplitude at resonance: A_max = f₀ / (2γ√(ω₀² - γ²))

Rust: `classical::resonance_amplitude`
    """
    ...

def coupled_normal_frequencies(k: float, k_coupling: float, m: float) -> tuple[float, float]:
    """
Normal-mode frequencies of two identical masses coupled by a spring:
ω₁ = √(k/m), ω₂ = √((k + 2k_c)/m)

Rust: `classical::coupled_normal_frequencies`
    """
    ...

def beat_frequency_coupled(freq1: float, freq2: float) -> float:
    """
Beat frequency of coupled oscillators: f_beat = |f1 - f2|

Rust: `classical::beat_frequency_coupled`
    """
    ...
