"""
Shannon information: entropy, divergence, and channel capacity.  Entropy in bits and in nats, the maximum-entropy bound for a given alphabet, and the entropy rate. Then the relations between two distributions: cross entropy, Kullback-Leibler divergence, and the Jensen-Shannon divergence -- which unlike KL is symmetric and bounded, which is why it is the one that behaves like a distance.  Mutual information and conditional entropy connect the two, and the binary entropy function gives the capacity of a binary symmetric channel as `C = 1 − H₂(p)`. Fisher information and the Cramér-Rao bound cover the estimation side.  For codes that approach these limits see `codes`.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def shannon_entropy(probabilities: list[float]) -> float:
    """
Shannon information: entropy, divergence, and channel capacity.

Entropy in bits and in nats, the maximum-entropy bound for a given
alphabet, and the entropy rate. Then the relations between two
distributions: cross entropy, Kullback-Leibler divergence, and the
Jensen-Shannon divergence -- which unlike KL is symmetric and bounded,
which is why it is the one that behaves like a distance.

Mutual information and conditional entropy connect the two, and the
binary entropy function gives the capacity of a binary symmetric
channel as `C = 1 − H₂(p)`. Fisher information and the Cramér-Rao
bound cover the estimation side.

For codes that approach these limits see `codes`.
H = -Σ pi × log₂(pi), skipping pi = 0.

Rust: `information_theory::shannon_entropy`
    """
    ...

def shannon_entropy_nats(probabilities: list[float]) -> float:
    """
H = -Σ pi × ln(pi), in nats.

Rust: `information_theory::shannon_entropy_nats`
    """
    ...

def max_entropy(n_symbols: int) -> float:
    """
H_max = log₂(N) for N equally likely symbols.

Rust: `information_theory::max_entropy`
    """
    ...

def entropy_rate(conditional_entropy: float) -> float:
    """
Identity function returning the conditional entropy value. Provided for API
completeness so callers can be explicit about what the quantity represents.

Rust: `information_theory::entropy_rate`
    """
    ...

def kl_divergence(p: list[float], q: list[float]) -> float:
    """
D_KL(P||Q) = Σ pi × ln(pi/qi), skipping pi = 0.

Rust: `information_theory::kl_divergence`
    """
    ...

def js_divergence(p: list[float], q: list[float]) -> float:
    """
Jensen-Shannon divergence: JSD(P||Q) = (D_KL(P||M) + D_KL(Q||M)) / 2
where M = (P + Q) / 2.

Rust: `information_theory::js_divergence`
    """
    ...

def cross_entropy(p: list[float], q: list[float]) -> float:
    """
H(P, Q) = -Σ pi × log₂(qi).

Rust: `information_theory::cross_entropy`
    """
    ...

def mutual_information(joint: list[float], marginal_x: list[float], marginal_y: list[float], nx: int, ny: int) -> float:
    """
I(X;Y) = Σ p(x,y) × ln(p(x,y) / (p(x) × p(y))).
`joint` is an nx×ny row-major probability table.

Rust: `information_theory::mutual_information`
    """
    ...

def conditional_entropy(joint: list[float], marginal_condition: list[float], nx: int, ny: int) -> float:
    """
H(Y|X) = -Σ p(x,y) × ln(p(y|x)).
`joint` is an nx×ny row-major probability table, `marginal_condition` are
the marginal probabilities p(x).

Rust: `information_theory::conditional_entropy`
    """
    ...

def binary_entropy(p: float) -> float:
    """
H(p) = -p × log₂(p) - (1-p) × log₂(1-p).

Rust: `information_theory::binary_entropy`
    """
    ...

def binary_symmetric_channel_capacity(error_prob: float) -> float:
    """
C = 1 - H(p) for a binary symmetric channel with crossover probability p.

Rust: `information_theory::binary_symmetric_channel_capacity`
    """
    ...

def compression_ratio(original_bits: float, compressed_bits: float) -> float:
    """
R = original_bits / compressed_bits.

Rust: `information_theory::compression_ratio`
    """
    ...

def redundancy(entropy: float, max_entropy: float) -> float:
    """
D = 1 - H / H_max.

Rust: `information_theory::redundancy`
    """
    ...

def efficiency(entropy: float, avg_code_length: float) -> float:
    """
η = H / L where L is average code length.

Rust: `information_theory::efficiency`
    """
    ...

def fisher_information_gaussian(sigma: float) -> float:
    """
I(μ) = 1/σ² for a Gaussian when estimating the mean.

Rust: `information_theory::fisher_information_gaussian`
    """
    ...

def cramer_rao_bound(fisher_info: float) -> float:
    """
Cramér-Rao lower bound: var(θ̂) ≥ 1 / I(θ).

Rust: `information_theory::cramer_rao_bound`
    """
    ...
