"""
Reactor physics: criticality, neutron diffusion, and shielding.  Criticality through the six-factor formula and `k_eff`, with reactivity and the reactor period. Neutron transport in diffusion theory: the diffusion coefficient and length, migration length, thermal utilization, and the flux in a slab.  Cross sections and reaction rates convert between microscopic and macroscopic pictures, including the 1/v absorption law. Operations covers reactor power, burnup and decay heat.  Shielding closes with attenuation, half- and tenth-value layers, and the buildup factor that corrects the exponential law for scattered photons -- the correction that matters, since ignoring it underestimates the dose behind a thick shield.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def k_effective(production_rate: float, loss_rate: float) -> float:
    """
Effective multiplication factor: k_eff = production_rate / loss_rate

Rust: `neutronics::k_effective`
    """
    ...

def reactivity(k_eff: float) -> float:
    """
Reactivity: ρ = (k - 1) / k

Rust: `neutronics::reactivity`
    """
    ...

def doubling_time(k_eff: float, neutron_lifetime: float) -> float:
    """
Doubling time for supercritical reactor: T = l × ln(2) / (k - 1)
Returns f64::INFINITY if k_eff <= 1.0 (not supercritical).

Rust: `neutronics::doubling_time`
    """
    ...

def six_factor_formula(eta: float, f: float, p: float, epsilon: float, p_fnl: float, p_tnl: float) -> float:
    """
Six-factor formula: k_eff = η × f × p × ε × P_FNL × P_TNL

Rust: `neutronics::six_factor_formula`
    """
    ...

def reproduction_factor(nu: float, sigma_f: float, sigma_a: float) -> float:
    """
Reproduction factor: η = ν × σ_f / σ_a

Rust: `neutronics::reproduction_factor`
    """
    ...

def diffusion_coefficient(transport_mfp: float) -> float:
    """
Diffusion coefficient: D = λ_tr / 3

Rust: `neutronics::diffusion_coefficient`
    """
    ...

def diffusion_length(diffusion_coeff: float, absorption_xs: float) -> float:
    """
Diffusion length: L = √(D / Σ_a)

Rust: `neutronics::diffusion_length`
    """
    ...

def migration_length(diffusion_length: float, slowing_down_length: float) -> float:
    """
Migration length: M = √(L² + τ) where τ is the Fermi age (slowing-down area)

Rust: `neutronics::migration_length`
    """
    ...

def thermal_utilization(sigma_a_fuel: float, sigma_a_total: float) -> float:
    """
Thermal utilization factor: f = Σ_a_fuel / Σ_a_total

Rust: `neutronics::thermal_utilization`
    """
    ...

def neutron_flux_slab(source: float, diffusion_coeff: float, sigma_a: float, x: float, half_thickness: float) -> float:
    """
Neutron flux in a slab reactor with uniform source:
φ(x) = (S / Σ_a) × (1 - cosh(x/L) / cosh(a/L))
where L = √(D/Σ_a) and a = half-thickness (extrapolated).

Rust: `neutronics::neutron_flux_slab`
    """
    ...

def microscopic_to_macroscopic(micro_xs: float, number_density: float) -> float:
    """
Macroscopic cross section from microscopic: Σ = N × σ

Rust: `neutronics::microscopic_to_macroscopic`
    """
    ...

def number_density(density: float, molar_mass: float) -> float:
    """
Number density from bulk density and molar mass: N = ρ × N_A / M

Rust: `neutronics::number_density`
    """
    ...

def mean_free_path_neutron(macro_xs: float) -> float:
    """
Mean free path for neutrons: λ = 1 / Σ

Rust: `neutronics::mean_free_path_neutron`
    """
    ...

def reaction_rate_neutron(macro_xs: float, flux: float) -> float:
    """
Neutron reaction rate: R = Σ × φ

Rust: `neutronics::reaction_rate_neutron`
    """
    ...

def one_over_v_xs(sigma_0: float, e_0: float, energy: float) -> float:
    """
1/v cross section law for thermal neutrons: σ(E) = σ₀ × √(E₀ / E)

Rust: `neutronics::one_over_v_xs`
    """
    ...

def reactor_power(fission_rate: float, energy_per_fission: float) -> float:
    """
Reactor thermal power: P = R_f × E_f

Rust: `neutronics::reactor_power`
    """
    ...

def burnup(power: float, time: float, mass_heavy_metal: float) -> float:
    """
Burnup: BU = P × t / M (MWd/kg when units are consistent)

Rust: `neutronics::burnup`
    """
    ...

def decay_heat_fraction(time_after_shutdown: float) -> float:
    """
Decay heat fraction (Way-Wigner approximation for long prior operation):
P/P₀ ≈ 0.066 × t^(-0.2)

Rust: `neutronics::decay_heat_fraction`
    """
    ...

def transmission_factor(macro_xs: float, thickness: float) -> float:
    """
Transmission factor (uncollided): I/I₀ = e^(-Σx)

Rust: `neutronics::transmission_factor`
    """
    ...

def half_value_layer(macro_xs: float) -> float:
    """
Half-value layer: HVL = ln(2) / Σ

Rust: `neutronics::half_value_layer`
    """
    ...

def tenth_value_layer(macro_xs: float) -> float:
    """
Tenth-value layer: TVL = ln(10) / Σ

Rust: `neutronics::tenth_value_layer`
    """
    ...

def buildup_factor_approx(macro_xs: float, thickness: float) -> float:
    """
Linear buildup factor approximation for thin shields: B ≈ 1 + Σx

Rust: `neutronics::buildup_factor_approx`
    """
    ...
