"""
Geometric and wave optics.  Refraction by Snell's law, the critical angle for total internal reflection, and the Brewster angle at which reflected light is fully polarized. Imaging through the thin-lens and mirror equations, magnification, lens power, combined focal lengths and the lensmaker's radius of curvature.  Wave optics covers single-slit minima, double-slit maxima, the grating equation, thin-film interference, and the Rayleigh resolution criterion `θ = 1.22 λ/D`. Malus's law closes it.  For Gaussian beams, fibre optics and ray transfer matrices see `photonics`.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def snells_law(n1: float, angle1_rad: float, n2: float) -> Optional[float]:
    """
Snell's law: n1 * sin(θ1) = n2 * sin(θ2) → θ2 = asin(n1 * sin(θ1) / n2)
Returns the refraction angle in radians, or None for total internal reflection.

Rust: `optics::snells_law`
    """
    ...

def critical_angle(n1: float, n2: float) -> Optional[float]:
    """
Critical angle for total internal reflection: θ_c = asin(n2 / n1)
Only valid when n1 > n2. Returns None otherwise.

Rust: `optics::critical_angle`
    """
    ...

def brewster_angle(n1: float, n2: float) -> float:
    """
Brewster's angle: θ_B = atan(n2 / n1)

Rust: `optics::brewster_angle`
    """
    ...

def refractive_index(speed_in_medium: float) -> float:
    """
Index of refraction: n = c / v

Rust: `optics::refractive_index`
    """
    ...

def speed_in_medium(refractive_index: float) -> float:
    """
Speed of light in a medium: v = c / n

Rust: `optics::speed_in_medium`
    """
    ...

def image_distance(focal_length: float, object_distance: float) -> float:
    """
Mirror/thin lens equation: 1/f = 1/d_o + 1/d_i → d_i = f*d_o / (d_o - f)

Rust: `optics::image_distance`
    """
    ...

def magnification(image_distance: float, object_distance: float) -> float:
    """
Magnification: m = -d_i / d_o

Rust: `optics::magnification`
    """
    ...

def magnification_from_heights(image_height: float, object_height: float) -> float:
    """
Magnification from image and object heights: m = h_i / h_o

Rust: `optics::magnification_from_heights`
    """
    ...

def lens_focal_length(n: float, r1: float, r2: float) -> float:
    """
Lens maker's equation: 1/f = (n-1) * (1/R1 - 1/R2)

Rust: `optics::lens_focal_length`
    """
    ...

def lens_power(focal_length: float) -> float:
    """
Power of a lens: P = 1/f (in diopters when f is in meters)

Rust: `optics::lens_power`
    """
    ...

def combined_focal_length(f1: float, f2: float) -> float:
    """
Combined focal length of two thin lenses in contact: 1/f = 1/f1 + 1/f2

Rust: `optics::combined_focal_length`
    """
    ...

def radius_of_curvature(focal_length: float) -> float:
    """
Mirror radius of curvature: R = 2f

Rust: `optics::radius_of_curvature`
    """
    ...

def single_slit_minimum(order: int, wavelength: float, slit_width: float) -> Optional[float]:
    """
Single slit diffraction minima: a * sin(θ) = m * λ → θ = asin(m * λ / a)
Returns angle in radians for the m-th minimum.

Rust: `optics::single_slit_minimum`
    """
    ...

def double_slit_maximum(order: int, wavelength: float, slit_separation: float) -> Optional[float]:
    """
Double slit maxima: d * sin(θ) = m * λ → θ = asin(m * λ / d)

Rust: `optics::double_slit_maximum`
    """
    ...

def diffraction_grating_angle(order: int, wavelength: float, grating_spacing: float) -> Optional[float]:
    """
Diffraction grating: d * sin(θ) = m * λ

Rust: `optics::diffraction_grating_angle`
    """
    ...

def rayleigh_resolution(wavelength: float, aperture_diameter: float) -> float:
    """
Rayleigh criterion (angular resolution): θ = 1.22 * λ / D

Rust: `optics::rayleigh_resolution`
    """
    ...

def thin_film_constructive_thickness(order: int, wavelength: float, film_index: float) -> float:
    """
Thin film interference (constructive, normal incidence):
2 * n * t = (m + 0.5) * λ for reflection with one phase change

Rust: `optics::thin_film_constructive_thickness`
    """
    ...

def constructive_path_diff(order: int, wavelength: float) -> float:
    """
Path difference for constructive interference: Δ = m * λ

Rust: `optics::constructive_path_diff`
    """
    ...

def destructive_path_diff(order: int, wavelength: float) -> float:
    """
Path difference for destructive interference: Δ = (m + 0.5) * λ

Rust: `optics::destructive_path_diff`
    """
    ...

def malus_law(initial_intensity: float, angle_rad: float) -> float:
    """
Malus's law: I = I_0 * cos^2(θ)

Rust: `optics::malus_law`
    """
    ...
