"""
Thermodynamics: gases, heat transfer, cycles and phase change.  The ideal gas law in each of its four solved forms, and the kinetic picture behind it -- average kinetic energy, RMS speed, mean free path. Work and entropy change along isothermal, isobaric and adiabatic paths.  Heat transfer by all three mechanisms: Fourier conduction (with an explicit 1-D stepper and its stability limit), Newton's law of cooling and convection, and radiative exchange. The dimensionless groups that classify convection -- Grashof, Rayleigh, Prandtl, Nusselt, Biot -- are here too.  Cycles through the Carnot efficiency and the coefficients of performance for refrigerators and heat pumps; phase change through latent heat, Clausius-Clapeyron, boiling-point elevation, freezing-point depression, and wet-steam quality. Temperature scale conversions round it out.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def ideal_gas_pressure(moles: float, temperature: float, volume: float) -> float:
    """
Ideal gas law: PV = nRT. Solve for pressure: P = nRT / V

Rust: `thermodynamics::ideal_gas_pressure`
    """
    ...

def ideal_gas_volume(moles: float, temperature: float, pressure: float) -> float:
    """
Solve for volume: V = nRT / P

Rust: `thermodynamics::ideal_gas_volume`
    """
    ...

def ideal_gas_temperature(pressure: float, volume: float, moles: float) -> float:
    """
Solve for temperature: T = PV / (nR)

Rust: `thermodynamics::ideal_gas_temperature`
    """
    ...

def ideal_gas_moles(pressure: float, volume: float, temperature: float) -> float:
    """
Number of moles: n = PV / (RT)

Rust: `thermodynamics::ideal_gas_moles`
    """
    ...

def average_kinetic_energy(temperature: float) -> float:
    """
Average kinetic energy of a gas molecule: KE = (3/2) * k_B * T

Rust: `thermodynamics::average_kinetic_energy`
    """
    ...

def rms_speed(temperature: float, molecular_mass: float) -> float:
    """
RMS speed of gas molecules: v_rms = sqrt(3 * k_B * T / m)

Rust: `thermodynamics::rms_speed`
    """
    ...

def mean_free_path(molecular_diameter: float, number_density: float) -> float:
    """
Mean free path: λ = 1 / (√2 * π * d^2 * n/V)

Rust: `thermodynamics::mean_free_path`
    """
    ...

def heat_transfer(mass: float, specific_heat: float, delta_temp: float) -> float:
    """
Heat transfer: Q = m * c * ΔT

Rust: `thermodynamics::heat_transfer`
    """
    ...

def heat_conduction_rate(conductivity: float, area: float, delta_temp: float, thickness: float) -> float:
    """
Heat conduction (Fourier's law): Q/t = k * A * ΔT / d

Rust: `thermodynamics::heat_conduction_rate`
    """
    ...

def heat_radiation_power(emissivity: float, area: float, temperature: float) -> float:
    """
Heat radiation (Stefan-Boltzmann law): P = ε * σ * A * T^4

Rust: `thermodynamics::heat_radiation_power`
    """
    ...

def net_radiation_power(emissivity: float, area: float, t_hot: float, t_cold: float) -> float:
    """
Net radiative heat transfer: P = ε * σ * A * (T_hot^4 - T_cold^4)

Rust: `thermodynamics::net_radiation_power`
    """
    ...

def newton_cooling(t_initial: float, t_environment: float, cooling_constant: float, time: float) -> float:
    """
Newton's law of cooling: dT/dt = -k * (T - T_env)
Returns temperature at time t: T(t) = T_env + (T0 - T_env) * e^(-k*t)

Rust: `thermodynamics::newton_cooling`
    """
    ...

def work_isothermal(moles: float, temperature: float, v1: float, v2: float) -> float:
    """
Work done by an ideal gas during isothermal expansion: W = nRT * ln(V2/V1)

Rust: `thermodynamics::work_isothermal`
    """
    ...

def work_isobaric(pressure: float, delta_v: float) -> float:
    """
Work done during isobaric (constant pressure) process: W = P * ΔV

Rust: `thermodynamics::work_isobaric`
    """
    ...

def work_adiabatic(p1: float, v1: float, p2: float, v2: float, gamma: float) -> float:
    """
Work done during adiabatic process: W = (P1*V1 - P2*V2) / (γ - 1)

Rust: `thermodynamics::work_adiabatic`
    """
    ...

def adiabatic_final_pressure(p1: float, v1: float, v2: float, gamma: float) -> float:
    """
Adiabatic relation: P1 * V1^γ = P2 * V2^γ → P2 = P1 * (V1/V2)^γ

Rust: `thermodynamics::adiabatic_final_pressure`
    """
    ...

def entropy_change_isothermal(heat: float, temperature: float) -> float:
    """
Entropy change for heat transfer at constant temperature: ΔS = Q / T

Rust: `thermodynamics::entropy_change_isothermal`
    """
    ...

def entropy_change_ideal_gas(moles: float, cv: float, t1: float, t2: float, v1: float, v2: float) -> float:
    """
Entropy change for an ideal gas: ΔS = n*Cv*ln(T2/T1) + n*R*ln(V2/V1)

Rust: `thermodynamics::entropy_change_ideal_gas`
    """
    ...

def carnot_efficiency(t_cold: float, t_hot: float) -> float:
    """
Carnot efficiency: η = 1 - T_cold / T_hot

Rust: `thermodynamics::carnot_efficiency`
    """
    ...

def thermal_efficiency(work: float, heat_input: float) -> float:
    """
Thermal efficiency: η = W / Q_hot

Rust: `thermodynamics::thermal_efficiency`
    """
    ...

def cop_refrigerator(heat_removed: float, work: float) -> float:
    """
Coefficient of performance (refrigerator): COP = Q_cold / W

Rust: `thermodynamics::cop_refrigerator`
    """
    ...

def cop_heat_pump(heat_delivered: float, work: float) -> float:
    """
Coefficient of performance (heat pump): COP = Q_hot / W

Rust: `thermodynamics::cop_heat_pump`
    """
    ...

def latent_heat(mass: float, specific_latent_heat: float) -> float:
    """
Heat for phase change: Q = m * L (latent heat)

Rust: `thermodynamics::latent_heat`
    """
    ...

def clausius_clapeyron(p1: float, t1: float, t2: float, molar_latent_heat: float) -> float:
    """
Clausius-Clapeyron (approximate): ln(P2/P1) = (L/R) * (1/T1 - 1/T2)
Returns P2 given P1, T1, T2, and molar latent heat L.

Rust: `thermodynamics::clausius_clapeyron`
    """
    ...

def convective_heat_rate(h: float, area: float, delta_temp: float) -> float:
    """
Newton's law of convection: Q/t = h×A×ΔT

Rust: `thermodynamics::convective_heat_rate`
    """
    ...

def thermal_diffusivity(conductivity: float, density: float, specific_heat: float) -> float:
    """
Thermal diffusivity: α = k/(ρ×cₚ)

Rust: `thermodynamics::thermal_diffusivity`
    """
    ...

def grashof_number(g: float, beta: float, delta_temp: float, length: float, kinematic_viscosity: float) -> float:
    """
Grashof number: Gr = gβΔTL³/ν²

Rust: `thermodynamics::grashof_number`
    """
    ...

def rayleigh_number(grashof: float, prandtl: float) -> float:
    """
Rayleigh number: Ra = Gr × Pr

Rust: `thermodynamics::rayleigh_number`
    """
    ...

def prandtl_number(kinematic_viscosity: float, thermal_diffusivity: float) -> float:
    """
Prandtl number: Pr = ν/α

Rust: `thermodynamics::prandtl_number`
    """
    ...

def nusselt_number(h: float, length: float, conductivity: float) -> float:
    """
Nusselt number: Nu = hL/k

Rust: `thermodynamics::nusselt_number`
    """
    ...

def biot_number(h: float, length: float, conductivity: float) -> float:
    """
Biot number: Bi = hL/k (external convection vs internal conduction)

Rust: `thermodynamics::biot_number`
    """
    ...

def heat_equation_step_1d(temperatures: MutableSequence[float], dx: float, dt: float, diffusivity: float) -> None:
    """
Explicit finite difference: T_i^(n+1) = T_i^n + α×dt/dx² × (T_(i+1) - 2T_i + T_(i-1))
Fixed boundary conditions (first and last elements unchanged).

Rust: `thermodynamics::heat_equation_step_1d`
    """
    ...

def heat_equation_stability(dx: float, diffusivity: float) -> float:
    """
Maximum stable time step for explicit finite difference: dt_max = dx²/(2α)

Rust: `thermodynamics::heat_equation_stability`
    """
    ...

def wien_displacement(temperature: float) -> float:
    """
Wien's displacement law: λ_max = b/T where b = 2.898e-3 m·K

Rust: `thermodynamics::wien_displacement`
    """
    ...

def spectral_exitance(wavelength: float, temperature: float) -> float:
    """
Planck's law: M = (2πhc²/λ⁵) × 1/(e^(hc/λkT) - 1)

Rust: `thermodynamics::spectral_exitance`
    """
    ...

def radiative_equilibrium_temperature(luminosity: float, distance: float, albedo: float) -> float:
    """
Radiative equilibrium temperature: T = ((L(1-a))/(16πσd²))^(1/4)

Rust: `thermodynamics::radiative_equilibrium_temperature`
    """
    ...

def celsius_to_kelvin(c: float) -> float:
    """
Celsius to Kelvin: K = C + 273.15

Rust: `thermodynamics::celsius_to_kelvin`
    """
    ...

def kelvin_to_celsius(k: float) -> float:
    """
Kelvin to Celsius: C = K - 273.15

Rust: `thermodynamics::kelvin_to_celsius`
    """
    ...

def celsius_to_fahrenheit(c: float) -> float:
    """
Celsius to Fahrenheit: F = C × 9/5 + 32

Rust: `thermodynamics::celsius_to_fahrenheit`
    """
    ...

def fahrenheit_to_celsius(f: float) -> float:
    """
Fahrenheit to Celsius: C = (F - 32) × 5/9

Rust: `thermodynamics::fahrenheit_to_celsius`
    """
    ...

def fahrenheit_to_kelvin(f: float) -> float:
    """
Fahrenheit to Kelvin via Celsius

Rust: `thermodynamics::fahrenheit_to_kelvin`
    """
    ...

def kelvin_to_fahrenheit(k: float) -> float:
    """
Kelvin to Fahrenheit via Celsius

Rust: `thermodynamics::kelvin_to_fahrenheit`
    """
    ...

def celsius_to_rankine(c: float) -> float:
    """
Celsius to Rankine: R = (C + 273.15) × 9/5

Rust: `thermodynamics::celsius_to_rankine`
    """
    ...

def rankine_to_celsius(r: float) -> float:
    """
Rankine to Celsius: C = R × 5/9 - 273.15

Rust: `thermodynamics::rankine_to_celsius`
    """
    ...

def boiling_point_elevation(kb: float, molality: float) -> float:
    """
Boiling point elevation: ΔTb = Kb × m

Rust: `thermodynamics::boiling_point_elevation`
    """
    ...

def freezing_point_depression(kf: float, molality: float) -> float:
    """
Freezing point depression: ΔTf = Kf × m

Rust: `thermodynamics::freezing_point_depression`
    """
    ...

def saturation_pressure(t: float, a: float, b: float, c: float) -> float:
    """
Antoine equation: log10(P) = A - B/(C+T), returns P

Rust: `thermodynamics::saturation_pressure`
    """
    ...

def heat_of_vaporization_trouton(boiling_point_k: float) -> float:
    """
Trouton's rule: ΔHvap ≈ 88 × Tb (J/mol)

Rust: `thermodynamics::heat_of_vaporization_trouton`
    """
    ...

def superheat_degree(actual_temp: float, saturation_temp: float) -> float:
    """
Degree of superheat: ΔT = T_actual - T_sat

Rust: `thermodynamics::superheat_degree`
    """
    ...

def subcool_degree(saturation_temp: float, actual_temp: float) -> float:
    """
Degree of subcooling: ΔT = T_sat - T_actual

Rust: `thermodynamics::subcool_degree`
    """
    ...

def quality(mass_vapor: float, mass_total: float) -> float:
    """
Steam quality (dryness fraction): x = m_vapor / m_total

Rust: `thermodynamics::quality`
    """
    ...

def specific_enthalpy_wet(hf: float, hfg: float, quality: float) -> float:
    """
Specific enthalpy of wet steam: h = hf + x × hfg

Rust: `thermodynamics::specific_enthalpy_wet`
    """
    ...
