"""
Wave propagation: mechanical, acoustic and seismic.  The kinematic relations (`v = fλ` and the wavenumber-frequency pair), displacement, energy density and intensity, and the inverse-square falloff of a spherical wave. The Doppler effect in both classical and relativistic forms, with the Mach cone angle for supersonic sources.  Standing waves on strings and in open and closed pipes, beats, and superposition. Boundaries are handled by impedance: the reflection and transmission coefficients follow from the impedance mismatch, which is also why they carry a sign.  Acoustics covers the speed of sound in a gas, sound pressure level and the decibel scale, and absorption and penetration depth. Seismology covers P-, S-, Rayleigh and Love wave speeds. Diffraction closes with the Fraunhofer single-slit pattern, the Airy disk radius and the Fresnel number.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def wave_speed(frequency: float, wavelength: float) -> float:
    """
Wave speed: v = f * λ

Rust: `waves::wave_speed`
    """
    ...

def wavelength(speed: float, frequency: float) -> float:
    """
Wavelength from speed and frequency: λ = v / f

Rust: `waves::wavelength`
    """
    ...

def frequency(speed: float, wavelength: float) -> float:
    """
Frequency from speed and wavelength: f = v / λ

Rust: `waves::frequency`
    """
    ...

def period(frequency: float) -> float:
    """
Period: T = 1 / f

Rust: `waves::period`
    """
    ...

def angular_frequency(frequency: float) -> float:
    """
Angular frequency: ω = 2πf

Rust: `waves::angular_frequency`
    """
    ...

def wave_number(wavelength: float) -> float:
    """
Wave number: k = 2π / λ

Rust: `waves::wave_number`
    """
    ...

def wave_displacement(amplitude: float, wave_number: float, x: float, angular_freq: float, t: float, phase: float) -> float:
    """
Transverse wave displacement: y(x,t) = A * sin(kx - ωt + φ)

Rust: `waves::wave_displacement`
    """
    ...

def wave_energy_density(amplitude: float, frequency: float, linear_density: float) -> float:
    """
Energy of a wave (proportional): E ∝ A^2 * f^2
Returns the energy for a given amplitude and frequency (with a constant factor).

Rust: `waves::wave_energy_density`
    """
    ...

def wave_intensity(power: float, area: float) -> float:
    """
Intensity of a wave: I = P / A (power per unit area)

Rust: `waves::wave_intensity`
    """
    ...

def spherical_wave_intensity(power: float, distance: float) -> float:
    """
Intensity falls off with distance (spherical wave): I = P / (4πr^2)

Rust: `waves::spherical_wave_intensity`
    """
    ...

def decibel_level(intensity: float, reference_intensity: float) -> float:
    """
Decibel level: β = 10 * log10(I / I_0)

Rust: `waves::decibel_level`
    """
    ...

def intensity_from_decibels(decibels: float, reference_intensity: float) -> float:
    """
Intensity from decibel level: I = I_0 * 10^(β/10)

Rust: `waves::intensity_from_decibels`
    """
    ...

def doppler_frequency(source_freq: float, wave_speed: float, observer_velocity: float, source_velocity: float) -> float:
    """
Doppler effect (sound): f' = f * (v + v_observer) / (v + v_source)
Convention: positive v_observer = observer moving toward source,
positive v_source = source moving away from observer.

Rust: `waves::doppler_frequency`
    """
    ...

def relativistic_doppler(source_freq: float, beta: float) -> float:
    """
Relativistic Doppler effect: f' = f * sqrt((1 + β) / (1 - β))
where β = v/c, positive β = approaching.

Rust: `waves::relativistic_doppler`
    """
    ...

def mach_cone_angle(mach: float) -> float:
    """
Mach cone half-angle: sin(θ) = v_sound / v_object = 1/M

Rust: `waves::mach_cone_angle`
    """
    ...

def standing_wave_frequency(harmonic: int, wave_speed: float, length: float) -> float:
    """
Frequencies of standing waves on a string fixed at both ends:
f_n = n * v / (2L)

Rust: `waves::standing_wave_frequency`
    """
    ...

def string_fundamental(length: float, tension: float, linear_density: float) -> float:
    """
Fundamental frequency of a string: f = (1/(2L)) * sqrt(T/μ)
T = tension, μ = linear mass density

Rust: `waves::string_fundamental`
    """
    ...

def open_pipe_frequency(harmonic: int, sound_speed: float, length: float) -> float:
    """
Standing waves in an open pipe: f_n = n * v / (2L) (all harmonics)

Rust: `waves::open_pipe_frequency`
    """
    ...

def closed_pipe_frequency(odd_harmonic: int, sound_speed: float, length: float) -> float:
    """
Standing waves in a closed pipe: f_n = n * v / (4L) (odd harmonics only)

Rust: `waves::closed_pipe_frequency`
    """
    ...

def beat_frequency(f1: float, f2: float) -> float:
    """
Beat frequency: f_beat = |f1 - f2|

Rust: `waves::beat_frequency`
    """
    ...

def superposition_amplitude(a1: float, a2: float, phase_diff: float) -> float:
    """
Superposition of two waves at a point (same frequency):
A_resultant = sqrt(A1^2 + A2^2 + 2*A1*A2*cos(Δφ))

Rust: `waves::superposition_amplitude`
    """
    ...

def speed_of_sound_gas(gamma: float, temperature: float, molar_mass: float) -> float:
    """
Speed of sound in an ideal gas: v = sqrt(γ * R * T / M)
γ = heat capacity ratio, M = molar mass

Rust: `waves::speed_of_sound_gas`
    """
    ...

def wave_speed_string(tension: float, linear_density: float) -> float:
    """
Wave speed on a string: v = sqrt(T / μ)

Rust: `waves::wave_speed_string`
    """
    ...

def phase_velocity(angular_freq: float, wave_number: float) -> float:
    """
Phase velocity: v_p = ω/k

Rust: `waves::phase_velocity`
    """
    ...

def group_velocity(d_omega: float, d_k: float) -> float:
    """
Group velocity: v_g = dω/dk

Rust: `waves::group_velocity`
    """
    ...

def wave_impedance(density: float, wave_speed: float) -> float:
    """
Acoustic impedance: Z = ρv

Rust: `waves::wave_impedance`
    """
    ...

def reflection_coefficient(z1: float, z2: float) -> float:
    """
Amplitude reflection coefficient: R = (Z2 - Z1)/(Z2 + Z1)

Rust: `waves::reflection_coefficient`
    """
    ...

def transmission_coefficient(z1: float, z2: float) -> float:
    """
Amplitude transmission coefficient: T = 2Z2/(Z1 + Z2)

Rust: `waves::transmission_coefficient`
    """
    ...

def intensity_reflection(z1: float, z2: float) -> float:
    """
Intensity reflection coefficient: R_I = ((Z2 - Z1)/(Z2 + Z1))²

Rust: `waves::intensity_reflection`
    """
    ...

def intensity_transmission(z1: float, z2: float) -> float:
    """
Intensity transmission coefficient: T_I = 4Z1Z2/(Z1 + Z2)²

Rust: `waves::intensity_transmission`
    """
    ...

def attenuated_amplitude(initial: float, attenuation_coeff: float, distance: float) -> float:
    """
Attenuated amplitude: A = A₀ × e^(-αx)

Rust: `waves::attenuated_amplitude`
    """
    ...

def absorption_coefficient_from_db(db_per_meter: float) -> float:
    """
Absorption coefficient from dB/m: α = dB × ln(10)/20

Rust: `waves::absorption_coefficient_from_db`
    """
    ...

def penetration_depth(attenuation_coeff: float) -> float:
    """
Penetration depth (skin depth): δ = 1/α

Rust: `waves::penetration_depth`
    """
    ...

def sound_pressure_level(pressure: float, reference: float) -> float:
    """
Sound pressure level: SPL = 20 × log10(p/p_ref)

Rust: `waves::sound_pressure_level`
    """
    ...

def acoustic_power(pressure: float, area: float, impedance: float) -> float:
    """
Acoustic power: P = p²A/Z

Rust: `waves::acoustic_power`
    """
    ...

def resonant_frequency_tube_open(length: float, speed: float) -> float:
    """
Resonant frequency of open tube: f = v/(2L)

Rust: `waves::resonant_frequency_tube_open`
    """
    ...

def resonant_frequency_tube_closed(length: float, speed: float) -> float:
    """
Resonant frequency of closed tube: f = v/(4L)

Rust: `waves::resonant_frequency_tube_closed`
    """
    ...

def acoustic_intensity_from_pressure(pressure: float, impedance: float) -> float:
    """
Acoustic intensity from pressure: I = p²/Z

Rust: `waves::acoustic_intensity_from_pressure`
    """
    ...

def wavelength_in_medium(frequency: float, speed_in_medium: float) -> float:
    """
Wavelength in a medium: λ = v/f

Rust: `waves::wavelength_in_medium`
    """
    ...

def p_wave_speed(bulk_modulus: float, shear_modulus: float, density: float) -> float:
    """
P-wave speed: vp = √((K + 4G/3)/ρ)

Rust: `waves::p_wave_speed`
    """
    ...

def s_wave_speed(shear_modulus: float, density: float) -> float:
    """
S-wave speed: vs = √(G/ρ)

Rust: `waves::s_wave_speed`
    """
    ...

def rayleigh_wave_speed(shear_speed: float, poisson_ratio: float) -> float:
    """
Rayleigh wave speed approximation: vR ≈ vs × (0.862 + 1.14ν)/(1 + ν)

Rust: `waves::rayleigh_wave_speed`
    """
    ...

def love_wave_speed_range(shear_speed_layer: float, shear_speed_halfspace: float) -> tuple[float, float]:
    """
Love wave speed range: between vs_layer and vs_halfspace

Rust: `waves::love_wave_speed_range`
    """
    ...

def path_difference_constructive(order: int, wavelength: float) -> float:
    """
Constructive interference path difference: Δ = mλ

Rust: `waves::path_difference_constructive`
    """
    ...

def path_difference_destructive(order: int, wavelength: float) -> float:
    """
Destructive interference path difference: Δ = (m + 0.5)λ

Rust: `waves::path_difference_destructive`
    """
    ...

def fraunhofer_single_slit_intensity(angle: float, slit_width: float, wavelength: float) -> float:
    """
Fraunhofer single-slit intensity: I/I₀ = (sin(β)/β)² where β = πa sin(θ)/λ
Returns 1.0 at θ = 0 (central maximum).

Rust: `waves::fraunhofer_single_slit_intensity`
    """
    ...

def airy_disk_radius(wavelength: float, focal_length: float, aperture: float) -> float:
    """
Airy disk radius: r = 1.22λf/D

Rust: `waves::airy_disk_radius`
    """
    ...

def fresnel_number(aperture: float, distance: float, wavelength: float) -> float:
    """
Fresnel number: F = a²/(λL)

Rust: `waves::fresnel_number`
    """
    ...
