"""
Phylogenetics: trees, the distance and character methods that build them, and the statistics read off them.  # What a tree is here  `PhyloTree` stores a parent index and a branch length per node, with leaves first and internal nodes after. That representation makes the two operations everything else needs -- walking to the root, and finding a common ancestor -- direct, at the cost of making "children of" a search. Trees in this module are rooted; an unrooted method such as neighbour joining produces a tree whose root is an artefact of the construction and carries no meaning, which is noted where it matters.  # Distances are not times  A branch length is a number of substitutions per site, not an elapsed time, and converting between them needs a rate that no method here estimates. UPGMA is the exception and it is an *assumption* rather than an inference: it produces an ultrametric tree, in which every leaf is equidistant from the root, which is true only under a strict molecular clock. Neighbour joining makes no such assumption, and the difference shows immediately on data where rates vary between lineages.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.linalg.matrix import Matrix
from rust_physics_engine.monte_carlo import Rng

class DistanceMethod:
    """
Which distance method a bootstrap replicate should use.

Rust: `biophysics::phylo::DistanceMethod`
    """
    ...

class PhyloTree:
    """
A rooted phylogenetic tree.

Nodes `0..leaf_count` are leaves; the rest are internal. The root is the
unique node whose parent is `None`.

Rust: `biophysics::phylo::PhyloTree`
    """
    def __init__(self, parent: list[Optional[int]], branch_length: list[float], labels: list[str]) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def root(self) -> int: ...
    def children(self, node: int) -> list[int]: ...
    def leaves(self) -> list[int]: ...
    def is_binary(self) -> bool: ...
    def path_to_root(self, node: int) -> list[int]: ...
    def depth(self, node: int) -> float: ...
    def height(self) -> float: ...
    def total_length(self) -> float: ...
    def mrca(self, a: int, b: int) -> int: ...
    def distance(self, a: int, b: int) -> float: ...
    def is_ultrametric(self, tolerance: float) -> bool: ...
    def splits(self) -> list[list[str]]: ...
    def bipartitions(self) -> list[list[str]]: ...
    def robinson_foulds(self, other: PhyloTree) -> int: ...
    def to_newick(self) -> str: ...
    @staticmethod
    def from_newick(text: str) -> PhyloTree: ...
    @property
    def parent(self) -> list[Optional[int]]: ...
    @property
    def branch_length(self) -> list[float]: ...
    @property
    def labels(self) -> list[str]: ...

def upgma(dist: Matrix | Sequence[Sequence[float]], labels: list[str]) -> PhyloTree:
    """
UPGMA: unweighted pair group method with arithmetic mean.

Repeatedly joins the two closest clusters and places their common
ancestor at half their distance, so every leaf ends up the same distance
from the root. That ultrametricity is *assumed*, not measured: UPGMA
returns a clocklike tree whether or not the data are clocklike, and on
data where one lineage evolves faster it will place that lineage's
long branch too close to the root -- the classic long-branch artefact.
Use `neighbor_joining` unless a clock is justified.

The distance between merged clusters is the mean over all pairs of
members, which is what makes the merge heights non-decreasing and the
result a valid ultrametric tree.

Errors:
Returns an error for a non-square, asymmetric, negative or non-finite
matrix, a label count that disagrees with it, or fewer than two taxa.

Rust: `biophysics::phylo::upgma`
    """
    ...

def neighbor_joining(dist: Matrix | Sequence[Sequence[float]], labels: list[str]) -> PhyloTree:
    """
Saitou and Nei's neighbour joining.

Joins the pair minimising `Q(i,j) = (n-2) d(i,j) - r_i - r_j`, where
`r_i` is the row sum, rather than the pair that is simply closest. The
correction is what makes the method consistent without a clock: two
taxa can be close together merely because both evolve slowly, and `Q`
discounts exactly that. Given an additive matrix the method recovers
the true tree exactly.

The result is an **unrooted** tree returned in rooted form: the final
node has three children and is a placeholder, not an inferred ancestor.
Do not read `PhyloTree::height` or `PhyloTree::depth` off it as
times, and expect `PhyloTree::is_binary` to be false at that node.

Non-additive data can imply a negative branch. Since a negative length
has no meaning as a number of substitutions, it is clamped to zero --
the standard remedy, and a sign that the data do not fit a tree.

Errors:
Returns an error for a malformed matrix (see `upgma`) or fewer than
three taxa.

Rust: `biophysics::phylo::neighbor_joining`
    """
    ...

def distance_matrix_jc69(seqs: list[list[int]]) -> Matrix:
    """
The matrix of Jukes-Cantor corrected pairwise distances.

Sites where either sequence is not one of A, C, G, T are skipped for
that pair, so different pairs may rest on different numbers of sites.

Errors:
Returns an error for fewer than two sequences, sequences of differing
or zero length, a pair with no comparable site, or a pair whose observed
difference has saturated at three quarters, where the correction gives
no finite answer.

Rust: `biophysics::phylo::distance_matrix_jc69`
    """
    ...

def parsimony_fitch(tree: PhyloTree, characters: list[int]) -> int:
    """
Fitch's parsimony score: the fewest character changes the tree needs.

`characters` holds one state per leaf, in the order `PhyloTree::leaves`
returns them. Working from the tips down, each node takes the
intersection of its children's state sets, or -- when that is empty --
their union at the cost of one change.

The score counts changes, not their positions: a site can be explained
by several equally parsimonious assignments, and parsimony picks none of
them. It is also biased when rates vary a lot between branches, where it
can be positively misled (long-branch attraction) into preferring the
wrong topology however much data you add.

Errors:
Returns an error if the character count differs from the leaf count or
more than 32 distinct states appear.

Rust: `biophysics::phylo::parsimony_fitch`
    """
    ...

def likelihood_jc69(tree: PhyloTree, seqs: list[list[int]]) -> float:
    """
The log-likelihood of an alignment on a tree under Jukes-Cantor, by
Felsenstein's pruning algorithm.

`seqs` holds one aligned sequence per leaf, in the order
`PhyloTree::leaves` returns them, and branch lengths are expected
substitutions per site. Under JC69 a branch of length `t` leaves a site
unchanged with probability `1/4 + 3/4 e^(-4t/3)` and sends it to each
other base with `1/4 - 1/4 e^(-4t/3)`; pruning sums over every ancestral
assignment in one pass up the tree rather than enumerating `4^nodes` of
them.

The result is a *log* likelihood because the likelihood itself
underflows: a thousand sites each contributing a factor near `0.25`
gives a number around `1e-600`, which is not representable.

Sites where a leaf carries an ambiguous or missing base contribute a
factor of one from that leaf -- the site still informs the others.

Errors:
Returns an error if the sequence count differs from the leaf count, the
sequences are empty or of differing length.

Rust: `biophysics::phylo::likelihood_jc69`
    """
    ...

def bootstrap_trees(seqs: list[list[int]], labels: list[str], replicates: int, method: DistanceMethod, rng: Rng) -> tuple[PhyloTree, list[float]]:
    """
Bootstrap support for the splits of a distance tree.

Builds a reference tree from the whole alignment, then resamples the
*columns* with replacement `replicates` times, rebuilds, and reports the
fraction of replicates recovering each branch of the reference. The
returned vector is aligned with `reference.bipartitions()`.

Branches are compared as unrooted bipartitions rather than rooted
clades. Neighbour joining's root is an artefact, so two replicates that
found the same tree can report a clade and its complement; treating
those as different answers would understate support for no reason.

Columns are the sampling unit because sites are what the model treats as
independent draws; resampling taxa instead would answer a different
question. High support means the signal is spread across the alignment
rather than resting on a handful of sites -- it is not a probability
that the split is true, and a consistently wrong method will support a
wrong split at 100%.

Replicates whose resampled alignment yields no usable distance matrix
(a saturated pair, say) are skipped, and the divisor counts only those
that succeeded.

Errors:
Returns an error for fewer than three sequences, unaligned or empty
sequences, a label count that disagrees, zero replicates, or a whole
alignment that yields no tree.

Rust: `biophysics::phylo::bootstrap_trees`
    """
    ...

def birth_death_tree(lambda_: float, mu: float, n_leaves: int, rng: Rng) -> PhyloTree:
    """
A birth-death tree, pruned to the lineages that survive.

Runs the forward process -- each lineage speciating at rate `lambda` and
dying at rate `mu` -- until `n_leaves` lineages are alive at once, then
removes the extinct ones and suppresses the resulting single-child
nodes. What comes back is the *reconstructed* tree, the only one a
phylogeny of living species could ever show.

That pruning is why extinction leaves a signature rather than
disappearing. Near the present, lineages have not yet had time to die,
so the reconstructed tree grows at the full rate `lambda` there while
deeper down it grows at `lambda - mu`. The surviving tree therefore
looks as though speciation accelerated toward the present -- the "pull
of the present", which shows up as a positive `gamma_statistic` and an
upturn in the `lineage_through_time` curve.

The tree is stopped at the first event *after* the target count is
reached, so the interval during which `n_leaves` lineages coexist has a
length rather than collapsing to zero.

The tree is ultrametric by construction -- every tip sits at the same
stopping time.

Errors:
Returns an error for a non-positive `lambda`, a negative or non-finite
`mu`, `mu >= lambda`, fewer than three leaves, or if every attempt died
out before reaching the target.

Rust: `biophysics::phylo::birth_death_tree`
    """
    ...

def gamma_statistic(tree: PhyloTree) -> float:
    """
Pybus and Harvey's gamma statistic.

Standard normal under a constant-rate pure-birth process, so it is a
direct test of that null: negative gamma means the internal branching
events sit closer to the root than a constant rate predicts -- an early
burst, or a diversification rate that slowed -- and positive gamma means
they crowd toward the present.

Extinction pushes gamma *positive* on a reconstructed tree even at a
constant rate: recent lineages have not yet had time to die, so nodes
crowd toward the present. A positive value is therefore not by itself
evidence of an accelerating rate. The bias runs the other way from the
slowdown test, which is why a significantly negative gamma is taken as
conservative evidence of a slowdown.

The statistic reads times off the tree, so it is meaningful only for an
ultrametric one; a tree with unequal tip depths is rejected rather than
silently misread.

Errors:
Returns an error for fewer than three tips, a tree that is not
ultrametric to `1e-8` relative, or one of zero height.

Rust: `biophysics::phylo::gamma_statistic`
    """
    ...

def lineage_through_time(tree: PhyloTree) -> list[tuple[float, int]]:
    """
The lineage-through-time curve: `(time, lineage count)` at the root, at
every branching, and at the present.

Time is measured from the root. Plotted with a log count axis, a
constant-rate pure-birth tree gives a straight line of slope `lambda`,
which is what makes the curve's departures readable: a bend downward
toward the tips is a slowdown, and the upturn near the present on a tree
with extinction is the pull of the present rather than a real burst.

For a tree whose tips are not all at the same depth, the final point
uses the deepest tip and the count there is the leaf total.

Errors:
Returns an error for a tree with fewer than two tips.

Rust: `biophysics::phylo::lineage_through_time`
    """
    ...
