"""
Finite-difference time domain: Maxwell's equations on a Yee grid.  # Why the grid is staggered  Maxwell's curl equations couple the two fields' time derivatives to each other's spatial derivatives. Yee's arrangement puts `E` and `H` half a cell apart in space *and* half a step apart in time, so that every derivative in the scheme is a centred difference straddling the point it is evaluated at. Nothing is interpolated and nothing is averaged: the update is second-order accurate while using the narrowest possible stencil, and it is explicit, so a step costs one pass over the arrays.  The arrangement also makes the discrete divergence of `B` exactly conserved -- the update adds a discrete curl, and the discrete divergence of a discrete curl is identically zero on this grid. A collocated scheme has to enforce that separately or watch it drift.  # The Courant limit is not a guideline  With `S = c dt / dx`, the scheme's numerical dispersion relation admits a real wavenumber for every real frequency only while `S <= 1` in one dimension, or `S <= 1/sqrt(d)` in `d` dimensions. Past that the scheme has a mode that grows geometrically, and it grows from rounding noise if nothing else. This is not accuracy degrading gently; it is a hard threshold, and `fdtd_courant_check` reports which side of it a set of parameters falls on.  # The magic time step  At exactly `S = 1` in one dimension the numerical dispersion relation becomes the exact one, and the update degenerates into a shift: a pulse moves one cell per step with its shape unchanged, to machine precision, forever. One dimension is the only place this happens -- in two or three the dispersion error depends on the propagation angle and cannot be cancelled at all angles at once, which is why a two-dimensional simulation is run at a Courant number safely below the limit rather than at it.  # Fields are normalised  The updates here track `E` and `eta_0 H` rather than `E` and `H`, which removes the free-space impedance from every line of the update and leaves the Courant number as the only coefficient. It also makes the two fields comparable in magnitude, which matters because the conserved energy adds their squares -- in unnormalised units one term would be `1e5` times the other and the sum would be numerical nonsense.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


class Boundary1d:
    """
What to do at the ends of a one-dimensional grid.

Rust: `fem::fdtd::Boundary1d`
    """
    ...

class Fdtd1d:
    """
The result of a one-dimensional run: the electric field at every
step, and the magnetic field alongside it.

Rust: `fem::fdtd::Fdtd1d`
    """
    def __init__(self, e: list[list[float]], h: list[list[float]]) -> None: ...
    def energy(self, eps_r: list[float], n: int) -> Optional[float]: ...
    @property
    def e(self) -> list[list[float]]: ...
    @property
    def h(self) -> list[list[float]]: ...

class Fdtd2d:
    """
The state of a two-dimensional run.

The final snapshot alone is close to useless for a driven problem --
it is whatever phase the oscillation happened to land on -- so the
envelope is carried alongside it. That is a deliberate departure from
returning a bare field: what a steady-state calculation is *for* is
the amplitude, and reconstructing it from one snapshot is not
possible.

Rust: `fem::fdtd::Fdtd2d`
    """
    def __init__(self, nx: int, ny: int, ez: list[float], envelope: list[float]) -> None: ...
    @property
    def nx(self) -> int: ...
    @property
    def ny(self) -> int: ...
    @property
    def ez(self) -> list[float]: ...
    @property
    def envelope(self) -> list[float]: ...

def fdtd_courant_check(dx: float, dt: float, c: float) -> bool:
    """
Whether a set of parameters satisfies the one-dimensional Courant
condition `c dt <= dx`.

Equality is admissible and is in fact the best possible choice in one
dimension: see the module note on the magic time step.

Rust: `fem::fdtd::fdtd_courant_check`
    """
    ...

def fdtd_courant_check_2d(dx: float, dy: float, dt: float, c: float) -> bool:
    """
The two-dimensional Courant condition, `c dt <= 1 / sqrt(1/dx^2 +
1/dy^2)`.

On a square grid that is `dx / (c sqrt(2))`, and unlike the
one-dimensional case the bound is not a good place to sit: the
dispersion error at the limit vanishes along the diagonals and is
worst along the axes, so no single Courant number is exact for every
direction.

Rust: `fem::fdtd::fdtd_courant_check_2d`
    """
    ...

def fdtd_1d(eps_r: list[float], source: Callable[[int], float], source_cell: int, courant: float, steps: int, boundary: Boundary1d) -> Fdtd1d:
    """
Marches the one-dimensional Yee scheme.

`eps_r` gives the relative permittivity of each cell, `courant` is
`c dt / dx` in vacuum, and `source` is added to `E` at `source_cell`
at every step -- a soft source, which a wave passes through rather
than reflecting off, unlike overwriting the cell.

Errors:

`SolveError::InvalidArgument` for a grid shorter than three cells,
a non-positive or non-finite permittivity, a source cell outside the
grid, a Courant number outside `(0, 1]`, or a Courant number above
the limit the grid's *fastest* medium sets -- past the limit the
scheme is unconditionally unstable and running it would produce
numbers rather than an answer.

Rust: `fem::fdtd::fdtd_1d`
    """
    ...

def photonic_crystal_bandgap_1d(eps_a: float, eps_b: float, d_a: float, d_b: float, omega_max: float, samples: int) -> list[tuple[float, float]]:
    """
The photonic band gaps of an infinite `a`/`b` bilayer stack, found
from the Bloch dispersion relation.

A period of the stack has a transfer matrix, and Bloch's theorem says
the propagating states are those whose transfer matrix has unit
modulus eigenvalues. For a two-layer period that reduces to


with `k_i = omega n_i / c`. A frequency for which the right-hand side
exceeds one in magnitude has no real `K`: nothing propagates, and
that is a gap. The prefactor `(n_a/n_b + n_b/n_a)/2` is at least one
with equality only when the two indices agree, which is the whole
reason a gap exists at all -- a homogeneous "stack" has none.

Frequencies are angular and the speed of light is taken as one, so a
frequency is really `omega L / c` in disguise; scaling every
thickness by a factor scales every gap edge by its reciprocal.

Returns the gaps below `omega_max` as `(low, high)` pairs, ascending,
with the edges refined by bisection rather than left at the sampling
resolution.

Errors:

`SolveError::InvalidArgument` for non-positive permittivities or
thicknesses, a non-positive frequency ceiling, or fewer than two
samples.

Rust: `fem::fdtd::photonic_crystal_bandgap_1d`
    """
    ...

def fdtd_2d_tm(eps_r: list[float], source_pos: tuple[int, int], source: Callable[[int], float], nx: int, ny: int, steps: int, pml: tuple[int, int], courant: float, reflection: float) -> Fdtd2d:
    """
Marches the two-dimensional transverse-magnetic Yee scheme with a
Berenger split-field perfectly matched layer.

`eps_r` is row-major over `nx * ny` cells. `source` gives the value
added softly at `source_pos` on each step, exactly as in
`fdtd_1d` -- a continuous sinusoid at `f` cycles per step is
`|s| (TAU * f * s as f64).sin()`, and a pulse is anything with
compact support. Taking the waveform rather than a frequency is what
lets a caller switch the drive off, which is the only way to measure
what a boundary reflects: with a source still running, the field near
it is the source's own and says nothing about the layer.

Ramp a continuous drive on rather than switching it: a step
broadcasts across the whole band the grid can carry, and none of it
is what was asked for.

Why the field is split:

A lossy layer absorbs, but an ordinary lossy layer also *reflects*,
because its impedance differs from the vacuum it adjoins. Berenger's
construction splits `E_z` into the two parts that the two spatial
derivatives feed, and damps each with the loss belonging to its own
axis. The resulting medium is matched at every angle and every
frequency, which no single isotropic conductivity can be: what is
left is only the reflection from grading the profile over a finite
depth, and that is what the `reflection` target controls.

The layer is backed by a conductor. That is not a flaw -- anything
that reaches the backing has crossed the graded layer twice and comes
back attenuated by the round-trip factor the grading was designed
for.

`pml` gives the depth on each axis separately, `(x, y)`. A depth of
zero on an axis leaves plain conducting walls there, which is what a
waveguide wants: absorbing its side walls would stop it being a
waveguide, while absorbing its ends stops the switch-on transient
rattling around forever and swamping the field being measured.

Errors:

`SolveError::InvalidArgument` for a grid smaller than the layers
need, a permittivity array of the wrong length or with a non-positive
entry, a source outside the grid, a non-finite frequency, a
reflection target outside `(0, 1)`, or a Courant number above the
two-dimensional limit for the fastest medium present.

Rust: `fem::fdtd::fdtd_2d_tm`
    """
    ...

def waveguide_cutoff_check_fdtd(width: int, length: int, mode: int, omega: float, courant: float, steps: int) -> float:
    """
Infers a parallel-plate waveguide's cutoff frequency from the
evanescent decay it shows when driven below that cutoff.

The guide is `width` cells between conducting plates, driven in its
`mode`-th transverse pattern at angular frequency `omega` in radians
per unit *time*, with the cell size and the speed of light both one
-- so a step advances the phase by `omega * S`, not by `omega`.
Below cutoff nothing propagates: the field falls off as
`exp(-alpha x)`, and measuring `alpha` down the guide gives the
cutoff back.

Which cutoff comes back:

Not the textbook `m pi c / a`. The grid has its own dispersion
relation,


and an evanescent `k_x = i alpha` turns the first term on the right
into `-sinh^2(alpha / 2)`. Solving for where `alpha` vanishes gives
the *numerical* cutoff


which is what this returns and what the simulation actually has. It
approaches the continuum value as the guide is resolved more finely,
from below -- the grid is always a little slow -- and the difference
is second order in the cell size. Reporting the continuum figure
would be reporting what the answer ought to be rather than what it
is.

Errors:

`SolveError::InvalidArgument` for a mode outside `1..width`, a
guide too short to measure a decay in, or a frequency at or above the
numerical cutoff, where there is no decay to measure;
`SolveError::NoConvergence` if the measured profile is not a clean
exponential, which is the honest answer when a mode is close to the
grid's resolution limit: three half-waves across ten cells decays
within a couple of cells, leaving too little of the profile above the
numerical floor to fit a slope to. Widening the guide fixes it.

Rust: `fem::fdtd::waveguide_cutoff_check_fdtd`
    """
    ...

def waveguide_cutoff_numerical(width: int, mode: int, courant: float) -> float:
    """
The numerical cutoff a parallel-plate guide of this width has on a
grid at this Courant number, `(2/S) arcsin(S sin(k_y/2))`.

The continuum answer is `m pi / a`; this is what the grid actually
gives, and it is always the smaller of the two.

Errors:

`SolveError::InvalidArgument` for a mode outside `1..width` or a
Courant number outside the plane limit.

Rust: `fem::fdtd::waveguide_cutoff_numerical`
    """
    ...
