"""
Spectral methods: global basis functions instead of local ones.  # What changes when the basis stops being local  A finite element expands the solution in functions that are nonzero on one or two cells. The matrix is sparse, and the accuracy is whatever the polynomial degree gives -- `h^2`, `h^3`, a fixed power of the mesh size no matter how smooth the answer is.  A spectral method expands in functions that are nonzero everywhere and smooth: complex exponentials on a periodic domain, Chebyshev polynomials on an interval. The matrix becomes dense, and in exchange the error stops obeying any fixed power of `N` at all. For an analytic function it falls geometrically -- adding a few points multiplies the error by a constant factor rather than reducing it by a fixed order -- and for a function with `k` continuous derivatives it falls as `N^-k`. The method is only as good as the solution is smooth, and it is *exactly* as good as that. Both halves are measured in the tests rather than asserted.  # Two Poisson solvers that are not the same solver  `transforms::fft::fft_poisson_2d` already solves the periodic Poisson problem with an FFT, but it is not a spectral method. It divides by the eigenvalue of the *five-point* Laplacian, `(2 cos kx + 2 cos ky - 4)/h^2`, which makes the discrete residual vanish to rounding -- exactly what a pressure projection in a fluid solver wants, since there the finite-difference divergence is the thing that must be zero. Against the continuum it is second-order accurate and no better.  `spectral_poisson_periodic` divides by the true symbol `-k^2`. Its discrete residual is not zero, and its error against the continuum solution is nil for anything the grid can represent and geometrically small otherwise. The two answers differ by `O(h^2)`, and which one is wanted depends on whether the discrete operator or the differential one is the thing being solved.  # Chebyshev points cluster, and they have to  Interpolating at equally spaced points on an interval diverges as the degree grows, even for functions as tame as `1/(1+25x^2)` -- Runge's phenomenon, and it is not a rounding problem but a property of the Lebesgue constant, which grows like `2^N/(N log N)`. The Chebyshev points `cos(j pi / N)` cluster towards the ends at a density that makes the Lebesgue constant grow only logarithmically, which is what makes high-degree interpolation usable at all.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.linalg.matrix import Matrix
from numeria.statistics.distributions import Poisson

def chebyshev_points(n: int, a: float, b: float) -> list[float]:
    """
The `n + 1` Chebyshev-Gauss-Lobatto points on `[a, b]`.

Ordered descending on `[-1, 1]` -- `x_j = cos(j pi / n)` runs from `1`
to `-1` -- which is the convention Trefethen's differentiation matrix
assumes, and mapped affinely onto `[a, b]`. Getting the order
backwards flips the sign of every derivative, silently.

Errors:

`SolveError::InvalidArgument` for `n == 0` or a degenerate
interval.

Rust: `fem::spectral_pde::chebyshev_points`
    """
    ...

def cheb_diff_matrix(n: int, a: float, b: float) -> Matrix:
    """
The Chebyshev differentiation matrix on `[a, b]`, `(n+1)` square.

Multiplying a vector of values at `chebyshev_points` by this matrix
gives the derivative of the degree-`n` polynomial through those
values, at the same points. For data that *is* a polynomial of degree
at most `n` the result is the exact derivative, to rounding, however
large `n` is.

The off-diagonal entries are Trefethen's
`(c_i / c_j) (-1)^{i+j} / (x_i - x_j)`, with `c` equal to two at the
ends and one inside. The diagonal is *not* set from its closed form
but as minus the sum of the rest of its row -- the negative sum trick.
The two agree analytically, and differ in floating point by
cancellation that grows with `n`; taking the sum makes the matrix
annihilate constants exactly instead of nearly, which matters because
the constant is the one thing every derivative operator must kill and
the error in it pollutes everything else.

Errors:

`SolveError::InvalidArgument` for `n == 0` or a degenerate
interval.

Rust: `fem::spectral_pde::cheb_diff_matrix`
    """
    ...

def cheb_differentiate(d: Matrix | Sequence[Sequence[float]], values: list[float]) -> list[float]:
    """
Differentiates values sampled at `chebyshev_points`.

Errors:

`SolveError::DimensionMismatch` if the sample count is not
`n + 1` for the matrix's `n`.

Rust: `fem::spectral_pde::cheb_differentiate`
    """
    ...

def chebyshev_collocation_bvp(p: Callable[[float], float], q: Callable[[float], float], f: Callable[[float], float], a: float, b: float, bc: tuple[float, float], n: int) -> list[float]:
    """
Solves `-(p u')' + q u = f` on `[a, b]` with Dirichlet ends by
Chebyshev collocation.

The operator is assembled as `-D diag(p) D + diag(q)` and the
equation is imposed at the interior collocation points, with the two
end rows replaced by the boundary conditions. Returns the `n + 1`
values at `chebyshev_points`.

Only Dirichlet conditions are offered. A flux condition in a
collocation method means replacing an end row by a row of the
differentiation matrix, which works but changes the conditioning
enough to deserve its own treatment rather than a flag here.

The matrix is dense and the cost is `O(n^3)`, which is the trade the
method makes: far fewer unknowns for the same accuracy, each of them
coupled to all the others.

Errors:

`SolveError::InvalidArgument` for a degenerate interval, `n < 2`,
a non-positive `p`, or non-finite data; `SolveError::Singular` if
the collocation matrix is singular, which a reaction term negative
enough to hit an eigenvalue will do.

Rust: `fem::spectral_pde::chebyshev_collocation_bvp`
    """
    ...

def spectral_poisson_periodic(f: list[float], length: float) -> list[float]:
    """
Solves `u'' = f` on a periodic interval of the given length, using
the true spectral symbol `-k^2`.

`f` is sampled at `n` equally spaced points starting at the left end;
the point at the right end is the same as the first and is not
included. The solution is fixed by taking it mean-free, which is the
only choice available: a periodic Poisson problem determines `u` only
up to a constant, and it has no solution at all unless `f` itself has
zero mean. A nonzero mean in the data is silently dropped -- the
alternative is refusing perfectly good data over a rounding-level
mean -- and `spectral_poisson_periodic` returns the solution of the
mean-free part.

Compare `transforms::fft::fft_poisson_2d`, which divides by
the five-point Laplacian's eigenvalue instead. See the module note:
they solve different problems and both are right.

Errors:

`SolveError::InvalidArgument` for fewer than two samples, a
non-positive length, or non-finite data.

Rust: `fem::spectral_pde::spectral_poisson_periodic`
    """
    ...

def spectral_second_derivative(u: list[float], length: float) -> list[float]:
    """
Differentiates a periodic sample twice with the spectral symbol,
which is the exact inverse of `spectral_poisson_periodic` on
mean-free data.

Errors:

As `spectral_poisson_periodic`.

Rust: `fem::spectral_pde::spectral_second_derivative`
    """
    ...

def spectral_convergence_demo(f: Callable[[float], float], df: Callable[[float], float], a: float, b: float, sizes: list[int]) -> list[float]:
    """
The largest error in the Chebyshev derivative of `f` at each degree
in `sizes`.

The point of the function is the *shape* of what it returns, not any
one entry. For an analytic `f` the sequence falls geometrically and a
log-log fit against `n` finds no fixed slope at all; for an `f` with
`k` continuous derivatives it falls as `n^-k` and the fit finds
exactly `k`. Plotting one without the other is what makes spectral
accuracy look like magic rather than like a statement about
smoothness.

Errors:

`SolveError::InvalidArgument` if any size is below one or the
interval is degenerate.

Rust: `fem::spectral_pde::spectral_convergence_demo`
    """
    ...
