"""
Extreme value theory and copulas: the distribution of maxima, the distribution of exceedances, and the dependence structure between them.  Ordinary statistics describes the middle of a distribution, where there is data. Extreme value theory describes the edge, where by construction there is almost none, and it does so by an argument that parallels the central limit theorem. Just as a normalised *sum* of independent variables has only one possible limit whatever the summands, a normalised *maximum* has only three -- Gumbel, Frechet, Weibull -- and the generalised extreme value family holds all three, distinguished by the sign of a single shape parameter. That is what licenses extrapolating past the largest observation: the tail shape is not assumed, it is forced.  Two routes lead to the same place. Taking the maximum of each block and fitting a GEV throws away every observation but one per block. Taking every exceedance over a high threshold instead keeps far more of the data, and the Pickands-Balkema-de Haan theorem says those exceedances follow a generalised Pareto distribution with the *same* shape parameter. The threshold approach is usually the better estimator; the block approach is easier to explain and needs no threshold chosen.  The shape parameter is the whole story. Negative means a bounded tail with a finite upper endpoint; zero means an exponential tail, where every moment exists; positive means a power-law tail, where moments beyond `1/xi` do not. A hundred-year return level computed under the wrong sign is not slightly wrong.  Copulas answer the other half of the question. Marginal tails say how extreme each variable gets; a copula says whether they get extreme together. The distinction matters because correlation does not capture it: a Gaussian copula has zero tail dependence at any correlation below one, so two variables can be strongly correlated in the body and yet asymptotically independent in the tail, which is precisely the failure mode a correlation-based risk model cannot see.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.patterns.tilings import Archimedean
from rust_physics_engine.linalg.matrix import Matrix
from rust_physics_engine.monte_carlo import Rng

class CopulaFamily:
    """
The Archimedean and elliptical families supported here.

Rust: `stochastic::extreme::CopulaFamily`
    """
    ...

def gev_pdf(x: float, mu: float, sigma: float, xi: float) -> float:
    """
The generalised extreme value density.

Outside the support -- above the upper endpoint when `xi < 0`, below the
lower one when `xi > 0` -- the density is zero.

Panics:
Panics unless `sigma` is positive.

Rust: `stochastic::extreme::gev_pdf`
    """
    ...

def gev_cdf(x: float, mu: float, sigma: float, xi: float) -> float:
    """
The generalised extreme value distribution function,
`exp(-[1 + xi (x - mu)/sigma]^(-1/xi))`.

Panics:
Panics unless `sigma` is positive.

Rust: `stochastic::extreme::gev_cdf`
    """
    ...

def gev_quantile(p: float, mu: float, sigma: float, xi: float) -> float:
    """
The GEV quantile at probability `p`.

`mu + (sigma / xi) [(-ln p)^(-xi) - 1]`, or the Gumbel form
`mu - sigma ln(-ln p)` when the shape vanishes.

Panics:
Panics unless `sigma` is positive and `p` lies strictly in `(0, 1)`.

Rust: `stochastic::extreme::gev_quantile`
    """
    ...

def gev_fit(maxima: list[float]) -> tuple[float, float, float]:
    """
Fits a GEV to block maxima by maximum likelihood, returning
`(location, scale, shape)`.

The scale is optimised on the log scale so it cannot go negative, and the
likelihood is infinite wherever an observation would fall outside the
support, which keeps the search inside the feasible region without an
explicit constraint. Started from the moment-matched Gumbel fit, which is
the shape-zero member of the family and a reliable neighbourhood to
descend from.

Errors:
Returns an error for fewer than ten observations, or if no feasible
parameter set is found.

Rust: `stochastic::extreme::gev_fit`
    """
    ...

def gumbel_fit(maxima: list[float]) -> tuple[float, float]:
    """
Fits a Gumbel distribution -- the GEV with shape fixed at zero -- by
maximum likelihood, returning `(location, scale)`.

Worth fitting separately rather than reading off a GEV fit: with the shape
pinned, the two remaining parameters are far better determined, and the
difference in log-likelihood against the free-shape fit is the natural
test of whether the tail is exponential.

Errors:
Returns an error for fewer than five observations or a constant sample.

Rust: `stochastic::extreme::gumbel_fit`
    """
    ...

def gpd_pdf(y: float, sigma: float, xi: float) -> float:
    """
The generalised Pareto density for an exceedance `y > 0`.

Panics:
Panics unless `sigma` is positive.

Rust: `stochastic::extreme::gpd_pdf`
    """
    ...

def gpd_cdf(y: float, sigma: float, xi: float) -> float:
    """
The generalised Pareto distribution function,
`1 - (1 + xi y / sigma)^(-1/xi)`.

Panics:
Panics unless `sigma` is positive.

Rust: `stochastic::extreme::gpd_cdf`
    """
    ...

def gpd_quantile(p: float, sigma: float, xi: float) -> float:
    """
The generalised Pareto quantile at probability `p`.

Panics:
Panics unless `sigma` is positive and `p` lies in `[0, 1)`.

Rust: `stochastic::extreme::gpd_quantile`
    """
    ...

def gpd_fit(exceedances: list[float]) -> tuple[float, float]:
    """
Fits a generalised Pareto distribution to threshold exceedances by
maximum likelihood, returning `(scale, shape)`.

The exceedances must already be measured from the threshold, so they are
all positive. This is the peaks-over-threshold half of the theory: by
Pickands-Balkema-de Haan the shape here is the same shape a GEV fit to
block maxima of the same data would find, but estimated from every large
observation rather than one per block.

Errors:
Returns an error for fewer than ten exceedances, a non-positive
exceedance, or a failure to find feasible parameters.

Rust: `stochastic::extreme::gpd_fit`
    """
    ...

def mean_residual_life(x: list[float], thresholds: list[float]) -> list[float]:
    """
The mean excess over each threshold: the average of `x - u` across the
observations that exceed `u`.

The standard threshold-selection diagnostic. If the exceedances over some
`u` follow a generalised Pareto, the mean excess above any higher
threshold is `(sigma + xi u) / (1 - xi)` -- *linear* in the threshold. So
the point above which the plot straightens is the point above which the
asymptotic theory has taken hold, and a slope of zero means an
exponential tail.

A threshold exceeded by nothing yields NaN, which is reported rather than
silently dropped.

Rust: `stochastic::extreme::mean_residual_life`
    """
    ...

def hill_estimator(x: list[float], k: int) -> float:
    """
The Hill estimator of the tail index from the `k` largest observations.

`(1/k) sum_{i=1}^{k} ln X_(i) - ln X_(k+1)`, where `X_(1)` is the largest.
Estimates `xi` for a heavy tail, and only for a heavy one: the derivation
assumes a regularly varying tail, so a negative or zero shape is outside
its scope and the estimator will still return a positive number there.

Choosing `k` is the usual bias-variance trade: too small and the estimate
is noisy, too large and observations from the body contaminate it.

Panics:
Panics unless `1 <= k < n` and all of the top `k + 1` observations are
positive.

Rust: `stochastic::extreme::hill_estimator`
    """
    ...

def return_level(mu: float, sigma: float, xi: float, period: float) -> float:
    """
The level exceeded on average once every `period` blocks, under a GEV fit.

The quantile at `1 - 1/period`. A hundred-year level is not the largest
value seen in a century; it is the level with a one-in-a-hundred chance of
being exceeded in any given year.

Panics:
Panics unless `sigma` is positive and `period` exceeds one.

Rust: `stochastic::extreme::return_level`
    """
    ...

def return_period(mu: float, sigma: float, xi: float, level: float) -> float:
    """
The average number of blocks between exceedances of `level`, the exact
inverse of `return_level`.

Infinite for a level at or above the finite upper endpoint of a bounded
tail, which is the honest answer: such a level is never exceeded.

Panics:
Panics unless `sigma` is positive.

Rust: `stochastic::extreme::return_period`
    """
    ...

def block_maxima(x: list[float], block: int) -> list[float]:
    """
The maximum of each consecutive block of `block` observations.

A trailing partial block is dropped: its maximum is drawn from fewer
observations and is not comparable with the rest, and including it biases
the fit downward.

Panics:
Panics if `block` is zero.

Rust: `stochastic::extreme::block_maxima`
    """
    ...

def extremal_index(x: list[float], threshold: float) -> float:
    """
The extremal index by the Ferro-Segers intervals estimator.

Roughly the reciprocal of the mean cluster size: 1 when exceedances arrive
independently, below 1 when they arrive in bursts. It matters because
clustering does not change *how many* exceedances there are but does
change how many *distinct events* they represent, and a return period
computed as though every exceedance were its own event overstates the
frequency by exactly this factor.

The intervals estimator works from the gaps between exceedances rather
than from a declustering rule, so it needs no run length chosen.

Returns 1 when there are too few exceedances to say anything.

Panics:
Panics if `x` is empty.

Rust: `stochastic::extreme::extremal_index`
    """
    ...

def kendall_tau(x: list[float], y: list[float]) -> float:
    """
Kendall's tau: the probability of concordance minus the probability of
discordance, estimated over all pairs.

Ties in either coordinate contribute nothing to either count. Unlike
Pearson correlation this depends only on the ranks, so it is invariant
under any increasing transformation of either variable -- which is exactly
what makes it a property of the copula rather than of the margins, and
what lets a copula parameter be recovered from it.

Panics:
Panics unless the series have equal length and at least two points.

Rust: `stochastic::extreme::kendall_tau`
    """
    ...

def spearman_rho(x: list[float], y: list[float]) -> float:
    """
Spearman's rho: Pearson correlation applied to the ranks.

Like Kendall's tau it is a function of the copula alone, but it weights
the whole distribution more evenly, so the two disagree in a way that is
itself informative about the shape of the dependence.

Panics:
Panics unless the series have equal length and at least two points.

Rust: `stochastic::extreme::spearman_rho`
    """
    ...

def copula_gaussian_sample(corr: Matrix | Sequence[Sequence[float]], n: int, rng: Rng) -> list[list[float]]:
    """
Samples `n` points from a Gaussian copula with the given correlation
matrix.

Draws from a multivariate normal by a Cholesky factor and maps each margin
through the standard normal distribution function, which is what leaves
uniform margins and keeps only the dependence.

Errors:
Returns an error if the matrix is not a valid correlation matrix -- not
square, not symmetric, or not positive definite.

Rust: `stochastic::extreme::copula_gaussian_sample`
    """
    ...

def copula_t_sample(corr: Matrix | Sequence[Sequence[float]], df: float, n: int, rng: Rng) -> list[list[float]]:
    """
Samples `n` points from a `t` copula with `df` degrees of freedom.

The same construction as the Gaussian copula but with a shared chi-squared
scaling across all coordinates. That single shared factor is what creates
tail dependence: occasionally it is small, every coordinate is inflated at
once, and the sample lands in a corner. The Gaussian copula has no such
mechanism, which is why its tail dependence is exactly zero.

Errors:
Returns an error for an invalid correlation matrix or `df` below one.

Rust: `stochastic::extreme::copula_t_sample`
    """
    ...

def copula_clayton(theta: float, n: int, rng: Rng) -> list[list[float]]:
    """
Samples `n` pairs from a bivariate Clayton copula by conditional
inversion.

`theta > 0`. Clayton concentrates its dependence in the *lower* tail: its
coefficient of lower tail dependence is `2^(-1/theta)`, while the upper is
zero. That asymmetry is the reason to reach for it -- joint crashes
without joint booms.

Panics:
Panics unless `theta` is positive.

Rust: `stochastic::extreme::copula_clayton`
    """
    ...

def copula_gumbel(theta: float, n: int, rng: Rng) -> list[list[float]]:
    """
Samples `n` pairs from a bivariate Gumbel copula.

`theta >= 1`. The mirror image of Clayton: upper tail dependence
`2 - 2^(1/theta)` and none in the lower tail.

The conditional distribution has no closed-form inverse, so this uses the
Marshall-Olkin frailty construction instead. The Gumbel generator is the
Laplace transform of a positive stable law, so drawing one such variate
and dividing two independent exponentials by it produces the copula
directly. The stable variate comes from Kanter's algorithm.

Panics:
Panics unless `theta >= 1`.

Rust: `stochastic::extreme::copula_gumbel`
    """
    ...

def copula_frank(theta: float, n: int, rng: Rng) -> list[list[float]]:
    """
Samples `n` pairs from a bivariate Frank copula by conditional inversion.

`theta` may be any non-zero real: positive for positive dependence,
negative for negative. Frank is the symmetric Archimedean copula, with no
tail dependence in either direction -- useful precisely when dependence in
the body should not imply dependence in the extremes.

Panics:
Panics if `theta` is zero, where the family degenerates to independence.

Rust: `stochastic::extreme::copula_frank`
    """
    ...

def copula_tau(family: CopulaFamily, theta: float) -> float:
    """
Kendall's tau implied by a copula family at parameter `theta`.

Each family has a closed-form relation, which is what makes inversion
possible: `2 arcsin(rho) / pi` for the Gaussian, `theta / (theta + 2)` for
Clayton, `1 - 1/theta` for Gumbel, and for Frank
`1 - 4 (1 - D_1(theta)) / theta` with `D_1` the Debye function.

Rust: `stochastic::extreme::copula_tau`
    """
    ...

def copula_fit_tau(data: list[list[float]], family: CopulaFamily) -> float:
    """
Fits a copula parameter by inverting Kendall's tau.

The method of moments applied to a rank statistic: measure tau from the
data, then solve the family's tau-theta relation for theta. It needs no
likelihood and no numerical optimisation for three of the four families,
and because tau depends only on the ranks the answer is unaffected by
whatever the margins happen to be -- which is the entire point of
separating a copula from its margins.

`data` holds one row per observation with two columns.

Errors:
Returns an error for the wrong shape, or for a sample tau outside the
range the family can represent -- Clayton and Gumbel model only positive
dependence, so a negative tau has no solution.

Rust: `stochastic::extreme::copula_fit_tau`
    """
    ...

def empirical_copula(data: list[list[float]]) -> list[list[float]]:
    """
The pseudo-observations of a sample: each column replaced by its ranks
divided by `n + 1`.

This is the empirical copula transform. Dividing by `n + 1` rather than
`n` keeps every value strictly inside `(0, 1)`, which matters because the
copula densities and tail statistics below take logarithms of them.
Whatever the marginal distributions were, the result has approximately
uniform margins and retains exactly the original dependence.

Errors:
Returns an error for empty or ragged input.

Rust: `stochastic::extreme::empirical_copula`
    """
    ...

def tail_dependence_coefficient(data: list[list[float]], q: float) -> tuple[float, float]:
    """
Empirical coefficients of `(lower, upper)` tail dependence at quantile
level `q`.

The lower coefficient estimates `P(V <= q | U <= q)` and the upper
`P(V > q | U > q)`, both computed on pseudo-observations so the margins
are irrelevant. Only one of the pair is informative at any given `q`: read
the lower coefficient at a small `q` and the upper at a `q` near one. At
`q = 0.01` the upper coefficient is the probability both variables exceed
their first percentile, which is close to one for any sample and says
nothing about the tail. As `q` approaches its limit these tend to the theoretical
coefficients: `2^(-1/theta)` and 0 for Clayton, 0 and `2 - 2^(1/theta)`
for Gumbel, and 0 for both under any Gaussian copula with correlation
below one.

The last of those is the practically important one. Two variables can have
a correlation of 0.9 and still, under a Gaussian copula, become
independent in the limit of extreme events.

Errors:
Returns an error for the wrong shape or a `q` outside `(0, 1)`.

Rust: `stochastic::extreme::tail_dependence_coefficient`
    """
    ...

def pickands_dependence(data: list[list[float]], t: float) -> float:
    """
The Pickands dependence function estimated at `t`, for a bivariate
extreme-value copula.

An extreme-value copula is determined entirely by a convex function `A` on
`[0, 1]` satisfying `max(t, 1-t) <= A(t) <= 1`. The two bounds are the two
extremes of dependence: `A == 1` is independence, and `A(t) = max(t, 1-t)`
is perfect dependence. Everything in between is a real dependence
structure, and `A` is the whole of it.

Estimated by Pickands' original construction, the reciprocal of the mean
of `min(xi/(1-t), eta/t)` over the transformed data.

Errors:
Returns an error for the wrong shape or a `t` outside `(0, 1)`.

Rust: `stochastic::extreme::pickands_dependence`
    """
    ...
