"""
Special functions: error function family, gamma family, and beta functions.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from . import bessel, beta, elliptic, erf, expint, gamma, legendre
from numeria.special.bessel import bessel_i0 as bessel_i0
from numeria.special.bessel import bessel_i1 as bessel_i1
from numeria.special.bessel import bessel_j0 as bessel_j0
from numeria.special.bessel import bessel_j1 as bessel_j1
from numeria.special.bessel import bessel_j_zeros as bessel_j_zeros
from numeria.special.bessel import bessel_jn as bessel_jn
from numeria.special.bessel import bessel_k0 as bessel_k0
from numeria.special.bessel import bessel_k1 as bessel_k1
from numeria.special.bessel import bessel_y0 as bessel_y0
from numeria.special.bessel import bessel_y1 as bessel_y1
from numeria.special.bessel import bessel_yn as bessel_yn
from numeria.special.beta import beta_inc as beta_inc
from numeria.special.expint import e1 as e1
from numeria.special.elliptic import ellipse_perimeter_exact as ellipse_perimeter_exact
from numeria.special.elliptic import elliptic_e as elliptic_e
from numeria.special.elliptic import elliptic_e_inc as elliptic_e_inc
from numeria.special.elliptic import elliptic_f as elliptic_f
from numeria.special.elliptic import elliptic_k as elliptic_k
from numeria.special.erf import erfc as erfc
from numeria.special.erf import erfinv as erfinv
from numeria.special.expint import exponential_integral as exponential_integral
from numeria.special.gamma import gamma_p as gamma_p
from numeria.special.gamma import gamma_q as gamma_q
from numeria.special.legendre import gauss_legendre_nodes as gauss_legendre_nodes
from numeria.special.elliptic import jacobi_elliptic as jacobi_elliptic
from numeria.special.legendre import legendre_p as legendre_p
from numeria.special.legendre import legendre_p_assoc as legendre_p_assoc
from numeria.special.gamma import lgamma as lgamma
from numeria.special.elliptic import pendulum_period_exact as pendulum_period_exact
from numeria.special.legendre import spherical_harmonic_real as spherical_harmonic_real


