"""
Legendre polynomials, associated Legendre functions, real spherical harmonics, and Gauss-Legendre quadrature nodes.  References: Abramowitz & Stegun ch. 8; Numerical Recipes §6.8 (`plgndr`) and §4.5 (`gauleg`).
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def legendre_p(n: int, x: float) -> float:
    """
Legendre polynomial Pₙ(x) by the Bonnet recurrence
(n+1)·P_{n+1} = (2n+1)·x·Pₙ − n·P_{n−1}.

Rust: `special::legendre::legendre_p`
    """
    ...

def legendre_p_assoc(l: int, m: int, x: float) -> float:
    """
Associated Legendre function Pₗᵐ(x) with the Condon-Shortley phase,
for |x| ≤ 1. Negative m uses
Pₗ^{−m} = (−1)ᵐ (l−m)!/(l+m)! Pₗᵐ.

Panics:
Panics unless |m| ≤ l and |x| ≤ 1.

Rust: `special::legendre::legendre_p_assoc`
    """
    ...

def spherical_harmonic_real(l: int, m: int, theta: float, phi: float) -> float:
    """
Real spherical harmonic Yₗₘ(θ, φ) (orthonormal on the sphere):
m > 0 pairs with cos(mφ), m < 0 with sin(|m|φ).

Panics:
Panics unless |m| ≤ l.

Rust: `special::legendre::spherical_harmonic_real`
    """
    ...

def gauss_legendre_nodes(n: int) -> tuple[list[float], list[float]]:
    """
Nodes and weights of the n-point Gauss-Legendre rule on [−1, 1]
(NR `gauleg`: Newton iteration on Pₙ from the Chebyshev-like initial
guess). Integrates polynomials up to degree 2n−1 exactly.

Panics:
Panics if n = 0.

Rust: `special::legendre::gauss_legendre_nodes`
    """
    ...
