"""
One-dimensional finite elements for `-(p u')' + q u = f`.  # The weak form  The strong form asks for a function whose second derivative satisfies the equation pointwise. Multiplying by a test function `v` that vanishes wherever `u` is prescribed, integrating over the interval and integrating the second-derivative term by parts gives  ```text a(u, v) = integral p u' v' + q u v dx = integral f v dx = L(v) ```  for every admissible `v`. Two things happened in that line. The solution now needs only one derivative rather than two, so a discontinuous `p` -- a layered material -- is admissible instead of fatal. And the boundary term `[p u' v]` that integration by parts produced is where flux conditions enter: prescribe nothing and the method silently imposes zero flux, which is why Neumann conditions are called *natural* and Dirichlet conditions, which have to be built into the space, are called *essential*.  # Why the answer is the best one available  Galerkin's method asks for the identity to hold not for every `v` but for every `v` in a finite dimensional subspace, and looks for `u_h` in that same subspace. Subtracting the two statements gives Galerkin orthogonality, `a(u - u_h, v_h) = 0` for every `v_h` in the space: the error is `a`-orthogonal to everything representable. When `a` is symmetric and positive definite it is an inner product, orthogonality of the error is exactly the characterisation of an orthogonal projection, and so  ```text ||u - u_h||_a  <=  ||u - v_h||_a   for every v_h in the space ```  with a constant of one. The finite element solution is not merely a good approximation in the energy norm; it is *the* best one. Nothing in a finite difference scheme corresponds to this. It is checked directly against the nodal interpolant in the property tests.  Equivalently, `u_h` minimises the energy `J(v) = a(v,v)/2 - L(v)` over the space -- the Ritz view -- which is why refining a mesh can only lower the computed energy: the coarse space sits inside the fine one.  # A variable coefficient is averaged, not sampled  Linear elements have a constant derivative on each element, so the quadrature in the stiffness term integrates `p` against a constant and reproduces its element *average* exactly. That has a consequence worth knowing: the discrete bilinear form still agrees with the true one on the element space itself, so `u_h` is the exact `a`-orthogonal projection of the true solution rather than an approximation of one, and the Pythagoras identity  ```text ||u - v_h||_a^2 = ||u - u_h||_a^2 + ||u_h - v_h||_a^2 ```  holds to rounding for every `v_h` in the space. It is not an accident of a smooth `p`: a `p` that jumps *within* an element is averaged the same way, which is the sense in which a finite element method handles a discontinuous coefficient gracefully rather than exactly.  # Nodal exactness, and its limits  For the pure Poisson problem `-u'' = f` with Dirichlet data, the linear element solution is exact *at the nodes*, to machine precision, on any mesh. The Green's function of `-d^2/dx^2` is piecewise linear with its kink at the source point, so for a mesh node it lies in the element space itself; pairing it against the orthogonal error gives `(u - u_h)(x_i) = 0`. This is a property of the operator, not a lucky cancellation, and it fails the moment either ingredient goes:  - a variable `p` makes the Green's function piecewise `int dx/p`, which is not piecewise linear, and nodal exactness disappears; - a reaction term `q` does the same; - for quadratic elements the piecewise linear Green's function of a *vertex* is still in the space, so vertices stay exact, but the one belonging to a midside node kinks in the middle of an element and is not. Quadratic elements are exact at element vertices and merely third-order accurate at the midsides.  Nodal exactness also needs the load `integral f phi_i` integrated exactly. Assembly here uses five-point Gauss-Legendre per element, exact through degree nine, so it holds to rounding for polynomial data and to quadrature error otherwise.  # Sign conventions  Flux conditions are stated with the *outward* normal, so the same `Bc::Neumann` value means the same physical thing at both ends: `p du/dn = g`, which is `-p u'(a) = g` on the left and `p u'(b) = g` on the right. `Bc::Robin` is `p du/dn + alpha u = g` in the same convention, and keeps the stiffness matrix symmetric.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.statistics.distributions import Poisson

class Bc:
    """
A boundary condition at one end of the interval.

Flux conditions use the outward normal, so a given value means the
same physical thing at either end.

Rust: `fem::fem1d::Bc`
    """
    ...

class Fem1dSolution:
    """
A finite element solution, with the mesh it lives on.

The solver functions return bare nodal values to match the shape of
the rest of the crate; wrapping them here is what makes it possible to
ask for the value *between* nodes, which is what an error norm needs.

Rust: `fem::fem1d::Fem1dSolution`
    """
    def __init__(self, a: float, b: float, degree: int, values: list[float]) -> None: ...
    @staticmethod
    def new(a: float, b: float, degree: int, values: list[float]) -> Fem1dSolution: ...
    def elements(self) -> int: ...
    def h(self) -> float: ...
    def nodes(self) -> list[float]: ...
    def eval(self, x: float) -> float: ...
    def eval_derivative(self, x: float) -> float: ...
    @property
    def a(self) -> float: ...
    @property
    def b(self) -> float: ...
    @property
    def degree(self) -> int: ...
    @property
    def values(self) -> list[float]: ...

def fem_1d_poisson(f: Callable[[float], float], a: float, b: float, bc: tuple[Bc, Bc], n: int) -> list[float]:
    """
Solves `-u'' = f` with linear elements on a uniform mesh of `n`
elements, returning the `n + 1` nodal values.

With exact load integration this is nodally exact -- see the module
documentation for why that is a property of the Laplacian rather than
of the discretisation.

Errors:

`SolveError::InvalidArgument` for an empty mesh, a degenerate
interval, or non-finite data; `SolveError::Singular` when both ends
carry a pure flux condition, which leaves the solution undetermined up
to an additive constant.

Rust: `fem::fem1d::fem_1d_poisson`
    """
    ...

def fem_1d_general(p: Callable[[float], float], q: Callable[[float], float], f: Callable[[float], float], a: float, b: float, bc: tuple[Bc, Bc], n: int) -> list[float]:
    """
Solves `-(p u')' + q u = f` with linear elements, returning the
`n + 1` nodal values.

Errors:

As `fem_1d_poisson`, and additionally
`SolveError::InvalidArgument` if `p` is not positive at a quadrature
point. A negative `q` large enough to make the operator indefinite is
reported as `SolveError::Singular`.

Rust: `fem::fem1d::fem_1d_general`
    """
    ...

def fem_1d_quadratic(p: Callable[[float], float], q: Callable[[float], float], f: Callable[[float], float], a: float, b: float, bc: tuple[Bc, Bc], n: int) -> list[float]:
    """
Solves `-(p u')' + q u = f` with quadratic elements, returning the
`2n + 1` nodal values: element vertices at the even indices and
midsides at the odd ones.

Errors:

As `fem_1d_general`.

Rust: `fem::fem1d::fem_1d_quadratic`
    """
    ...

def fem_1d_error_l2(u_h: Fem1dSolution, u_exact: Callable[[float], float]) -> float:
    """
The `L2` norm of the error against an exact solution.

Rust: `fem::fem1d::fem_1d_error_l2`
    """
    ...

def fem_1d_error_h1_seminorm(u_h: Fem1dSolution, du_exact: Callable[[float], float]) -> float:
    """
The `H1` seminorm of the error: the `L2` norm of the derivative
difference alone.

For the Poisson problem this is the energy norm, up to the factor the
coefficient `p` contributes, and so it is the norm in which the finite
element solution is the best approximation available.

Rust: `fem::fem1d::fem_1d_error_h1_seminorm`
    """
    ...

def fem_1d_error_h1(u_h: Fem1dSolution, u_exact: Callable[[float], float], du_exact: Callable[[float], float]) -> float:
    """
The full `H1` norm of the error, `sqrt(L2^2 + seminorm^2)`.

Rust: `fem::fem1d::fem_1d_error_h1`
    """
    ...

def convergence_rate(errors: list[float], hs: list[float]) -> float:
    """
The observed order of convergence: the least-squares slope of
`ln(error)` against `ln(h)`.

A method converging as `C h^k` returns `k`. Fitting all the points
rather than taking the ratio of the last two is deliberate -- a single
ratio is a difference of two noisy logarithms and inherits the noise
of both.

Errors:

`SolveError::InvalidArgument` unless there are at least two pairs of
matching length, all strictly positive and finite, with at least two
distinct spacings.

Rust: `fem::fem1d::convergence_rate`
    """
    ...
