"""
Triangular finite elements in the plane.  # The linear triangle  On a triangle the three barycentric coordinates are themselves the linear shape functions, and their gradients are constant. That single fact does most of the work: the stiffness integral `integral grad(phi_i) . grad(phi_j)` has a constant integrand, so it is the gradient product times the triangle's area, with no quadrature involved and no error introduced. The whole element matrix for the Laplacian is  ```text K_ij = (b_i b_j + c_i c_j) / (4 A) ```  where `b` and `c` are the edge-opposite coordinate differences and `A` is the signed area. The two-dimensional method inherits everything the one-dimensional one has -- Galerkin orthogonality, energy minimisation, best approximation in the energy norm -- because none of those arguments mentions the dimension.  # What the mesh has to guarantee  Two conditions matter and they are different in kind.  *Conformity* is structural: two triangles meet along a whole shared edge or at a single shared vertex, never at a vertex hanging in the middle of a neighbour's edge. Without it the assembled function is not continuous and the space is not a subspace of `H1`, so the theory does not apply at all. It is checked here by counting: every edge belongs to one triangle or two, never more.  *Shape* is quantitative. The interpolation error carries a factor of `1/sin(theta_min)`, so a mesh of slivers converges at the same rate with a much worse constant. `FemMesh2::quality_min_angle` reports the worst angle in the mesh, and uniform refinement leaves it exactly unchanged -- the four children of a triangle are all similar to their parent, which is the property that makes repeated refinement safe and that a red-green or longest-edge scheme has to work to recover.  # Delaunay and the maximum principle  The off-diagonal stiffness entry for an interior edge is `-(cot alpha + cot beta)/2`, the two angles opposite the edge in the triangles sharing it. It is nonpositive exactly when those angles sum to no more than `pi` -- which is the Delaunay condition. So a Delaunay triangulation gives an M-matrix, and an M-matrix gives a discrete maximum principle: a nonnegative load produces a nonnegative solution, and a harmonic one attains its extremes on the boundary. On a badly shaped non-Delaunay mesh the discrete solution can overshoot its own boundary data while still converging, which is exactly the kind of defect a plausibility check on a picture would miss.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.linalg.sparse import CsrMatrix
from rust_physics_engine.statistics.distributions import Poisson
from rust_physics_engine.math import Vec2

class FemMesh2:
    """
A conforming triangulation of a planar region.

Rust: `fem::fem2d::FemMesh2`
    """
    def __init__(self, nodes: list[Vec2 | Sequence[float]], tris: list[list[int]], boundary: list[int]) -> None: ...
    @staticmethod
    def new(nodes: list[Vec2 | Sequence[float]], tris: list[list[int]]) -> FemMesh2: ...
    @staticmethod
    def rect(w: float, h: float, nx: int, ny: int) -> FemMesh2: ...
    @staticmethod
    def disk(r: float, n: int) -> FemMesh2: ...
    @staticmethod
    def from_delaunay(points: list[Vec2 | Sequence[float]]) -> FemMesh2: ...
    def refine_uniform(self) -> FemMesh2: ...
    def quality_min_angle(self) -> float: ...
    def area(self) -> float: ...
    def edge_count(self) -> int: ...
    @property
    def nodes(self) -> list[Vec2]: ...
    @property
    def tris(self) -> list[list[int]]: ...
    @property
    def boundary(self) -> list[int]: ...

def fem_2d_poisson(mesh: FemMesh2, f: Callable[[Vec2 | Sequence[float]], float], dirichlet: Callable[[Vec2 | Sequence[float]], Optional[float]]) -> list[float]:
    """
Solves `-div(grad u) = f` on the mesh with the given Dirichlet data.

`dirichlet` is consulted at every boundary node; returning `None`
leaves that node free, which imposes the natural zero-flux condition
there. Returning `None` everywhere leaves the constant in the kernel
and is reported as `SolveError::Singular`.

The system is symmetric positive definite once the data is applied, so
it is solved by Jacobi-preconditioned conjugate gradients.

Errors:

`SolveError::InvalidArgument` for non-finite data,
`SolveError::Singular` if nothing pins the solution, and
`SolveError::NoConvergence` if the iteration stalls.

Rust: `fem::fem2d::fem_2d_poisson`
    """
    ...

def fem_2d_reaction_diffusion(mesh: FemMesh2, c: Callable[[Vec2 | Sequence[float]], float], f: Callable[[Vec2 | Sequence[float]], float], dirichlet: Callable[[Vec2 | Sequence[float]], Optional[float]]) -> list[float]:
    """
Solves `-div(grad u) + c u = f` on the mesh with Dirichlet data.

A positive `c` is a reaction term and keeps the problem coercive; a
negative one is the Helmholtz operator `-lap - k^2`, which loses
positive definiteness once `k^2` passes the first eigenvalue of the
domain. See `fem_2d_helmholtz` for that case, which needs a
different solver.

Errors:

As `fem_2d_poisson`, and `SolveError::NotPositiveDefinite` if the
reaction term makes the system indefinite.

Rust: `fem::fem2d::fem_2d_reaction_diffusion`
    """
    ...

def stiffness_matrix(mesh: FemMesh2) -> CsrMatrix:
    """
The assembled stiffness matrix of the Laplacian, with no boundary
conditions applied.

The off-diagonal entry for an edge is minus half the sum of the
cotangents of the two angles opposite it -- the identity that ties the
M-matrix property to the Delaunay condition, since a cotangent turns
negative exactly when its angle turns obtuse. Every row sums to zero,
because the three shape functions of a triangle sum to the constant
one and so their gradients sum to zero.

Rust: `fem::fem2d::stiffness_matrix`
    """
    ...

def mass_matrix(mesh: FemMesh2) -> CsrMatrix:
    """
The assembled consistent mass matrix.

`A/6` on the diagonal and `A/12` off it, per triangle. Its entries sum
to the area of the mesh, since the shape functions form a partition of
unity; the *lumped* alternative, which puts each row's total on its
diagonal, is what an explicit time integrator wants and is a different
matrix with the same total.

Rust: `fem::fem2d::mass_matrix`
    """
    ...

def element_gradient(mesh: FemMesh2, values: list[float], tri: int) -> Optional[Vec2]:
    """
The gradient of a nodal field on one triangle, which is constant
there because the field is linear.

Returns `None` for an out-of-range triangle index or a mismatched
value count.

Rust: `fem::fem2d::element_gradient`
    """
    ...

def dirichlet_energy(mesh: FemMesh2, values: list[float]) -> float:
    """
The Dirichlet energy `integral |grad u|^2` of a nodal field, computed
exactly.

It is exact rather than quadrature-limited because the gradient is
constant on each triangle, so the integral is a sum of area times a
squared length. This is the energy norm the finite element solution
minimises, and the quantity that must fall when the mesh is refined.

Errors:

`SolveError::DimensionMismatch` if the value count does not match
the node count.

Rust: `fem::fem2d::dirichlet_energy`
    """
    ...

def interpolate(mesh: FemMesh2, values: list[float], p: Vec2 | Sequence[float]) -> Optional[float]:
    """
Evaluates a nodal field at an arbitrary point by locating the
containing triangle and interpolating barycentrically.

Returns `None` if the point lies outside every triangle, or if the
value count does not match the mesh. The search is linear in the
triangle count -- there is no spatial index here, so this is for
sampling an answer rather than for an inner loop.

Rust: `fem::fem2d::interpolate`
    """
    ...

def fem_2d_helmholtz(mesh: FemMesh2, k: float, f: Callable[[Vec2 | Sequence[float]], float], dirichlet: Callable[[Vec2 | Sequence[float]], Optional[float]]) -> list[float]:
    """
Solves the Helmholtz problem `-lap u - k^2 u = f` with Dirichlet data.

This is the same assembly as `fem_2d_reaction_diffusion` with a
negative reaction term, but it needs a different solver and the reason
is structural rather than numerical. Once `k^2` passes the first
Dirichlet eigenvalue of the domain the operator stops being positive
definite, and conjugate gradients -- which is a minimisation method --
has nothing left to minimise. A dense LU factorisation is used
instead, which costs `O(n^3)` in the node count and confines this
function to modest meshes.

At `k^2` exactly equal to an eigenvalue the operator is singular: the
homogeneous problem has a nonzero solution, so the inhomogeneous one
has either none or a whole line of them. That is resonance, not a
numerical accident, and it is reported as `SolveError::Singular`.
Approaching an eigenvalue the response grows like the reciprocal of
the distance to it.

Errors:

`SolveError::InvalidArgument` for non-finite data,
`SolveError::Singular` at or extremely close to a resonance.

Rust: `fem::fem2d::fem_2d_helmholtz`
    """
    ...

def fem_eigenvalues_drum(mesh: FemMesh2, count: int) -> list[float]:
    """
The `count` smallest eigenvalues of the Dirichlet Laplacian on the
mesh -- the squared frequencies of a drum clamped at its rim.

The discrete problem is the generalised one `K phi = lambda M phi`
over the interior nodes, solved by transforming it to a standard
symmetric problem through the Cholesky factor of the mass matrix.
Using the consistent mass matrix rather than a lumped one matters
here: lumping shifts the eigenvalues downwards, and it is precisely
their being *upper* bounds that makes them useful.

That bound is the property worth knowing. The discrete eigenvalues
come from the Rayleigh quotient minimised over a subspace of the true
admissible space, and a minimum over less is never smaller, so every
computed eigenvalue is an upper bound on the true one and refining the
mesh can only lower it. A method whose eigenvalues approach the answer
from below has a defect, however good its error looks.

The dense eigensolver is `O(n^3)` in the interior node count, so this
is for meshes of hundreds of nodes rather than thousands.

Errors:

`SolveError::InvalidArgument` if `count` is zero or exceeds the
number of interior nodes; `SolveError::NotPositiveDefinite` if the
mass matrix fails to factor, and whatever the eigensolver reports.

Rust: `fem::fem2d::fem_eigenvalues_drum`
    """
    ...

def fem_eigenmodes_drum(mesh: FemMesh2, count: int) -> tuple[list[float], list[list[float]]]:
    """
The `count` lowest drum modes: eigenvalues and the matching nodal
eigenvectors, the latter given over all nodes with zeros on the
clamped boundary.

Eigenvectors are normalised so that the mass-weighted norm
`phi^T M phi` is one, which is the discrete form of normalising the
mode shape in `L2`.

Errors:

As `fem_eigenvalues_drum`.

Rust: `fem::fem2d::fem_eigenmodes_drum`
    """
    ...

def fem_2d_elasticity_plane_stress(mesh: FemMesh2, e: float, nu: float, loads: list[tuple[int, Vec2 | Sequence[float]]], fixed: list[tuple[int, Vec2 | Sequence[float]]]) -> list[Vec2]:
    """
Solves the plane-stress elasticity problem on the mesh.

`loads` are point forces applied at nodes and `fixed` prescribes
displacements at nodes, both components at once. Unit thickness is
assumed throughout, so a force is a force per unit thickness.

The constant-strain triangle:

Displacement is linear on each triangle, so strain -- its gradient --
is constant there, and so is stress. That makes the element matrix
`A B^T D B` with no quadrature, exactly as for the Laplacian, and it
makes the stress field piecewise constant and discontinuous across
every edge. The discontinuity is not a bug to be smoothed away
silently: its size is an error estimate, and averaging it to the
nodes before showing it to anyone is how a coarse mesh comes to look
convincing.

What has to be pinned:

The stiffness matrix has a three-dimensional kernel: two translations
and one infinitesimal rotation. Prescribing fewer than three
independent degrees of freedom leaves the body free to move without
straining, and the system is singular no matter how many loads are
applied. This is checked directly.

Errors:

`SolveError::InvalidArgument` for a non-positive modulus, a
Poisson's ratio outside `(-1, 0.5)`, an out-of-range node index, or
non-finite data; `SolveError::Singular` if the constraints leave a
rigid body motion free.

Rust: `fem::fem2d::fem_2d_elasticity_plane_stress`
    """
    ...

def element_strain(mesh: FemMesh2, u: list[Vec2 | Sequence[float]], tri: int) -> Optional[list[float]]:
    """
The constant strain `(eps_x, eps_y, gamma)` of one triangle, given a
nodal displacement field.

`gamma` is the engineering shear strain, twice the tensor component.
Returns `None` for an out-of-range index or a mismatched field.

Rust: `fem::fem2d::element_strain`
    """
    ...

def element_stress(mesh: FemMesh2, u: list[Vec2 | Sequence[float]], e: float, nu: float, tri: int) -> Optional[list[float]]:
    """
The constant stress `(sigma_x, sigma_y, tau)` of one triangle.

Returns `None` for an out-of-range index, a mismatched field, or
material constants outside their admissible ranges.

Rust: `fem::fem2d::element_stress`
    """
    ...

def strain_energy(mesh: FemMesh2, u: list[Vec2 | Sequence[float]], e: float, nu: float) -> float:
    """
The total strain energy `(1/2) integral sigma : eps`.

At equilibrium this is half the work the applied loads do, which is
Clapeyron's theorem and follows from nothing more than the stiffness
matrix being symmetric.

Errors:

`SolveError::DimensionMismatch` for a mismatched field and
`SolveError::InvalidArgument` for invalid material constants.

Rust: `fem::fem2d::strain_energy`
    """
    ...

def von_mises_stress(mesh: FemMesh2, u: list[Vec2 | Sequence[float]], e: float, nu: float) -> list[float]:
    """
The von Mises equivalent stress of each triangle, given a nodal
displacement field.

One value per triangle, not per node: the strain of a linear
displacement field is constant on an element and discontinuous across
its edges. That discontinuity is not a bug to be smoothed away
silently -- its size is an error estimate, and averaging it to the
nodes before showing it to anyone is how a coarse mesh comes to look
convincing.

In plane stress the out-of-plane stress is zero rather than free, so
the equivalent stress is
`sqrt(sx^2 - sx sy + sy^2 + 3 tau^2)`. A consequence worth noticing:
equal biaxial tension `sx = sy = s` gives `|s|`, not zero. The
three-dimensional intuition that hydrostatic stress cannot yield a
material does not survive into plane stress, because a state that is
hydrostatic *in plane* has a free surface out of it and so is not
hydrostatic at all.

Errors:

`SolveError::DimensionMismatch` if the displacement count does not
match the node count, and `SolveError::InvalidArgument` for invalid
material constants.

Rust: `fem::fem2d::von_mises_stress`
    """
    ...

def fem_2d_heat_transient(mesh: FemMesh2, initial: list[float], alpha: float, dt: float, steps: int, theta: float, source: Callable[[Vec2 | Sequence[float]], float], dirichlet: Callable[[Vec2 | Sequence[float]], Optional[float]]) -> list[list[float]]:
    """
Marches the heat equation `u_t = alpha lap u + f` with the
`theta` scheme, returning `steps + 1` snapshots starting from the
initial field.

The step solves
`(M + theta alpha dt K) u_next = (M - (1-theta) alpha dt K) u + dt F`.
`theta = 0` is forward Euler, `1` backward Euler, `1/2`
Crank-Nicolson.

Stability, and the difference between A-stable and L-stable:

Applied to a discrete eigenmode the scheme multiplies its amplitude
by `(1 - (1-theta) a) / (1 + theta a)` each step, with
`a = alpha lambda dt`. For `theta >= 1/2` that factor has magnitude
below one for every positive `a`, which is A-stability, and forward
Euler instead needs `a < 2`.

Crank-Nicolson is A-stable but *not* L-stable: as `a` grows its factor
tends to `-1`, not to zero. A mode too stiff to resolve therefore
survives while flipping sign every step, which is why a discontinuous
initial condition rings under Crank-Nicolson and why the usual remedy
is to take the first couple of steps with backward Euler, whose
factor does tend to zero. That contrast is asserted in the tests.

Errors:

`SolveError::InvalidArgument` for a mismatched initial field, a
non-positive step, a `theta` outside `[0, 1]`, a negative diffusivity
or non-finite data; whatever the linear solver reports otherwise.

Rust: `fem::fem2d::fem_2d_heat_transient`
    """
    ...
