"""
Euclidean 3D geometric algebra Cl(3, 0).
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.manifold.clifford import Multivector
from numeria.quaternion import Quaternion
from numeria.math import Vec3

def vec(v: Vec3 | Sequence[float]) -> Multivector:
    """
Grade-1 vector.

Rust: `manifold::clifford::cl3::vec`
    """
    ...

def bivec(b: Vec3 | Sequence[float]) -> Multivector:
    """
Bivector dual to the vector b (the plane with normal b).

Rust: `manifold::clifford::cl3::bivec`
    """
    ...

def pseudoscalar() -> Multivector:
    """
The pseudoscalar e123.

Rust: `manifold::clifford::cl3::pseudoscalar`
    """
    ...

def rotor(axis: Vec3 | Sequence[float], angle: float) -> Multivector:
    """
Rotor for a rotation about `axis` by `angle` (matches quaternion
rotation).

Rust: `manifold::clifford::cl3::rotor`
    """
    ...

def rotate(v: Vec3 | Sequence[float], r: Multivector) -> Vec3:
    """
Rotate a vector with a rotor: R v R~.

Rust: `manifold::clifford::cl3::rotate`
    """
    ...

def cross_via_wedge(a: Vec3 | Sequence[float], b: Vec3 | Sequence[float]) -> Vec3:
    """
The cross product via the wedge: a x b = -I (a ∧ b).

Rust: `manifold::clifford::cl3::cross_via_wedge`
    """
    ...

def reflect(v: Vec3 | Sequence[float], n: Vec3 | Sequence[float]) -> Vec3:
    """
Reflect v in the plane with unit normal n.

Rust: `manifold::clifford::cl3::reflect`
    """
    ...

def to_vec3(m: Multivector) -> Optional[Vec3]:
    """
Extract the grade-1 part as a Vec3 (None if other grades dominate).

Rust: `manifold::clifford::cl3::to_vec3`
    """
    ...

def plane_from_points(a: Vec3 | Sequence[float], b: Vec3 | Sequence[float], c: Vec3 | Sequence[float]) -> Multivector:
    """
The plane (bivector) through three points, with weight twice the
triangle area.

Rust: `manifold::clifford::cl3::plane_from_points`
    """
    ...

def line_from_points(a: Vec3 | Sequence[float], b: Vec3 | Sequence[float]) -> Multivector:
    """
The line direction blade through two points (their difference).

Rust: `manifold::clifford::cl3::line_from_points`
    """
    ...

def rotor_to_quaternion(r: Multivector) -> Optional[Quaternion]:
    """
Rotor as quaternion.

Rust: `manifold::clifford::cl3::rotor_to_quaternion`
    """
    ...
