"""
Integer programming, dynamic programming, and combinatorial search.  Adding "and the answer must be a whole number" to a linear program changes its character completely. The feasible region stops being a convex polyhedron and becomes a scatter of lattice points inside one, so the guarantee that made linear programming easy -- that an optimum sits at a vertex, reachable by local moves -- is gone. What remains is the relaxation: drop the integrality, solve the linear program, and use its value as a bound on what any integer solution could achieve. Branch and bound is that observation applied recursively, and the bound is the only reason it terminates before enumerating everything.  Most problems here have that flavour. A few do not, and those are the dynamic programming classics: when a problem decomposes into overlapping subproblems whose optimal solutions compose, the exponential search collapses to a table and the answer is exact in polynomial time. Knapsack, edit distance and the rest are here because the boundary between the two situations is worth being able to see -- the 0/1 knapsack is NP-hard and yet has a pseudo-polynomial table, which is not a contradiction but a statement about what "polynomial" is measured against.  Where an exact method is impractical the module gives a greedy one with its proven ratio: first-fit-decreasing bin packing within `11/9` of optimal, greedy set cover within `H_n`, longest-processing-time scheduling within `4/3 - 1/(3m)`. Those ratios are worst-case guarantees rather than typical behaviour, and the tests check the guarantee holds against an exact answer on small instances rather than checking the greedy answer is merely plausible.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.statistics.distributions import Exponential
from rust_physics_engine.optimization.lp import LpProblem
from rust_physics_engine.linalg.matrix import Matrix

class EditOp:
    """
One edit in a transformation from one sequence to another.

Rust: `optimization::integer::EditOp`
    """
    ...

def branch_and_bound(p: LpProblem, integer_vars: list[int], node_limit: int) -> Optional[tuple[list[float], float]]:
    """
Solves a mixed-integer linear program by branch and bound.

Solves the linear relaxation; if the named variables all came out integral
the answer is optimal, and otherwise one fractional variable is chosen and
the problem split into the branch where it is rounded down and the branch
where it is rounded up. The relaxation's value bounds every integer
solution below it, so a branch whose relaxation is already worse than the
best integer solution found can be discarded whole -- which is the entire
content of the method, and the reason it beats enumeration.

`node_limit` caps the search. Returns `None` if the problem is infeasible
over the integers, or if the limit is reached before any integer solution
is found.

Errors:
Returns an error if a named variable is out of range, or the underlying
linear program is malformed.

Rust: `optimization::integer::branch_and_bound`
    """
    ...

def gomory_cuts(p: LpProblem, integer_vars: list[int], max_cuts: int) -> LpProblem:
    """
Adds Chvatal-Gomory rounding cuts to a linear program.

A cut is only worth the name if it is valid: satisfied by every integer
point of the feasible region, while removing part of the fractional
relaxation. The rounding cut earns that as follows. Scale a `<=` row by
some `lambda > 0`, so `lambda a . x <= lambda b` still holds. Rounding each
coefficient down can only lower the left-hand side when `x >= 0`, so
`floor(lambda a) . x <= lambda b`. But the left-hand side is now an integer
combination of integers, hence an integer, so it is bounded by the floor of
the right:


Every non-negative integer point survives that, and a fractional one need
not. Multipliers are tried at the reciprocals of the row's own
coefficients and at a few small fractions, and a cut is kept only when the
current relaxation optimum actually violates it.

Errors:
Returns an error unless every variable is integer and non-negative, which
is what the rounding argument requires, or if the relaxation has no
optimum.

Rust: `optimization::integer::gomory_cuts`
    """
    ...

def knapsack_01(values: list[int], weights: list[int], capacity: int) -> tuple[int, list[bool]]:
    """
The 0/1 knapsack by dynamic programming: each item taken at most once.

Returns the best value and which items to take. The table is
`O(n * capacity)`, which is polynomial in the *value* of the capacity but
exponential in the number of digits it takes to write it down -- the
problem is NP-hard, and the table is pseudo-polynomial rather than a
contradiction of that.

Panics:
Panics unless the value and weight lists have the same length.

Rust: `optimization::integer::knapsack_01`
    """
    ...

def knapsack_unbounded(values: list[int], weights: list[int], capacity: int) -> tuple[int, list[int]]:
    """
The unbounded knapsack: each item available without limit.

Returns the best value and how many of each item to take. A one-dimensional
table suffices, because an item may be reused within the same pass.

Panics:
Panics unless the lists match in length and every weight is positive.

Rust: `optimization::integer::knapsack_unbounded`
    """
    ...

def knapsack_bounded(values: list[int], weights: list[int], limits: list[int], capacity: int) -> tuple[int, list[int]]:
    """
The bounded knapsack: each item available up to its own limit.

Expanded by binary splitting -- an item with a limit of `k` becomes items
of multiplicity `1, 2, 4, ...` summing to `k` -- so any count up to the
limit is expressible and the 0/1 solver applies. That costs
`O(log k)` copies rather than the `k` a naive expansion would need.

Panics:
Panics unless all three lists match in length.

Rust: `optimization::integer::knapsack_bounded`
    """
    ...

def knapsack_multiple(values: list[int], weights: list[int], capacities: list[int]) -> tuple[int, list[Optional[int]]]:
    """
The multiple knapsack: several bins, each item into at most one.

Solved greedily by value density with a first-fit placement, which is not
exact -- the problem is NP-hard even with two bins -- so the result is a
lower bound on the optimum. Returns the total value and the bin each item
went into, `None` for an item left out.

Panics:
Panics unless the lists match in length.

Rust: `optimization::integer::knapsack_multiple`
    """
    ...

def knapsack_branch_bound(values: list[int], weights: list[int], capacity: int) -> tuple[int, list[bool]]:
    """
The 0/1 knapsack by branch and bound over the fractional relaxation.

The relaxation of a knapsack is solved by taking items in density order
and splitting the last one, which gives a bound in linear time once the
items are sorted. Nodes whose bound cannot beat the incumbent are pruned.

Exact, and must agree with `knapsack_01` on every instance -- one walks a
table and the other a search tree, so their agreement is a real check on
both.

Panics:
Panics unless the lists match in length.

Rust: `optimization::integer::knapsack_branch_bound`
    """
    ...

def subset_sum(xs: list[int], target: int) -> Optional[list[int]]:
    """
Indices of a subset summing exactly to `target`, if one exists.

Panics:
Panics if the values are large enough that the table would not fit.

Rust: `optimization::integer::subset_sum`
    """
    ...

def subset_sum_count(xs: list[int], target: int) -> int:
    """
How many subsets sum exactly to `target`.

Counted as a `BigInt`, since the number of subsets of an `n`-element set
is `2^n` and the count routinely overflows a machine word well before the
table does.

Rust: `optimization::integer::subset_sum_count`
    """
    ...

def partition_min_diff(xs: list[int]) -> tuple[int, list[bool]]:
    """
Splits the values into two groups whose totals are as close as possible.

Returns the difference and the membership flags. The problem is
NP-hard in general and solved here by the subset-sum table over half the
total, which is exact and pseudo-polynomial.

Rust: `optimization::integer::partition_min_diff`
    """
    ...

def bin_packing_ffd(sizes: list[float], capacity: float) -> list[list[int]]:
    """
Bin packing by first-fit-decreasing: sort the items large to small and put
each into the first bin it fits.

Returns the item indices in each bin. The rule uses at most
`11/9 OPT + 6/9` bins, a bound that is tight -- so the tests check the
guarantee against an exact answer rather than checking the result merely
looks reasonable.

Panics:
Panics if any item exceeds the bin capacity, which makes packing
impossible rather than merely hard.

Rust: `optimization::integer::bin_packing_ffd`
    """
    ...

def bin_packing_lower_bound(sizes: list[float], capacity: float) -> int:
    """
The fewest bins any packing could use: the total size divided by the
capacity, rounded up.

A valid lower bound because a bin holds at most `capacity`, so no packing
can use fewer. It is not always attainable -- three items of size 0.4 need
two bins though their total is 1.2 -- which is exactly why it is a bound
and not an answer.

Rust: `optimization::integer::bin_packing_lower_bound`
    """
    ...

def bin_packing_exact_small(sizes: list[float], capacity: float) -> list[list[int]]:
    """
The exact minimum number of bins, by trying each count in turn.

Exponential, and meant for the small instances the tests use to check the
first-fit-decreasing guarantee. Returns the packing.

Panics:
Panics under the same conditions as `bin_packing_ffd`.

Rust: `optimization::integer::bin_packing_exact_small`
    """
    ...

def set_cover_greedy(universe_n: int, sets: list[list[int]]) -> Optional[list[int]]:
    """
Greedy set cover: repeatedly take the set covering the most of what is
still uncovered.

Returns the indices of the chosen sets, or `None` if the sets do not cover
the universe at all. Greedy uses at most `H_n` times the optimal number of
sets, where `H_n` is the `n`-th harmonic number, and no polynomial
algorithm does asymptotically better unless P equals NP -- so this is not
a placeholder for something better.

Rust: `optimization::integer::set_cover_greedy`
    """
    ...

def set_cover_exact_small(universe_n: int, sets: list[list[int]]) -> Optional[list[int]]:
    """
The exact minimum set cover, by trying every subset of the sets in order of
size.

For the small instances that make the greedy ratio checkable.

Panics:
Panics if there are more than 20 sets, where the enumeration stops being
reasonable.

Rust: `optimization::integer::set_cover_exact_small`
    """
    ...

def facility_location_greedy(open_costs: list[float], serve_costs: Matrix | Sequence[Sequence[float]]) -> tuple[float, list[bool]]:
    """
Uncapacitated facility location, solved greedily.

`open_costs[i]` is the fixed cost of opening facility `i` and
`serve_costs[(i, j)]` the cost of serving client `j` from it. Facilities
are opened one at a time, each time the one whose opening cost plus
improved service most reduces the total.

Returns the total cost and which facilities to open.

Panics:
Panics unless the shapes agree and there is at least one facility.

Rust: `optimization::integer::facility_location_greedy`
    """
    ...

def cutting_stock_column_generation(demand: list[int], lengths: list[int], stock_length: int, max_rounds: int) -> float:
    """
The cutting stock problem by column generation, relaxed.

Each cutting pattern is a column of the linear program, and there are far
too many to write down, so patterns are generated on demand: solve the
relaxation over the patterns in hand, read the dual prices off it, and ask
which single new pattern would be most profitable at those prices. That
subproblem is an unbounded knapsack, and when its best pattern is not
profitable the relaxation is optimal over *all* patterns without ever
having enumerated them.

Returns the relaxed number of stock lengths needed, which lower-bounds the
integer answer.

Errors:
Returns an error if the inputs disagree in length, or a piece is longer
than the stock.

Rust: `optimization::integer::cutting_stock_column_generation`
    """
    ...

def coin_change_min(coins: list[int], amount: int) -> Optional[list[int]]:
    """
The fewest coins summing to `amount`, or `None` if no combination does.

Returns how many of each denomination. Greedy is wrong for general
denominations -- with coins 1, 3, 4 and an amount of 6, greedy takes
4 + 1 + 1 while two threes do it -- so this is a table, not a loop.

Rust: `optimization::integer::coin_change_min`
    """
    ...

def coin_change_count(coins: list[int], amount: int) -> int:
    """
How many combinations of coins sum to `amount`, order disregarded.

Iterating coins in the outer loop is what makes this count combinations
rather than permutations: each coin is considered once for the whole table,
so `1 + 2` and `2 + 1` are never both counted.

Rust: `optimization::integer::coin_change_count`
    """
    ...

def longest_increasing_subsequence(x: list[float]) -> list[int]:
    """
Indices of a longest strictly increasing subsequence, in `O(n log n)`.

The trick is to keep, for each length, the smallest value that can end a
subsequence of that length. That list is sorted by construction, so the
position each new element belongs at is a binary search rather than a scan
-- which is what turns the quadratic table into an `n log n` sweep.

Rust: `optimization::integer::longest_increasing_subsequence`
    """
    ...

def edit_distance(a: list[int], b: list[int]) -> int:
    """
The Levenshtein distance: the fewest single-symbol insertions, deletions
and substitutions turning `a` into `b`.

It is a metric on sequences -- symmetric, zero only between equal
sequences, and obeying the triangle inequality -- which is what makes it
usable for clustering and nearest-neighbour search rather than merely a
similarity score.

Rust: `optimization::integer::edit_distance`
    """
    ...

def edit_distance_ops(a: list[int], b: list[int]) -> list[EditOp]:
    """
The edits themselves, in order, from a full table.

Applying them to `a` reproduces `b`, and their count of non-`Keep`
operations is exactly `edit_distance`.

Rust: `optimization::integer::edit_distance_ops`
    """
    ...

def longest_common_subsequence(a: list[int], b: list[int]) -> list[int]:
    """
A longest common subsequence of two sequences.

Rust: `optimization::integer::longest_common_subsequence`
    """
    ...

def matrix_chain_order(dims: list[int]) -> tuple[int, str]:
    """
The cheapest way to parenthesise a chain of matrix multiplications.

`dims` holds the shared dimensions: matrix `k` is `dims[k]` by
`dims[k + 1]`. Returns the scalar multiplication count and the
parenthesisation as a string.

The order matters enormously -- multiplying a `1x100`, `100x1` and `1x100`
chain costs 200 one way and 20,000 the other -- and the number of
parenthesisations is Catalan, so the table is what makes it tractable.

Panics:
Panics unless there are at least two dimensions.

Rust: `optimization::integer::matrix_chain_order`
    """
    ...

def rod_cutting(prices: list[int], n: int) -> tuple[int, list[int]]:
    """
The most valuable way to cut a rod of length `n` into pieces.

`prices[k]` is what a piece of length `k + 1` sells for. Returns the value
and the piece lengths.

Rust: `optimization::integer::rod_cutting`
    """
    ...

def egg_drop(eggs: int, floors: int) -> int:
    """
The fewest drops that always determine the critical floor, with `eggs`
eggs and `floors` floors.

The classic answer for two eggs and a hundred floors is fourteen: drop
from 14, then 27, then 39, and so on, each interval one shorter than the
last so the worst case stays flat.

Rust: `optimization::integer::egg_drop`
    """
    ...

def optimal_bst(frequencies: list[float]) -> float:
    """
The expected search cost of the optimal binary search tree over keys with
the given access frequencies.

Frequencies are taken in key order. The optimum is not the balanced tree:
a key accessed far more often than the rest belongs near the root even if
that unbalances everything else.

Rust: `optimization::integer::optimal_bst`
    """
    ...

def viterbi_generic(transition: Matrix | Sequence[Sequence[float]], emission: Matrix | Sequence[Sequence[float]]) -> list[int]:
    """
The least-cost state path through a trellis.

`transition[(a, b)]` is the cost of moving from state `a` to state `b`, and
`emission[(s, t)]` the cost of state `s` at time `t`. Returns the best path.

The same recursion as the probabilistic Viterbi algorithm in
`stochastic::hmm`, stated in costs rather than log-probabilities -- which
is the more general form, since any additive path cost works.

Errors:
Returns an error if the matrices disagree in shape or there are no steps.

Rust: `optimization::integer::viterbi_generic`
    """
    ...

def exact_cover_dlx(matrix: list[list[bool]]) -> Optional[list[int]]:
    """
Solves an exact cover problem: choose rows so that every column is covered
exactly once.

Implemented as Knuth's Algorithm X with the column-selection heuristic that
makes dancing links effective -- always branch on the column with the
fewest remaining options, which fails fast and keeps the search tree
narrow. The doubly linked list of the classic implementation is replaced
here by bitmask bookkeeping, which is the same algorithm with the same
search order for the column counts this module needs.

Returns the chosen row indices, or `None` if no exact cover exists.

Errors:
Returns an error for a ragged matrix or more than 64 columns.

Rust: `optimization::integer::exact_cover_dlx`
    """
    ...

def n_queens(n: int) -> list[list[int]]:
    """
Every placement of `n` non-attacking queens, each as the column of the
queen in each row.

Panics:
Panics if `n` exceeds 12, where the count runs into the hundreds of
thousands and the list stops being a sensible return value.

Rust: `optimization::integer::n_queens`
    """
    ...

def n_queens_count(n: int) -> int:
    """
How many placements of `n` non-attacking queens exist.

The sequence begins 1, 0, 0, 2, 10, 4, 40, 92 for boards one to eight wide
-- there is no solution on a three-square board, and a six-square board has
fewer than a five-square one, which is the usual surprise.

Panics:
Panics if `n` exceeds 14.

Rust: `optimization::integer::n_queens_count`
    """
    ...

def constraint_propagation_ac3(domains: list[int], constraints: list[tuple[int, int]]) -> Optional[list[int]]:
    """
Arc consistency by AC-3: prunes values that cannot participate in any
solution.

`domains[i]` is a bitmask of the values variable `i` may take, and
`constraints` lists pairs `(i, j)` that must differ. Repeatedly removes any
value in one domain with no support in a neighbour's, until nothing
changes.

Returns the reduced domains, or `None` if some domain empties -- which
proves the constraints unsatisfiable without any search. AC-3 never removes
a value that appears in a solution, so the reduced domains are a sound
simplification rather than a heuristic.

Rust: `optimization::integer::constraint_propagation_ac3`
    """
    ...
