"""
Common gases.  Molar mass, density at STP, specific heat at constant pressure and the specific heat ratio `γ`, thermal conductivity, viscosity and the speed of sound.  `γ` is the entry most often needed: it fixes the adiabatic relations and the speed of sound `c = √(γRT/M)`, and it follows the molecular structure -- about 5/3 for a monatomic gas, 7/5 for a diatomic one.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


class Gas:
    """
Common gases.

Molar mass, density at STP, specific heat at constant pressure and the
specific heat ratio `γ`, thermal conductivity, viscosity and the speed
of sound.

`γ` is the entry most often needed: it fixes the adiabatic relations
and the speed of sound `c = √(γRT/M)`, and it follows the molecular
structure -- about 5/3 for a monatomic gas, 7/5 for a diatomic one.
A gas with its thermodynamic and transport properties at STP.

All values use SI units:
- `molar_mass`: kg/mol
- `cp`, `cv`: J/(kg*K)
- `density_stp`: kg/m^3
- `dynamic_viscosity`: Pa*s
- `thermal_conductivity`: W/(m*K)

Rust: `materials::gases::Gas`
    """
    @property
    def name(self) -> str: ...
    @property
    def formula(self) -> str: ...
    @property
    def molar_mass(self) -> float: ...
    @property
    def specific_heat_ratio(self) -> float: ...
    @property
    def cp(self) -> float: ...
    @property
    def cv(self) -> float: ...
    @property
    def density_stp(self) -> float: ...
    @property
    def dynamic_viscosity(self) -> float: ...
    @property
    def thermal_conductivity(self) -> float: ...

def by_name(name: str) -> Optional[Gas]:
    """
Looks up a gas by name using case-insensitive ASCII comparison.

Zero-allocation: uses `eq_ignore_ascii_case` instead of `to_lowercase`.

Rust: `materials::gases::by_name`
    """
    ...

def all() -> list[Gas]:
    """
Returns a slice of all gases in the database.

Rust: `materials::gases::all`
    """
    ...
