"""
Audio-rate oscillators and test signals: PolyBLEP anti-aliased classics, additive resynthesis, mipmapped wavetables, colored noise, chirps, and measurement sweeps.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.statistics.distributions import Exponential

class NoiseColor:
    """
Noise spectra for `NoiseGen`.

Rust: `audio::oscillators::NoiseColor`
    """
    ...

class NoiseGen:
    """
Deterministic colored-noise generator.

Rust: `audio::oscillators::NoiseGen`
    """
    def __init__(self, seed: int, color: NoiseColor) -> None: ...
    def next(self) -> float: ...

class Oscillator:
    """
Phase-accumulating audio oscillator (PolyBLEP for saw/square,
polyBLAMP triangle, seeded noise, optional wavetables).

Rust: `audio::oscillators::Oscillator`
    """
    def __init__(self, kind: Waveform, freq: float, fs: float) -> None: ...
    def next(self) -> float: ...
    def set_freq(self, freq: float) -> None: ...
    def set_phase(self, phase: float) -> None: ...
    def block(self, n: int) -> list[float]: ...
    def fm(self, mod_hz: float) -> float: ...
    def hard_sync(self, reset: bool) -> None: ...
    @property
    def phase(self) -> float: ...
    @property
    def freq(self) -> float: ...
    @property
    def fs(self) -> float: ...
    @property
    def kind(self) -> Waveform: ...

class Waveform:
    """
Waveform selector for `Oscillator`.

Rust: `audio::oscillators::Waveform`
    """
    ...

class Wavetable:
    """
Mipmapped single-cycle wavetable: table m is band-limited so that it
can play at up to `base_freqs[m]` without aliasing.

Rust: `audio::oscillators::Wavetable`
    """
    def __init__(self, tables: list[list[float]], base_freqs: list[float]) -> None: ...
    @staticmethod
    def from_fn(f: Callable[[float], float], size: int, n_mips: int, fs: float) -> Wavetable: ...
    @staticmethod
    def from_harmonics(amps: list[float], size: int, n_mips: int, fs: float) -> Wavetable: ...
    def lookup(self, phase: float, freq: float) -> float: ...
    @staticmethod
    def saw(fs: float) -> Wavetable: ...
    @staticmethod
    def square(fs: float) -> Wavetable: ...
    @staticmethod
    def triangle(fs: float) -> Wavetable: ...
    @property
    def tables(self) -> list[list[float]]: ...
    @property
    def base_freqs(self) -> list[float]: ...

def polyblep_saw(phase: float, dt: float) -> float:
    """
Anti-aliased sawtooth (−1..1) at phase t with increment dt.

Rust: `audio::oscillators::polyblep_saw`
    """
    ...

def polyblep_square(phase: float, dt: float, duty: float) -> float:
    """
Anti-aliased pulse with the given duty cycle.

Rust: `audio::oscillators::polyblep_square`
    """
    ...

def polyblep_triangle(phase: float, dt: float) -> float:
    """
Anti-aliased triangle (corner smoothing by polyBLAMP; triangle
aliasing is already −12 dB/oct so the correction is mild).

Rust: `audio::oscillators::polyblep_triangle`
    """
    ...

def additive_saw(phase: float, n_harmonics: int) -> float:
    """
Band-limited saw from its Fourier series (n harmonics).

Rust: `audio::oscillators::additive_saw`
    """
    ...

def additive_square(phase: float, n_harmonics: int) -> float:
    """
Band-limited square from its Fourier series.

Rust: `audio::oscillators::additive_square`
    """
    ...

def additive_triangle(phase: float, n_harmonics: int) -> float:
    """
Band-limited triangle from its Fourier series.

Rust: `audio::oscillators::additive_triangle`
    """
    ...

def chirp_linear(f0: float, f1: float, duration: float, fs: float) -> list[float]:
    """
Linear chirp from f0 to f1 over `duration` seconds.

Rust: `audio::oscillators::chirp_linear`
    """
    ...

def chirp_exponential(f0: float, f1: float, duration: float, fs: float) -> list[float]:
    """
Exponential (logarithmic-sweep) chirp.

Rust: `audio::oscillators::chirp_exponential`
    """
    ...

def chirp_hyperbolic(f0: float, f1: float, duration: float, fs: float) -> list[float]:
    """
Hyperbolic chirp (linear period sweep).

Rust: `audio::oscillators::chirp_hyperbolic`
    """
    ...

def sine_sweep_with_inverse(f0: float, f1: float, duration: float, fs: float) -> tuple[list[float], list[float]]:
    """
Farina exponential sweep and its inverse filter: convolving the two
yields (a delayed) impulse, the standard impulse-response
measurement pair.

Rust: `audio::oscillators::sine_sweep_with_inverse`
    """
    ...

def impulse(n: int, pos: int) -> list[float]:
    """
Unit impulse at `pos` in an n-sample buffer.

Rust: `audio::oscillators::impulse`
    """
    ...

def dc(n: int, level: float) -> list[float]:
    """
Constant (DC) buffer.

Rust: `audio::oscillators::dc`
    """
    ...

def multisine(freqs: list[float], amps: list[float], phases: list[float], n: int, fs: float) -> list[float]:
    """
Sum of sinusoids with per-tone amplitude and phase.

Panics:
Panics if the parameter arrays differ in length.

Rust: `audio::oscillators::multisine`
    """
    ...

def schroeder_phase_multisine(n_tones: int, n: int, fs: float) -> list[float]:
    """
Schroeder-phase multisine of `n_tones` bin-aligned harmonics of
fs/n: near-minimal crest factor for broadband excitation.

Rust: `audio::oscillators::schroeder_phase_multisine`
    """
    ...

def pulse_train(freq: float, width: float, n: int, fs: float) -> list[float]:
    """
Rectangular pulse train: `width` seconds high per period.

Rust: `audio::oscillators::pulse_train`
    """
    ...

def band_limited_impulse_train(freq: float, n: int, fs: float) -> list[float]:
    """
Band-limited impulse train (all cosine harmonics up to Nyquist,
unit DC component).

Rust: `audio::oscillators::band_limited_impulse_train`
    """
    ...
