"""
Singular value decomposition by one-sided Jacobi rotations.  Reference: Golub & Van Loan §8.6 / Demmel & Veselić, "Jacobi's method is more accurate than QR". Produces the thin decomposition A = U·Σ·Vᵀ with U m×n (orthonormal columns where σ > 0), Σ the non-negative singular values in descending order, and Vᵀ n×n.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.linalg import Mat3
from numeria.linalg.matrix import Matrix
from numeria.math import Vec3

class Svd:
    """
Thin SVD: A = U·Σ·Vᵀ.

Rust: `linalg::svd::Svd`
    """
    def __init__(self, u: Matrix | Sequence[Sequence[float]], sigma: list[float], vt: Matrix | Sequence[Sequence[float]]) -> None: ...
    @property
    def u(self) -> Matrix: ...
    @property
    def sigma(self) -> list[float]: ...
    @property
    def vt(self) -> Matrix: ...

def svd(a: Matrix | Sequence[Sequence[float]]) -> Svd:
    """
One-sided Jacobi SVD of an m×n matrix with m ≥ n; for m < n the
transpose is factored and the roles of U and V are swapped.

Rust: `linalg::svd::svd`
    """
    ...

def pseudoinverse(a: Matrix | Sequence[Sequence[float]], rcond: float) -> Matrix:
    """
Moore-Penrose pseudoinverse A⁺ = V·Σ⁺·Uᵀ; singular values below
`rcond · σ_max` are treated as zero.

Rust: `linalg::svd::pseudoinverse`
    """
    ...

def rank(a: Matrix | Sequence[Sequence[float]], tol: float) -> int:
    """
Numerical rank: the number of singular values greater than `tol`.

Rust: `linalg::svd::rank`
    """
    ...

def kabsch(p: list[Vec3 | Sequence[float]], q: list[Vec3 | Sequence[float]]) -> Mat3:
    """
Kabsch algorithm: the rotation R minimizing Σ‖R·pᵢ − qᵢ‖².

Both point sets are used as given (no centroid subtraction); center
them first for the usual superposition problem. Fails with
`DimensionMismatch` when the sets differ in length and
`InvalidArgument` when fewer than 3 points are supplied.

Rust: `linalg::svd::kabsch`
    """
    ...
