"""
Computational neuroscience: single neurons, spike trains, synapses and the small networks built from them.  # Units  The conductance-based models use the squid axon's units throughout: millivolts, milliseconds, microfarads and microamps per square centimetre, and millisiemens per square centimetre. A rate is therefore a count per millisecond unless a function says otherwise, and the spike frequencies reported by the F-I curves are converted to hertz where that is the useful number. The reduced models -- FitzHugh-Nagumo and the drift-diffusion process -- carry no units at all.  # What a spike is here  Every model that fires does so by one of two mechanisms, and the difference decides what can be asked of it. Hodgkin-Huxley, Morris-Lecar and FitzHugh-Nagumo generate the spike from their own dynamics: the upstroke is a solution of the equations and the threshold is not a parameter but an emergent property of the vector field. The integrate-and-fire family -- LIF, Izhikevich, AdEx -- *stipulates* the spike: the equations describe only the approach, and a rule replaces the voltage when it crosses a number. The second kind is far cheaper and reproduces firing statistics well; it has no answer to questions about the spike's shape, because the shape was never computed.  Spikes are detected in a trace by an upward crossing of a fixed level, which is the right test for a model whose spikes are tall and brief.  # Equilibrium potentials  `biophysics::nernst_potential` and `biophysics::goldman_potential` already provide the reversal potentials these models take as constants, and are not repeated here.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.statistical_mechanics.kinetics import Inhibition
from numeria.linalg.matrix import Matrix
from numeria.statistics.distributions import Poisson
from numeria.monte_carlo import Rng

class MorrisLecar:
    """
Morris-Lecar's parameters, in the squid axon's units.

Rust: `biophysics::neuro::MorrisLecar`
    """
    def __init__(self, c_m: float, g_l: float, g_ca: float, g_k: float, v_l: float, v_ca: float, v_k: float, v1: float, v2: float, v3: float, v4: float, phi: float) -> None: ...
    @staticmethod
    def hopf() -> MorrisLecar: ...
    @staticmethod
    def saddle_node() -> MorrisLecar: ...
    @property
    def c_m(self) -> float: ...
    @property
    def g_l(self) -> float: ...
    @property
    def g_ca(self) -> float: ...
    @property
    def g_k(self) -> float: ...
    @property
    def v_l(self) -> float: ...
    @property
    def v_ca(self) -> float: ...
    @property
    def v_k(self) -> float: ...
    @property
    def v1(self) -> float: ...
    @property
    def v2(self) -> float: ...
    @property
    def v3(self) -> float: ...
    @property
    def v4(self) -> float: ...
    @property
    def phi(self) -> float: ...

def spike_times(trace: list[tuple[float, float]], level: float) -> list[float]:
    """
The times at which a voltage trace crosses `level` upward, interpolated
between samples.

The level is the caller's because the models here peak at very
different voltages: Hodgkin-Huxley and Izhikevich overshoot well past
zero, while `adex` tops out at `v_t + 10 * slope`, which is usually
still negative. A detector fixed at zero would report that an AdEx
neuron never fires.

Rust: `biophysics::neuro::spike_times`
    """
    ...

def hh_steady_state(v: float) -> tuple[float, float, float]:
    """
The steady-state gating variables at a holding potential.

A gate settles at `alpha / (alpha + beta)`; starting a run anywhere
else adds a transient that has nothing to do with the stimulus.

Rust: `biophysics::neuro::hh_steady_state`
    """
    ...

def hodgkin_huxley(i_ext: Callable[[float], float], t_end: float, dt: float) -> list[tuple[float, float, float, float, float]]:
    """
The Hodgkin-Huxley membrane, integrated with fixed-step RK4.

Returns `(t, V, m, h, n)` per step. The run starts from the gating
variables' steady state at `HH_V_REST`, so an unstimulated axon stays
where it is instead of relaxing through a spurious transient.

The action potential is not built in. Sodium activation `m` is fast and
its cube makes the inward current explosive; inactivation `h` and
potassium activation `n` are ten times slower and end it. That
separation of timescales is the whole mechanism, and it is why the
threshold is a property of the trajectory rather than a parameter.

A strongly *hyperpolarising* current is the one thing this integrator
cannot take. Below about -25 uA/cm^2 the voltage falls far enough that
`beta_m`, which grows exponentially as the membrane hyperpolarises,
reaches thousands per millisecond and a fixed step of 0.01 ms is no
longer stable. That is reported as a breakdown rather than returned as
a trace full of nonsense. Depolarising currents have no such limit:
hundreds of uA/cm^2 integrate cleanly, and simply drive the model into
depolarisation block.

Errors:
Returns an error for a non-positive `t_end`, a `dt` outside `(0, 0.05]`
-- above which fixed-step RK4 loses the upstroke -- a `dt` that is not
smaller than `t_end`, or an integration that diverges.

Rust: `biophysics::neuro::hodgkin_huxley`
    """
    ...

def hh_spike_times(trace: list[tuple[float, float, float, float, float]]) -> list[float]:
    """
The spike times in a Hodgkin-Huxley trace.

Rust: `biophysics::neuro::hh_spike_times`
    """
    ...

def hh_spike_threshold_estimate() -> float:
    """
The smallest sustained current, in uA/cm^2, that makes the model fire.

Found by bisection on "does a 120 ms step produce a spike". This is the
rheobase, and it is not the same thing as a voltage threshold: a brief
pulse well above this current can fail to fire, and the model has no
single voltage at which firing becomes inevitable.

Rust: `biophysics::neuro::hh_spike_threshold_estimate`
    """
    ...

def hh_fi_curve(currents: list[float]) -> list[tuple[float, float]]:
    """
The firing rate in hertz against sustained current, for each current in
`currents`.

Hodgkin-Huxley's F-I curve is discontinuous: at the rheobase the rate
jumps to about 50 Hz rather than rising from zero, because the
oscillation is born through a subcritical Hopf bifurcation with a
finite frequency. A neuron whose rate can be tuned smoothly to
arbitrarily low values -- a type I neuron -- needs a different
bifurcation, which `morris_lecar` can be parameterised to show.

The first 30 ms of each run are discarded so the onset transient does
not enter the rate.

Errors:
Returns an error if `currents` is empty or holds a value that is not
finite.

Rust: `biophysics::neuro::hh_fi_curve`
    """
    ...

def fitzhugh_nagumo_neuron(a: float, b: float, tau: float, current: float, v0: float, w0: float, t_end: float, dt: float) -> list[tuple[float, float, float]]:
    """
FitzHugh-Nagumo, the two-variable caricature of an excitable membrane.

`dv/dt = v - v^3/3 - w + I`, `dw/dt = (v + a - b w) / tau`. Returns
`(t, v, w)` per step, dimensionless throughout.

The point of the reduction is that two variables can be drawn: the
cubic `v` nullcline and the straight `w` nullcline cross at a fixed
point, and whether that crossing sits on the cubic's middle branch
decides whether the neuron rests or oscillates. Excitability -- a small
push decaying, a slightly larger one taking a long excursion -- is
visible in the phase plane in a way it is not in four dimensions.

Errors:
Returns an error for a non-positive `tau`, or a run length or step size
out of range.

Rust: `biophysics::neuro::fitzhugh_nagumo_neuron`
    """
    ...

def morris_lecar(params: MorrisLecar, current: float, v0: float, w0: float, t_end: float, dt: float) -> list[tuple[float, float, float]]:
    """
Morris-Lecar, a calcium-potassium membrane with one gating variable.

Returns `(t, V, w)` per step. The calcium current is instantaneous,
which is what removes the second gate: only potassium activation `w`
has its own equation.

Errors:
Returns an error for a non-positive capacitance or slope, or a run
length or step size out of range.

Rust: `biophysics::neuro::morris_lecar`
    """
    ...

def izhikevich(a: float, b: float, c: float, d: float, current: float, t_end: float, dt: float) -> list[tuple[float, float]]:
    """
Izhikevich's two-variable spiking model.

`v' = 0.04 v^2 + 5 v + 140 - u + I` and `u' = a (b v - u)`, with the
reset `v <- c`, `u <- u + d` once `v` reaches 30 mV. Returns `(t, v)`
per step, with the spike sample set to the 30 mV peak so a trace can be
plotted without the reset looking like a downstroke.

The quadratic term is what makes it a spike generator rather than a
leaky integrator: above the unstable fixed point `v` runs away in finite
time, and the reset is what stops it. Two parameters then buy most of
the qualitative variety real neurons show -- see
`izhikevich_presets`.

The published implementation advances `v` in two half-steps for
stability, and that is what is done here; `dt` is the reporting step.

Errors:
Returns an error for a non-positive `a`, or a run length or step size
out of range.

Rust: `biophysics::neuro::izhikevich`
    """
    ...

def izhikevich_presets() -> list[tuple[str, list[float]]]:
    """
The five firing patterns Izhikevich's paper names, as `(a, b, c, d)`.

Regular spiking, intrinsically bursting, chattering, fast spiking and
low-threshold spiking. `c` and `d` set what happens after a spike, so
they are what separates a regular spiker from a burster; `a` and `b`
set the recovery variable's speed and its coupling to voltage.

Rust: `biophysics::neuro::izhikevich_presets`
    """
    ...

def adex(c_m: float, g_l: float, e_l: float, slope: float, v_t: float, tau_w: float, a: float, b: float, v_reset: float, current: float, t_end: float, dt: float) -> list[tuple[float, float, float]]:
    """
The adaptive exponential integrate-and-fire neuron.

`C dV/dt = -g_L (V - E_L) + g_L dt_slope exp((V - v_t)/dt_slope) - w + I`
with `tau_w dw/dt = a (V - E_L) - w`, and the reset `V <- v_reset`,
`w <- w + b` at the peak. Returns `(t, V, w)` per step.

The exponential term is fitted to the sodium activation curve, so the
upstroke's *shape* near threshold is right even though the spike itself
is still stipulated. The adaptation current `w` is what the leaky
integrator lacks: it accumulates over a spike train and slows it, which
is the commonest firing pattern in cortex and cannot be produced by a
model with one variable.

The recorded spike sample sits at the peak `v_t + 10 * slope`, which is
where `spike_times` should be pointed to count them.

Errors:
Returns an error for a non-positive capacitance, conductance, slope or
adaptation time constant, or a run length or step size out of range.

Rust: `biophysics::neuro::adex`
    """
    ...

def lif_neuron(current: float, tau: float, v_th: float, v_reset: float, refractory: float, noise: float, t_end: float, dt: float, rng: Rng) -> list[float]:
    """
The leaky integrate-and-fire neuron's spike times.

`tau dV/dt = -(V - V_rest) + R I`, with a spike and a reset to
`v_reset` whenever `V` reaches `v_th`, and an absolute refractory
period during which the voltage is clamped. Gaussian current noise of
standard deviation `noise` is added per unit time, scaled so the
result does not depend on `dt`.

The voltage between spikes carries no information the times do not, so
only the times are returned.

Errors:
Returns an error for a non-positive `tau`, a negative refractory period
or noise, a threshold at or below the reset, or a run length or step
size out of range.

Rust: `biophysics::neuro::lif_neuron`
    """
    ...

def lif_fi_exact(current: float, tau: float, v_th: float, v_reset: float, refractory: float) -> float:
    """
The leaky integrate-and-fire firing rate in the noiseless case, exactly.

`1 / (t_ref + tau ln((I - V_reset)/(I - V_th)))` for a current above
threshold, and zero otherwise. The rest potential is taken as zero, so
`I` is measured in the same units as the voltages.

The logarithm is what makes the curve saturate: doubling a large
current barely changes the rate, because the refractory period comes to
dominate. Below `v_th` the neuron never fires however long you wait --
the exact zero, not a very small number.

Errors:
Returns an error for a non-positive `tau`, a negative refractory
period, or a threshold at or below the reset.

Rust: `biophysics::neuro::lif_fi_exact`
    """
    ...

def interspike_intervals(spikes: list[float]) -> list[float]:
    """
The gaps between successive spikes.

Errors:
Returns an error if the times are not sorted, since an unsorted train
would silently produce negative intervals.

Rust: `biophysics::neuro::interspike_intervals`
    """
    ...

def cv_isi(spikes: list[float]) -> float:
    """
The coefficient of variation of the interspike intervals.

One for a Poisson process, because an exponential distribution's
standard deviation equals its mean; near zero for a regular pacemaker;
and above one for a bursting cell, whose intervals come in two very
different sizes. It is a measure of *irregularity*, not of rate: it is
unchanged by running the clock faster.

Errors:
Returns an error for fewer than three spikes, an unsorted train, or a
mean interval of zero.

Rust: `biophysics::neuro::cv_isi`
    """
    ...

def fano_factor(counts: list[int]) -> float:
    """
The Fano factor of a set of counts: variance over mean.

One for a Poisson process. Unlike `cv_isi` this is measured over a
window, so the two can disagree: a train with regular intervals but a
drifting rate has a low CV and a high Fano factor, because the
irregularity is between windows rather than within them.

Errors:
Returns an error for fewer than two counts or a mean of zero.

Rust: `biophysics::neuro::fano_factor`
    """
    ...

def poisson_spike_train(rate: float, t_end: float, rng: Rng) -> list[float]:
    """
A homogeneous Poisson spike train on `[0, t_end)`.

Generated by accumulating exponential waiting times, which is exact --
there is no time step and so no chance of two spikes in one bin.

Errors:
Returns an error for a non-positive rate or run length, or an expected
count above ten million.

Rust: `biophysics::neuro::poisson_spike_train`
    """
    ...

def psth(trains: list[list[float]], bin: float, t_end: float) -> list[float]:
    """
The peri-stimulus time histogram: the mean firing rate in each bin,
across trials.

Dividing by the bin width and the trial count is what makes this a
rate rather than a count, and is what lets histograms with different
binnings be compared. The bin width is the whole choice in a PSTH: too
wide and a transient response is smeared into the background, too
narrow and every bin is zero or one.

Errors:
Returns an error for no trials, a non-positive bin width or window, or
a spike time outside `[0, t_end)`.

Rust: `biophysics::neuro::psth`
    """
    ...

def raster_data(trains: list[list[float]]) -> list[tuple[float, int]]:
    """
Every spike as a `(time, trial)` pair, sorted by time.

The raster is the raw data a PSTH averages away, and the two answer
different questions: a response present on every trial and one present
on half the trials at twice the rate give the same histogram.

Rust: `biophysics::neuro::raster_data`
    """
    ...

def spike_triggered_average(stimulus: list[float], dt: float, spikes: list[float], window: int) -> list[float]:
    """
The spike-triggered average: the mean stimulus in the `window` samples
before a spike.

Returned oldest sample first, so the last entry is the stimulus at the
spike itself. Spikes too early for a full window are skipped, and the
count of those that contributed decides the divisor.

This estimates the neuron's linear filter only if the stimulus is white:
any correlation in the stimulus appears in the average and will be
mistaken for structure in the neuron. The usual remedy is to whiten by
the stimulus autocorrelation, which is a different calculation from
this one.

Errors:
Returns an error for an empty stimulus, a non-positive sampling step, a
zero window, a window longer than the stimulus, or no usable spike.

Rust: `biophysics::neuro::spike_triggered_average`
    """
    ...

def tuning_curve_fit_von_mises(angles: list[float], rates: list[float]) -> tuple[float, float, float]:
    """
Fits `r(theta) = amplitude * exp(kappa * cos(theta - preferred))` to a
set of angles and rates, returning `(preferred, kappa, amplitude)`.

Taking logarithms turns the von Mises form into
`ln r = ln A + (kappa cos mu) cos theta + (kappa sin mu) sin theta`,
which is linear in three coefficients and so is solved exactly rather
than searched for. `preferred` comes back in `(-pi, pi]`.

The price of the linearisation is that it fits the log rate, so it
weights a doubling at a low rate as heavily as a doubling at the peak.
With noiseless data that costs nothing and the fit is exact; with noisy
data it biases toward the flanks.

Errors:
Returns an error for fewer than three points, mismatched lengths, a
non-positive rate, or angles that do not determine the fit -- all equal,
or spread over too little of the circle.

Rust: `biophysics::neuro::tuning_curve_fit_von_mises`
    """
    ...

def synapse_exp(g_max: float, tau: float, spikes: list[float], t: float) -> float:
    """
The conductance of an exponential synapse at time `t`, given the
presynaptic spike times.

Each spike adds `g_max` instantaneously and it decays as
`exp(-(t - t_spike)/tau)`. Conductances sum, so a burst arriving within
a time constant produces more than one spike's worth -- which is what
makes a synapse a low-pass filter of its input rather than a repeater.

Errors:
Returns an error for a non-positive `tau` or an unsorted spike train.

Rust: `biophysics::neuro::synapse_exp`
    """
    ...

def alpha_synapse(g_max: float, tau: float, spikes: list[float], t: float) -> float:
    """
The conductance of an alpha synapse at time `t`.

`g_max * x * exp(1 - x)` with `x = (t - t_spike)/tau`, which peaks at
exactly `g_max` one time constant after the spike. The rise is what
distinguishes it from `synapse_exp`: a real conductance cannot jump,
and the delay to peak matters when the question is whether two inputs
coincide.

Errors:
Returns an error for a non-positive `tau` or an unsorted spike train.

Rust: `biophysics::neuro::alpha_synapse`
    """
    ...

def stdp_window(delta: float, a_plus: float, a_minus: float, tau_plus: float, tau_minus: float) -> float:
    """
The spike-timing-dependent plasticity window: the weight change for a
post-minus-pre interval of `delta`.

Positive `delta` -- the postsynaptic spike came second -- potentiates by
`a_plus exp(-delta/tau_plus)`; negative depresses by
`-a_minus exp(delta/tau_minus)`. Exactly simultaneous spikes give zero,
which is the discontinuity at the origin the rule is known for: a
millisecond either way is the difference between strengthening and
weakening.

Errors:
Returns an error for a non-positive time constant or a negative
amplitude.

Rust: `biophysics::neuro::stdp_window`
    """
    ...

def stdp_train(pre: list[float], post: list[float], a_plus: float, a_minus: float, tau_plus: float, tau_minus: float) -> float:
    """
The total weight change from every pre-post pair in two trains.

This is the all-to-all rule: each presynaptic spike is paired with each
postsynaptic spike. It is the simplest interpretation and not the only
one -- nearest-neighbour pairing gives noticeably less potentiation at
high rates, because a burst's later spikes no longer each count against
every earlier one.

Errors:
Returns an error for a bad window parameter, an unsorted train, or more
than ten million pairs.

Rust: `biophysics::neuro::stdp_train`
    """
    ...

def izhikevich_network(n_exc: int, n_inh: int, t_end: float, rng: Rng) -> list[tuple[float, int]]:
    """
Izhikevich's randomly connected network of excitatory and inhibitory
neurons, returning every spike as `(time in ms, neuron index)`.

Excitatory neurons are regular spikers scattered toward chattering by a
squared random factor, inhibitory ones toward fast spiking, exactly as
in the published network; each neuron receives a random thalamic drive
each millisecond, with the excitatory population driven harder. All
weights are all-to-all with random excitatory strengths and stronger
fixed inhibitory ones.

The behaviour worth looking for is that the population synchronises
into gamma-band rhythms without any oscillator being built in: the
rhythm is a property of the excitatory-inhibitory loop, not of the
cells. Inhibition being both stronger and faster than excitation is
what produces it.

Errors:
Returns an error for no excitatory or no inhibitory neurons, more than
four thousand in total, or a non-positive run length.

Rust: `biophysics::neuro::izhikevich_network`
    """
    ...

def hopfield_store(patterns: list[list[int]]) -> Matrix:
    """
The Hebbian weight matrix storing a set of +-1 patterns.

`w_ij = (1/n) sum_p x_i^p x_j^p` with a zero diagonal. The rule is
local and one-shot: each pattern is written by a single pass and never
revisited, which is why the network cannot unlearn and why capacity is
the limiting resource rather than training time.

Errors:
Returns an error for no patterns, patterns of differing or zero length,
or an entry that is not exactly +1 or -1.

Rust: `biophysics::neuro::hopfield_store`
    """
    ...

def hopfield_recall(w: Matrix | Sequence[Sequence[float]], probe: list[int], steps: int) -> list[int]:
    """
Recalls from a probe by sweeping the units in index order, stopping
early once a whole sweep changes nothing. `steps` counts sweeps.

The updates are sequential rather than simultaneous, and the difference
is not cosmetic. Flipping one unit at a time against the current state
can only lower the energy `-1/2 x' W x` when the weights are symmetric
with a zero diagonal, so recall converges to a fixed point. Updating
every unit at once against the *old* state has no such guarantee: it
can raise the energy and settle into a two-cycle that oscillates
forever between two states, neither of them stored. What it converges *to* need not be a stored
pattern: mixtures of three stored patterns are also minima, and so are
the negatives of everything stored, since flipping every unit leaves
the energy unchanged.

Errors:
Returns an error for a non-square matrix, a probe of the wrong length,
or a probe entry that is not exactly +1 or -1.

Rust: `biophysics::neuro::hopfield_recall`
    """
    ...

def hopfield_energy(w: Matrix | Sequence[Sequence[float]], state: list[int]) -> float:
    """
The energy of a state under a Hopfield weight matrix.

Errors:
Returns an error for a non-square matrix or a state of the wrong length.

Rust: `biophysics::neuro::hopfield_energy`
    """
    ...

def hopfield_capacity_check(n: int, stored: int, trials: int, rng: Rng) -> float:
    """
The fraction of stored patterns recalled exactly from themselves, over
`trials` random pattern sets of size `stored`.

Recall from the pattern itself is the easiest possible test, so this
measures storage rather than error correction. It falls off sharply
near `0.138 n` patterns: below that the stored patterns are stable, and
above it the crosstalk between them overwhelms the signal and the
network forgets everything at once rather than degrading gracefully.

Errors:
Returns an error for a network or trial count of zero, no patterns to
store, or a request above five hundred units.

Rust: `biophysics::neuro::hopfield_capacity_check`
    """
    ...

def wilson_cowan(c_ee: float, c_ei: float, c_ie: float, c_ii: float, p_e: float, p_i: float, tau_e: float, tau_i: float, slope: float, threshold: float, e0: float, i0: float, t_end: float, dt: float) -> list[tuple[float, float, float]]:
    """
The Wilson-Cowan equations for coupled excitatory and inhibitory
populations, returning `(t, E, I)`.

`tau_e dE/dt = -E + S(c_ee E - c_ei I + p_e)` and the matching
equation for `I`, with `S` the logistic function. `E` and `I` are
fractions of each population active, so they stay in `[0, 1]`.

This is a mean-field model: it describes what a population does on
average and says nothing about individual spikes or their timing.
Oscillations here are oscillations of the *rate*, which is a different
claim from the synchrony a spiking network shows, and the two need not
coincide.

Errors:
Returns an error for a non-positive time constant or slope, initial
activity outside `[0, 1]`, or a run length or step size out of range.

Rust: `biophysics::neuro::wilson_cowan`
    """
    ...

def length_constant(r_m: float, r_i: float, diameter: float) -> float:
    """
The passive cable's length constant `sqrt(d R_m / (4 R_i))`.

With `r_m` in ohm-cm^2, `r_i` in ohm-cm and the diameter in cm, the
answer is in cm. The square root is the reason thin processes are
electrically short: halving the diameter shortens the reach only by
`sqrt(2)`, but that is enough that a dendritic spine's neck is a
different electrical world from its parent branch.

Errors:
Returns an error for a non-positive resistance or diameter.

Rust: `biophysics::neuro::length_constant`
    """
    ...

def cable_equation_1d(length: float, lambda_: float, v_injected: float, points: int) -> list[float]:
    """
The steady-state voltage along a finite passive cable with current
injected at one end and the far end sealed.

Returns `points` samples of `V(x)` over `[0, length]`, solved from the
discretised cable equation `lambda^2 V'' = V` rather than from the
closed form, so the boundary conditions are imposed rather than
assumed. The analytic answer for a sealed end is
`V(x) = V(0) cosh((L - x)/lambda) / cosh(L/lambda)`.

A sealed end is not a neutral choice. Current that reaches it has
nowhere to go, so the voltage there is *higher* than an infinite cable
would give -- an end effect that grows as the cable shortens relative
to its length constant.

Errors:
Returns an error for a non-positive length or length constant, fewer
than three points, or a singular system.

Rust: `biophysics::neuro::cable_equation_1d`
    """
    ...

def reaction_time_ddm(drift: float, threshold: float, noise: float, dt: float, trials: int, rng: Rng) -> list[tuple[float, bool]]:
    """
Simulated reaction times from the drift-diffusion model, as
`(time, chose the positive bound)`.

Evidence accumulates from zero with constant `drift` and Gaussian noise
until it reaches `+threshold` or `-threshold`. The model's appeal is
that one mechanism produces both the choice and its latency, and it
predicts the awkward fact that errors and correct responses have
nearly the same distribution of times when the starting point is
unbiased.

Errors:
Returns an error for a non-positive threshold, noise or step, no
trials, or a run that exhausts the fifty-million-step budget shared
across all trials.

Rust: `biophysics::neuro::reaction_time_ddm`
    """
    ...

def ddm_analytic_accuracy(drift: float, threshold: float, noise: float) -> float:
    """
The exact probability that unbiased evidence reaches the positive
bound: `1 / (1 + exp(-2 * drift * threshold / noise^2))`.

This is the gambler's-ruin answer for Brownian motion with drift
between symmetric absorbing barriers, and it depends on the three
parameters only through `drift * threshold / noise^2`. Doubling the
drift and the noise variance together therefore changes the accuracy
not at all, only the time taken.

Errors:
Returns an error for a non-positive threshold or noise.

Rust: `biophysics::neuro::ddm_analytic_accuracy`
    """
    ...

HH_C_M: float

HH_G_NA: float

HH_G_K: float

HH_G_L: float

HH_E_NA: float

HH_E_K: float

HH_E_L: float

HH_V_REST: float
