"""
Coherent noise: Perlin gradient noise (Perlin 2002), OpenSimplex2 (ported from K.jpg's reference implementation), value noise, Worley cellular noise, fractal combinators (fBm, turbulence, ridged and hybrid multifractals, domain warping, curl noise), and terrain synthesis (diamond-square, spectral synthesis, thermal and hydraulic erosion, void-and-cluster blue noise).
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.spatial.primitives import Aabb
from rust_physics_engine.patterns.symmetry import Lattice
from rust_physics_engine.spatial.primitives import Rect
from rust_physics_engine.monte_carlo import Rng
from rust_physics_engine.math import Vec2
from rust_physics_engine.math import Vec3

class ErosionParams:
    """
Hydraulic erosion droplet parameters (Beyer 2015-style droplet
simulation).

Rust: `fractals::noise::ErosionParams`
    """
    def __init__(self, inertia: float, capacity: float, min_capacity: float, erode_speed: float, deposit_speed: float, evaporate_speed: float, gravity: float, max_lifetime: int) -> None: ...
    @property
    def inertia(self) -> float: ...
    @property
    def capacity(self) -> float: ...
    @property
    def min_capacity(self) -> float: ...
    @property
    def erode_speed(self) -> float: ...
    @property
    def deposit_speed(self) -> float: ...
    @property
    def evaporate_speed(self) -> float: ...
    @property
    def gravity(self) -> float: ...
    @property
    def max_lifetime(self) -> int: ...

class FbmParams:
    """
Fractional Brownian motion parameters.

Rust: `fractals::noise::FbmParams`
    """
    def __init__(self, octaves: int, lacunarity: float, gain: float, frequency: float, amplitude: float) -> None: ...
    @property
    def octaves(self) -> int: ...
    @property
    def lacunarity(self) -> float: ...
    @property
    def gain(self) -> float: ...
    @property
    def frequency(self) -> float: ...
    @property
    def amplitude(self) -> float: ...

class GaborKernel:
    """
One Gabor kernel: a Gaussian-windowed cosine wave.

Rust: `fractals::noise::GaborKernel`
    """
    def __init__(self, center: Vec2 | Sequence[float], frequency: float, orientation: float, bandwidth: float, amplitude: float, phase: float) -> None: ...
    @property
    def center(self) -> Vec2: ...
    @property
    def frequency(self) -> float: ...
    @property
    def orientation(self) -> float: ...
    @property
    def bandwidth(self) -> float: ...
    @property
    def amplitude(self) -> float: ...
    @property
    def phase(self) -> float: ...

class Metric:
    """
Distance metrics for Worley noise.

Rust: `fractals::noise::Metric`
    """
    ...

class OpenSimplex2:
    """
OpenSimplex2 noise (the "faster" variant): visually isotropic
gradient noise on simplex-style lattices, in [-1, 1]. The 3-D
evaluator uses the ImproveXY lattice orientation; 4-D noise is
not ported — use `Perlin::noise_4d` when a fourth dimension is
needed.

Rust: `fractals::noise::OpenSimplex2`
    """
    def __init__(self, seed: int) -> None: ...
    def noise_2d(self, x: float, y: float) -> float: ...
    def noise_3d(self, x: float, y: float, z: float) -> float: ...

class Perlin:
    """
Classic improved Perlin gradient noise (Perlin, "Improving
Noise", 2002) with a seeded permutation table. Values are in
[-1, 1] and zero at every integer lattice point.

Rust: `fractals::noise::Perlin`
    """
    def __init__(self, seed: int) -> None: ...
    def noise_1d(self, x: float) -> float: ...
    def noise_2d(self, x: float, y: float) -> float: ...
    def noise_3d(self, x: float, y: float, z: float) -> float: ...
    def noise_4d(self, x: float, y: float, z: float, w: float) -> float: ...
    def gradient_2d(self, x: float, y: float) -> Vec2: ...
    def gradient_3d(self, x: float, y: float, z: float) -> Vec3: ...

class ValueNoise:
    """
Lattice value noise: random values at integer lattice points,
interpolated (quintic-smoothed bilinear, optional bicubic).

Rust: `fractals::noise::ValueNoise`
    """
    def __init__(self, seed: int) -> None: ...
    def noise_2d(self, x: float, y: float) -> float: ...
    def noise_3d(self, x: float, y: float, z: float) -> float: ...
    def noise_2d_cubic(self, x: float, y: float) -> float: ...

class Worley:
    """
Worley (cellular) noise: one feature point per grid cell of size
`cell`, hashed from the seed; F1/F2 are the distances to the
nearest and second-nearest feature points under `metric`.

Rust: `fractals::noise::Worley`
    """
    def __init__(self, seed: int, cell: float) -> None: ...
    def f1_2d(self, x: float, y: float) -> float: ...
    def f2_2d(self, x: float, y: float) -> float: ...
    def f2_minus_f1_2d(self, x: float, y: float) -> float: ...
    def f1_3d(self, x: float, y: float, z: float) -> float: ...
    def f2_3d(self, x: float, y: float, z: float) -> float: ...
    def cell_id_2d(self, x: float, y: float) -> int: ...
    @property
    def metric(self) -> Metric: ...

def fbm_2d(n: Callable[[float, float], float], x: float, y: float, p: FbmParams) -> float:
    """
fBm: Σ amplitude·gainⁱ · n(frequency·lacunarityⁱ · x).

Rust: `fractals::noise::fbm_2d`
    """
    ...

def fbm_3d(n: Callable[[float, float, float], float], x: float, y: float, z: float, p: FbmParams) -> float:
    """
3-D fBm.

Rust: `fractals::noise::fbm_3d`
    """
    ...

def turbulence_2d(n: Callable[[float, float], float], x: float, y: float, p: FbmParams) -> float:
    """
Turbulence: fBm of |n| (Perlin 1985's marble basis).

Rust: `fractals::noise::turbulence_2d`
    """
    ...

def ridged_multifractal_2d(n: Callable[[float, float], float], x: float, y: float, p: FbmParams, offset: float, gain: float) -> float:
    """
Musgrave's ridged multifractal: octaves of (offset − |n|)²,
each weighted by the previous octave's signal.

Rust: `fractals::noise::ridged_multifractal_2d`
    """
    ...

def hybrid_multifractal(n: Callable[[float, float, float], float], x: float, y: float, z: float, p: FbmParams, offset: float) -> float:
    """
Musgrave's hybrid multifractal (3-D): additive multifractal with
octave weights damped by the running product.

Rust: `fractals::noise::hybrid_multifractal`
    """
    ...

def billow_2d(n: Callable[[float, float], float], x: float, y: float, p: FbmParams) -> float:
    """
Billow: fBm of 2|n| − 1 (puffy cloud look).

Rust: `fractals::noise::billow_2d`
    """
    ...

def domain_warp_2d(n: Callable[[float, float], float], x: float, y: float, p: FbmParams, warp_strength: float, iterations: int) -> float:
    """
Iterated domain warping (Quilez): the sample point is repeatedly
displaced by an fBm offset field before the final evaluation.

Rust: `fractals::noise::domain_warp_2d`
    """
    ...

def domain_warp_3d(n: Callable[[float, float, float], float], x: float, y: float, z: float, p: FbmParams, strength: float, iterations: int) -> float:
    """
3-D iterated domain warping.

Rust: `fractals::noise::domain_warp_3d`
    """
    ...

def curl_noise_2d(n: Callable[[float, float], float], x: float, y: float, eps: float) -> Vec2:
    """
Divergence-free 2-D flow from a scalar noise potential:
v = (∂ψ/∂y, −∂ψ/∂x) by central differences.

Panics:
Panics unless `eps > 0`.

Rust: `fractals::noise::curl_noise_2d`
    """
    ...

def curl_noise_3d(n: Callable[[float, float, float], float], x: float, y: float, z: float, eps: float) -> Vec3:
    """
Divergence-free 3-D flow: curl of a vector potential whose three
components are offset copies of `n` (Bridson et al. 2007).

Panics:
Panics unless `eps > 0`.

Rust: `fractals::noise::curl_noise_3d`
    """
    ...

def noise_field_2d(n: Callable[[float, float], float], bounds: Rect, w: int, h: int) -> ScalarField2:
    """
Samples a noise function into a scalar field.

Rust: `fractals::noise::noise_field_2d`
    """
    ...

def noise_field_3d(n: Callable[[float, float, float], float], bounds: Aabb, res: tuple[int, int, int]) -> ScalarField3:
    """
Samples a noise function into a 3-D scalar field.

Rust: `fractals::noise::noise_field_3d`
    """
    ...

def terrain_heightmap(seed: int, w: int, h: int, p: FbmParams, erosion_iters: int) -> list[float]:
    """
fBm heightmap (row-major, `w` × `h`) with optional thermal
erosion: material moves down slopes exceeding the talus angle,
smoothing scree until the terrain settles.

Panics:
Panics unless the grid has at least 2×2 samples.

Rust: `fractals::noise::terrain_heightmap`
    """
    ...

def hydraulic_erosion(height: MutableSequence[float], w: int, h: int, droplets: int, rng: Rng, params: ErosionParams) -> None:
    """
Simulates `droplets` water droplets over the heightmap, eroding
and depositing material along their paths.

Panics:
Panics unless the grid is at least 3×3 and `height.len() == w·h`.

Rust: `fractals::noise::hydraulic_erosion`
    """
    ...

def diamond_square(size_pow2: int, roughness: float, seed: int) -> list[float]:
    """
Diamond-square (plasma) fractal heightmap on a
(2^size_pow2 + 1)² grid, row-major, roughness halving the random
amplitude at each subdivision.

Panics:
Panics unless `1 <= size_pow2 <= 12`.

Rust: `fractals::noise::diamond_square`
    """
    ...

def spectral_synthesis_2d(w: int, h: int, beta: float, seed: int) -> list[float]:
    """
1/f^β spectral synthesis by direct summation of 64 random plane
waves with amplitudes f^{−β/2} (row-major, values roughly in
[-1, 1] after normalization).

Panics:
Panics unless the grid has at least 2×2 samples.

Rust: `fractals::noise::spectral_synthesis_2d`
    """
    ...

def white_noise_2d(seed: int, x: float, y: float) -> float:
    """
Stateless hash white noise in [-1, 1]: the same (seed, x, y)
always yields the same value, with no correlation between
nearby inputs.

Rust: `fractals::noise::white_noise_2d`
    """
    ...

def blue_noise_texture(w: int, h: int, seed: int) -> list[float]:
    """
Void-and-cluster blue-noise threshold texture (Ulichney 1993):
returns ranks normalized to [0, 1), toroidally tileable; every
rank appears exactly once.

Panics:
Panics unless `w·h >= 4` (and `w, h >= 2`).

Rust: `fractals::noise::blue_noise_texture`
    """
    ...

def gabor_noise_2d(x: float, y: float, kernels: list[GaborKernel]) -> float:
    """
Sparse Gabor noise: the sum of the kernels at (x, y)
(Lagae et al. 2009 with an explicit kernel list).

Rust: `fractals::noise::gabor_noise_2d`
    """
    ...
