"""
Scalar and polynomial root finding.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def bisection(f: Callable[[float], float], a: float, b: float, tol: float, max_iter: int) -> Optional[float]:
    """
Bisection method for finding a root of f in [a, b].
Returns `None` if f(a) and f(b) have the same sign.

Rust: `numerical::roots::bisection`
    """
    ...

def newton_raphson(f: Callable[[float], float], df: Callable[[float], float], x0: float, tol: float, max_iter: int) -> Optional[float]:
    """
Newton-Raphson method starting from x0.
Returns `None` if the derivative is zero or the method does not converge within max_iter.

Rust: `numerical::roots::newton_raphson`
    """
    ...

def secant(f: Callable[[float], float], x0: float, x1: float, tol: float, max_iter: int) -> Optional[float]:
    """
Secant method starting from two initial guesses x0 and x1.
Returns `None` if the method does not converge within max_iter.

Rust: `numerical::roots::secant`
    """
    ...

def polynomial_eval(coeffs: list[float], x: float) -> float:
    """
Evaluates a real polynomial by Horner's rule; `coeffs` are ordered
highest degree first.

Panics:
Panics if `coeffs` is empty.

Rust: `numerical::roots::polynomial_eval`
    """
    ...

def polynomial_eval_complex(coeffs: list[float], z: complex) -> complex:
    """
Horner evaluation of a real-coefficient polynomial at a complex
point; `coeffs` are ordered highest degree first.

Panics:
Panics if `coeffs` is empty.

Rust: `numerical::roots::polynomial_eval_complex`
    """
    ...

def polynomial_roots(coeffs: list[float]) -> list[complex]:
    """
All complex roots of a real polynomial (coefficients highest degree
first) via the Durand-Kerner (Weierstrass) simultaneous iteration.

Leading zeros are stripped; the root count equals the degree.
Returns `InvalidArgument` for constant (degree-0) or all-zero input
and `NoConvergence` if the iteration stalls.

Rust: `numerical::roots::polynomial_roots`
    """
    ...

def brent_root(f: Callable[[float], float], a: float, b: float, tol: float, max_iter: int) -> float:
    """
Brent's method: bracketing root finder combining bisection, secant,
and inverse quadratic interpolation (Brent 1973; NR §9.3).
Superlinear convergence with guaranteed bracket retention.

Returns `InvalidArgument` unless f(a) and f(b) have opposite signs.

Rust: `numerical::roots::brent_root`
    """
    ...
