"""
Knots and space curves: parametric knot families, Frenet and rotation-minimizing frames, curvature/torsion estimates, and the classical knot invariants computable from a curve in space — writhe and linking number by the Gauss integral, crossing numbers of projections, and the Alexander polynomial from a knot diagram.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.spatial.frame import Frame
from rust_physics_engine.spatial.primitives import Polyline
from rust_physics_engine.math import Vec3

def torus_knot(p: int, q: int, r_major: float, r_minor: float, t: float) -> Vec3:
    """
Point on the (p, q) torus knot at parameter `t` ∈ [0, 2π):
winds `p` times around the torus axis and `q` times through the
hole of the torus with radii `r_major` > `r_minor`.

x = (R + r cos qt) cos pt, y = (R + r cos qt) sin pt, z = r sin qt.

Panics:
Panics unless `p, q >= 1` and `r_major > r_minor > 0`.

Rust: `patterns::knots::torus_knot`
    """
    ...

def torus_knot_curve(p: int, q: int, r_major: float, r_minor: float, n: int) -> Polyline:
    """
Closed polyline sampling of the (p, q) torus knot with `n`
vertices.

Panics:
Panics unless `n >= 3` (and the `torus_knot` preconditions hold).

Rust: `patterns::knots::torus_knot_curve`
    """
    ...

def lissajous_knot(nx: int, ny: int, nz: int, phase_x: float, phase_y: float, phase_z: float, t: float) -> Vec3:
    """
Point on a Lissajous knot: x = cos(nx t + φx), y = cos(ny t + φy),
z = cos(nz t + φz). Coprime frequencies with generic phases give
knotted closed curves (e.g. (3, 2, 7) with φ = (0.7, 0.2, 0)).

Rust: `patterns::knots::lissajous_knot`
    """
    ...

def trefoil(t: float) -> Vec3:
    """
The trefoil knot 3₁ in its symmetric parametrization:
(sin t + 2 sin 2t, cos t − 2 cos 2t, −sin 3t), t ∈ [0, 2π).

Rust: `patterns::knots::trefoil`
    """
    ...

def figure_eight_knot(t: float) -> Vec3:
    """
The figure-eight knot 4₁:
((2 + cos 2t) cos 3t, (2 + cos 2t) sin 3t, sin 4t), t ∈ [0, 2π).

Rust: `patterns::knots::figure_eight_knot`
    """
    ...

def cinquefoil(t: float) -> Vec3:
    """
The cinquefoil (Solomon's seal) knot 5₁ = (2, 5) torus knot on
the torus R = 2, r = 1.

Rust: `patterns::knots::cinquefoil`
    """
    ...

def frenet_frame(curve: Callable[[float], Vec3 | Sequence[float]], t: float, h: float) -> Optional[Frame]:
    """
Frenet frame of a curve at `t` by central differences with step
`h`: x axis = unit tangent T, y = principal normal N, z =
binormal B = T × N. `None` where the frame is undefined (zero
speed or zero curvature).

Panics:
Panics unless `h > 0`.

Rust: `patterns::knots::frenet_frame`
    """
    ...

def frenet_frames_polyline(pl: Polyline) -> list[Frame]:
    """
Discrete Frenet frames at every vertex of a polyline (tangent by
central difference, normal from the discrete curvature vector).
Straight stretches inherit the previous normal so the field stays
continuous.

Panics:
Panics unless the polyline has at least 2 points.

Rust: `patterns::knots::frenet_frames_polyline`
    """
    ...

def parallel_transport_frames(pl: Polyline) -> list[Frame]:
    """
Rotation-minimizing frames along a polyline by the double
reflection method (Wang, Jüttler, Zheng & Liu 2008): each step
reflects the previous frame in the chord bisector plane and then
in the tangent bisector plane, which transports the normal with
no spurious twist (fourth-order accurate for smooth curves).

Panics:
Panics unless the polyline has at least 2 points.

Rust: `patterns::knots::parallel_transport_frames`
    """
    ...

def curvature_torsion(curve: Callable[[float], Vec3 | Sequence[float]], t: float, h: float) -> tuple[float, float]:
    """
Curvature and torsion of a curve at `t` by finite differences:
κ = |c′ × c″| / |c′|³ and τ = (c′ × c″)·c‴ / |c′ × c″|².

Panics:
Panics unless `h > 0`.

Rust: `patterns::knots::curvature_torsion`
    """
    ...

def total_curvature(pl: Polyline) -> float:
    """
Total curvature of a polyline: the sum of exterior turning angles
between consecutive segments. For closed knotted curves this is
at least 4π (Fáry-Milnor).

Rust: `patterns::knots::total_curvature`
    """
    ...

def writhe(pl: Polyline) -> float:
    """
Writhe of a closed polyline: the Gauss double integral
Wr = (1/4π) ∮∮ (dr₁ × dr₂)·(r₁ − r₂)/|r₁ − r₂|³, evaluated
exactly over segment pairs by the solid-angle formula. Planar
curves have writhe 0.

Panics:
Panics unless the polyline is closed with at least 3 points.

Rust: `patterns::knots::writhe`
    """
    ...

def linking_number(a: Polyline, b: Polyline) -> int:
    """
Linking number of two closed polylines by the Gauss double sum;
the result is an integer for disjoint closed curves.

Panics:
Panics unless both polylines are closed with at least 3 points.

Rust: `patterns::knots::linking_number`
    """
    ...

def crossing_number_projection(pl: Polyline, direction: Vec3 | Sequence[float]) -> int:
    """
Number of crossings in the projection of the polyline along
`direction` (transverse double points of the diagram).

Panics:
Panics unless the polyline is closed and `direction` is non-zero.

Rust: `patterns::knots::crossing_number_projection`
    """
    ...

def alexander_polynomial_coeffs(pl: Polyline) -> list[int]:
    """
Alexander polynomial coefficients (lowest degree first) computed
from the diagram of the closed polyline projected along +z. Arcs
run between undercrossings; each crossing contributes the
abelianized Fox-derivative row of its Wirtinger relation
(over-arc 1 − t, incoming under-arc t, outgoing under-arc −1 for
a positive crossing), one row and one column are deleted, and the
determinant is recovered by evaluation at integer points and
Lagrange interpolation. Normalized so the constant term is
non-zero and the leading coefficient positive; the unknot (no
crossings) gives `[1]`.

The projection must be regular: only transverse double points.
Sample the curve finely enough that no segment participates in
two crossings with nearly equal positions.

Panics:
Panics unless the polyline is closed with at least 3 points.

Rust: `patterns::knots::alexander_polynomial_coeffs`
    """
    ...

def knot_tube(pl: Polyline, radius: float, segments: int) -> Mesh:
    """
Sweeps a circle of `radius` along the polyline (delegates to
`mesh::generate::tube_along_polyline`).

Rust: `patterns::knots::knot_tube`
    """
    ...

def helix(radius: float, pitch: float, turns: float, n: int) -> Polyline:
    """
Circular helix of given radius, pitch (rise per turn), and number
of turns, sampled at `n` points.

Panics:
Panics unless `radius > 0`, `turns > 0`, and `n >= 2`.

Rust: `patterns::knots::helix`
    """
    ...

def double_helix(radius: float, pitch: float, turns: float, n: int, phase: float) -> tuple[Polyline, Polyline]:
    """
Two helices on the same axis separated by `phase` radians (DNA
uses phase ≈ 2.1 rad for the minor/major groove asymmetry).

Rust: `patterns::knots::double_helix`
    """
    ...

def viviani_curve(a: float, t: float) -> Vec3:
    """
Viviani's curve: the intersection of the sphere of radius 2a with
the cylinder of radius a tangent to its vertical axis:
(a(1 + cos t), a sin t, 2a sin(t/2)), t ∈ [0, 4π) for the full
figure-eight.

Panics:
Panics unless `a > 0`.

Rust: `patterns::knots::viviani_curve`
    """
    ...

def tennis_ball_curve(a: float, b: float, t: float) -> Vec3:
    """
Tennis-ball seam curve: (a cos t + b cos 3t, a sin t − b sin 3t,
2 √(ab) sin 2t) lies on the sphere of radius a + b.

Panics:
Panics unless `a, b > 0`.

Rust: `patterns::knots::tennis_ball_curve`
    """
    ...
