"""
Random and low-discrepancy sampling: Poisson disk (Bridson), blue-noise ranking, stratified jitter, uniform samplers over shapes, random polygons (Valtr), random rotations (Shoemake), and Lloyd relaxation.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.spatial.primitives import Aabb
from rust_physics_engine.spatial.primitives import Circle
from rust_physics_engine.spatial.primitives import Obb
from rust_physics_engine.statistics.distributions import Poisson
from rust_physics_engine.spatial.primitives import Polygon2
from rust_physics_engine.quaternion import Quaternion
from rust_physics_engine.spatial.primitives import Rect
from rust_physics_engine.monte_carlo import Rng
from rust_physics_engine.spatial.primitives import Sphere
from rust_physics_engine.spatial.primitives import Triangle
from rust_physics_engine.spatial.primitives import Triangle2
from rust_physics_engine.math import Vec2
from rust_physics_engine.math import Vec3

def poisson_disk_2d(region: Rect, min_dist: float, k: int, rng: Rng) -> list[Vec2]:
    """
Bridson's Poisson disk sampling in a rectangle ("Fast Poisson Disk
Sampling in Arbitrary Dimensions", SIGGRAPH 2007): no two samples
closer than `min_dist`, maximal up to `k` candidate attempts per
active sample.

Panics:
Panics unless `min_dist > 0` and `k >= 1`.

Rust: `patterns::sampling::poisson_disk_2d`
    """
    ...

def poisson_disk_3d(region: Aabb, min_dist: float, k: int, rng: Rng) -> list[Vec3]:
    """
Bridson Poisson disk sampling in a box (3-D).

Panics:
Panics unless `min_dist > 0` and `k >= 1`.

Rust: `patterns::sampling::poisson_disk_3d`
    """
    ...

def poisson_disk_polygon(poly: Polygon2, min_dist: float, k: int, rng: Rng) -> list[Vec2]:
    """
Poisson disk sampling restricted to a polygon: Bridson over the
bounding rectangle, samples outside the polygon rejected.

Panics:
Panics unless `min_dist > 0`, `k >= 1`, and the polygon has >= 3
vertices.

Rust: `patterns::sampling::poisson_disk_polygon`
    """
    ...

def poisson_disk_variable(region: Rect, density: Callable[[Vec2 | Sequence[float]], float], k: int, rng: Rng) -> list[Vec2]:
    """
Variable-density Poisson disk sampling: `density` maps a point to
its local minimum distance (larger density value = larger
spacing). Dart throwing against a conflict grid keyed by the
smallest local radius.

Panics:
Panics unless `k >= 1` and `density` returns positive values over
the region (sampled at the corners and center).

Rust: `patterns::sampling::poisson_disk_variable`
    """
    ...

def poisson_disk_surface(mesh: Mesh, min_dist: float, rng: Rng) -> list[Vec3]:
    """
Poisson disk sampling on a mesh surface by dart throwing over
area-weighted surface samples.

Panics:
Panics unless `min_dist > 0` and the mesh has positive area.

Rust: `patterns::sampling::poisson_disk_surface`
    """
    ...

def blue_noise_void_cluster(w: int, h: int, n: int) -> list[Vec2]:
    """
Blue-noise point ranking on a `w` x `h` grid by the void-and-cluster
method (Ulichney 1993, toroidal Gaussian energy): returns the `n`
best-spread grid cell centers.

Panics:
Panics unless `n <= w * h / 2` and the grid is nonempty.

Rust: `patterns::sampling::blue_noise_void_cluster`
    """
    ...

def stratified_2d(nx: int, ny: int, jitter: float, rng: Rng) -> list[Vec2]:
    """
Stratified jittered samples on the unit square: one sample per
cell of an `nx` x `ny` grid, jittered by `jitter` in [0, 1].

Panics:
Panics unless `nx, ny >= 1` and `jitter` is in [0, 1].

Rust: `patterns::sampling::stratified_2d`
    """
    ...

def uniform_in_triangle(t: Triangle2, rng: Rng) -> Vec2:
    """
Uniform point in a 2-D triangle by the square-root warp.

Rust: `patterns::sampling::uniform_in_triangle`
    """
    ...

def uniform_in_triangle_3d(t: Triangle, rng: Rng) -> Vec3:
    """
Uniform point in a 3-D triangle.

Rust: `patterns::sampling::uniform_in_triangle_3d`
    """
    ...

def uniform_in_polygon(poly: Polygon2, rng: Rng) -> Vec2:
    """
Uniform point in a simple polygon: triangulate, pick a triangle by
area, sample it.

Panics:
Panics when the polygon cannot be triangulated.

Rust: `patterns::sampling::uniform_in_polygon`
    """
    ...

def uniform_in_circle(c: Circle, rng: Rng) -> Vec2:
    """
Uniform point inside a circle.

Rust: `patterns::sampling::uniform_in_circle`
    """
    ...

def uniform_on_circle(c: Circle, rng: Rng) -> Vec2:
    """
Uniform point on a circle's boundary.

Rust: `patterns::sampling::uniform_on_circle`
    """
    ...

def uniform_in_sphere(s: Sphere, rng: Rng) -> Vec3:
    """
Uniform point inside a sphere (cube-root radial warp).

Rust: `patterns::sampling::uniform_in_sphere`
    """
    ...

def uniform_on_sphere(s: Sphere, rng: Rng) -> Vec3:
    """
Uniform point on a sphere's surface.

Rust: `patterns::sampling::uniform_on_sphere`
    """
    ...

def uniform_on_hemisphere(n: Vec3 | Sequence[float], rng: Rng) -> Vec3:
    """
Uniform direction on the unit hemisphere around `n`.

Panics:
Panics when `n` is zero.

Rust: `patterns::sampling::uniform_on_hemisphere`
    """
    ...

def cosine_weighted_hemisphere(n: Vec3 | Sequence[float], rng: Rng) -> Vec3:
    """
Cosine-weighted direction on the hemisphere around `n` (Malley's
method: uniform disk lifted to the sphere).

Panics:
Panics when `n` is zero.

Rust: `patterns::sampling::cosine_weighted_hemisphere`
    """
    ...

def uniform_in_aabb(b: Aabb, rng: Rng) -> Vec3:
    """
Uniform point inside an axis-aligned box.

Rust: `patterns::sampling::uniform_in_aabb`
    """
    ...

def uniform_in_obb(b: Obb, rng: Rng) -> Vec3:
    """
Uniform point inside an oriented box.

Rust: `patterns::sampling::uniform_in_obb`
    """
    ...

def uniform_on_aabb_surface(b: Aabb, rng: Rng) -> Vec3:
    """
Uniform point on the surface of an axis-aligned box
(area-weighted face choice).

Rust: `patterns::sampling::uniform_on_aabb_surface`
    """
    ...

def uniform_in_annulus(c: Vec2 | Sequence[float], r_in: float, r_out: float, rng: Rng) -> Vec2:
    """
Uniform point in the annulus between `r_in` and `r_out`.

Panics:
Panics unless `0 <= r_in < r_out`.

Rust: `patterns::sampling::uniform_in_annulus`
    """
    ...

def uniform_in_cone(axis: Vec3 | Sequence[float], angle: float, rng: Rng) -> Vec3:
    """
Uniform direction within the cone of half-angle `angle` around
`axis` (solid-angle uniform).

Panics:
Panics unless `axis` is nonzero and `angle` is in (0, π].

Rust: `patterns::sampling::uniform_in_cone`
    """
    ...

def random_convex_polygon(n: int, rng: Rng) -> Polygon2:
    """
Random convex polygon with `n` vertices by Valtr's algorithm
(uniform over convex polygons in the unit square), counterclockwise.

Panics:
Panics unless `n >= 3`.

Rust: `patterns::sampling::random_convex_polygon`
    """
    ...

def random_simple_polygon(n: int, rng: Rng) -> Polygon2:
    """
Random simple polygon: random points untangled by repeatedly
swapping crossing edges (2-opt), which strictly shortens the
perimeter and therefore terminates.

Panics:
Panics unless `n >= 3`.

Rust: `patterns::sampling::random_simple_polygon`
    """
    ...

def random_rotation(rng: Rng) -> Quaternion:
    """
Uniform random rotation by Shoemake's subgroup algorithm (uniform
over SO(3)).

Rust: `patterns::sampling::random_rotation`
    """
    ...

def random_unit_vector(rng: Rng) -> Vec3:
    """
Uniform random unit vector (normalized Gaussian triple).

Rust: `patterns::sampling::random_unit_vector`
    """
    ...

def stipple(density: Callable[[Vec2 | Sequence[float]], float], region: Rect, n: int, iterations: int, rng: Rng) -> list[Vec2]:
    """
Weighted stippling: `n` seed points relaxed by density-weighted
Lloyd iterations, so point density tracks `density`.

Panics:
Panics unless `n >= 1` and `density` is nonnegative where sampled.

Rust: `patterns::sampling::stipple`
    """
    ...
