"""
Room acoustics, psychoacoustic scales, and musical pitch.  Reverberation by Sabine (`RT60 = 0.161 V / A`) and by Eyring, which differ in how they treat a very absorptive room: Sabine's formula is a diffuse-field approximation that never reaches zero however absorptive the surfaces, while Eyring's does. Room modes, critical distance and the mass-law transmission loss follow.  The perceptual scales -- mel, bark, ERB, A-weighting, equal-loudness phon -- map physical frequency and level onto what a listener reports, and are fits to listening data rather than derivations. Musical pitch is here too: equal temperament, cents, and MIDI note conversion.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def sabine_reverberation(volume: float, total_absorption: float) -> float:
    """
Sabine reverberation time: T60 = 0.161 V / A (seconds).

Rust: `acoustics::sabine_reverberation`
    """
    ...

def eyring_reverberation(volume: float, surface_area: float, avg_absorption_coeff: float) -> float:
    """
Eyring reverberation time: T60 = 0.161 V / (-S × ln(1 - ā)) (seconds).

Rust: `acoustics::eyring_reverberation`
    """
    ...

def total_absorption(surfaces: list[tuple[float, float]]) -> float:
    """
Total absorption area: A = Σ(Si × αi).
Each tuple is (area_m2, absorption_coefficient).

Rust: `acoustics::total_absorption`
    """
    ...

def room_constant(surface_area: float, avg_absorption: float) -> float:
    """
Room constant: R = S × ā / (1 - ā).

Rust: `acoustics::room_constant`
    """
    ...

def critical_distance(room_constant: float, directivity: float) -> float:
    """
Critical distance: dc = √(Q × R / (16π)).

Rust: `acoustics::critical_distance`
    """
    ...

def room_mode_frequency(length: float, width: float, height: float, nx: int, ny: int, nz: int, speed: float) -> float:
    """
Axial/tangential/oblique room mode frequency:
f = (c/2) × √((nx/L)² + (ny/W)² + (nz/H)²).

Rust: `acoustics::room_mode_frequency`
    """
    ...

def add_db(db1: float, db2: float) -> float:
    """
Energetic sum of two decibel levels: 10 × log₁₀(10^(dB1/10) + 10^(dB2/10)).

Rust: `acoustics::add_db`
    """
    ...

def add_db_multiple(levels: list[float]) -> float:
    """
Energetic sum of multiple decibel levels.

Rust: `acoustics::add_db_multiple`
    """
    ...

def subtract_db(total_db: float, background_db: float) -> float:
    """
Subtract background noise: 10 × log₁₀(10^(total/10) - 10^(bg/10)).

Rust: `acoustics::subtract_db`
    """
    ...

def distance_attenuation(db_at_ref: float, ref_distance: float, distance: float) -> float:
    """
Inverse-square distance attenuation: L2 = L1 - 20 × log₁₀(d2 / d1).

Rust: `acoustics::distance_attenuation`
    """
    ...

def a_weighting(frequency: float) -> float:
    """
A-weighting filter approximation (dBA relative weighting at a given frequency).

Rust: `acoustics::a_weighting`
    """
    ...

def equal_loudness_phon(spl: float, frequency: float) -> float:
    """
Rough equal-loudness approximation in phon.
At 1 kHz the phon value equals the SPL. At other frequencies a simple
A-weighting-derived correction is applied. This is NOT a full ISO 226
implementation.

Rust: `acoustics::equal_loudness_phon`
    """
    ...

def bark_scale(frequency: float) -> float:
    """
Bark critical-band rate: z = 13 × atan(0.76 f/1000) + 3.5 × atan((f/7500)²).

Rust: `acoustics::bark_scale`
    """
    ...

def mel_scale(frequency: float) -> float:
    """
Mel scale: m = 2595 × log₁₀(1 + f/700).

Rust: `acoustics::mel_scale`
    """
    ...

def frequency_from_mel(mel: float) -> float:
    """
Inverse mel scale: f = 700 × (10^(m/2595) - 1).

Rust: `acoustics::frequency_from_mel`
    """
    ...

def noise_reduction(tl: float, receiving_absorption: float, common_area: float) -> float:
    """
Noise reduction through a partition: NR = TL + 10 × log₁₀(A / S).

Rust: `acoustics::noise_reduction`
    """
    ...

def transmission_loss_mass_law(surface_density: float, frequency: float) -> float:
    """
Single-panel mass law transmission loss: TL = 20 × log₁₀(m × f) - 47.

Rust: `acoustics::transmission_loss_mass_law`
    """
    ...

def sound_transmission_class_estimate(tl_500: float) -> float:
    """
Rough STC estimate (≈ TL at 500 Hz).

Rust: `acoustics::sound_transmission_class_estimate`
    """
    ...

def atmospheric_absorption_coeff(frequency: float, temperature: float, humidity: float) -> float:
    """
Simplified atmospheric absorption coefficient in dB/km.
α ≈ 0.01 × (f/1000)^1.7 × (1 + 0.01×(T-20)) × (1 - 0.005×RH).

Rust: `acoustics::atmospheric_absorption_coeff`
    """
    ...

def ground_effect_excess(distance: float, source_height: float, receiver_height: float) -> float:
    """
Simplified excess ground attenuation (dB) for propagation over soft ground.
Uses a basic geometric model based on path-length difference.

Rust: `acoustics::ground_effect_excess`
    """
    ...

def harmonic_frequency(fundamental: float, n: int) -> float:
    """
Nth harmonic frequency: f_n = n × f_fundamental

Rust: `acoustics::harmonic_frequency`
    """
    ...

def harmonic_series(fundamental: float, max_harmonic: int) -> list[float]:
    """
Generate harmonic series up to max_harmonic: [f, 2f, 3f, ..., nf]

Rust: `acoustics::harmonic_series`
    """
    ...

def equal_temperament_ratio(semitones: float) -> float:
    """
Frequency ratio between two musical interval semitones (equal temperament):
ratio = 2^(semitones/12)

Rust: `acoustics::equal_temperament_ratio`
    """
    ...

def midi_to_frequency(midi_note: float) -> float:
    """
Frequency of a note in equal temperament given A4=440Hz reference:
f = 440 × 2^((midi_note - 69)/12) where midi_note 69 = A4

Rust: `acoustics::midi_to_frequency`
    """
    ...

def frequency_to_midi(frequency: float) -> float:
    """
MIDI note number from frequency: n = 69 + 12×log₂(f/440)

Rust: `acoustics::frequency_to_midi`
    """
    ...

def cents(f1: float, f2: float) -> float:
    """
Cents difference between two frequencies: c = 1200 × log₂(f2/f1)

Rust: `acoustics::cents`
    """
    ...

def circular_membrane_frequency(bessel_zero: float, wave_speed: float, radius: float) -> float:
    """
Frequency of a circular membrane mode (drum):
f_mn = (α_mn × v) / (2π × r)
where α_mn are zeros of Bessel functions. Common modes:
(0,1)=2.405, (1,1)=3.832, (2,1)=5.136, (0,2)=5.520

Rust: `acoustics::circular_membrane_frequency`
    """
    ...

def rectangular_plate_fundamental(length: float, flexural_rigidity: float, mass_per_area: float) -> float:
    """
Rectangular plate fundamental frequency:
f = (π/(2L²)) × √(D/(ρh)) where D = Eh³/(12(1-ν²))
Simplified: takes flexural rigidity D, density×thickness (ρh), and length

Rust: `acoustics::rectangular_plate_fundamental`
    """
    ...

def total_harmonic_distortion(fundamental_amplitude: float, harmonic_amplitudes: list[float]) -> float:
    """
Harmonic distortion: THD = √(Σ V_n²) / V_1 for n=2..N
Takes fundamental amplitude and harmonic amplitudes [2nd, 3rd, ...]

Rust: `acoustics::total_harmonic_distortion`
    """
    ...

def harmonic_synthesis(fundamental: float, harmonics: list[tuple[int, float, float]], t: float) -> float:
    """
Synthesize a waveform from harmonics at a given time:
y(t) = Σ a_n × sin(2π × n × f × t + φ_n)
Each tuple is (harmonic_number, amplitude, phase)

Rust: `acoustics::harmonic_synthesis`
    """
    ...

def inharmonic_frequency(fundamental: float, n: int, b_coeff: float) -> float:
    """
Inharmonicity coefficient for a stiff string (piano):
f_n = n × f₁ × √(1 + B × n²) where B = π³Ed⁴/(64TL²)
Takes the precomputed inharmonicity coefficient B

Rust: `acoustics::inharmonic_frequency`
    """
    ...
