"""
Classical electromagnetism, from Coulomb's law to radiating dipoles.  Electrostatics (Coulomb force and field, potential, Gauss flux, capacitance), magnetostatics (the force on a moving charge, the field of a wire, solenoid and toroid, dipole moments and torques), induction (Faraday and motional EMF, self and mutual inductance), and circuits from Ohm's law through RC transients to the AC steady state -- complex reactance, RLC impedance, resonance, quality factor and bandwidth, power factor, and transformer ratios.  The wave section covers the free-space relations: propagation speed, the Poynting magnitude, energy density, the impedance of free space `Z₀ = μ₀c ≈ 376.73 Ω`, dipole radiation and the Larmor power.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.math import Vec3

def coulomb_force(q1: float, q2: float, distance: float) -> float:
    """
Coulomb's law: F = k_e * |q1 * q2| / r^2

Rust: `electromagnetism::coulomb_force`
    """
    ...

def coulomb_force_signed(q1: float, q2: float, distance: float) -> float:
    """
Coulomb force (signed, 1D): positive = repulsive, negative = attractive

Rust: `electromagnetism::coulomb_force_signed`
    """
    ...

def coulomb_force_vec(q1: float, pos1: Vec3 | Sequence[float], q2: float, pos2: Vec3 | Sequence[float]) -> Vec3:
    """
Coulomb force vector from charge at pos1 to charge at pos2.

Rust: `electromagnetism::coulomb_force_vec`
    """
    ...

def electric_field_point_charge(charge: float, distance: float) -> float:
    """
Electric field due to a point charge: E = k_e * q / r^2

Rust: `electromagnetism::electric_field_point_charge`
    """
    ...

def electric_field_vec(charge: float, charge_pos: Vec3 | Sequence[float], field_point: Vec3 | Sequence[float]) -> Vec3:
    """
Electric field vector at a point due to a charge at a given position.

Rust: `electromagnetism::electric_field_vec`
    """
    ...

def electric_potential(charge: float, distance: float) -> float:
    """
Electric potential due to a point charge: V = k_e * q / r

Rust: `electromagnetism::electric_potential`
    """
    ...

def electric_potential_energy(q1: float, q2: float, distance: float) -> float:
    """
Electric potential energy: U = k_e * q1 * q2 / r

Rust: `electromagnetism::electric_potential_energy`
    """
    ...

def electric_flux_gauss(enclosed_charge: float) -> float:
    """
Electric flux through a surface (Gauss's law): Φ = q_enclosed / ε_0

Rust: `electromagnetism::electric_flux_gauss`
    """
    ...

def capacitance_parallel_plate(area: float, separation: float) -> float:
    """
Capacitance of a parallel plate capacitor: C = ε_0 * A / d

Rust: `electromagnetism::capacitance_parallel_plate`
    """
    ...

def capacitor_energy(capacitance: float, voltage: float) -> float:
    """
Energy stored in a capacitor: U = 0.5 * C * V^2

Rust: `electromagnetism::capacitor_energy`
    """
    ...

def ohms_law_voltage(current: float, resistance: float) -> float:
    """
Ohm's law: V = I * R

Rust: `electromagnetism::ohms_law_voltage`
    """
    ...

def ohms_law_current(voltage: float, resistance: float) -> float:
    """
Ohm's law: I = V / R

Rust: `electromagnetism::ohms_law_current`
    """
    ...

def ohms_law_resistance(voltage: float, current: float) -> float:
    """
Ohm's law: R = V / I

Rust: `electromagnetism::ohms_law_resistance`
    """
    ...

def electrical_power(voltage: float, current: float) -> float:
    """
Electrical power: P = V * I

Rust: `electromagnetism::electrical_power`
    """
    ...

def electrical_power_from_current(current: float, resistance: float) -> float:
    """
Electrical power: P = I^2 * R

Rust: `electromagnetism::electrical_power_from_current`
    """
    ...

def resistors_series(resistances: list[float]) -> float:
    """
Resistors in series: R_total = R1 + R2 + ...

Rust: `electromagnetism::resistors_series`
    """
    ...

def resistors_parallel(resistances: list[float]) -> float:
    """
Resistors in parallel: 1/R_total = 1/R1 + 1/R2 + ...

Rust: `electromagnetism::resistors_parallel`
    """
    ...

def capacitors_series(capacitances: list[float]) -> float:
    """
Capacitors in series: 1/C_total = 1/C1 + 1/C2 + ...

Rust: `electromagnetism::capacitors_series`
    """
    ...

def capacitors_parallel(capacitances: list[float]) -> float:
    """
Capacitors in parallel: C_total = C1 + C2 + ...

Rust: `electromagnetism::capacitors_parallel`
    """
    ...

def rc_time_constant(resistance: float, capacitance: float) -> float:
    """
RC time constant: τ = R * C

Rust: `electromagnetism::rc_time_constant`
    """
    ...

def rc_charging_voltage(v0: float, resistance: float, capacitance: float, time: float) -> float:
    """
Voltage across charging capacitor: V(t) = V0 * (1 - e^(-t/RC))

Rust: `electromagnetism::rc_charging_voltage`
    """
    ...

def magnetic_force_on_charge(charge: float, velocity: float, b_field: float, angle_rad: float) -> float:
    """
Magnetic force on a moving charge: F = q * v * B * sin(θ)

Rust: `electromagnetism::magnetic_force_on_charge`
    """
    ...

def lorentz_force(charge: float, e_field: Vec3 | Sequence[float], velocity: Vec3 | Sequence[float], b_field: Vec3 | Sequence[float]) -> Vec3:
    """
Lorentz force: F = q * (E + v × B)

Rust: `electromagnetism::lorentz_force`
    """
    ...

def magnetic_field_wire(current: float, distance: float) -> float:
    """
Magnetic field from a long straight wire: B = μ_0 * I / (2π * r)

Rust: `electromagnetism::magnetic_field_wire`
    """
    ...

def force_between_wires(i1: float, i2: float, distance: float) -> float:
    """
Magnetic force between two parallel wires per unit length: F/L = μ_0 * I1 * I2 / (2π * d)

Rust: `electromagnetism::force_between_wires`
    """
    ...

def cyclotron_radius(mass: float, velocity: float, charge: float, b_field: float) -> float:
    """
Cyclotron radius: r = m*v / (|q|*B)

Rust: `electromagnetism::cyclotron_radius`
    """
    ...

def cyclotron_frequency(charge: float, b_field: float, mass: float) -> float:
    """
Cyclotron frequency: f = |q|*B / (2π*m)

Rust: `electromagnetism::cyclotron_frequency`
    """
    ...

def faraday_emf(num_turns: float, delta_flux: float, delta_time: float) -> float:
    """
Faraday's law (magnitude): EMF = -N * dΦ/dt

Rust: `electromagnetism::faraday_emf`
    """
    ...

def motional_emf(b_field: float, length: float, velocity: float) -> float:
    """
Motional EMF: ε = B * L * v

Rust: `electromagnetism::motional_emf`
    """
    ...

def inductor_energy(inductance: float, current: float) -> float:
    """
Inductance energy: U = 0.5 * L * I^2

Rust: `electromagnetism::inductor_energy`
    """
    ...

def wavelength_from_frequency(frequency: float) -> float:
    """
Relationship between wavelength and frequency: c = λ * f

Rust: `electromagnetism::wavelength_from_frequency`
    """
    ...

def frequency_from_wavelength(wavelength: float) -> float:
    """
Frequency from wavelength: f = c / λ

Rust: `electromagnetism::frequency_from_wavelength`
    """
    ...

def poynting_magnitude(e_field: float, b_field: float) -> float:
    """
Poynting vector magnitude (EM wave intensity): S = E * B / μ_0

Rust: `electromagnetism::poynting_magnitude`
    """
    ...

def solenoid_field(mu0: float, turns_per_length: float, current: float) -> float:
    """
Solenoid magnetic field: B = μ₀nI

Rust: `electromagnetism::solenoid_field`
    """
    ...

def toroid_field(mu0: float, total_turns: float, current: float, radius: float) -> float:
    """
Toroid magnetic field: B = μ₀NI/(2πr)

Rust: `electromagnetism::toroid_field`
    """
    ...

def magnetic_flux(b_field: float, area: float, angle: float) -> float:
    """
Magnetic flux: Φ = BA cos(θ)

Rust: `electromagnetism::magnetic_flux`
    """
    ...

def magnetic_energy_density(b_field: float) -> float:
    """
Magnetic energy density: u = B²/(2μ₀)

Rust: `electromagnetism::magnetic_energy_density`
    """
    ...

def mutual_inductance_coaxial(mu0: float, n1: float, n2: float, area: float, length: float) -> float:
    """
Mutual inductance of coaxial solenoids: M = μ₀n₁n₂AL

Rust: `electromagnetism::mutual_inductance_coaxial`
    """
    ...

def self_inductance_solenoid(mu0: float, turns: float, area: float, length: float) -> float:
    """
Self-inductance of a solenoid: L = μ₀N²A/l

Rust: `electromagnetism::self_inductance_solenoid`
    """
    ...

def magnetic_dipole_moment(current: float, area: float) -> float:
    """
Magnetic dipole moment: m = IA

Rust: `electromagnetism::magnetic_dipole_moment`
    """
    ...

def torque_on_dipole(moment: float, b_field: float, angle: float) -> float:
    """
Torque on a magnetic dipole: τ = mB sin(θ)

Rust: `electromagnetism::torque_on_dipole`
    """
    ...

def capacitive_reactance(frequency: float, capacitance: float) -> float:
    """
Capacitive reactance: Xc = 1/(2πfC)

Rust: `electromagnetism::capacitive_reactance`
    """
    ...

def inductive_reactance(frequency: float, inductance: float) -> float:
    """
Inductive reactance: XL = 2πfL

Rust: `electromagnetism::inductive_reactance`
    """
    ...

def impedance_rlc_series(resistance: float, inductive_reactance: float, capacitive_reactance: float) -> float:
    """
Impedance of a series RLC circuit: Z = √(R² + (XL - XC)²)

Rust: `electromagnetism::impedance_rlc_series`
    """
    ...

def resonant_frequency_lc(inductance: float, capacitance: float) -> float:
    """
Resonant frequency of an LC circuit: f₀ = 1/(2π√(LC))

Rust: `electromagnetism::resonant_frequency_lc`
    """
    ...

def power_factor(resistance: float, impedance: float) -> float:
    """
Power factor: cos(φ) = R/Z

Rust: `electromagnetism::power_factor`
    """
    ...

def rms_voltage(peak: float) -> float:
    """
RMS voltage: V_rms = V_peak/√2

Rust: `electromagnetism::rms_voltage`
    """
    ...

def rms_current(peak: float) -> float:
    """
RMS current: I_rms = I_peak/√2

Rust: `electromagnetism::rms_current`
    """
    ...

def ac_power_average(vrms: float, irms: float, power_factor: float) -> float:
    """
Average AC power: P = V_rms × I_rms × cos(φ)

Rust: `electromagnetism::ac_power_average`
    """
    ...

def quality_factor_rlc(inductance: float, capacitance: float, resistance: float) -> float:
    """
Quality factor of an RLC circuit: Q = (1/R)√(L/C)

Rust: `electromagnetism::quality_factor_rlc`
    """
    ...

def bandwidth_rlc(resonant_freq: float, quality: float) -> float:
    """
Bandwidth of an RLC circuit: BW = f₀/Q

Rust: `electromagnetism::bandwidth_rlc`
    """
    ...

def em_wave_speed(permittivity: float, permeability: float) -> float:
    """
EM wave speed in a medium: v = 1/√(εμ)

Rust: `electromagnetism::em_wave_speed`
    """
    ...

def refractive_index_from_em(permittivity_rel: float, permeability_rel: float) -> float:
    """
Refractive index from relative permittivity and permeability: n = √(ε_r × μ_r)

Rust: `electromagnetism::refractive_index_from_em`
    """
    ...

def characteristic_impedance(permeability: float, permittivity: float) -> float:
    """
Characteristic impedance of a medium: η = √(μ/ε)

Rust: `electromagnetism::characteristic_impedance`
    """
    ...

def free_space_impedance() -> float:
    """
Free-space impedance: η₀ = √(μ₀/ε₀) ≈ 377 Ω

Rust: `electromagnetism::free_space_impedance`
    """
    ...

def energy_density_em(e_field: float, b_field: float) -> float:
    """
Total EM energy density: u = ε₀E²/2 + B²/(2μ₀)

Rust: `electromagnetism::energy_density_em`
    """
    ...

def radiation_intensity_dipole(power: float, angle: float) -> float:
    """
Radiation intensity of a Hertzian dipole: I(θ) = (3P/(8π)) × sin²(θ)

Rust: `electromagnetism::radiation_intensity_dipole`
    """
    ...

def larmor_power(charge: float, acceleration: float) -> float:
    """
Larmor radiated power: P = q²a²/(6πε₀c³)

Rust: `electromagnetism::larmor_power`
    """
    ...

def transformer_voltage(v_primary: float, n_primary: float, n_secondary: float) -> float:
    """
Transformer secondary voltage: V₂ = V₁ × N₂/N₁

Rust: `electromagnetism::transformer_voltage`
    """
    ...

def transformer_current(i_primary: float, n_primary: float, n_secondary: float) -> float:
    """
Transformer secondary current: I₂ = I₁ × N₁/N₂

Rust: `electromagnetism::transformer_current`
    """
    ...
