"""
Implicit (stiff-stable) ODE steps: backward Euler and BDF2.  Both solve their implicit update equation with damped-free Newton iteration; the Jacobian of f is user-supplied or, when `None`, approximated by forward finite differences (an opaque `f64` closure cannot be differentiated with `core::dual`, so finite differences stand in for it here).
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional



