"""
Discrete Fourier transform utilities.  These are thin wrappers over `transforms::fft` (Step 0 of roadmap Part 3): every length now runs in O(n log n) via the mixed-radix / Bluestein FFT while keeping the original `(re, im)` tuple API.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def dft(signal: list[float]) -> list[tuple[float, float]]:
    """
Discrete Fourier Transform: `X[k] = Σ x[n]·e^(-j2πkn/N)`, returns (real, imag) pairs

Rust: `statistics::fourier::dft`
    """
    ...

def inverse_dft(spectrum: list[tuple[float, float]]) -> list[float]:
    """
Inverse DFT: `x[n] = (1/N)·Σ X[k]·e^(j2πkn/N)`

Rust: `statistics::fourier::inverse_dft`
    """
    ...

def power_spectrum(signal: list[float]) -> list[float]:
    """
Power spectrum: `|X[k]|² = Re² + Im²` for each frequency bin.

Uses the real FFT and reconstructs the upper half from conjugate
symmetry. Output length always equals `signal.len()`.

Rust: `statistics::fourier::power_spectrum`
    """
    ...

def dominant_frequency(signal: list[float], sample_rate: float) -> float:
    """
Find the dominant frequency in a signal: f_peak = k_max · f_s / N

Rust: `statistics::fourier::dominant_frequency`
    """
    ...
