"""
The five Lagrange points of the circular restricted three-body problem.  L1, L2 and L3 lie on the line through the two masses and are found by solving a quintic numerically; L4 and L5 sit at the vertices of equilateral triangles with the two masses and are exact.  The collinear points are unstable saddles -- a spacecraft there needs station-keeping -- while L4 and L5 are stable for a mass ratio below about 1/24.96, which is why Jupiter's Trojan asteroids stay put. The Hill radius is here as well.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.math import Vec3

def hill_radius(distance: float, body_mass: float, primary_mass: float) -> float:
    """
Computes the Hill sphere radius: r_H = d (m / 3M)^(1/3).

Rust: `astrophysics::lagrange::hill_radius`
    """
    ...

def lagrange_points(primary_pos: Vec3 | Sequence[float], primary_mass: float, body_pos: Vec3 | Sequence[float], body_vel: Vec3 | Sequence[float], body_mass: float) -> list[Vec3]:
    """
Computes all five Lagrange points (L1-L5) for a two-body system in the co-rotating frame.

Rust: `astrophysics::lagrange::lagrange_points`
    """
    ...

def circular_velocity(mu: float, distance: float) -> float:
    """
Computes the circular orbital velocity: v_c = √(μ/r).

Rust: `astrophysics::lagrange::circular_velocity`
    """
    ...

def escape_ratio(speed: float, escape_vel: float) -> float:
    """
Computes the ratio of current speed to escape velocity: v / v_esc.

Rust: `astrophysics::lagrange::escape_ratio`
    """
    ...
