"""
Orbital manoeuvres: combined burns, patched conics, gravity assists and the perturbation that dominates low orbits.  # What lives elsewhere  The impulsive transfers themselves are already in `propulsion`: `hohmann_delta_v`, `hohmann_transfer_time`, `bi_elliptic_delta_v`, `delta_v_plane_change`, `tsiolkovsky_delta_v` and `delta_v_staged`. The Roche limit is in `astrophysics::tidal` and the Hill radius in `astrophysics::lagrange`. This module adds what those do not cover, and reuses rather than repeats them.  # Why delta-v is the currency  Every manoeuvre here is priced in velocity change rather than in fuel, because the conversion between them is exponential: Tsiolkovsky's equation says the mass ratio is `e^(dv/v_e)`, so a mission's delta-v budget is a linear quantity that adds up while its mass is not. Ten per cent more delta-v is not ten per cent more spacecraft.  The other consequence is the Oberth effect. A burn's *energy* gain is `v dv`, proportional to the speed you already have, so the same delta-v spent deep in a gravity well buys far more energy than the same delta-v spent far from it. That is why escape burns are made at periapsis and why a flyby is worth planning around.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.math import Vec3

def combined_maneuver(v1: float, v2: float, plane_change: float) -> float:
    """
The delta-v of a combined speed change and plane change, by the law of
cosines.

`sqrt(v1^2 + v2^2 - 2 v1 v2 cos(di))`. Doing both at once is always
cheaper than doing them one after the other, because the two vector
changes partly cancel -- the triangle inequality, applied to velocity.
The saving is largest when the plane change is large, which is why an
inclination change is combined with an apoapsis burn wherever the
mission allows.

Errors:
Returns an error for a negative speed or a non-finite input.

Rust: `astrophysics::maneuvers::combined_maneuver`
    """
    ...

def sphere_of_influence(distance: float, body_mass: float, primary_mass: float) -> float:
    """
The radius of a body's sphere of influence:
`a (m_body / m_primary)^(2/5)`.

Inside it the body's gravity dominates the primary's for the purposes
of a patched-conic approximation, and outside it does not. The
two-fifths power is not the equal-force radius, which would be a
square root: it comes from comparing the *perturbing* accelerations
rather than the direct ones, and it is the boundary at which
switching which body you orbit makes the smaller error.

The sphere is a fiction. Gravity has no boundary, and a real
trajectory feels both bodies throughout; the patched conic is an
approximation whose error is largest exactly at the crossing, where
the neglected body's pull is at its relative peak.

Errors:
Returns an error for a non-positive distance or mass, or a body more
massive than its primary.

Rust: `astrophysics::maneuvers::sphere_of_influence`
    """
    ...

def patched_conic_escape(parking_radius: float, mu: float, v_infinity: float) -> float:
    """
The delta-v to leave a circular parking orbit on a hyperbola with the
given excess speed: `sqrt(v_infinity^2 + 2 mu / r) - sqrt(mu / r)`.

The first term is the speed needed at radius `r` to arrive at infinity
still moving at `v_infinity`; the second is what a circular orbit
already provides. The gap is small compared with either, which is the
Oberth effect in its most practical form: escaping from low orbit
costs about 0.41 of the circular speed, and the deeper the parking
orbit the smaller that fraction becomes.

Errors:
Returns an error for a non-positive radius or gravitational parameter,
a negative excess speed, or a non-finite input.

Rust: `astrophysics::maneuvers::patched_conic_escape`
    """
    ...

def gravity_assist_deflection(v_infinity: float, periapsis: float, mu: float) -> float:
    """
The turn angle of a hyperbolic flyby:
`2 arcsin(1 / (1 + r_p v_inf^2 / mu))`.

A gravity assist changes the direction of the excess velocity, not its
magnitude -- in the *planet's* frame the spacecraft arrives and leaves
at the same speed. The gain is in the sun's frame, where rotating the
excess velocity vector adds or subtracts from the planet's orbital
motion, and the planet loses exactly as much momentum as the
spacecraft gains.

The turn is largest for a slow approach and a close pass. A fast
spacecraft is barely deflected, which is why an assist buys less the
more energy you already have.

Errors:
Returns an error for a non-positive periapsis, gravitational parameter
or excess speed, or a non-finite input.

Rust: `astrophysics::maneuvers::gravity_assist_deflection`
    """
    ...

def oberth_effect_dv(speed: float, delta_v: float, radius: float, mu: float) -> float:
    """
The speed after an impulsive burn of `delta_v` made at radius `r`,
through the energy it buys.

The point of the function is the comparison it makes possible: the same
delta-v spent at two radii leaves the craft with different energies,
and the difference is `v dv` -- large where `v` is large, which is deep
in the well. Burning at periapsis rather than apoapsis can double the
escape energy for the same fuel.

Errors:
Returns an error for a non-positive radius or gravitational parameter,
a negative speed, or a non-finite input.

Rust: `astrophysics::maneuvers::oberth_effect_dv`
    """
    ...

def j2_raan_drift(a: float, e: float, inclination: float, j2: float, body_radius: float, mu: float) -> float:
    """
The nodal regression rate from the Earth's oblateness, in radians per
second.

`-3/2 n J2 (R/p)^2 cos(i)`, with `p = a(1 - e^2)` and `n` the mean
motion. The `cos i` is what makes the whole thing useful: the drift is
westward for a prograde orbit, zero at exactly ninety degrees, and
eastward beyond it. A retrograde orbit at the right inclination
therefore drifts eastward at precisely the rate the Earth goes round
the sun -- see `sun_synchronous_inclination`.

J2 dominates every other perturbation in low orbit by three orders of
magnitude, which is why a first-order treatment of it is worth more
than a careful treatment of anything else.

Errors:
Returns an error for a non-positive semi-major axis, body radius or
gravitational parameter, an eccentricity outside `[0, 1)`, or a
non-finite input.

Rust: `astrophysics::maneuvers::j2_raan_drift`
    """
    ...

def sun_synchronous_inclination(a: float, e: float, j2: float, body_radius: float, mu: float, drift_per_second: float) -> float:
    """
The inclination at which J2 makes an orbit sun-synchronous.

The node must drift eastward by one turn a year, which is
`1.991e-7 rad/s`. Solving `j2_raan_drift` for the inclination gives
a value just past ninety degrees -- about 98 degrees for a low orbit --
and it must be retrograde, since a prograde orbit's node drifts the
wrong way.

The orbit is sun-synchronous in the sense that it crosses the equator
at the same local solar time every pass, which is what makes imaging
comparable between days. It says nothing about lighting at high
latitudes, where the geometry differs.

Errors:
Returns an error for a non-positive semi-major axis, body radius or
gravitational parameter, an eccentricity outside `[0, 1)`, or an orbit
for which no inclination gives the required drift -- which happens
when the orbit is too high for J2 to turn it fast enough.

Rust: `astrophysics::maneuvers::sun_synchronous_inclination`
    """
    ...

def ground_track(r0: Vec3 | Sequence[float], v0: Vec3 | Sequence[float], mu: float, rotation_rate: float, duration: float, samples: int) -> list[tuple[float, float]]:
    """
The ground track of an orbit: `(longitude, latitude)` in radians at
each sample, accounting for the body turning underneath.

The longitude drift per orbit is what makes a track a spiral rather
than a closed curve: the body turns by `rotation_rate * period` while
the orbit plane stays put, so each pass crosses the equator further
west. A track closes only when the period is a rational fraction of
the rotation, which is what a repeat-ground-track orbit is designed
for.

The latitude never exceeds the inclination, and reaches it exactly
twice per orbit. That bound is the reason a polar orbit is needed to
see the poles at all.

Errors:
Returns an error for a bad state, a non-positive gravitational
parameter, no samples, more than a million, or a propagation failure.

Rust: `astrophysics::maneuvers::ground_track`
    """
    ...
