"""
Option pricing: closed forms, lattices, Monte Carlo and a PDE solver.  # Conventions  Rates and volatilities are continuously compounded and annualised; time is in years. `q` is a continuous dividend yield, which also serves as a foreign interest rate for a currency option and as a convenience yield for a commodity. A `call: bool` argument names the payoff: `max(S - K, 0)` when true and `max(K - S, 0)` when false.  # Why there are so many methods for one number  They price different things, and where they overlap they check each other. `black_scholes` is exact but only for a European payoff on a lognormal process. A lattice (`binomial_crr`, `trinomial`) handles early exercise, at the cost of converging to the closed form only in the limit -- and it converges by oscillating around the answer, not by approaching it from one side. Monte Carlo (`monte_carlo_european` and the path-dependent payoffs) handles anything you can simulate, and pays for that with an error that falls like the square root of the path count, which is why the variance reduction here is not an optimisation but the difference between usable and not.  # The volatility argument is the whole problem  Black-Scholes takes one volatility for all strikes. Real option prices do not admit one: the implied volatilities of options on the same underlying and expiry form a smile, and a model with a single sigma cannot produce it. That is not a defect in the arithmetic, it is the lognormal assumption failing. `merton_jump_price` and the Heston model add mechanisms that generate a smile, and `volatility_smile_svi` simply parameterises one without a mechanism.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.statistics.distributions import Gamma
from numeria.statistics.distributions import Poisson
from numeria.monte_carlo import Rng

class Barrier:
    """
Which barrier a knock-out or knock-in option watches.

Rust: `finance::options::Barrier`
    """
    ...

class Greeks:
    """
The first-order sensitivities of an option price.

Rust: `finance::options::Greeks`
    """
    def __init__(self, delta: float, gamma: float, vega: float, theta: float, rho: float) -> None: ...
    @property
    def delta(self) -> float: ...
    @property
    def gamma(self) -> float: ...
    @property
    def vega(self) -> float: ...
    @property
    def theta(self) -> float: ...
    @property
    def rho(self) -> float: ...

class Svi:
    """
The raw SVI parameterisation of a volatility smile.

Rust: `finance::options::Svi`
    """
    def __init__(self, a: float, b: float, rho: float, m: float, sigma: float) -> None: ...
    @property
    def a(self) -> float: ...
    @property
    def b(self) -> float: ...
    @property
    def rho(self) -> float: ...
    @property
    def m(self) -> float: ...
    @property
    def sigma(self) -> float: ...

def black_scholes(s: float, k: float, t: float, r: float, sigma: float, q: float, call: bool) -> float:
    """
The Black-Scholes-Merton price of a European option.

`S e^(-qT) N(d1) - K e^(-rT) N(d2)` for a call, and the mirror for a
put. The two terms are not "probability times payoff": the first is the
value of receiving the share if exercised, computed under a measure in
which the share is the numeraire, and the second is the strike times
the risk-neutral probability of exercise. Reading `N(d2)` as a
real-world probability is the commonest misreading of the formula --
it is a probability under a measure chosen to make discounted prices
martingales, and has nothing to say about what the share will do.

Zero volatility or zero time to expiry both collapse the formula to
the discounted intrinsic value, which is handled directly rather than
left to divide by zero.

Errors:
Returns an error for a non-positive price or strike, a negative time or
volatility, or any input that is not finite.

Rust: `finance::options::black_scholes`
    """
    ...

def bs_greeks(s: float, k: float, t: float, r: float, sigma: float, q: float, call: bool) -> Greeks:
    """
The Black-Scholes Greeks.

`vega` is per unit of volatility (so divide by 100 for "per volatility
point"), `theta` is per year (divide by 365 for a daily decay), and
`rho` is per unit of rate. Those conventions differ between desks and
are the commonest source of a factor of a hundred.

Gamma and vega are the same for a call and a put, because the two
differ by a forward contract, which is linear in the spot and does not
depend on volatility at all. That identity is exact and is what the
tests check rather than the individual numbers.

Errors:
Returns an error for the same inputs as `black_scholes`, and for a
zero time or volatility, where the derivatives do not exist.

Rust: `finance::options::bs_greeks`
    """
    ...

def implied_volatility(price: float, s: float, k: float, t: float, r: float, q: float, call: bool) -> Optional[float]:
    """
The volatility that reproduces an observed price, or `None` if no
volatility does.

Price is strictly increasing in volatility, so the root is unique where
it exists; the search brackets it by doubling and then bisects, taking
Newton steps where vega is large enough to trust and falling back to
bisection where it is not. Deep out-of-the-money options have vega
near zero over a wide range of volatilities, which is exactly where a
pure Newton iteration diverges and where the answer is least
meaningful.

`None` means no volatility can be recovered, for either of two
reasons. The price may be outside the model's range -- below the
no-arbitrage floor (the discounted intrinsic value), above the
ceiling, or unreachable at any volatility the doubling search reaches.
Or the price may simply not determine one: a deep in-the-money option
with weeks left has a vega around `1e-13`, and prices identically at
5% and at 20% volatility to the last bit of a double. Returning a
number there would be reporting rounding noise as a measurement, so
the answer is withheld when vega falls below `1e-8` relative to the
price.

Errors:
Returns an error for a non-positive price or strike, a non-positive
time, or a negative observed price.

Rust: `finance::options::implied_volatility`
    """
    ...

def put_call_parity_check(call: float, put: float, s: float, k: float, t: float, r: float, q: float) -> float:
    """
The put-call parity residual: `C - P - S e^(-qT) + K e^(-rT)`.

Zero for any pair of European prices that admit no arbitrage,
*whatever* model produced them, because the identity follows from the
payoffs alone: holding a call and selling a put is the same as holding
the forward. A residual is therefore a statement about the prices, not
about the model, and this is the sharpest check available on a pricing
routine that has no closed form to compare with.

Rust: `finance::options::put_call_parity_check`
    """
    ...

def binomial_crr(s: float, k: float, t: float, r: float, sigma: float, q: float, steps: int, call: bool, american: bool) -> float:
    """
The Cox-Ross-Rubinstein binomial tree.

Up and down moves of `e^(±sigma sqrt(dt))` with the risk-neutral
probability that makes the discounted price a martingale. Set
`american` to allow exercise at every node.

Convergence to Black-Scholes is `O(1/steps)` but *oscillatory*: the
error alternates in sign as the strike moves between two adjacent
terminal nodes, so a tree with 101 steps can be further from the answer
than one with 100. Averaging two consecutive step counts removes most
of it, and is why an odd-even pair is the honest way to quote a
lattice price.

Errors:
Returns an error for bad option parameters, zero steps, more than
twenty thousand steps, or a `dt` so large that the risk-neutral
probability leaves `[0, 1]` -- which happens when the drift outruns
what the volatility can span in one step.

Rust: `finance::options::binomial_crr`
    """
    ...

def trinomial(s: float, k: float, t: float, r: float, sigma: float, q: float, steps: int, call: bool, american: bool) -> float:
    """
A trinomial tree with an up, down and unchanged move.

The third branch buys a free parameter, used here to set the space step
to `sigma sqrt(3 dt)`, which is the choice that makes the tree stable
and its convergence smoother than the binomial's. It is the same
explicit finite-difference scheme as the binomial in different
clothing, and the extra branch is what keeps the scheme's coefficients
positive over a wider range of steps.

The probabilities here match the first two moments of the *log* price.
That is the usual construction and it has a consequence worth knowing:
unlike Cox-Ross-Rubinstein, whose up-probability is chosen to make the
price itself a martingale exactly, this tree is a martingale only to
`O(dt^2)`. So its call and put prices satisfy put-call parity only to
that order -- a residual of about `2e-3` on a two-and-a-half-year
option at seven steps, falling as `1/steps^2` and reaching `4e-8` by
sixteen hundred. The tree is arbitrage-free in the limit and not
before it. Use `binomial_crr` where an exactly consistent call and
put matter more than a smooth convergence.

Errors:
As `binomial_crr`, with a lower step ceiling since the work is
quadratic in the step count.

Rust: `finance::options::trinomial`
    """
    ...

def monte_carlo_european(s: float, k: float, t: float, r: float, sigma: float, q: float, call: bool, paths: int, rng: Rng) -> tuple[float, float]:
    """
A European option by Monte Carlo, returning `(price, standard error)`.

Two variance reductions are applied, and both are exact rather than
heuristic:

*Antithetic variates* price each draw with `z` and `-z`. The pair has
the same distribution as two independent draws, so the estimator stays
unbiased, and the negative correlation between the two payoffs shrinks
the variance of their mean.

*A control variate* uses the discounted terminal price, whose expected
value under the risk-neutral measure is exactly `S e^(-qT)` -- known,
not estimated. Subtracting `beta` times its error from each payoff
cannot bias the result whatever `beta` is, and choosing `beta` by
regression on the same sample minimises the variance.

The reported standard error is the error *of the reduced estimator*,
so it is the honest one to compare against the closed form: a price
two standard errors from Black-Scholes is a failure, and the tests
treat it as one.

Errors:
Returns an error for bad option parameters or a path count outside
`[2, 2e7]`.

Rust: `finance::options::monte_carlo_european`
    """
    ...

def monte_carlo_asian(s: float, k: float, t: float, r: float, sigma: float, q: float, call: bool, steps: int, paths: int, rng: Rng) -> tuple[float, float]:
    """
An arithmetic-average Asian option by Monte Carlo, returning
`(price, standard error)`.

The average is taken over the `steps` monitoring dates, excluding the
start. Averaging is what makes the option cheaper than its European
twin: the average of a lognormal has lower variance than its terminal
value, and lower variance means a lower option price at the same
forward.

There is no closed form for the arithmetic average -- the sum of
lognormals is not lognormal -- which is why this is a simulation and
not a formula. The *geometric* average does have one, and that is what
makes a geometric control variate the standard variance reduction
here; it is not applied, so expect the error to fall only as the
square root of the path count.

Errors:
Returns an error for bad option parameters, a path count outside
`[2, 2e7]`, a step count of zero, or more than fifty million total
steps.

Rust: `finance::options::monte_carlo_asian`
    """
    ...

def monte_carlo_barrier(s: float, k: float, barrier: float, kind: Barrier, t: float, r: float, sigma: float, q: float, call: bool, steps: int, paths: int, rng: Rng) -> tuple[float, float]:
    """
A barrier option by Monte Carlo, returning `(price, standard error)`.

The barrier is checked only at the `steps` monitoring dates. That is a
*discretely monitored* option and it is worth strictly more than a
continuously monitored one, because a path can cross the barrier and
come back between observations. The gap closes slowly, like
`1/sqrt(steps)`, so a daily-monitored option priced with twelve steps
is materially mispriced -- the discretisation is a modelling choice
here, not a numerical detail.

The in-out parity holds by construction: a knock-in and its matching
knock-out sum to the vanilla option, since every path pays into exactly
one of them.

Errors:
As `monte_carlo_asian`, plus a non-positive barrier level.

Rust: `finance::options::monte_carlo_barrier`
    """
    ...

def monte_carlo_lookback(s: float, k: float, t: float, r: float, sigma: float, q: float, call: bool, steps: int, paths: int, rng: Rng) -> tuple[float, float]:
    """
A fixed-strike lookback option by Monte Carlo, returning
`(price, standard error)`.

A call pays on the running maximum and a put on the running minimum, so
the holder is credited with the best price the path ever reached. It is
therefore worth at least as much as the European option with the same
strike, always and path by path, and the tests use that as an ordering
rather than a number.

Discrete monitoring cuts the price for the same reason it raises a
knock-out's: the sampled extremum is closer to the terminal value than
the continuous one.

Errors:
As `monte_carlo_asian`.

Rust: `finance::options::monte_carlo_lookback`
    """
    ...

def longstaff_schwartz_american(s: float, k: float, t: float, r: float, sigma: float, q: float, call: bool, steps: int, paths: int, rng: Rng) -> float:
    """
The Longstaff-Schwartz price of an American option by least-squares
Monte Carlo.

Working backwards from expiry, the continuation value at each exercise
date is regressed on a quadratic in the current price, using only the
paths that are in the money -- and the *fitted* value, not the
realised one, decides whether to exercise. Using the realised future
payoff to make the decision would be looking ahead, and would produce a
price above the true one.

The estimate is biased low in principle, because the exercise rule
comes from a finite regression and any suboptimal rule undervalues the
option. In practice with a low-order basis it can also come out high
on the same sample the rule was fitted on, which is why the tests
compare it against a binomial tree with a tolerance rather than
asserting a direction.

Errors:
As `monte_carlo_asian`, and for fewer than two exercise dates.

Rust: `finance::options::longstaff_schwartz_american`
    """
    ...

def merton_jump_price(s: float, k: float, t: float, r: float, sigma: float, q: float, lambda_: float, jump_mean: float, jump_vol: float, call: bool) -> float:
    """
Merton's jump-diffusion price, as a Poisson-weighted sum of
Black-Scholes prices.

A jump arriving at rate `lambda` multiplies the price by a lognormal
factor with log-mean `jump_mean` and log-standard-deviation
`jump_vol`. Conditioning on the number of jumps makes each term
lognormal again, so the price is an exact infinite sum of Black-Scholes
prices with adjusted rate and volatility, truncated here once the
Poisson weights are exhausted.

The drift compensator `-lambda * (e^(jump_mean + jump_vol^2/2) - 1)`
is what keeps the discounted price a martingale: jumps add expected
return, and it must be taken back out of the diffusion or the model
prices an arbitrage.

Jumps are what generate a smile. A single lognormal cannot make
out-of-the-money options expensive relative to at-the-money ones; a
mixture over jump counts has fatter tails and does exactly that.

Errors:
Returns an error for bad option parameters, a negative jump intensity
or volatility, or a non-positive maturity.

Rust: `finance::options::merton_jump_price`
    """
    ...

def heston_price_mc(s: float, k: float, t: float, r: float, q: float, v0: float, kappa: float, theta: float, xi: float, rho: float, call: bool, steps: int, paths: int, rng: Rng) -> tuple[float, float]:
    """
A Heston stochastic-volatility price by Monte Carlo, returning
`(price, standard error)`.

The variance follows `dv = kappa (theta - v) dt + xi sqrt(v) dW`, with
the variance's Brownian motion correlated with the price's at `rho`.
That correlation is the model's point: a negative `rho` makes the
volatility rise as the price falls, which produces the downward-sloping
implied volatility skew that equity markets actually show, and which no
symmetric model can.

The variance is simulated with a full-truncation Euler scheme -- the
variance is floored at zero wherever a step takes it negative. Exact
simulation of the variance process is possible but expensive, and
full truncation is the standard compromise; it biases the price
slightly, and the bias falls with the step count rather than the path
count, so refining paths alone will not remove it.

Errors:
Returns an error for bad option parameters, a negative initial or
long-run variance, a non-positive mean reversion or volatility of
volatility, a correlation outside `[-1, 1]`, or a step or path count
outside its budget.

Rust: `finance::options::heston_price_mc`
    """
    ...

def volatility_smile_svi(params: Svi | Sequence[float], k: float) -> float:
    """
Total implied variance under raw SVI:
`a + b (rho (k - m) + sqrt((k - m)^2 + sigma^2))`.

`k` is log-moneyness `ln(K/F)` and the result is *total* variance
`sigma_implied^2 * T`, not annualised variance. SVI is a shape, not a
model: it has no process behind it and makes no prediction, and its
value is that five parameters fit an observed smile closely and the
wings are linear in `k`, which is what Lee's moment formula requires of
any arbitrage-free smile.

Errors:
Returns an error for a negative `b`, a non-positive `sigma`, a `rho`
outside `[-1, 1]`, or a total variance that comes out negative -- which
is an arbitrage, not a small numerical matter.

Rust: `finance::options::volatility_smile_svi`
    """
    ...

def svi_fit(log_moneyness: list[float], total_variance: list[float]) -> Svi:
    """
Fits raw SVI to observed total variances by Nelder-Mead on the sum of
squared errors.

The objective is not convex and the parameters trade off against each
other -- `b` and `sigma` in particular are nearly degenerate for a
shallow smile -- so the search is restarted from the best point found,
which is what rescues it from the flat valley a single pass stalls in.
A good fit here means the shape matches, not that the parameters are
identified.

Errors:
Returns an error for fewer than five points, mismatched lengths, or a
non-positive total variance among the targets.

Rust: `finance::options::svi_fit`
    """
    ...

def bs_pde_crank_nicolson(s: float, k: float, t: float, r: float, sigma: float, q: float, call: bool, american: bool, space: int, time_steps: int) -> float:
    """
The Black-Scholes PDE solved by Crank-Nicolson on a log-price grid.

Solves `dV/dt + (r - q - sigma^2/2) dV/dx + (sigma^2/2) d2V/dx2 = rV`
backwards from the payoff, on `space` points spanning six standard
deviations either side of the log spot, with Dirichlet boundaries set
to the discounted no-arbitrage values. Set `american` to apply the
early-exercise constraint after each step, which makes the scheme a
projected one and costs its second-order accuracy in time near the
exercise boundary.

Crank-Nicolson is used rather than a fully implicit scheme because it
is second order in time as well as space. The price of that is that it
is only *A*-stable and not *L*-stable: it damps high-frequency error
slowly, so the kink in the payoff at the strike rings for several steps
rather than being smoothed away, and the Greeks near the strike are
visibly noisier than the price. Starting with a few fully implicit
steps -- Rannacher smoothing -- is the standard remedy and is what the
first two steps here do.

Errors:
Returns an error for bad option parameters, fewer than eleven space
points, no time steps, more than ten million grid cells, or a
tridiagonal system that will not solve.

Rust: `finance::options::bs_pde_crank_nicolson`
    """
    ...

def delta_hedging_sim(s: float, k: float, t: float, r: float, hedge_vol: float, realised_vol: float, q: float, call: bool, rebalances: int, paths: int, rng: Rng) -> tuple[float, float]:
    """
Simulates delta hedging a short European option, returning
`(mean profit and loss, standard deviation)`.

The option is sold at its Black-Scholes price and the position is
rehedged `rebalances` times at the model delta; the P&L is what remains
at expiry after the payoff is settled.

The mean is near zero because the option was sold at its fair price,
but the *standard deviation* is the point: it falls like
`1/sqrt(rebalances)`, so cutting the residual risk in half costs four
times as many trades. That trade-off, not the mean, is what makes
continuous hedging a limit rather than a procedure -- with any
transaction cost at all, the total cost grows as `sqrt(rebalances)`
while the risk falls as `1/sqrt(rebalances)`, and an optimum exists at
a finite frequency.

A hedge run at a volatility different from the one the path was
generated with does not have a zero mean; the difference is the
volatility arbitrage, and it is what the tests check rather than the
noise.

Errors:
Returns an error for bad option parameters, no rebalances, a
non-positive maturity, or a path count outside `[2, 2e7]`.

Rust: `finance::options::delta_hedging_sim`
    """
    ...
