"""
Portfolio construction and performance measurement.  # What mean-variance optimisation actually does  Markowitz's problem is: given expected returns and a covariance matrix, find the weights minimising variance at each level of expected return. It has a closed form, and that is both its appeal and its trap. The optimiser is an *error maximiser*: it puts weight where the estimated return is highest relative to the estimated risk, which is exactly where the estimates are most likely to be wrong. Expected returns estimated from a decade of monthly data carry standard errors of the same order as the differences between assets, so the "optimal" portfolio is often a leveraged bet on estimation noise.  Nothing here shrinks, regularises or constrains, because the roadmap's signatures do not. `min_variance_weights` uses only the covariance matrix, which is estimated far more reliably than the mean, and is for that reason the one output here that survives contact with real data.  # Returns compound, and that decides which average to use  `returns_from_prices` gives simple returns, whose *arithmetic* mean is the expected one-period return. `log_returns` gives continuously compounded returns, which add across periods, so their *sum* is the total log return. Mixing them up produces the standard error of quoting an arithmetic mean as though it were achievable: a series that gains 50% then loses 50% has an arithmetic mean return of zero and has lost a quarter of its value.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.statistics.distributions import Beta
from numeria.linalg.matrix import Matrix

def returns_from_prices(prices: list[float]) -> list[float]:
    """
Simple period returns `p[t]/p[t-1] - 1`.

Errors:
Returns an error for fewer than two prices, or a non-positive or
non-finite price.

Rust: `finance::portfolio::returns_from_prices`
    """
    ...

def log_returns(prices: list[float]) -> list[float]:
    """
Continuously compounded returns `ln(p[t]/p[t-1])`.

These add across periods, which is what makes them the right thing to
average when the question is about growth over time rather than about
the next period. They are always smaller than the simple return, by
roughly half the variance, which is the whole content of the
arithmetic-geometric gap.

Errors:
As `returns_from_prices`.

Rust: `finance::portfolio::log_returns`
    """
    ...

def portfolio_variance(cov: Matrix | Sequence[Sequence[float]], weights: list[float]) -> float:
    """
The portfolio variance `w' C w`.

Errors:
Returns an error for a malformed covariance matrix or mismatched
weights.

Rust: `finance::portfolio::portfolio_variance`
    """
    ...

def min_variance_weights(cov: Matrix | Sequence[Sequence[float]]) -> list[float]:
    """
The global minimum-variance weights, which sum to one.

`w = C^-1 1 / (1' C^-1 1)`. Expected returns do not appear, which is
why this is the mean-variance output that survives real data: a
covariance matrix estimated from the same sample that produced a
hopeless mean estimate is still usually good enough to rank risk.

Weights may be negative -- the problem as posed allows short positions,
and with correlated assets the minimum-variance solution frequently
takes them.

Errors:
Returns an error for a malformed or singular covariance matrix, or one
whose implied weights do not sum to a usable total.

Rust: `finance::portfolio::min_variance_weights`
    """
    ...

def tangency_portfolio(mu: list[float], cov: Matrix | Sequence[Sequence[float]], risk_free: float) -> list[float]:
    """
The tangency portfolio: the weights maximising the Sharpe ratio at a
given risk-free rate.

`w = C^-1 (mu - rf) / (1' C^-1 (mu - rf))`. Every portfolio on the
efficient frontier with a risk-free asset available is a mix of this
one and cash, which is the two-fund separation theorem -- and it is
what makes "the market portfolio" a meaningful object in CAPM.

The normalisation fails when the excess returns are orthogonal to the
inverse-covariance-weighted ones, and flips sign when the excess
returns are net negative, at which point the "tangency portfolio" is a
short position and the geometry has broken down. Both are reported
rather than returned as numbers.

Errors:
Returns an error for a malformed or singular covariance matrix,
mismatched means, or excess returns that do not determine a tangency.

Rust: `finance::portfolio::tangency_portfolio`
    """
    ...

def markowitz_frontier(mu: list[float], cov: Matrix | Sequence[Sequence[float]], points: int) -> list[tuple[float, float, list[float]]]:
    """
The efficient frontier as `(standard deviation, expected return,
weights)`, from the minimum-variance point up to the highest mean.

Each point solves the two-constraint problem exactly through the
standard `a, b, c` scalars, so no numerical optimisation is involved.
The frontier is a hyperbola in mean-standard-deviation space and a
parabola in mean-variance space, and its lower half -- the same
variances at lower returns -- is dominated and not returned.

Short positions are permitted throughout. A frontier computed with a
no-short constraint is a different and much better behaved object,
and it has no closed form.

Errors:
Returns an error for a malformed or singular covariance matrix,
mismatched means, fewer than two points, more than ten thousand, or
means that are all equal, where the frontier degenerates to a point.

Rust: `finance::portfolio::markowitz_frontier`
    """
    ...

def risk_parity_weights(cov: Matrix | Sequence[Sequence[float]]) -> list[float]:
    """
Risk-parity weights: each asset contributes the same share of total
portfolio risk.

The condition is `w_i (C w)_i` equal across assets, which has no closed
form. It is solved here by the fixed point of
`w_i <- sqrt(w_i / (C w)_i)`, renormalised each pass: at rest that
gives `w_i^2 = k^2 w_i / (C w)_i`, so `w_i (C w)_i` is the same
constant for every asset, which is the condition itself.

The square root is not decoration. The undamped update
`w_i <- w_i / (C w)_i` converges to `(C w)_i` equal across assets --
which is the *minimum-variance* condition, not this one, and gives
visibly different weights whenever the assets differ in volatility.

This is not the same as equal weights, nor as inverse-volatility
weights -- those coincide with it only when correlations are all
equal. The appeal is that it needs no expected returns at all, which
removes the input mean-variance optimisation is most damaged by.

Weights are constrained positive, which is what makes the problem well
posed: the equal-risk-contribution condition has no positive solution
requirement built in, and shorting breaks the interpretation.

Errors:
Returns an error for a malformed covariance matrix, or an iteration
that does not converge.

Rust: `finance::portfolio::risk_parity_weights`
    """
    ...

def risk_contributions(cov: Matrix | Sequence[Sequence[float]], weights: list[float]) -> list[float]:
    """
Each asset's share of total portfolio risk: `w_i (C w)_i / (w' C w)`.

The shares sum to one by construction, which is what makes "risk
contribution" a decomposition rather than a metaphor -- variance is a
quadratic form and Euler's theorem splits it exactly.

Errors:
As `portfolio_variance`, plus a portfolio with no variance.

Rust: `finance::portfolio::risk_contributions`
    """
    ...

def sharpe(returns: list[float], risk_free: float) -> float:
    """
The Sharpe ratio: mean excess return divided by its standard deviation.

Per period, not annualised -- multiplying by the square root of the
periods per year is the usual annualisation and it assumes returns are
independent, which is exactly what a trending or mean-reverting series
is not.

The denominator penalises upside and downside alike. A strategy that
occasionally doubles is punished for it, which is what `sortino`
addresses, and a strategy that sells insurance -- small steady gains
and a rare catastrophe -- scores well right up until the catastrophe.
The ratio says nothing about the shape of the distribution beyond its
first two moments.

Errors:
Returns an error for fewer than two returns, a non-finite value, or a
series with no variation.

Rust: `finance::portfolio::sharpe`
    """
    ...

def sortino(returns: list[float], risk_free: float, target: float) -> float:
    """
The Sortino ratio: mean excess return over the downside deviation.

The denominator is the root mean square of the shortfalls below
`target`, counting periods above it as zero rather than dropping them.
That choice matters: dividing by the count of losing periods instead
would make a strategy look better simply for losing less often, and
the two conventions differ by a factor that grows as losses get rarer.

Errors:
Returns an error for fewer than two returns, a non-finite value, or a
series that never falls below the target.

Rust: `finance::portfolio::sortino`
    """
    ...

def max_drawdown(prices: list[float]) -> float:
    """
The maximum drawdown: the largest peak-to-trough fall, as a positive
fraction of the peak.

Computed against the running maximum, so it is a property of the path
and not of the endpoints. Two series with the same start and end can
have wildly different drawdowns, which is the point -- it measures what
an investor would have had to sit through.

Errors:
Returns an error for fewer than two prices, or a non-positive price.

Rust: `finance::portfolio::max_drawdown`
    """
    ...

def calmar(prices: list[float], periods_per_year: float) -> float:
    """
The Calmar ratio: annualised return divided by maximum drawdown.

`periods_per_year` converts the series' own period into a year. The
return used is the *geometric* one -- the constant rate that would have
produced the same total growth -- because that is what an investor
actually earned, unlike the arithmetic mean.

Errors:
Returns an error for fewer than two prices, a non-positive price or
period count, or a series with no drawdown to divide by.

Rust: `finance::portfolio::calmar`
    """
    ...

def information_ratio(portfolio: list[float], benchmark: list[float]) -> float:
    """
The information ratio: mean active return over its tracking error.

Active return is the portfolio's minus the benchmark's, period by
period. It is the Sharpe ratio of a long-short position against the
benchmark, which is why it is the natural measure for a manager judged
relative to an index rather than to cash.

Errors:
Returns an error for mismatched or too-short series, a non-finite
value, or an active series with no variation.

Rust: `finance::portfolio::information_ratio`
    """
    ...

def capm_beta(asset: list[float], market: list[float]) -> tuple[float, float]:
    """
The CAPM regression of an asset on the market, returning
`(alpha, beta)`.

Beta is `cov(asset, market) / var(market)` and alpha is the intercept
that remains. Beta is an estimate of sensitivity and nothing more: it
is a single number summarising a scatter that may not be linear, it is
unstable across sample periods, and a high R-squared is required before
it means very much at all.

Errors:
Returns an error for mismatched or too-short series, a non-finite
value, or a market series with no variation.

Rust: `finance::portfolio::capm_beta`
    """
    ...

def kelly_fraction(p: float, b: float) -> float:
    """
The Kelly fraction for a discrete bet won with probability `p` paying
`b` to one: `p - (1 - p)/b`.

Maximises the expected *logarithm* of wealth, which is the growth rate
achieved almost surely over many repetitions. A negative answer means
the bet has no edge and the optimal stake is nothing.

The fraction assumes the edge is known exactly. Overestimating it
pushes the stake past the growth-optimal point, where growth falls
faster than it rose: staking twice the Kelly fraction earns no more
than the risk-free rate however large the edge, and beyond that it
loses. That is why practitioners bet a fraction of it.

Errors:
Returns an error for a probability outside `[0, 1]` or a non-positive
payout.

Rust: `finance::portfolio::kelly_fraction`
    """
    ...

def kelly_continuous(mu: float, sigma: float, risk_free: float) -> float:
    """
The continuous Kelly fraction `(mu - rf)/sigma^2`.

The same object for a lognormal asset: the leverage maximising the
long-run growth rate. It is also the tangency portfolio's leverage
under one asset, which is not a coincidence -- both maximise the
Sharpe-like quantity `(mu - rf)/sigma` scaled by the risk taken.

Errors:
Returns an error for a non-positive volatility or a non-finite input.

Rust: `finance::portfolio::kelly_continuous`
    """
    ...
