"""
Convolutional and turbo codes, and the channels they run over.  A convolutional code has no block length. The encoder is a shift register: each input bit is combined with the last few, and the output depends on a sliding window rather than on a partition of the message. That makes the code a walk through a *trellis* -- a graph whose vertices are the register states and whose edges are the possible inputs -- and decoding the problem of finding the walk that best matches what arrived. Viterbi's algorithm is dynamic programming on that graph, and it is optimal: it returns the maximum-likelihood sequence, not an approximation to it.  Turbo codes take two such encoders, feed the second an interleaved copy of the message, and decode by having the two halves exchange opinions. What each passes the other is *extrinsic* information -- what it concluded about a bit from everything except that bit's own channel evidence -- and keeping the exchange extrinsic is the whole trick. Feeding back a decoder's full opinion would let it hear its own guess reflected as independent confirmation, and the iteration would converge confidently to nonsense.  The capacity functions at the end say where the limits are. A rate-`1/2` binary code cannot work below about `0.187` decibels of `Eb/N0`, whatever it is; turbo codes reached within a few tenths of that, which is why they ended a thirty-year search.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.monte_carlo import Rng

class ConvolutionalCode:
    """
A rate `1/n` convolutional code, given by its constraint length and
generator polynomials.

The generators are the taps of the shift register, conventionally written
in octal: the NASA standard's `171` and `133` are `0o171` and `0o133`,
seven bits each for a constraint length of seven. Bit `k - 1` of a
generator is the current input and bit zero the oldest bit in memory.

Rust: `codes::convolutional::ConvolutionalCode`
    """
    def __init__(self, k: int, polys: list[int]) -> None: ...
    @staticmethod
    def nasa_standard() -> ConvolutionalCode: ...
    def memory(self) -> int: ...
    def trellis_states(self) -> int: ...
    def outputs(self) -> int: ...
    def step(self, state: int, input: bool) -> tuple[list[bool], int]: ...
    def encode(self, bits: list[bool]) -> list[bool]: ...
    def viterbi_decode(self, recv_hard: list[bool]) -> list[bool]: ...
    def viterbi_soft(self, llr: list[float]) -> list[bool]: ...
    def free_distance_estimate(self) -> int: ...
    def puncture(self, encoded: list[bool], pattern: list[bool]) -> list[bool]: ...
    def depuncture_llr(self, punctured: list[float], pattern: list[bool], full_len: int) -> list[float]: ...
    @property
    def k(self) -> int: ...
    @property
    def polys(self) -> list[int]: ...

class RscCode:
    """
A rate-`1/2` recursive systematic convolutional encoder: the message
passes through unchanged, and one parity stream is generated with
feedback.

Feedback is what makes a turbo code work. Without it, a low-weight input
gives a low-weight output whichever order the bits arrive in, so
interleaving buys nothing; with it, a weight-one input drives the register
forever and only very particular inputs produce light parity. The
interleaver can then almost always break whatever pattern was light for
the first encoder.

Rust: `codes::convolutional::RscCode`
    """
    def __init__(self, k: int, feedback: int, feedforward: int) -> None: ...
    @staticmethod
    def standard() -> RscCode: ...
    def memory(self) -> int: ...
    def trellis_states(self) -> int: ...
    def step(self, state: int, input: bool) -> tuple[bool, int]: ...
    def terminating_input(self, state: int) -> bool: ...
    def encode(self, bits: list[bool]) -> tuple[list[bool], int]: ...
    def encode_terminated(self, bits: list[bool]) -> tuple[list[bool], list[bool]]: ...
    def bcjr_extrinsic(self, ys: list[float], yp: list[float], la: list[float]) -> list[float]: ...
    def ends_at_zero(self, bits: list[bool]) -> bool: ...
    @property
    def k(self) -> int: ...
    @property
    def feedback(self) -> int: ...
    @property
    def feedforward(self) -> int: ...

class TurboCode:
    """
A turbo code: two recursive systematic encoders sharing a message, the
second seeing it through an interleaver.

Rust: `codes::convolutional::TurboCode`
    """
    def __init__(self, rsc: RscCode, interleaver: list[int]) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def encode(self, msg: list[bool]) -> tuple[list[bool], list[bool], list[bool]]: ...
    def decode_bcjr(self, ys: list[float], yp1: list[float], yp2: list[float], iters: int) -> list[bool]: ...
    @property
    def rsc(self) -> RscCode: ...
    @property
    def interleaver(self) -> list[int]: ...

def interleaver_block(n: int, rows: int) -> list[int]:
    """
A block interleaver: write the sequence into a rectangle row by row, read
it out column by column.

Returns the permutation `pi` with `pi[i]` the source index of output `i`.
It spreads any run of `rows` consecutive positions to distance `rows`
apart, which is what turns a burst into scattered single errors that a
random-error code can handle.

Panics:
Panics unless `rows` divides `n` and both are positive.

Rust: `codes::convolutional::interleaver_block`
    """
    ...

def interleaver_random(n: int, rng: Rng) -> list[int]:
    """
A uniformly random interleaver.

Rust: `codes::convolutional::interleaver_random`
    """
    ...

def qpp_interleaver(n: int, f1: int, f2: int) -> list[int]:
    """
A quadratic permutation polynomial interleaver: `pi(i) = f1 i + f2 i^2`
modulo `n`, the family LTE uses.

It is a permutation exactly when `f1` is coprime to `n` and every prime
dividing `n` also divides `f2` -- conditions cheap enough to check, which
is the point: an LTE receiver reconstructs the interleaver from two
integers instead of storing a table of six thousand entries.

Panics:
Panics unless the parameters give a permutation.

Rust: `codes::convolutional::qpp_interleaver`
    """
    ...

def awgn_channel(bits: list[bool], snr_db: float, rng: Rng) -> list[float]:
    """
Transmits bits over an additive white Gaussian noise channel with binary
phase shift keying, returning the received samples.

A zero bit is sent as `+1` and a one as `-1`, so the received value is
`±1` plus a Gaussian of variance `1 / (2 * 10^(snr_db/10))`. That variance
is the one that makes `snr_db` the symbol energy to noise density ratio
`Es/N0` in decibels.

Rust: `codes::convolutional::awgn_channel`
    """
    ...

def awgn_sigma(snr_db: float) -> float:
    """
The noise standard deviation for a given `Es/N0` in decibels, with unit
symbol energy.

Rust: `codes::convolutional::awgn_sigma`
    """
    ...

def llr_from_awgn(samples: list[float], sigma: float) -> list[float]:
    """
The log-likelihood ratios a Gaussian channel implies, positive for a zero
bit.

Rust: `codes::convolutional::llr_from_awgn`
    """
    ...

def bsc_channel(bits: list[bool], p: float, rng: Rng) -> list[bool]:
    """
Transmits bits over a binary symmetric channel that flips each with
probability `p`.

Panics:
Panics unless `p` is in `[0, 1]`.

Rust: `codes::convolutional::bsc_channel`
    """
    ...

def ber_simulation(code: ConvolutionalCode, snr_db_range: list[float], n_bits: int, rng: Rng) -> list[tuple[float, float]]:
    """
Bit error rates against signal to noise ratio, for a convolutional code
decoded softly.

`snr_db_range` is `Eb/N0` in decibels -- energy per *information* bit,
which is the only fair way to compare codes of different rates, since a
stronger code spends more channel symbols on each message bit and must be
charged for them.

Panics:
Panics if `n_bits` is zero.

Rust: `codes::convolutional::ber_simulation`
    """
    ...

def binary_entropy(p: float) -> float:
    """
Binary entropy in bits.

Rust: `codes::convolutional::binary_entropy`
    """
    ...

def capacity_bsc(p: float) -> float:
    """
The capacity of a binary symmetric channel: `1 - H(p)` bits per use.

Panics:
Panics unless `p` is in `[0, 1]`.

Rust: `codes::convolutional::capacity_bsc`
    """
    ...

def capacity_bec(e: float) -> float:
    """
The capacity of a binary erasure channel: `1 - e` bits per use.

The one channel whose capacity needs no argument: a fraction `e` of the
symbols never arrive, and the rest arrive perfectly.

Panics:
Panics unless `e` is in `[0, 1]`.

Rust: `codes::convolutional::capacity_bec`
    """
    ...

def channel_capacity_awgn(snr: float) -> float:
    """
The capacity of a real additive white Gaussian noise channel with the
given signal to noise ratio: `0.5 log2(1 + snr)` bits per use.

`snr` here is the ratio of signal power to noise *variance*. That is not
`Es/N0`: a real channel has variance `N0/2`, so the ratio to pass is
twice `Es/N0`. Comparing this against `channel_capacity_bpsk`, which
takes `Es/N0`, without that factor is the easy way to conclude that
restricting the input alphabet raises capacity.

Panics:
Panics if the ratio is negative.

Rust: `codes::convolutional::channel_capacity_awgn`
    """
    ...

def channel_capacity_bpsk(snr: float) -> float:
    """
The capacity of a Gaussian channel whose input is restricted to `+/-1`.

Restricting the input costs something: at high signal to noise the
unrestricted channel's capacity grows without bound while this saturates
at one bit per use, because one bit is all a binary symbol can carry. The
expectation has no closed form and is integrated numerically.

Panics:
Panics if the ratio is negative.

Rust: `codes::convolutional::channel_capacity_bpsk`
    """
    ...

def shannon_limit_bpsk(rate: float) -> float:
    """
The lowest `Eb/N0`, in decibels, at which a binary code of the given rate
can work.

Found by bisecting `channel_capacity_bpsk` for the point where capacity
equals the rate, then converting from `Es/N0` to `Eb/N0` by dividing out
the rate. At rate one half the answer is about `0.187` decibels; as the
rate falls towards zero it approaches `-1.59`, which is `10 log10(ln 2)`
and is the limit for any code at any rate.

Panics:
Panics unless the rate is in `(0, 1)`.

Rust: `codes::convolutional::shannon_limit_bpsk`
    """
    ...

def shannon_limit_unconstrained(rate: float) -> float:
    """
The same limit for a channel with no restriction on the input alphabet:
`(2^(2R) - 1) / (2R)`, in decibels.

Always at or below `shannon_limit_bpsk`, since removing a restriction
cannot make a channel worse, and equal to it in the limit of low rate.

Panics:
Panics unless the rate is positive.

Rust: `codes::convolutional::shannon_limit_unconstrained`
    """
    ...
