"""
Dimensional analysis: Buckingham's theorem, the named groups, natural units and the Planck scale.  # Buckingham's theorem is a rank computation  A physical relation among `n` quantities built from `r` independent dimensions can be rewritten as a relation among exactly `n - r` dimensionless groups. That is not a heuristic: the dimension vectors form the columns of a matrix, a dimensionless product of powers is a vector in its null space, and the dimension of a null space is the column count minus the rank. Every part of it is linear algebra over the rationals.  Which is why `buckingham_pi` works in `Rational` rather than in floating point. An exponent vector is *exactly* in the null space or it is not, and a group whose dimensions cancel to `1e-16` instead of to zero is not a dimensionless group -- it is a rounding error that will be reported as physics. The returned exponents are exact rationals for the same reason: the Reynolds number's exponents happen to be integers, but the null space basis of a general problem is not integral, and rounding it would silently change the group.  The theorem says how many groups there are, not which ones. Any basis of the null space works, and the conventional groups -- Reynolds, Froude, Mach -- are particular choices made for physical reasons that the algebra knows nothing about. `dimensionless_groups_named` lists those conventions; `buckingham_pi` finds a basis and makes no claim that it is the one anybody would name.  # Natural units are a change of bookkeeping, not of physics  Setting `hbar = c = 1` makes length, time and mass powers of a single unit, conventionally energy: `[L] = [T] = [E]^-1` and `[M] = [E]`. Nothing physical changes -- the dimensionless combinations are the same -- but a quantity's dimension collapses to one integer, its energy power, and `natural_units_convert` returns the magnitude in `eV` to that power. Electromagnetic and thermal dimensions need further conventions to absorb, so a dimension involving amperes, kelvin, moles or candela is refused rather than guessed at.  # Checking a formula is not the same as evaluating it  `dimensional_check_formula` walks a symbolic expression and asks whether it is dimensionally coherent: that every term of every sum agrees, and that nothing dimensioned is handed to a sine or an exponential. Neither question can be answered by running the formula, because both sides of `x + v` are perfectly good floats. It is the check a physicist does by eye before believing an algebra step, done mechanically, and it catches the dropped factor that numerical testing cannot.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.units.quantity import Dim
from numeria.exact.symbolic import Expr

def buckingham_pi(dims: list[Dim]) -> list[list[Fraction]]:
    """
A basis for the dimensionless groups of a set of quantities.

Returns exactly `n - rank` vectors of `n` exact rational exponents.
The product of the quantities raised to those exponents is
dimensionless, exactly.

Any basis of the null space is a valid answer and this one is
whichever the elimination produces; see the module note on why that
is not the same as producing the groups anybody has named.

Errors:

`DimError::Malformed` if given no quantities.

Rust: `units::dimensional::buckingham_pi`
    """
    ...

def is_dimensionless_group(dims: list[Dim], exponents: list[Fraction]) -> bool:
    """
Checks that a vector of exponents really does cancel every dimension.

Exact: the sum of each row is compared against zero, not against a
tolerance.

Errors:

`DimError::Malformed` if the lengths disagree.

Rust: `units::dimensional::is_dimensionless_group`
    """
    ...

def dimensionless_groups_named() -> list[tuple[str, str, str]]:
    """
The dimensionless groups that have names, with their formulas and
what each compares.

The formulas are the conventional ones. Each is *a* member of its
problem's null space rather than the only one -- see the module note.

Rust: `units::dimensional::dimensionless_groups_named`
    """
    ...

def natural_units_power(dim: Dim) -> int:
    """
The power of energy a dimension corresponds to when `hbar = c = 1`.

`[M] = [E]`, `[L] = [T] = [E]^-1`, so the power is
`kg - m - s`.

Errors:

`DimError::Mismatch` if the dimension involves amperes, kelvin,
moles or candela, which need further conventions to absorb and are
refused rather than guessed at.

Rust: `units::dimensional::natural_units_power`
    """
    ...

def natural_units_convert(value: float, dim: Dim) -> float:
    """
Expresses an SI magnitude in electron volts to the power
`natural_units_power` gives.

Errors:

As `natural_units_power`.

Rust: `units::dimensional::natural_units_convert`
    """
    ...

def planck_units() -> list[tuple[str, float, str]]:
    """
The Planck units, as `(name, value, unit)`.

Each is built from `hbar`, `c` and `G` alone, which is the point:
they are the only combination of those three with the dimensions of a
length, a time, a mass and so on, so they are the scale at which
gravity and quantum mechanics are the same size. The defining
relations are checked in the tests against the CODATA values rather
than the numbers being copied in.

Rust: `units::dimensional::planck_units`
    """
    ...

def dimensional_check_formula(expr: Expr, var_dims: list[tuple[str, Dim]]) -> Dim:
    """
The dimension of a symbolic expression, given the dimension of every
variable in it.

This is the check a physicist runs before believing an algebra step,
done mechanically. It is worth having as code because the two rules
it enforces are the ones a hand derivation drops:

* **Every term of a sum has to have the same dimension.** A length
  plus a time is not a longer length, it is a mistake, and it is the
  mistake a dropped factor produces.
* **A transcendental function's argument has to be dimensionless.**
  `sin`, `exp` and `ln` are defined by their power series, and a
  series adds `x` to `x^3` to `x^5`, so `x` can only be a pure
  number. `exp(-t/tau)` is meaningful and `exp(-t)` is not, and the
  difference is the missing timescale.

Neither rule can be checked by evaluating the formula: both sides of
`x + v` are finite floats. They are properties of the expression, and
this walks the expression.

`var_dims` maps each variable name to its dimension; the first
matching entry wins. Numeric literals are dimensionless.

Exponents:

`Pow(b, e)` needs `e` to be a literal number, because the dimension
of `b^e` depends on the *value* of `e` and not on its dimension.
When the base is dimensionless the exponent may be anything
dimensionless -- `2^n` is a pure number whatever `n` is -- but when
the base carries dimensions the exponent must be a literal -- an
`Expr::Rat` or an `Expr::Const` -- and the base's exponents must
all be divisible by the literal's denominator.

A `Const` is read as the dyadic rational it exactly is, which needs
no guessing: `0.5` is one half, so `Pow(x, 0.5)` is a square root
and behaves like one. `0.1` is not one tenth, it is the
power-of-two fraction the float holds, and no dimension is
divisible by that denominator, so `l^0.1` is reported as a root
that does not exist rather than quietly rounded into one that
does.

Errors:

`DimError::Mismatch` when the terms of a sum disagree or a
transcendental is handed something dimensioned;
`DimError::UnknownVar` for a variable missing from `var_dims`;
`DimError::NotAPerfectRoot` for a root that does not come out
exactly; `DimError::Malformed` for an exponent that is not a
literal; `DimError::Overflow` if an exponent leaves `i8`.

Examples:

Rust: `units::dimensional::dimensional_check_formula`
    """
    ...
