"""
Boundary layers: Blasius and Falkner-Skan similarity solutions (shooting), Thwaites and Head integral methods, turbulent wall laws, transition and separation criteria, rotating and oscillating layers, and flat-plate heat transfer.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.math import Vec2

def blasius_solve(eta_max: float, n: int) -> list[tuple[float, float, float, float]]:
    """
Blasius flat-plate similarity solution: rows (η, f, f′, f″) with
f‴ + ½ f f″ = 0, solved by RK4 shooting on f″(0).

Rust: `cfd::boundary_layer::blasius_solve`
    """
    ...

def blasius_profile(y: float, x: float, u_inf: float, nu: float) -> float:
    """
Blasius streamwise velocity u(y) at station x.

Rust: `cfd::boundary_layer::blasius_profile`
    """
    ...

def blasius_thickness(x: float, u_inf: float, nu: float) -> tuple[float, float, float]:
    """
Blasius thicknesses (δ99, δ*, θ) at station x.

Rust: `cfd::boundary_layer::blasius_thickness`
    """
    ...

def blasius_cf(x: float, u_inf: float, nu: float) -> float:
    """
Local Blasius skin friction 0.664/√Re_x.

Rust: `cfd::boundary_layer::blasius_cf`
    """
    ...

def blasius_drag_plate(l: float, width: float, u_inf: float, nu: float, rho: float) -> float:
    """
Total laminar drag of one side of a flat plate.

Rust: `cfd::boundary_layer::blasius_drag_plate`
    """
    ...

def falkner_skan_solve(beta: float, eta_max: float, n: int) -> list[tuple[float, float, float]]:
    """
Falkner-Skan wedge-flow similarity: rows (η, f, f′) for
f‴ + f f″ + β(1 − f′²) = 0.

Rust: `cfd::boundary_layer::falkner_skan_solve`
    """
    ...

def falkner_skan_separation_beta() -> float:
    """
Falkner-Skan separation parameter β = −0.1988.

Rust: `cfd::boundary_layer::falkner_skan_separation_beta`
    """
    ...

def thwaites_method(u_e: Callable[[float], float], x: list[float], nu: float) -> list[tuple[float, float, float, float]]:
    """
Thwaites integral method along stations `x` with edge velocity
`u_e(x)`: rows (θ, λ, H, cf).

Rust: `cfd::boundary_layer::thwaites_method`
    """
    ...

def thwaites_separation_point(u_e: Callable[[float], float], x: list[float], nu: float) -> Optional[float]:
    """
First station where Thwaites' λ drops below −0.09 (separation).

Rust: `cfd::boundary_layer::thwaites_separation_point`
    """
    ...

def pohlhausen_profile(eta: float, lambda_: float) -> float:
    """
Pohlhausen quartic velocity profile u/U at η = y/δ with shape
parameter λ.

Rust: `cfd::boundary_layer::pohlhausen_profile`
    """
    ...

def turbulent_bl_power_law(y: float, delta: float, n: float) -> float:
    """
Turbulent 1/n power-law profile.

Rust: `cfd::boundary_layer::turbulent_bl_power_law`
    """
    ...

def turbulent_cf_prandtl(re_x: float) -> float:
    """
Local turbulent skin friction (Prandtl 1/5-power law) 0.0592 Re⁻⅕.

Rust: `cfd::boundary_layer::turbulent_cf_prandtl`
    """
    ...

def turbulent_cf_schlichting(re_x: float) -> float:
    """
Schlichting's local turbulent skin friction (2 log₁₀Re − 0.65)⁻²·³.

Rust: `cfd::boundary_layer::turbulent_cf_schlichting`
    """
    ...

def turbulent_thickness_1_7(x: float, re_x: float) -> float:
    """
Turbulent boundary-layer thickness δ = 0.37 x / Re_x^{1/5}.

Rust: `cfd::boundary_layer::turbulent_thickness_1_7`
    """
    ...

def law_of_the_wall(y_plus: float, kappa: float, b: float) -> float:
    """
Logarithmic law of the wall u⁺ = ln(y⁺)/κ + B.

Rust: `cfd::boundary_layer::law_of_the_wall`
    """
    ...

def spalding(y_plus: float) -> float:
    """
Spalding's composite wall profile: u⁺(y⁺) by inverting
y⁺ = u⁺ + e^{−κB}(e^{κu⁺} − 1 − κu⁺ − (κu⁺)²/2 − (κu⁺)³/6).

Rust: `cfd::boundary_layer::spalding`
    """
    ...

def van_driest_damping(y_plus: float, a: float) -> float:
    """
Van Driest near-wall damping 1 − e^{−y⁺/A}.

Rust: `cfd::boundary_layer::van_driest_damping`
    """
    ...

def y_plus(y: float, u_tau: float, nu: float) -> float:
    """
Wall coordinate y⁺ = y u_τ/ν.

Rust: `cfd::boundary_layer::y_plus`
    """
    ...

def u_tau(tau_w: float, rho: float) -> float:
    """
Friction velocity √(τ_w/ρ).

Rust: `cfd::boundary_layer::u_tau`
    """
    ...

def first_cell_height(y_plus_target: float, u_inf: float, nu: float, re_l: float, l: float) -> float:
    """
First-cell height for a target y⁺ on a plate of length `l`
(turbulent flat-plate friction estimate).

Rust: `cfd::boundary_layer::first_cell_height`
    """
    ...

def transition_re_x_estimate(turbulence_intensity: float) -> float:
    """
Mayle-style transition estimate: Re_θt ≈ 400 Ti^{−5/8} (Ti in
percent), converted to Re_x with the Blasius relation θ =
0.664 x/√Re_x.

Rust: `cfd::boundary_layer::transition_re_x_estimate`
    """
    ...

def michel_transition_criterion(re_theta: float, re_x: float) -> bool:
    """
Michel's transition criterion: Re_θ > 1.174 (1 + 22400/Re_x) Re_x^0.46.

Rust: `cfd::boundary_layer::michel_transition_criterion`
    """
    ...

def head_entrainment_method(u_e: Callable[[float], float], x: list[float], nu: float, theta0: float, h0: float) -> list[tuple[float, float, float]]:
    """
Head's entrainment integral method for turbulent boundary layers:
rows (θ, H, cf) marched along `x`.

Rust: `cfd::boundary_layer::head_entrainment_method`
    """
    ...

def stratford_separation_criterion(cp: float, x: float, dcp_dx: float, re_x: float) -> bool:
    """
Stratford's turbulent separation criterion:
Cp √(x dCp/dx) ≥ 0.39 (10⁻⁶ Re_x)^{0.1}.

Rust: `cfd::boundary_layer::stratford_separation_criterion`
    """
    ...

def ekman_spiral(z: float, u_g: float, f: float, nu: float) -> Vec2:
    """
Ekman spiral velocity (u, v) at height z for geostrophic wind `u_g`.

Rust: `cfd::boundary_layer::ekman_spiral`
    """
    ...

def ekman_depth(nu: float, f: float) -> float:
    """
Ekman layer depth π√(2ν/f).

Rust: `cfd::boundary_layer::ekman_depth`
    """
    ...

def stokes_second_problem(y: float, t: float, u0: float, omega: float, nu: float) -> float:
    """
Stokes' second problem (oscillating plate): u(y, t).

Rust: `cfd::boundary_layer::stokes_second_problem`
    """
    ...

def stokes_first_problem(y: float, t: float, u0: float, nu: float) -> float:
    """
Stokes' first problem (impulsively started plate): u = u0 erfc(η).

Rust: `cfd::boundary_layer::stokes_first_problem`
    """
    ...

def couette_flow(y: float, h: float, u_wall: float, dp_dx: float, mu: float) -> float:
    """
Plane Couette-Poiseuille flow u(y) between plates 0 and h.

Rust: `cfd::boundary_layer::couette_flow`
    """
    ...

def flat_plate_heat_transfer_laminar(re_x: float, pr: float) -> float:
    """
Laminar flat-plate local Nusselt number 0.332 Re_x^½ Pr^⅓.

Rust: `cfd::boundary_layer::flat_plate_heat_transfer_laminar`
    """
    ...

def thermal_bl_ratio(pr: float) -> float:
    """
Thermal to velocity boundary-layer thickness ratio ≈ Pr^{−1/3}.

Rust: `cfd::boundary_layer::thermal_bl_ratio`
    """
    ...
