"""
Porous-media flow: Darcy's law and extensions, unsaturated flow (Richards equation with Van Genuchten retention), well hydraulics, solute transport, and two-phase relations (Leverett, Corey, Buckley-Leverett).
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.cfd.grid import CellField2

class VanGenuchten:
    """
Van Genuchten soil retention parameters (`alpha` in 1/m, `k_s` in m/s).

Rust: `cfd::porous::VanGenuchten`
    """
    def __init__(self, theta_r: float, theta_s: float, alpha: float, n: float, k_s: float) -> None: ...
    def theta(self, h: float) -> float: ...
    def effective_saturation(self, h: float) -> float: ...
    def k(self, h: float) -> float: ...
    def capacity(self, h: float) -> float: ...
    def head_from_theta(self, theta: float) -> float: ...
    @staticmethod
    def sand() -> VanGenuchten: ...
    @staticmethod
    def loam() -> VanGenuchten: ...
    @staticmethod
    def clay() -> VanGenuchten: ...
    @property
    def theta_r(self) -> float: ...
    @property
    def theta_s(self) -> float: ...
    @property
    def alpha(self) -> float: ...
    @property
    def n(self) -> float: ...
    @property
    def k_s(self) -> float: ...

def darcy_velocity(k: float, mu: float, grad_p: float) -> float:
    """
Darcy velocity (specific discharge) q = -(k/mu) grad p; returns the
magnitude for a pressure gradient `grad_p` (Pa/m).

Rust: `cfd::porous::darcy_velocity`
    """
    ...

def darcy_flow_rate(k: float, a: float, mu: float, dp: float, l: float) -> float:
    """
Volumetric flow rate through area `a` over length `l` under pressure
difference `dp`: Q = k A dp / (mu L).

Rust: `cfd::porous::darcy_flow_rate`
    """
    ...

def permeability_kozeny_carman(porosity: float, d_particle: float) -> float:
    """
Kozeny-Carman permeability of a packed bed of spheres of diameter
`d_particle` (Ergun-consistent constant 150):
k = phi^3 d^2 / (150 (1-phi)^2).

Rust: `cfd::porous::permeability_kozeny_carman`
    """
    ...

def carman_kozeny_fibers(porosity: float, d_fiber: float) -> float:
    """
Approximate Kozeny-type permeability of a random fiber mat with fiber
diameter `d_fiber` (Kozeny constant ~ 5 with the fiber specific surface
4/d): k = phi^3 d^2 / (80 (1-phi)^2).

Rust: `cfd::porous::carman_kozeny_fibers`
    """
    ...

def ergun_pressure_drop(u: float, d: float, porosity: float, mu: float, rho: float, l: float) -> float:
    """
Ergun pressure drop over bed length `l` for superficial velocity `u`:
dP/L = 150 mu u (1-phi)^2/(phi^3 d^2) + 1.75 rho u^2 (1-phi)/(phi^3 d).

Rust: `cfd::porous::ergun_pressure_drop`
    """
    ...

def forchheimer(k: float, beta: float, mu: float, rho: float, u: float) -> float:
    """
Forchheimer pressure gradient magnitude: dp/dx = mu u / k + beta rho u^2.

Rust: `cfd::porous::forchheimer`
    """
    ...

def brinkman_velocity_profile(y: float, h: float, k: float, mu: float, dp_dx: float) -> float:
    """
Brinkman flow in a porous channel of height `h` driven by `dp_dx`:
u(y) = -(k/mu) dp/dx [1 - cosh((y - h/2)/sqrt(k)) / cosh(h/(2 sqrt(k)))].

Rust: `cfd::porous::brinkman_velocity_profile`
    """
    ...

def hydraulic_conductivity(k: float, rho: float, g: float, mu: float) -> float:
    """
Hydraulic conductivity K = k rho g / mu (m/s).

Rust: `cfd::porous::hydraulic_conductivity`
    """
    ...

def brooks_corey(h: float, h_b: float, lambda_: float) -> float:
    """
Brooks-Corey effective saturation for entry pressure head `h_b` (m) and
pore-size index `lambda`.

Rust: `cfd::porous::brooks_corey`
    """
    ...

def richards_equation_1d(theta0: list[float], soil: VanGenuchten | Sequence[float], dz: float, dt: float, steps: int, bc_top: float, bc_bottom: float) -> list[list[float]]:
    """
Explicit finite-volume Richards equation in 1D (z positive downward),
theta-form so mass is conserved exactly. Boundary conditions are water
fluxes (m/s, positive downward): `bc_top` enters the first cell,
`bc_bottom` leaves the last. Returns the water-content profile after each
step (`steps + 1` rows including the initial state).

Rust: `cfd::porous::richards_equation_1d`
    """
    ...

def theis_drawdown(q: float, t_coeff: float, s: float, r: float, t: float) -> float:
    """
Theis transient drawdown at radius `r` and time `t` for pumping rate `q`,
transmissivity `t_coeff` and storativity `s`:
s_d = Q/(4 pi T) W(u), u = r^2 S/(4 T t), W = E1.

Rust: `cfd::porous::theis_drawdown`
    """
    ...

def thiem_steady(q: float, t_coeff: float, r1: float, r2: float, h1: float) -> float:
    """
Thiem steady-state head at radius `r2` given head `h1` at `r1`:
h2 = h1 + Q/(2 pi T) ln(r2/r1).

Rust: `cfd::porous::thiem_steady`
    """
    ...

def dupuit_unconfined(h1: float, h2: float, l: float, x: float) -> float:
    """
Dupuit unconfined flow between heads `h1` and `h2` over length `l`:
the water-table height at distance `x`.

Rust: `cfd::porous::dupuit_unconfined`
    """
    ...

def groundwater_flow_2d(k_field: CellField2, bc: list[tuple[int, int, float]], recharge: CellField2) -> CellField2:
    """
Steady 2D groundwater flow: solve div(K grad h) = -recharge with
Dirichlet head fixed at the listed `(i, j, head)` cells and no-flow
elsewhere on the boundary. Gauss-Seidel with harmonic-mean face
conductivities.

Rust: `cfd::porous::groundwater_flow_2d`
    """
    ...

def peclet_porous(u: float, l: float, d: float) -> float:
    """
Peclet number for porous transport: Pe = u l / D.

Rust: `cfd::porous::peclet_porous`
    """
    ...

def dispersion_coefficient(alpha_l: float, u: float, d_m: float) -> float:
    """
Hydrodynamic dispersion coefficient D = alpha_L u + D_m.

Rust: `cfd::porous::dispersion_coefficient`
    """
    ...

def advection_dispersion_1d(c: list[float], u: float, d: float, dx: float, dt: float, retardation: float, decay: float) -> list[float]:
    """
One explicit step of the 1D advection-dispersion-reaction equation with
retardation factor R and first-order decay:
R dc/dt + u dc/dx = D d2c/dx2 - R lambda c (upwind advection).

Rust: `cfd::porous::advection_dispersion_1d`
    """
    ...

def ogata_banks(x: float, t: float, u: float, d: float) -> float:
    """
Ogata-Banks solution for continuous injection at x = 0 into an initially
clean semi-infinite column: c/c0 at (x, t).

Rust: `cfd::porous::ogata_banks`
    """
    ...

def capillary_pressure_leverett(sw: float, porosity: float, k: float, sigma: float, theta: float) -> float:
    """
Leverett J-function scaling of capillary pressure:
Pc = sigma cos(theta) sqrt(phi/k) J(Sw), with J = 0.5 Sw^{-1/2}.

Rust: `cfd::porous::capillary_pressure_leverett`
    """
    ...

def relative_permeability_corey(sw: float, sw_r: float, so_r: float, n: float) -> tuple[float, float]:
    """
Corey relative permeabilities `(k_rw, k_ro)` with residual saturations
and exponent `n`.

Rust: `cfd::porous::relative_permeability_corey`
    """
    ...

def buckley_leverett(x: float, t: float, u_total: float, porosity: float, mu_w: float, mu_o: float, sw_r: float, so_r: float) -> float:
    """
Buckley-Leverett water saturation at position `x` and time `t` for total
(Darcy) velocity `u_total` injected into a column at connate water
saturation, using quadratic Corey curves. Returns Sw(x, t) including the
Welge shock front.

Rust: `cfd::porous::buckley_leverett`
    """
    ...

def bioclogging_porosity_change(phi0: float, biomass: float, rho_biofilm: float) -> float:
    """
Porosity reduction by biofilm growth: phi = phi0 - biomass/rho_biofilm.

Rust: `cfd::porous::bioclogging_porosity_change`
    """
    ...

def effective_thermal_conductivity_porous(k_s: float, k_f: float, porosity: float) -> float:
    """
Effective thermal conductivity of a saturated porous medium (geometric
mean mixing): k_eff = k_s^(1-phi) k_f^phi.

Rust: `cfd::porous::effective_thermal_conductivity_porous`
    """
    ...

def gravity_number(k: float, rho: float, mu: float, u: float) -> float:
    """
Gravity number: ratio of gravity to viscous forces in porous flow
(used in the tests for scaling sanity).

Rust: `cfd::porous::gravity_number`
    """
    ...
