"""
Shallow water equations: well-balanced HLL finite volumes with hydrostatic reconstruction and wet/dry handling (1D and 2D), the Stoker dam-break solution, water-wave dispersion relations, ocean spectra, and Gerstner waves.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.monte_carlo import Rng
from numeria.sim.fluid_sim import ShallowWater1D
from numeria.math import Vec2
from numeria.math import Vec3

class ShallowWater2D:
    """
2D shallow water solver on a square grid: HLL fluxes with Audusse
hydrostatic reconstruction (well-balanced over bathymetry), Manning
friction, Coriolis, and wet/dry tolerance.

Rust: `cfd::shallow_water::ShallowWater2D`
    """
    def __init__(self, nx: int, ny: int, dx: float, g: float) -> None: ...
    def set_bathymetry(self, f: Callable[[float, float], float]) -> None: ...
    def set_dam_break(self, x_split: float, h_l: float, h_r: float) -> None: ...
    def set_gaussian_bump(self, cx: float, cy: float, amp: float, sigma: float, base_depth: float) -> None: ...
    def add_source(self, i: int, j: int, rate: float) -> None: ...
    def step(self, cfl: float) -> float: ...
    def run_until(self, t: float) -> None: ...
    def wet_cells(self) -> int: ...
    def total_volume(self) -> float: ...
    def total_energy(self) -> float: ...
    def froude_field(self) -> list[float]: ...
    def max_depth(self) -> float: ...
    @property
    def nx(self) -> int: ...
    @property
    def ny(self) -> int: ...
    @property
    def dx(self) -> float: ...
    @property
    def h(self) -> list[float]: ...
    @property
    def hu(self) -> list[float]: ...
    @property
    def hv(self) -> list[float]: ...
    @property
    def bathymetry(self) -> list[float]: ...
    @property
    def g(self) -> float: ...
    @property
    def manning_n(self) -> float: ...
    @property
    def coriolis(self) -> float: ...
    @property
    def dry_tol(self) -> float: ...
    @property
    def time(self) -> float: ...

def swe_1d_exact_dam_break(x: float, t: float, h_l: float, h_r: float, g: float) -> tuple[float, float]:
    """
Stoker's exact wet-bed dam-break solution: (h, u) at position x
(dam at x = 0) and time t.

Rust: `cfd::shallow_water::swe_1d_exact_dam_break`
    """
    ...

def swe_1d_step_hll(h: MutableSequence[float], hu: MutableSequence[float], b: list[float], dx: float, g: float, dt: float, dry: float, reflective: bool) -> None:
    """
1D well-balanced SWE step on columns with bathymetry (helper used by
the tsunami run-up model and `ShallowWater1D::step_hll`).

Rust: `cfd::shallow_water::swe_1d_step_hll`
    """
    ...

def tsunami_runup_1d(slope: float, a: float, sigma: float, x0: float, n: int, domain: float, t_end: float, n_samples: int) -> list[float]:
    """
Tsunami run-up on a plane beach of slope `slope`: an offshore
Gaussian wave of amplitude `a` (width `sigma`, centered at world
x = x0) propagates onto the beach. Returns the shoreline position
sampled at each of `n_samples` uniform times up to `t_end`.

Rust: `cfd::shallow_water::tsunami_runup_1d`
    """
    ...

def wave_speed_shallow(h: float, g: float) -> float:
    """
Shallow-water wave speed √(gh).

Rust: `cfd::shallow_water::wave_speed_shallow`
    """
    ...

def dispersion_shallow(k: float, h: float, g: float) -> float:
    """
Shallow-water dispersion ω = k√(gh).

Rust: `cfd::shallow_water::dispersion_shallow`
    """
    ...

def dispersion_deep(k: float, g: float) -> float:
    """
Deep-water dispersion ω = √(gk).

Rust: `cfd::shallow_water::dispersion_deep`
    """
    ...

def dispersion_full(k: float, h: float, g: float) -> float:
    """
Full linear dispersion ω = √(gk tanh(kh)).

Rust: `cfd::shallow_water::dispersion_full`
    """
    ...

def stokes_drift(a: float, k: float, h: float, g: float) -> float:
    """
Stokes drift at the surface: U = a²ωk cosh(2kh)/(2 sinh²(kh)).

Rust: `cfd::shallow_water::stokes_drift`
    """
    ...

def wave_breaking_criterion(h_over_lambda: float) -> bool:
    """
Miche/steepness breaking criterion: waves break when H/λ exceeds
1/7.

Rust: `cfd::shallow_water::wave_breaking_criterion`
    """
    ...

def jonswap_spectrum(f: float, hs: float, tp: float, gamma: float) -> float:
    """
JONSWAP spectrum S(f) (m²/Hz) for significant wave height `hs`, peak
period `tp`, and peak-enhancement `gamma` (≈3.3), normalized so that
∫S df = hs²/16.

Rust: `cfd::shallow_water::jonswap_spectrum`
    """
    ...

def pierson_moskowitz(f: float, u10: float) -> float:
    """
Pierson-Moskowitz spectrum for wind speed `u10` (m/s) at 10 m.

Rust: `cfd::shallow_water::pierson_moskowitz`
    """
    ...

def wave_field_from_spectrum(spectrum: Callable[[float], float], n: int, fs: float, rng: Rng) -> list[float]:
    """
Synthesize a sea-surface elevation time series from a one-sided
spectrum (random phases): `n` samples at rate `fs`.

Rust: `cfd::shallow_water::wave_field_from_spectrum`
    """
    ...

def gerstner_wave(p: Vec2 | Sequence[float], t: float, waves: list[tuple[float, float, float, Vec2 | Sequence[float]]]) -> Vec3:
    """
Gerstner (trochoidal) wave displacement of the surface point whose
rest position is `p`, summing waves given as (amplitude, wavelength,
speed, direction).

Rust: `cfd::shallow_water::gerstner_wave`
    """
    ...

def kelvin_wake_angle() -> float:
    """
Kelvin ship-wake half angle arcsin(1/3) ≈ 19.47°.

Rust: `cfd::shallow_water::kelvin_wake_angle`
    """
    ...
