"""
Digital signal processing: window functions, FIR/IIR filter design, resampling, and phase utilities.  The window generators and first-order RC filters that used to live in `signal_processing` moved here; the old paths re-export them.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from . import fir, iir, phase, resample, windows
from numeria.dsp.iir import Biquad as Biquad
from numeria.dsp.fir import FirState as FirState
from numeria.dsp.iir import IirKind as IirKind
from numeria.dsp.iir import Sos as Sos
from numeria.dsp.iir import Svf as Svf
from numeria.dsp.windows import WindowKind as WindowKind
from numeria.dsp.windows import WindowMetrics as WindowMetrics
from numeria.dsp.iir import a_weighting_filter as a_weighting_filter
from numeria.dsp.iir import bessel as bessel
from numeria.dsp.iir import bilinear_transform as bilinear_transform
from numeria.dsp.windows import blackman_window as blackman_window
from numeria.dsp.iir import butterworth as butterworth
from numeria.dsp.iir import butterworth_order as butterworth_order
from numeria.dsp.iir import c_weighting_filter as c_weighting_filter
from numeria.dsp.iir import chebyshev1 as chebyshev1
from numeria.dsp.iir import chebyshev2 as chebyshev2
from numeria.dsp.resample import cic_decimate as cic_decimate
from numeria.dsp.iir import dc_blocker as dc_blocker
from numeria.dsp.resample import decimate as decimate
from numeria.dsp.iir import elliptic as elliptic
from numeria.dsp.iir import filtfilt as filtfilt
from numeria.dsp.fir import filtfilt_fir as filtfilt_fir
from numeria.dsp.fir import fir_apply as fir_apply
from numeria.dsp.fir import fir_apply_fft as fir_apply_fft
from numeria.dsp.fir import fir_bandpass as fir_bandpass
from numeria.dsp.fir import fir_bandstop as fir_bandstop
from numeria.dsp.fir import fir_differentiator as fir_differentiator
from numeria.dsp.fir import fir_freq_response as fir_freq_response
from numeria.dsp.fir import fir_gaussian as fir_gaussian
from numeria.dsp.fir import fir_group_delay as fir_group_delay
from numeria.dsp.fir import fir_highpass as fir_highpass
from numeria.dsp.fir import fir_hilbert as fir_hilbert
from numeria.dsp.fir import fir_kaiser_design as fir_kaiser_design
from numeria.dsp.fir import fir_least_squares as fir_least_squares
from numeria.dsp.fir import fir_lowpass as fir_lowpass
from numeria.dsp.fir import fir_parks_mcclellan as fir_parks_mcclellan
from numeria.dsp.fir import fir_raised_cosine as fir_raised_cosine
from numeria.dsp.fir import fir_root_raised_cosine as fir_root_raised_cosine
from numeria.dsp.fir import fir_savitzky_golay as fir_savitzky_golay
from numeria.dsp.iir import first_order_highpass as first_order_highpass
from numeria.dsp.iir import first_order_lowpass as first_order_lowpass
from numeria.dsp.iir import group_delay as group_delay
from numeria.dsp.phase import group_delay_from_phase as group_delay_from_phase
from numeria.dsp.resample import half_band_filter as half_band_filter
from numeria.dsp.windows import hamming_window as hamming_window
from numeria.dsp.windows import hann_window as hann_window
from numeria.dsp.iir import iir_apply as iir_apply
from numeria.dsp.iir import impulse_response as impulse_response
from numeria.dsp.windows import kaiser_beta_for_attenuation as kaiser_beta_for_attenuation
from numeria.dsp.iir import one_pole_lowpass as one_pole_lowpass
from numeria.dsp.phase import phase_difference as phase_difference
from numeria.dsp.phase import phase_locked_loop as phase_locked_loop
from numeria.dsp.phase import phase_vs_reference as phase_vs_reference
from numeria.dsp.iir import rbj_q_from_bandwidth as rbj_q_from_bandwidth
from numeria.dsp.windows import rectangular_window as rectangular_window
from numeria.dsp.resample import resample_cubic as resample_cubic
from numeria.dsp.resample import resample_linear as resample_linear
from numeria.dsp.resample import resample_rational as resample_rational
from numeria.dsp.resample import resample_sinc as resample_sinc
from numeria.dsp.resample import resample_to_rate as resample_to_rate
from numeria.dsp.resample import sinc_interpolate as sinc_interpolate
from numeria.dsp.iir import state_variable_filter as state_variable_filter
from numeria.dsp.iir import step_response as step_response
from numeria.dsp.iir import tf_to_zpk as tf_to_zpk
from numeria.dsp.phase import unwrap_phase as unwrap_phase
from numeria.dsp.phase import unwrap_phase_2d as unwrap_phase_2d
from numeria.dsp.resample import upsample as upsample
from numeria.dsp.windows import window as window
from numeria.dsp.windows import window_metrics as window_metrics
from numeria.dsp.phase import wrap_phase as wrap_phase
from numeria.dsp.phase import zero_crossing_times as zero_crossing_times
from numeria.dsp.iir import zpk_to_sos as zpk_to_sos


