"""
Sample-rate conversion: integer up/down sampling, polyphase rational resampling, windowed-sinc/linear/cubic interpolation, CIC decimation, and half-band filters.  Anti-aliasing and interpolation kernels are symmetric windowed-sinc filters applied centered ("same" alignment), so resampled signals keep zero net delay.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def upsample(x: list[float], factor: int) -> list[float]:
    """
Integer upsampling: zero-stuff by `factor`, then interpolate with a
Kaiser-windowed sinc low-pass at the original Nyquist. Output length
is `x.len() * factor`.

Panics:
Panics if `factor == 0`.

Rust: `dsp::resample::upsample`
    """
    ...

def decimate(x: list[float], factor: int) -> list[float]:
    """
Integer decimation: anti-alias low-pass at the new Nyquist, then
keep every `factor`-th sample. Output length ⌈n/factor⌉.

Panics:
Panics if `factor == 0`.

Rust: `dsp::resample::decimate`
    """
    ...

def resample_rational(x: list[float], up: int, down: int) -> list[float]:
    """
Rational resampling by up/down with a single polyphase Kaiser-sinc
kernel. Output length ⌈n·up/down⌉.

Panics:
Panics if `up == 0` or `down == 0`.

Rust: `dsp::resample::resample_rational`
    """
    ...

def resample_to_rate(x: list[float], fs_in: float, fs_out: float) -> list[float]:
    """
Resample from `fs_in` to `fs_out`, approximating the ratio with a
rational up/down (denominator ≤ 1000) and delegating to
`resample_rational`.

Panics:
Panics unless both rates are positive.

Rust: `dsp::resample::resample_to_rate`
    """
    ...

def sinc_interpolate(x: list[float], t: float, half_width: int) -> float:
    """
Windowed-sinc (Hann) interpolation of the sample stream at fractional
index t (samples), using `half_width` taps on each side.

Rust: `dsp::resample::sinc_interpolate`
    """
    ...

def resample_sinc(x: list[float], ratio: float, half_width: int) -> list[float]:
    """
Arbitrary-ratio resampling by windowed-sinc interpolation; output
length ⌈n·ratio⌉.

Panics:
Panics if `ratio <= 0`.

Rust: `dsp::resample::resample_sinc`
    """
    ...

def resample_linear(x: list[float], ratio: float) -> list[float]:
    """
Linear-interpolation resampling (cheap, −12 dB/oct images).

Panics:
Panics if `ratio <= 0`.

Rust: `dsp::resample::resample_linear`
    """
    ...

def resample_cubic(x: list[float], ratio: float) -> list[float]:
    """
Catmull-Rom cubic resampling.

Panics:
Panics if `ratio <= 0`.

Rust: `dsp::resample::resample_cubic`
    """
    ...

def cic_decimate(x: list[float], factor: int, stages: int) -> list[float]:
    """
Cascaded integrator-comb decimation: `stages` integrators, decimate
by `factor`, `stages` combs; output scaled by factor^stages so DC
gain is one.

Panics:
Panics if `factor == 0` or `stages == 0`.

Rust: `dsp::resample::cic_decimate`
    """
    ...

def half_band_filter(n_taps: int) -> list[float]:
    """
Half-band FIR: odd length, every second tap zero (except the 0.5
center), cutoff 0.25 — the workhorse for factor-2 stages.

Panics:
Panics unless `n_taps` is odd and ≥ 7.

Rust: `dsp::resample::half_band_filter`
    """
    ...
