"""
The arithmetic underneath public-key cryptography, for study rather than for use.  **None of this is safe to deploy.** Every routine here branches and indexes on secret values, so the time it takes and the memory it touches leak what it is working on; a modular exponentiation that skips a squaring when a bit is zero tells anyone timing it how many bits are set. Real implementations are written to take the same time and the same path whatever the key, use blinding to break the correlation between input and timing, and are audited for the dozen further side channels that remain. Nothing here does any of that, and the key sizes the tests use are small enough to factor over lunch.  What it is for is seeing why the constructions work. RSA rests on the fact that exponentiating by `e` and then by `d` returns you to where you started whenever `ed = 1` modulo the group order -- so anyone who can compute the group order can find `d`, and the security assumption is exactly that factoring `n` is hard. Diffie-Hellman and elliptic curve Diffie-Hellman rest on the same shape in a different group. Shamir's scheme rests on a polynomial of degree `k - 1` being determined by `k` points and by no fewer. Each of those is a theorem, and the tests here check the theorem rather than the ciphertext.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.monte_carlo import Rng

class EcCurve:
    """
A short Weierstrass curve `y^2 = x^3 + a x + b` over the prime field
`F_p`.

The points form a group under the chord-and-tangent construction: three
points on a line sum to the identity, so adding two points means drawing
the line through them, finding the third intersection, and reflecting it.
That the construction is associative is the one non-obvious fact, and it
is what makes the whole subject possible.

Rust: `codes::crypto_math::EcCurve`
    """
    def __init__(self, a: int, b: int, p: int) -> None: ...
    def is_on_curve(self, pt: EcPoint) -> bool: ...
    def negate(self, pt: EcPoint) -> EcPoint: ...
    def add(self, p1: EcPoint, p2: EcPoint) -> EcPoint: ...
    def double(self, pt: EcPoint) -> EcPoint: ...
    def scalar_mul(self, k: int, pt: EcPoint) -> EcPoint: ...
    def all_points(self) -> list[EcPoint]: ...
    def order_naive_small(self) -> int: ...
    def point_order_small(self, pt: EcPoint) -> int: ...
    def random_point(self, rng: Rng) -> EcPoint: ...
    @staticmethod
    def secp256k1() -> EcCurve: ...
    @staticmethod
    def secp256k1_generator() -> tuple[EcPoint, int]: ...
    @staticmethod
    def p256() -> EcCurve: ...
    @staticmethod
    def p256_generator() -> tuple[EcPoint, int]: ...
    @property
    def a(self) -> int: ...
    @property
    def b(self) -> int: ...
    @property
    def p(self) -> int: ...

class EcPoint:
    """
A point on a short Weierstrass curve, or the point at infinity.

Rust: `codes::crypto_math::EcPoint`
    """
    ...

def rsa_keygen(bits: int, rng: Rng) -> tuple[int, int, int]:
    """
Generates an RSA modulus and exponent pair: `(n, e, d)`.

Two primes of about `bits / 2` each are drawn, `n` is their product, and
`d` inverts `e` modulo the Carmichael function of `n` -- the exponent of
the multiplicative group, which is the least value that works and so gives
the smallest `d`. The public exponent is 65537, whose binary form has two
set bits and therefore encrypts in seventeen squarings.

Panics:
Panics unless `bits` is between 16 and 2048. Anything in that range is far
too small to protect anything.

Rust: `codes::crypto_math::rsa_keygen`
    """
    ...

def rsa_keygen_with_primes(bits: int, rng: Rng) -> tuple[int, int, int, int, int]:
    """
Generates a key and keeps the primes, which the Chinese remainder form of
decryption needs.

Panics:
Panics unless `bits` is between 16 and 2048.

Rust: `codes::crypto_math::rsa_keygen_with_primes`
    """
    ...

def rsa_encrypt(m: int, e: int, n: int) -> int:
    """
Textbook RSA encryption: `m^e` modulo `n`.

Deterministic, and therefore not a secure encryption scheme on its own --
the same message always gives the same ciphertext, so an attacker who can
guess the plaintext can confirm the guess. Real use pads the message with
randomness first.

Rust: `codes::crypto_math::rsa_encrypt`
    """
    ...

def rsa_decrypt(c: int, d: int, n: int) -> int:
    """
Textbook RSA decryption: `c^d` modulo `n`.

Rust: `codes::crypto_math::rsa_decrypt`
    """
    ...

def rsa_crt_decrypt(c: int, d: int, p: int, q: int) -> int:
    """
Decryption through the Chinese remainder theorem, given the two primes.

Working modulo `p` and `q` separately and recombining costs about a
quarter of the work, since modular exponentiation is cubic in the operand
size and the operands are half as long. Every real implementation does
this, which is also why a fault during one of the two halves famously
reveals the factorisation.

Panics:
Panics if `p` and `q` are not coprime, so that the recombination has no
inverse.

Rust: `codes::crypto_math::rsa_crt_decrypt`
    """
    ...

def diffie_hellman_demo(p: int, g: int, rng: Rng) -> tuple[tuple[int, int], tuple[int, int], int]:
    """
A Diffie-Hellman exchange in full: both parties' key pairs and the shared
secret they arrive at.

Returns `((a, A), (b, B), s)` where `A = g^a`, `B = g^b` and
`s = B^a = A^b`, all modulo `p`. The exchange works because
exponentiation commutes; it is secure only if recovering `a` from `g^a` is
hard, which needs `p` to be a large safe prime and `g` to generate a large
subgroup. Neither is checked here.

Panics:
Panics unless `p` is at least three.

Rust: `codes::crypto_math::diffie_hellman_demo`
    """
    ...

def ecdh_demo(curve: EcCurve, g: EcPoint, order: int, rng: Rng) -> tuple[tuple[int, EcPoint], tuple[int, EcPoint], EcPoint]:
    """
An elliptic curve Diffie-Hellman exchange in full.

Returns `((a, aG), (b, bG), s)`. The same construction as the
multiplicative version, in a group where the best known attack is
square-root time rather than sub-exponential -- which is why a 256-bit
curve stands against a 3072-bit modulus.

Panics:
Panics if the base point is not on the curve.

Rust: `codes::crypto_math::ecdh_demo`
    """
    ...

def ec_count_points_small(curve: EcCurve) -> int:
    """
The number of points on a small curve, including infinity.

Panics:
Panics if the field has more than a million elements.

Rust: `codes::crypto_math::ec_count_points_small`
    """
    ...

def hasse_bound_check(count: int, p: int) -> bool:
    """
Whether a point count satisfies Hasse's theorem.

The count lies within `2 sqrt(p)` of `p + 1`. That is a remarkably tight
bound -- the group is always about as large as the field, never a constant
factor away -- and it is what makes a curve's security predictable from
its field size alone.

Rust: `codes::crypto_math::hasse_bound_check`
    """
    ...

def shamir_split(secret: int, k: int, n: int, prime: int, rng: Rng) -> list[tuple[int, int]]:
    """
Splits a secret into `n` shares of which any `k` suffice.

The secret is the constant term of a random polynomial of degree `k - 1`
over `F_prime`, and a share is that polynomial's value at a non-zero
point. Any `k` points determine the polynomial by interpolation, and any
`k - 1` leave the constant term uniformly distributed -- so fewer than `k`
shares give not merely a hard problem but no information at all. That is
what makes the scheme *perfect*, and it is rare.

Panics:
Panics unless `1 <= k <= n`, `n` is below the prime, and the secret is a
non-negative residue below it.

Rust: `codes::crypto_math::shamir_split`
    """
    ...

def shamir_reconstruct(shares: list[tuple[int, int]], prime: int) -> int:
    """
Recovers the secret from any `k` shares by Lagrange interpolation at zero.

Panics:
Panics on an empty share list, on a repeated abscissa, or if the modulus
is not prime enough for the required inverses to exist.

Rust: `codes::crypto_math::shamir_reconstruct`
    """
    ...

def one_time_pad(data: list[int], key: list[int]) -> list[int]:
    """
Exclusive-or of the data with a repeating key.

With a key as long as the message, drawn uniformly and never reused, this
is the one cipher with a proof of perfect secrecy: the ciphertext is
independent of the plaintext, so an adversary with unlimited computation
learns nothing. With a short key repeated, it is a Vigenere cipher and
`vigenere_break` undoes it. The gap between those two is entirely the
key.

Panics:
Panics on an empty key.

Rust: `codes::crypto_math::one_time_pad`
    """
    ...

def lfsr(taps: int, state: int, n: int) -> list[bool]:
    """
A Fibonacci linear feedback shift register: `n` output bits from a state
and a tap mask.

The new bit is the parity of the tapped positions, and the register shifts
right. The output is a linear recurrence over `GF(2)`, which is what makes
it fast, and also what makes it hopeless as a cipher on its own:
`berlekamp_massey_attack` recovers the whole register from twice its
length in output.

Tap bit zero, or the step map is not reversible and the register cannot
reach every state -- see `lfsr_period`.

Panics:
Panics on a zero tap mask.

Rust: `codes::crypto_math::lfsr`
    """
    ...

def lfsr_period(taps: int, width: int) -> int:
    """
The period of a shift register of the given width, by running it until it
repeats.

A width-`w` register has at most `2^w - 1` states before it must repeat,
and reaches that only for a *primitive* tap polynomial. The all-zero state
is absorbing, which is why the maximum is one short of the state count.

The step map is a bijection only when bit zero is tapped: without it, the
outgoing bit does not influence the feedback, two states share an image,
and the register runs into a cycle it can never leave and never started
on. Returns zero in that case, meaning the register never comes back.

Rust: `codes::crypto_math::lfsr_period`
    """
    ...

def berlekamp_massey_attack(stream: list[bool]) -> tuple[int, int]:
    """
Recovers the shortest linear recurrence a bit stream satisfies, as
`(length, taps)`.

The Berlekamp-Massey algorithm, over `GF(2)`. Given `2L` bits of output
from a register of length `L` it returns that register, which is why a
bare shift register is not a cipher: the keystream reveals the key
generator in time linear in its size.

Rust: `codes::crypto_math::berlekamp_massey_attack`
    """
    ...

def hash_avalanche_test(h: Callable[[list[int]], int], trials: int, rng: Rng) -> float:
    """
How close a hash comes to flipping half its output bits when one input bit
changes.

Returns the mean fraction of output bits that flip. A good hash sits at a
half: every output bit should be an unbiased, independent-looking function
of every input bit, so that no partial information about the input
survives. A value far from a half is a structural weakness a distinguisher
can be built from.

Panics:
Panics if `trials` is zero.

Rust: `codes::crypto_math::hash_avalanche_test`
    """
    ...

def birthday_bound(n_bits: int) -> float:
    """
The number of samples at which a collision becomes likely for an output of
`n_bits`.

About `2^(n/2)`, up to a constant: with `k` samples there are about
`k^2 / 2` pairs and each collides with probability `2^-n`, so the count of
collisions reaches one near the square root. It is why a 128-bit hash
offers 64 bits of collision resistance, not 128.

Rust: `codes::crypto_math::birthday_bound`
    """
    ...

def frequency_analysis(text: list[int]) -> list[float]:
    """
The frequency of each letter, ignoring everything else, as fractions
summing to one.

Rust: `codes::crypto_math::frequency_analysis`
    """
    ...

def index_of_coincidence(text: list[int]) -> float:
    """
The index of coincidence: the chance that two letters drawn at random from
the text are the same.

About `0.066` for English and `0.038` for a uniform jumble. Because it is
unchanged by a substitution -- relabelling the letters does not change how
often two match -- it tells a monoalphabetic cipher from a polyalphabetic
one without any guess about the key, which is what makes it the first
measurement to take.

Rust: `codes::crypto_math::index_of_coincidence`
    """
    ...

def kasiski_examination(text: list[int]) -> list[int]:
    """
Candidate key lengths from repeated trigrams, as Kasiski proposed.

A trigram repeating in the ciphertext usually means the same plaintext
trigram met the same stretch of key, so the gap between the two is a
multiple of the key length. Returns the lengths that divide the most gaps,
best first.

Rust: `codes::crypto_math::kasiski_examination`
    """
    ...

def caesar_break(text: list[int]) -> int:
    """
The Caesar shift that best matches English letter frequencies.

Scored by the dot product of the observed and expected distributions,
which is largest when the two line up -- the same statistic as chi-squared
scoring, with the arithmetic the other way up.

Rust: `codes::crypto_math::caesar_break`
    """
    ...

def vigenere_break(text: list[int], max_key: int) -> str:
    """
The most likely Vigenere key, searching lengths up to `max_key`.

The key length is chosen by the average index of coincidence of the
columns -- at the true length each column is a Caesar shift of English and
so looks like English, and at any other length the columns are jumbled --
and each column is then solved as its own Caesar shift.

Panics:
Panics if `max_key` is zero.

Rust: `codes::crypto_math::vigenere_break`
    """
    ...

def perfect_shuffle_permutation(n: int, out: bool) -> list[int]:
    """
The permutation a perfect riffle shuffle applies to `n` cards.

An *out* shuffle keeps the top card on top; an *in* shuffle pushes it to
second. Eight out-shuffles restore a 52-card deck and 52 in-shuffles do,
which is the standard demonstration that a deterministic shuffle is no
shuffle at all.

Panics:
Panics unless `n` is positive and even.

Rust: `codes::crypto_math::perfect_shuffle_permutation`
    """
    ...

def permutation_cipher_period(perm: list[int]) -> int:
    """
How many times a permutation must be applied before everything returns
home: the least common multiple of its cycle lengths.

Panics:
Panics unless the input is a permutation of `0..n`.

Rust: `codes::crypto_math::permutation_cipher_period`
    """
    ...
