"""
Gaussian process regression.  # A distribution over functions, conditioned  A Gaussian process says that any finite set of function values is jointly normal, with a covariance given by the kernel. Regression is then not fitting but conditioning: the posterior over an unobserved point is the conditional of a multivariate normal, and that has a closed form. There is no optimisation anywhere in `Gp::fit` -- it is one Cholesky factorisation, and the answer is exact given the kernel.  Two consequences are worth stating because they surprise people and because they are exactly testable.  *The posterior variance does not depend on what was observed.* It is `k(x,x) - k_*^T K^-1 k_*`, and `y` does not appear. Uncertainty in a Gaussian process is a statement about where the data *is*, not about what it said. Doubling every observation doubles the mean and leaves every error bar alone.  *With no noise the mean interpolates exactly and the variance vanishes at the data.* The conditional of a normal on one of its own coordinates is a point mass. Adding noise is what turns interpolation into smoothing, and the residual at the data grows from zero in proportion to it.  # Which kernel is a modelling choice, not a detail  The kernel *is* the prior. A squared exponential asserts that the function is infinitely differentiable, which is a very strong claim and the reason its posterior can look implausibly smooth between widely spaced points. The Matern family asserts a finite number of derivatives -- `3/2` gives one, `5/2` gives two -- and is usually the better default for anything physical. A periodic kernel asserts exact periodicity, and `KernelFn::Periodic` satisfies `k(x, x + p) = k(x, x)` to rounding rather than approximately.  Kernels are closed under addition and multiplication, which is what `KernelFn::Sum` and `KernelFn::Product` are for: a sum models additive structure (a trend plus a wiggle), a product models interaction (a periodicity whose amplitude decays).  # The marginal likelihood balances fit against complexity on its own  `log p(y | X)` splits into a data-fit term `-y^T K^-1 y / 2` and a complexity penalty `-log|K| / 2`. Making the kernel more flexible improves the first and costs the second, and the trade is not a hyperparameter anyone chose -- it falls out of the normalisation of a probability distribution. That is why hyperparameters can be tuned by maximising it without a validation set.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.monte_carlo import Rng

class Gp:
    """
A fitted Gaussian process.

Rust: `learn::gp::Gp`
    """
    @staticmethod
    def fit(kernel: KernelFn, noise: float, x: list[list[float]], y: list[float]) -> Gp: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def condition_estimate(self) -> float: ...
    def predict(self, x_star: list[list[float]]) -> tuple[list[float], list[float]]: ...
    def log_marginal_likelihood(self) -> float: ...
    def optimize_hyperparams(self, restarts: int, rng: Rng) -> Gp: ...
    def sample_posterior(self, x_star: list[list[float]], count: int, rng: Rng) -> list[list[float]]: ...
    @property
    def kernel(self) -> KernelFn: ...
    @property
    def noise(self) -> float: ...

class KernelFn:
    """
A covariance function.

Rust: `learn::gp::KernelFn`
    """
    def eval(self, a: list[float], b: list[float]) -> float: ...
    def is_valid(self) -> bool: ...
    def parameters(self) -> list[float]: ...
    def with_parameters(self, values: list[float]) -> KernelFn: ...

def sample_prior(kernel: KernelFn, x: list[list[float]], count: int, rng: Rng) -> list[list[float]]:
    """
Draws sample functions from a prior with the given kernel.

Errors:

`SolveError::InvalidArgument` for an invalid kernel or an empty or
ragged point set; `SolveError::NotPositiveDefinite` if the
covariance matrix cannot be factored.

Rust: `learn::gp::sample_prior`
    """
    ...
