"""
Chemical kinetics: rate laws, deterministic and stochastic reaction networks, enzyme saturation, equilibrium composition, oscillating mechanisms, nucleation and transformation, and the acid-base and electrochemical relations that share their arithmetic.  # What lives here and what lives in `chemistry`  The elementary single-formula relations -- the Arrhenius rate, the equilibrium constant from a free energy, the Nernst potential, pH from a proton concentration -- are already in `chemistry`, and are not duplicated. This module is the part that needs a solver: networks integrated in time, fits inverted from data, compositions found by root-finding, and the stochastic algorithms.  # Units  Concentrations are molar, times are seconds, energies are joules per mole and temperatures are kelvin, so `R` rather than `k_B` appears throughout. The one exception is `kramers_rate_check`, which follows its own literature convention of barrier heights in units of `k_B T`; it is marked at the function.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.finance.options import Barrier
from rust_physics_engine.fractals.automata import Brusselator
from rust_physics_engine.linalg.matrix import Matrix
from rust_physics_engine.statistics.distributions import Poisson
from rust_physics_engine.monte_carlo import Rng

class Inhibition:
    """
Which way an inhibitor acts.

Rust: `statistical_mechanics::kinetics::Inhibition`
    """
    ...

class Reaction:
    """
One elementary reaction, as species indices with their stoichiometric
coefficients.

Rust: `statistical_mechanics::kinetics::Reaction`
    """
    def __init__(self, reactants: list[tuple[int, int]], products: list[tuple[int, int]]) -> None: ...
    def order(self) -> int: ...
    def net_change(self, species: int) -> list[int]: ...
    @property
    def reactants(self) -> list[tuple[int, int]]: ...
    @property
    def products(self) -> list[tuple[int, int]]: ...

def stoichiometry_matrix(reactions: list[Reaction], species: int) -> Matrix:
    """
The stoichiometry matrix: species by reaction, each entry the net change
in that species when that reaction fires once.

Errors:
Returns an error for no reactions, no species, or a species index outside
the declared count.

Rust: `statistical_mechanics::kinetics::stoichiometry_matrix`
    """
    ...

def mass_action_rates(reactions: list[Reaction], k: list[float], concentrations: list[float]) -> list[float]:
    """
The deterministic mass-action rate of each reaction at a composition.

`v_j = k_j prod_i c_i^m_ij`. Note the contrast with the stochastic
propensity in `gillespie_ssa`, which uses a falling factorial rather
than a power: a bimolecular reaction of a species with itself has rate
`k c^2` in the continuum and `k x (x - 1) / 2` in molecule counts, and
the two agree only when the count is large. Conflating them is the
classic way to get a stochastic simulation that quietly disagrees with
its own rate equations.

Errors:
Returns an error for a rate constant per reaction mismatch, a negative
rate constant, or a species index outside the composition.

Rust: `statistical_mechanics::kinetics::mass_action_rates`
    """
    ...

def rate_equations(stoich: Matrix | Sequence[Sequence[float]], rates: Callable[[list[float]], list[float]], c0: list[float], t_end: float, rtol: float) -> list[tuple[float, list[float]]]:
    """
Integrates a reaction network in time with an adaptive implicit method.

Chemical networks are almost always stiff -- a fast pre-equilibrium
alongside a slow overall conversion means the fastest and slowest
timescales differ by orders of magnitude -- and an explicit integrator is
then limited by the *fastest* one long after it has ceased to matter.
The step here is backward Euler -- A-stable, and L-stable, so a mode far
faster than the step is damped rather than merely bounded -- taken once
at the full step and twice at half. The difference is the local error
estimate, and their Richardson combination `2 y_half - y_full` is the
second-order value actually kept.

A multistep formula would be the conventional choice and is the wrong one
here: BDF2 assumes a uniform step, and an adaptive controller varies it
every step, so the history it is handed is at the wrong spacing and the
resulting inconsistency dominates the error estimate. A one-step method
with Richardson has no history to get wrong.

The step is limited by the solution's own timescale as well as by the
error estimate, and that second limit is not redundant. On an
*oscillatory* system step doubling can be fooled outright: an L-stable
method damps hard at a step much longer than the period, so the coarse
and fine solutions both collapse toward the fixed point, agree closely
with each other, and report a small error -- whereupon the controller
grows the step further. A run can end up stepping clean over whole
oscillations while its error estimate reports success. Bounding the step
by `|c| / |dc/dt|` prevents that, because it looks at the dynamics rather
than at the difference between two equally wrong answers.

Returns `(time, composition)` at each accepted step.

Errors:
Returns an error for a mismatched initial composition, a non-positive
end time or tolerance, or if the Newton iteration inside a step fails to
converge even at the smallest permitted step.

Rust: `statistical_mechanics::kinetics::rate_equations`
    """
    ...

def gillespie_ssa(reactions: list[Reaction], k: list[float], x0: list[int], t_end: float, max_events: int, rng: Rng) -> list[tuple[float, list[int]]]:
    """
Gillespie's direct method: an exact realisation of the chemical master
equation.

Exact in a strong sense -- the trajectory is drawn from the true
distribution of the jump process, with no time discretisation at all.
The waiting time to the next event is exponential with rate equal to the
total propensity, and which reaction fires is chosen in proportion to
its own. Returns `(time, counts)` after each event, including the
initial state.

Errors:
Returns an error for a malformed network or a non-positive end time.

Rust: `statistical_mechanics::kinetics::gillespie_ssa`
    """
    ...

def tau_leaping(reactions: list[Reaction], k: list[float], x0: list[int], t_end: float, tau: float, rng: Rng) -> list[tuple[float, list[int]]]:
    """
Explicit tau-leaping: many reaction events per step, each count drawn
from a Poisson distribution.

Trades exactness for speed. Over a leap of `tau` the propensities are
held fixed, so the number of firings of reaction `j` is Poisson with
mean `a_j tau` -- correct only while `tau` is short enough that the
propensities really do not change much, which is the whole art of the
method. Too long a leap drives species negative; this implementation
rejects a leap that would and retries it at half the length rather than
clamping, since clamping silently changes the reaction network.

Errors:
Returns an error for a malformed network, a non-positive end time or
leap.

Rust: `statistical_mechanics::kinetics::tau_leaping`
    """
    ...

def michaelis_menten(s: float, vmax: float, km: float) -> float:
    """
The Michaelis-Menten rate `v = vmax s / (km + s)`.

Rust: `statistical_mechanics::kinetics::michaelis_menten`
    """
    ...

def hill_equation(s: float, vmax: float, k: float, n: float) -> float:
    """
The Hill rate `v = vmax s^n / (k^n + s^n)`.

The exponent is a measure of cooperativity, not a molecularity: a Hill
coefficient of 2.8 for haemoglobin does not mean 2.8 oxygen molecules
bind at once, it means four sites bind with positive cooperativity and
the two-state fit lands there.

Rust: `statistical_mechanics::kinetics::hill_equation`
    """
    ...

def mm_fit(s: list[float], v: list[float]) -> tuple[float, float]:
    """
Fits `vmax` and `km` to saturation data by least squares on the
*residuals of the rate itself*, by Gauss-Newton.

Deliberately not the Lineweaver-Burk fit. Inverting the data transforms
the error along with it, so the points at the lowest substrate -- where
the relative error is largest -- become the ones with the largest
leverage, and the fitted `vmax` is biased. The double-reciprocal plot
remains useful for *seeing* the mechanism, which is what
`lineweaver_burk` is for; it is not the way to get the numbers.

Errors:
Returns an error for fewer than three points, mismatched lengths,
negative concentrations or rates, or a fit that does not converge.

Rust: `statistical_mechanics::kinetics::mm_fit`
    """
    ...

def lineweaver_burk(s: list[float], v: list[float]) -> tuple[list[tuple[float, float]], float, float]:
    """
The double-reciprocal transform: `(1/s, 1/v)` for each point, plus the
straight line through them as `(slope, intercept)`.

The line has slope `km / vmax` and intercept `1 / vmax`. Useful for
reading a mechanism off a plot -- competitive, uncompetitive and
non-competitive inhibition give visibly different families of lines --
and a poor way to extract the constants; see `mm_fit`.

Errors:
Returns an error for fewer than two points, mismatched lengths, or a
non-positive concentration or rate, which the transform cannot represent.

Rust: `statistical_mechanics::kinetics::lineweaver_burk`
    """
    ...

def hill_fit(s: list[float], v: list[float]) -> tuple[float, float, float]:
    """
Fits the Hill parameters `(vmax, k, n)` by Gauss-Newton.

Errors:
Returns an error for fewer than four points, mismatched lengths, or
non-positive data.

Rust: `statistical_mechanics::kinetics::hill_fit`
    """
    ...

def enzyme_inhibition(s: float, i: float, vmax: float, km: float, ki: float, kind: Inhibition) -> float:
    """
The inhibited Michaelis-Menten rate.

The three mechanisms are distinguished by *which* constant moves, not by
how much the rate falls -- which is why a single rate measurement can
never identify the mechanism and a substrate series can.

Errors:
Returns an error for a non-positive `km` or inhibition constant, or a
negative concentration.

Rust: `statistical_mechanics::kinetics::enzyme_inhibition`
    """
    ...

def steady_state_approx_check(e0: float, s0: float, k1: float, k_minus1: float, k2: float, t_end: float) -> float:
    """
How far a mechanism is from its steady-state approximation, as the
largest relative difference in the intermediate's concentration.

The approximation holds when the intermediate is consumed as fast as it
is made, which for Michaelis-Menten means the enzyme is scarce beside the
substrate. Returns the discrepancy so the caller can see *whether* it
holds rather than assuming it.

Errors:
Returns an error for non-positive rate constants or concentrations.

Rust: `statistical_mechanics::kinetics::steady_state_approx_check`
    """
    ...

def equilibrium_composition(stoich: Matrix | Sequence[Sequence[float]], k_eq: list[float], totals: list[tuple[list[float], float]]) -> list[float]:
    """
The equilibrium composition of a set of reactions with known constants,
found by minimising the total residual of the mass-action and
conservation conditions.

Each reaction contributes `prod c^nu = k_eq` and each conserved element
contributes a total. Solved by Newton on the logarithms of the
concentrations, which keeps every one positive without a constraint --
a composition can approach zero but never reach or cross it, which is
what the physical problem requires and what an unconstrained solve on the
concentrations themselves does not respect.

`totals` is one row per conserved quantity, giving each species' content
and the total amount.

Errors:
Returns an error for mismatched shapes, a non-positive constant or total,
or a system that does not converge.

Rust: `statistical_mechanics::kinetics::equilibrium_composition`
    """
    ...

def oscillating_brusselator(a: float, b: float, c0: tuple[float, float], t_end: float) -> list[tuple[float, list[float]]]:
    """
The Brusselator, integrated in time.

`A -> X`, `2X + Y -> 3X`, `B + X -> Y + D`, `X -> E`, with `A` and `B`
held fixed. The steady state `(a, b/a)` loses stability in a Hopf
bifurcation exactly at `b = 1 + a^2`, and above it the system settles
onto a limit cycle whose amplitude does not depend on where it started.
That sharp threshold is what makes it the standard test of an oscillating
mechanism: the transition is a property of the equations, not of the
integrator.

Errors:
Returns an error for non-positive parameters or a bad initial state.

Rust: `statistical_mechanics::kinetics::oscillating_brusselator`
    """
    ...

def brusselator_oscillates(a: float, b: float) -> bool:
    """
Whether the Brusselator oscillates at these parameters: `b > 1 + a^2`.

Rust: `statistical_mechanics::kinetics::brusselator_oscillates`
    """
    ...

def oregonator(epsilon: float, delta: float, q: float, f: float, c0: tuple[float, float, float], t_end: float) -> list[tuple[float, list[float]]]:
    """
The Oregonator, the Field-Noyes reduction of the Belousov-Zhabotinsky
reaction, in its scaled form.

Genuinely stiff: `epsilon` and `delta` are of order `10^-2` and `10^-4`,
so the three variables move on timescales four orders of magnitude
apart, and an explicit integrator would be pinned to the fastest one for
the whole run. This is the case the implicit solver in
`rate_equations` exists for.

Errors:
Returns an error for non-positive parameters or a bad initial state.

Rust: `statistical_mechanics::kinetics::oregonator`
    """
    ...

def lotka_volterra_chemical(a: float, k1: float, k2: float, k3: float, c0: tuple[float, float], t_end: float) -> tuple[list[tuple[float, list[float]]], list[float]]:
    """
The chemical Lotka-Volterra mechanism: `A + X -> 2X`, `X + Y -> 2Y`,
`Y -> B`, with `A` held fixed.

Returns the trajectory together with the conserved quantity
`V = k2 x + k2 y - k3 ln x - k1 a ln y`, which is constant along every
orbit. That constant is the reason the orbits are closed curves rather
than a limit cycle: the system is conservative, and unlike the
Brusselator its amplitude *does* depend on where it started. Reporting
it lets a caller see the integrator's drift directly.

Errors:
Returns an error for non-positive parameters or a non-positive initial
state, for which the conserved quantity is undefined.

Rust: `statistical_mechanics::kinetics::lotka_volterra_chemical`
    """
    ...

def autocatalysis_ignition(a0: float, b0: float, k: float) -> float:
    """
The ignition time of an autocatalytic reaction `A + B -> 2B`, defined as
the moment the product passes half its final amount.

The closed form is the logistic inflection: with `a0 + b0` conserved,
`t = ln(a0 / b0) / (k (a0 + b0))`. The induction period is set by how
*little* product there is at the start, which is why an autocatalytic
reaction can sit apparently inert for a long time and then go over in a
moment.

Errors:
Returns an error for a non-positive rate constant or a non-positive
initial amount of either species.

Rust: `statistical_mechanics::kinetics::autocatalysis_ignition`
    """
    ...

def chain_reaction_criticality(k_branch: float, k_term: float) -> float:
    """
Whether a branching chain reaction runs away, and by how much: the
branching ratio `k_branch / k_term`.

Above one the chain carriers multiply and the reaction accelerates
without bound; below one it dies out. The threshold is exactly one and
nothing continuous separates the two behaviours, which is why an
explosion limit is a sharp line in pressure and temperature rather than
a gradual onset.

Errors:
Returns an error for a non-positive termination rate.

Rust: `statistical_mechanics::kinetics::chain_reaction_criticality`
    """
    ...

def eyring(delta_h: float, delta_s: float, t: float) -> float:
    """
The Eyring rate `(k_B T / h) exp(dS/R) exp(-dH/RT)`.

Differs from Arrhenius in what the prefactor means: here it is
`k_B T / h`, a universal frequency of about `6 x 10^12` per second at
room temperature, and all the chemistry sits in the entropy of
activation. The two forms fit the same data equally well and disagree
about why.

Errors:
Returns an error for a non-positive temperature.

Rust: `statistical_mechanics::kinetics::eyring`
    """
    ...

def transition_state_theory_rate(delta_g: float, t: float, transmission: float) -> float:
    """
Transition-state theory with a transmission coefficient.

`k = kappa (k_B T / h) exp(-dG/RT)`. The coefficient is the fraction of
trajectories that cross the barrier and *stay* crossed; transition-state
theory assumes it is one, which makes the theory an upper bound on the
true rate rather than an estimate of it.

Errors:
Returns an error for a non-positive temperature or a coefficient outside
zero to one.

Rust: `statistical_mechanics::kinetics::transition_state_theory_rate`
    """
    ...

def kramers_rate_check(gamma: float, barrier_frequency: float) -> float:
    """
The Kramers rate in the moderate-to-high friction regime, relative to the
transition-state result.

`k / k_TST = sqrt(1 + (gamma / 2 omega_b)^2) - gamma / (2 omega_b)`,
which is at most one and falls toward `omega_b / gamma` as the friction
grows: a solvent that couples strongly to the reaction coordinate makes
recrossing likely, and every recrossing is a barrier passage that did not
produce a product. This is the transmission coefficient that
`transition_state_theory_rate` takes on faith.

Barrier frequency and friction are in the same units; the ratio is what
matters.

Errors:
Returns an error for a non-positive barrier frequency or a negative
friction.

Rust: `statistical_mechanics::kinetics::kramers_rate_check`
    """
    ...

def kinetic_isotope_effect_estimate(nu_light: float, nu_heavy: float, t: float) -> float:
    """
The semiclassical kinetic isotope effect from the change in zero-point
energy alone.

`k_light / k_heavy = exp(h (nu_light - nu_heavy) / (2 k_B T))`. The
hydrogen-deuterium maximum near seven at room temperature comes out of
this and nothing else; a measured ratio well above it is evidence of
tunnelling, which this estimate deliberately omits so that the excess is
visible rather than absorbed into a fitted parameter.

Frequencies are in reciprocal centimetres.

Errors:
Returns an error for a non-positive temperature or frequency.

Rust: `statistical_mechanics::kinetics::kinetic_isotope_effect_estimate`
    """
    ...

def temperature_jump_relaxation(k_forward: float, k_reverse: float) -> float:
    """
The relaxation time of a reaction perturbed from equilibrium by a
temperature jump.

For `A <-> B` the relaxation is a single exponential with rate
`k_forward + k_reverse` -- the *sum*, not either one. That is what makes
the technique work: a single measured relaxation gives the sum, the
equilibrium constant gives the ratio, and together they give both rate
constants, which no steady-state measurement can separate.

Errors:
Returns an error if both rate constants are zero or either is negative.

Rust: `statistical_mechanics::kinetics::temperature_jump_relaxation`
    """
    ...

def nucleation_rate_cnt(barrier: float, prefactor: float, t: float) -> float:
    """
The classical nucleation rate `J = A exp(-dG* / k_B T)`.

The exponent is enormous and its argument is a cube over a square, so
the rate spans dozens of orders of magnitude over a small change in
supersaturation. That extreme sensitivity is the physics, not a defect of
the model: it is why nucleation appears to have a threshold.

Errors:
Returns an error for a non-positive temperature or prefactor.

Rust: `statistical_mechanics::kinetics::nucleation_rate_cnt`
    """
    ...

def nucleation_barrier(surface_tension: float, number_density: float, driving_force: float) -> float:
    """
The classical nucleation barrier for a spherical nucleus:
`16 pi sigma^3 / (3 (n dmu)^2)`.

Errors:
Returns an error for a non-positive surface tension, density or driving
force.

Rust: `statistical_mechanics::kinetics::nucleation_barrier`
    """
    ...

def jmak_avrami(t: float, k: float, n: float) -> float:
    """
The Johnson-Mehl-Avrami-Kolmogorov transformed fraction
`1 - exp(-(k t)^n)`.

The exponent carries the mechanism: roughly 4 for three-dimensional
growth from a constant nucleation rate, 3 when all sites nucleate at
once, and lower for growth confined to a plane or a line. The point of
fitting it is to read the dimensionality off the kinetics.

Rust: `statistical_mechanics::kinetics::jmak_avrami`
    """
    ...

def avrami_fit(times: list[float], fraction: list[float]) -> tuple[float, float]:
    """
Fits `(k, n)` to transformed-fraction data.

The double logarithm `ln(-ln(1 - x)) = n ln t + n ln k` makes the fit
linear and exact, which is the one case where a transform of the data is
the right thing to do: the relation is exactly linear in the transformed
variables, so no error is being reshaped, only re-expressed.

Errors:
Returns an error for fewer than two usable points -- a fraction of zero
or one carries no information, since the transform sends it to infinity.

Rust: `statistical_mechanics::kinetics::avrami_fit`
    """
    ...

def photochemistry_quantum_yield(molecules: float, photons_absorbed: float) -> float:
    """
The quantum yield: molecules transformed per photon absorbed.

A yield above one is not an error -- a chain reaction initiated by one
photon can transform thousands of molecules -- so no upper bound is
imposed.

Errors:
Returns an error for a non-positive photon count or a negative product
count.

Rust: `statistical_mechanics::kinetics::photochemistry_quantum_yield`
    """
    ...

def ph_from_equilibria(acids: list[tuple[float, float]], base_conc: float) -> float:
    """
The pH of a solution of one or more acids, by solving the full charge
balance rather than any approximation.

Each acid is `(pKa, total concentration)`; `base_conc` is added strong
base. The equation solved is
`[H+] + [base] = K_w/[H+] + sum_a C_a K_a / (K_a + [H+])`,
which includes the water autoprotolysis and the depletion of the acid as
it dissociates. Neither can be dropped in general: the usual
`sqrt(K_a C)` shortcut assumes both, and it fails for a dilute acid
(where water dominates) and for a strong one (where the acid is nearly
all dissociated and the depletion is the whole story). Solved by
bisection on `pH`, which cannot diverge because the balance is monotone
in `[H+]`.

Errors:
Returns an error for a negative concentration or an empty system with no
base.

Rust: `statistical_mechanics::kinetics::ph_from_equilibria`
    """
    ...

def titration_curve(acid_pka: float, acid_conc: float, acid_volume: float, base_conc: float, volume_max: float, points: int) -> list[tuple[float, float]]:
    """
A titration curve: pH against the volume of strong base added.

Returns `(volume added, pH)` at each of `points` steps up to
`volume_max`. Dilution is accounted for -- both the acid and the base
are diluted by the growing total volume -- which is what puts the
equivalence point of a weak acid above pH 7 rather than at it.

Errors:
Returns an error for a non-positive volume, concentration or point
count.

Rust: `statistical_mechanics::kinetics::titration_curve`
    """
    ...

def buffer_henderson_hasselbalch(pka: float, ratio: float) -> float:
    """
Henderson-Hasselbalch: `pH = pKa + log10(base / acid)`.

An approximation, and one whose failure is predictable: it assumes the
dissociation does not appreciably change either concentration, so it is
accurate within about a unit of the pKa and wrong outside that. Compare
against `ph_from_equilibria`, which makes no such assumption.

Errors:
Returns an error for a non-positive ratio.

Rust: `statistical_mechanics::kinetics::buffer_henderson_hasselbalch`
    """
    ...

def debye_huckel_activity(z: float, ionic_strength: float) -> float:
    """
The Debye-Huckel activity coefficient of an ion.

The extended law `log10 gamma = -A z^2 sqrt(I) / (1 + sqrt I)`, with
`A = 0.509` for water at 25 degrees. The limiting law without the
denominator is only good below about `I = 0.01`; the extended form holds
to roughly `I = 0.1`, and above that no simple expression does.

Errors:
Returns an error for a negative ionic strength.

Rust: `statistical_mechanics::kinetics::debye_huckel_activity`
    """
    ...

def nernst(e0: float, z: float, ratio: float, t: float) -> float:
    """
The Nernst potential from a concentration ratio.

A thin wrapper on `chemistry::nernst_potential` in the form the
kinetics literature uses. At 25 degrees and one electron the slope is
59.16 mV per decade, which is the number every ion-selective electrode
is calibrated against.

Errors:
Returns an error for a non-positive temperature, electron count or
ratio.

Rust: `statistical_mechanics::kinetics::nernst`
    """
    ...

def butler_volmer(i0: float, alpha: float, eta: float, z: float, t: float) -> float:
    """
The Butler-Volmer current density
`i0 (exp(alpha z F eta / RT) - exp(-(1 - alpha) z F eta / RT))`.

At small overpotential the two exponentials cancel to leading order and
the current is *linear* in `eta` with a slope `i0 z F / RT` -- the
charge-transfer resistance. At large overpotential one term dominates
and the relation becomes the logarithmic Tafel law. Both limits come out
of the same expression, which is why fitting a Tafel slope to
near-equilibrium data gives a meaningless exchange current.

Errors:
Returns an error for a non-positive temperature or exchange current, an
asymmetry outside zero to one, or a non-positive electron count.

Rust: `statistical_mechanics::kinetics::butler_volmer`
    """
    ...

def cottrell_current(z: float, area: float, concentration: float, diffusivity: float, t: float) -> float:
    """
The Cottrell current `z F A c sqrt(D / (pi t))` for a diffusion-limited
electrode.

Falls as the inverse square root of time, not exponentially: the
depletion layer grows as `sqrt(D t)`, so the gradient that drives the
current thins in proportion. The same square root governs every
semi-infinite diffusion problem.

Errors:
Returns an error for a non-positive time, area, diffusion coefficient,
concentration or electron count.

Rust: `statistical_mechanics::kinetics::cottrell_current`
    """
    ...
