"""
Molecular dynamics: pair potentials, a cell-list force evaluation, a symplectic integrator, thermostats and barostats, and the structural and transport measurements taken from a trajectory.  # Units  Everything here is in *reduced* Lennard-Jones units: `sigma`, `eps`, the particle mass and Boltzmann's constant are all one unless the caller says otherwise, so a temperature is an energy and a pressure is an energy per volume. This is not a convenience -- mixing SI constants into a molecular dynamics run is how the field's worst bugs happen, because the equations of motion are dimensionally consistent under any consistent choice and silently wrong under an inconsistent one. See `lj_reduced_units_note`.  The roadmap gives `MdSystem` a `SpatialHash` field. The general-purpose hash in `spatial::kdtree` owns a copy of every position and knows nothing about periodic images, so this module carries its own cell list instead: it is rebuilt each step from the live positions and wraps at the box boundary, which is what the minimum-image convention needs.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.monte_carlo import Rng
from rust_physics_engine.statistics.inference import TestResult
from rust_physics_engine.stochastic.timeseries import Var
from rust_physics_engine.math import Vec3

class MdSample:
    """
One record from a trajectory.

Rust: `statistical_mechanics::md::MdSample`
    """
    def __init__(self, time: float, kinetic: float, potential: float, total: float, temperature: float, pressure: float) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def kinetic(self) -> float: ...
    @property
    def potential(self) -> float: ...
    @property
    def total(self) -> float: ...
    @property
    def temperature(self) -> float: ...
    @property
    def pressure(self) -> float: ...

class MdSystem:
    """
A box of particles interacting through one pair potential.

Rust: `statistical_mechanics::md::MdSystem`
    """
    def __init__(self, pos: list[Vec3 | Sequence[float]], vel: list[Vec3 | Sequence[float]], mass: list[float], box_size: Vec3 | Sequence[float], periodic: bool, potential: Potential, cutoff: float) -> None: ...
    @staticmethod
    def lattice_fcc(cells: int, density: float, temperature: float, eps: float, sigma: float, rng: Rng) -> MdSystem: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def volume(self) -> float: ...
    def wrap(self, p: Vec3 | Sequence[float]) -> Vec3: ...
    def minimum_image(self, d: Vec3 | Sequence[float]) -> Vec3: ...
    def remove_drift(self) -> None: ...
    def rescale_to_temperature(self, target: float) -> None: ...
    def forces(self) -> list[Vec3]: ...
    def refresh_forces(self) -> None: ...
    def potential_energy(self) -> float: ...
    def kinetic_energy(self) -> float: ...
    def total_momentum(self) -> Vec3: ...
    def degrees_of_freedom(self) -> float: ...
    def temperature(self) -> float: ...
    def pressure_virial(self) -> float: ...
    def sample(self) -> MdSample: ...
    def step_velocity_verlet(self, dt: float) -> None: ...
    def thermostat_berendsen(self, t_target: float, tau: float, dt: float) -> None: ...
    def thermostat_nose_hoover(self, t_target: float, q: float, dt: float) -> None: ...
    def thermostat_langevin(self, t_target: float, gamma: float, dt: float, rng: Rng) -> None: ...
    def barostat_berendsen(self, p_target: float, compressibility: float, tau: float, dt: float) -> None: ...
    def equilibrate(self, steps: int, dt: float, t_target: float, rng: Rng) -> None: ...
    def run_nve(self, steps: int, dt: float) -> list[MdSample]: ...
    def run_trajectory(self, steps: int, dt: float, stride: int) -> tuple[list[list[Vec3]], list[list[Vec3]]]: ...
    def rdf(self, bins: int, r_max: float) -> list[float]: ...
    def structure_factor(self, k_values: list[float]) -> list[float]: ...
    def maxwell_boltzmann_check(self) -> TestResult: ...
    def melting_indicator_lindemann(self, traj: list[list[Vec3 | Sequence[float]]]) -> float: ...
    @staticmethod
    def msd(traj: list[list[Vec3 | Sequence[float]]]) -> list[float]: ...
    @staticmethod
    def diffusion_coefficient(msd: list[float], dt: float) -> float: ...
    @staticmethod
    def vacf(traj_vel: list[list[Vec3 | Sequence[float]]]) -> list[float]: ...
    @staticmethod
    def vdos_from_vacf(vacf: list[float], dt: float) -> list[float]: ...
    @property
    def pos(self) -> list[Vec3]: ...
    @property
    def unwrapped(self) -> list[Vec3]: ...
    @property
    def vel(self) -> list[Vec3]: ...
    @property
    def mass(self) -> list[float]: ...
    @property
    def charge(self) -> list[float]: ...
    @property
    def box_size(self) -> Vec3: ...
    @property
    def periodic(self) -> bool: ...
    @property
    def potential(self) -> Potential: ...
    @property
    def cutoff(self) -> float: ...
    @property
    def time(self) -> float: ...
    @property
    def nose_hoover_zeta(self) -> float: ...

class Potential:
    """
A pair potential, as a function of the separation alone.

Each variant supplies both the energy and the force so that they cannot
drift apart: a force that is not the negative gradient of the energy in
use will conserve nothing, and the failure looks exactly like an
integrator bug.

Rust: `statistical_mechanics::md::Potential`
    """
    def evaluate(self, r: float, qi: float, qj: float) -> tuple[float, float]: ...
    def is_charged(self) -> bool: ...

def energy_drift(samples: list[MdSample | Sequence[float]]) -> float:
    """
The secular drift of the total energy over a record, relative to its mean.

This is the slope of a least-squares line through the total energy,
multiplied by the elapsed time -- not the spread. A symplectic
integrator's energy *oscillates* with an amplitude set by the step size
and does not go anywhere; reporting that oscillation as drift would
condemn a correct integrator, and reporting the maximum deviation would
do the same. What distinguishes a good integrator from a bad one is
whether the oscillation has a trend under it.

Errors:
Returns an error for fewer than three samples or a zero time span.

Rust: `statistical_mechanics::md::energy_drift`
    """
    ...

def lj_reduced_units_note() -> str:
    """
What the reduced units in this module mean.

Rust: `statistical_mechanics::md::lj_reduced_units_note`
    """
    ...

def lj_phase_point(t_star: float, rho_star: float) -> str:
    """
A rough phase from the Lennard-Jones phase diagram.

Boundaries taken from the accepted triple point near `(T* = 0.69,
rho* = 0.84)` and critical point near `(T* = 1.32, rho* = 0.31)`. It is a
classification, not an equation of state, and near a boundary it should
not be trusted over an actual measurement.

Rust: `statistical_mechanics::md::lj_phase_point`
    """
    ...

def ewald_sum_energy_lite(charges: list[float], pos: list[Vec3 | Sequence[float]], box_l: float, alpha: float, k_max: int) -> float:
    """
The Ewald energy of a set of point charges in a periodic box.

A charged system cannot be truncated: the Coulomb sum is only
conditionally convergent, so its value depends on the order of
summation and a spherical cutoff gives a different -- wrong -- answer.
Ewald splits the sum with a Gaussian screen into a real-space part that
converges quickly and a reciprocal-space part that does the same, plus
the self-energy of the screens.

Errors:
Returns an error for mismatched lengths, a non-positive box or splitting
parameter, an empty system, or a net charge, for which the sum is not
defined without a neutralising background.

Rust: `statistical_mechanics::md::ewald_sum_energy_lite`
    """
    ...

def harmonic_crystal_heat_capacity_check(energies: list[float], temperature: float, particles: int) -> float:
    """
The heat capacity per particle of a system from its energy fluctuations,
in units of Boltzmann's constant.

`C_v = Var(E) / (k T^2)`. A classical harmonic crystal must return three:
each particle has three quadratic kinetic and three quadratic potential
degrees of freedom, and equipartition gives `k/2` to each. That is the
Dulong-Petit law, and it is the check this function exists for -- a
simulation that reports anything else at a temperature well above the
Debye temperature has a bug, not a discovery.

Errors:
Returns an error for fewer than two energies, no particles, or a
non-positive temperature.

Rust: `statistical_mechanics::md::harmonic_crystal_heat_capacity_check`
    """
    ...

def virial_coefficient_b2(potential: Potential, t: float, r_max: float, n: int) -> float:
    """
The second virial coefficient by numerical integration of the Mayer
function.

`B2(T) = -2 pi int_0^rmax (exp(-u(r)/T) - 1) r^2 dr`. It changes sign at
the Boyle temperature, where attraction and repulsion cancel and the gas
is ideal to first order in the density -- about `T* = 3.418` for
Lennard-Jones.

Errors:
Returns an error for a non-positive temperature or range, or an odd or
too-small interval count.

Rust: `statistical_mechanics::md::virial_coefficient_b2`
    """
    ...

def mean_free_path(density: float, sigma: float) -> float:
    """
The mean free path `1 / (sqrt 2 n sigma)`, with `sigma` the collision
cross-section.

The `sqrt 2` is not decoration: it accounts for the *relative* motion of
the two colliding particles, and dropping it overestimates the path by
forty per cent.

Errors:
Returns an error for a non-positive density or cross-section.

Rust: `statistical_mechanics::md::mean_free_path`
    """
    ...

def collision_rate(density: float, sigma: float, mean_speed: float) -> float:
    """
The collision rate per particle, `sqrt 2 n sigma v_mean`.

Errors:
Returns an error for a non-positive density, cross-section or speed.

Rust: `statistical_mechanics::md::collision_rate`
    """
    ...

def green_kubo_viscosity_lite(stress_xy: list[float], dt: float, volume: float, temperature: float) -> float:
    """
The shear viscosity from a Green-Kubo integral of the off-diagonal
stress autocorrelation.

`eta = V / (k T) int_0^inf <P_xy(0) P_xy(t)> dt`, integrated up to the
first lag at which the estimated correlation stops being positive.

That truncation is not an optimisation. Past a few correlation times the
estimate of `<P(0) P(t)>` is noise of a size set by the sample count, and
integrating thousands of such lags accumulates a random walk whose spread
is comparable to the whole integral -- for an exponential correlation
with a thirty-sample time and thirty thousand samples, the tail
contributes as much scatter as the signal contains. Integrating to the
end of the record therefore returns a number that is mostly noise, which
looks like a plausible viscosity and is not one.

The cost of truncating is a known one: stopping at the first zero
crossing loses the part of the tail already below the noise floor, so the
result is a few per cent low. That is the accepted trade, and it is the
direction of the remaining error -- a short record still *underestimates*
rather than scattering, because the tail it cannot see carries real
weight.

Errors:
Returns an error for fewer than two samples or a non-positive step,
volume or temperature.

Rust: `statistical_mechanics::md::green_kubo_viscosity_lite`
    """
    ...

def umbrella_sampling_pmf(histograms: list[list[float]], centers: list[float], k: float, bin_lo: float, bin_width: float, temperature: float) -> list[float]:
    """
A potential of mean force from umbrella-sampling histograms, by
self-consistent WHAM.

Each window is biased by `k (x - centre)^2 / 2`, and the windows have to
be combined by solving for one free-energy offset per window: simply
unbiasing each histogram and averaging leaves the offsets arbitrary, and
the resulting curve has a step at every window boundary.

`histograms[w][b]` is the count in bin `b` of window `w`; bin `b` is
centred at `bin_lo + (b + 0.5) * bin_width`.

Errors:
Returns an error for no windows, mismatched lengths, a non-positive bin
width, force constant or temperature, or if the iteration does not
converge.

Rust: `statistical_mechanics::md::umbrella_sampling_pmf`
    """
    ...

def steered_pull(force_along: Callable[[float], float], start: float, speed: float, k: float, dt: float, steps: int) -> list[float]:
    """
A steered-molecular-dynamics pull: a harmonic restraint whose centre
moves at constant speed, returning the accumulated work at each step.

The work is *not* the free-energy difference. It exceeds it by the
dissipation, and only in the reversible limit do the two coincide --
which is what Jarzynski's equality repairs, by averaging `exp(-W/kT)`
over repeated pulls rather than averaging the work itself.

Errors:
Returns an error for a non-positive step, force constant or step count.

Rust: `statistical_mechanics::md::steered_pull`
    """
    ...

def jarzynski_free_energy(work: list[float], temperature: float) -> float:
    """
Jarzynski's estimate of the free-energy difference from a set of
non-equilibrium work values.

`exp(-dF/kT) = <exp(-W/kT)>`. The average is dominated by the rare
trajectories with the *smallest* work, which is why the estimator is
notoriously hard to converge: the trajectories that matter most are the
ones sampled least.

Errors:
Returns an error for no work values or a non-positive temperature.

Rust: `statistical_mechanics::md::jarzynski_free_energy`
    """
    ...
