"""
The 118 chemical elements.  Atomic number, symbol, name, atomic mass, density, melting and boiling points, and thermal and electrical conductivity, with lookup by atomic number, symbol or name.  Densities are for the standard state at room temperature, so gases are quoted at STP. Where an element has no stable isotope the atomic mass is that of the longest-lived one, and properties that have never been measured are absent rather than guessed.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.audio.envelope import Ar

class Element:
    """
A chemical element with its physical and chemical properties.

All values use SI units unless otherwise noted:
- `density`: kg/m^3
- `melting_point`, `boiling_point`: Kelvin
- `specific_heat`: J/(kg*K)
- `thermal_conductivity`: W/(m*K)
- `ionization_energy`, `electron_affinity`: eV
- `atomic_radius`: pm (picometers)

Rust: `materials::elements::Element`
    """
    @property
    def atomic_number(self) -> int: ...
    @property
    def symbol(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def atomic_mass(self) -> float: ...
    @property
    def density(self) -> float: ...
    @property
    def melting_point(self) -> float: ...
    @property
    def boiling_point(self) -> float: ...
    @property
    def specific_heat(self) -> float: ...
    @property
    def thermal_conductivity(self) -> float: ...
    @property
    def electronegativity(self) -> float: ...
    @property
    def ionization_energy(self) -> float: ...
    @property
    def electron_affinity(self) -> float: ...
    @property
    def atomic_radius(self) -> float: ...
    @property
    def category(self) -> ElementCategory: ...
    @property
    def standard_state(self) -> StandardState: ...
    @property
    def electron_configuration(self) -> str: ...
    @property
    def oxidation_states(self) -> str: ...

class ElementCategory:
    """
The 118 chemical elements.

Atomic number, symbol, name, atomic mass, density, melting and boiling
points, and thermal and electrical conductivity, with lookup by atomic
number, symbol or name.

Densities are for the standard state at room temperature, so gases are
quoted at STP. Where an element has no stable isotope the atomic mass
is that of the longest-lived one, and properties that have never been
measured are absent rather than guessed.
Classification of an element within the periodic table.

Rust: `materials::elements::ElementCategory`
    """
    ...

class StandardState:
    """
The standard state of an element at room temperature and pressure (STP).

Rust: `materials::elements::StandardState`
    """
    ...

def by_atomic_number(z: int) -> Optional[Element]:
    """
Looks up an element by its atomic number (1..=118).

Returns `None` if `z` is outside the valid range.
This is an O(1) direct index lookup.

Rust: `materials::elements::by_atomic_number`
    """
    ...

def by_symbol(symbol: str) -> Optional[Element]:
    """
Looks up an element by its chemical symbol (case-sensitive, e.g. "He", "Fe").

Performs a linear scan over the 118 elements with direct string comparison.

Rust: `materials::elements::by_symbol`
    """
    ...

def by_symbol_static(symbol: str) -> Optional[Element]:
    """
O(1) lookup for commonly used element symbols, falling back to linear scan.

Covers the 27 most frequently looked-up elements (H, He, Li, Be, B, C, N,
O, F, Ne, Na, Mg, Al, Si, P, S, Cl, Ar, K, Ca, Fe, Cu, Zn, Ag, Au, Pb, U)
via a match statement that returns a direct index into the static array.
All other symbols fall back to `by_symbol`.

Rust: `materials::elements::by_symbol_static`
    """
    ...

def by_name(name: str) -> Optional[Element]:
    """
Looks up an element by name using case-insensitive ASCII comparison.

Zero-allocation: uses `eq_ignore_ascii_case` instead of `to_lowercase`.

Rust: `materials::elements::by_name`
    """
    ...

def all() -> list[Element]:
    """
Returns a slice of all 118 elements, ordered by atomic number.

Rust: `materials::elements::all`
    """
    ...
