#!/usr/bin/env python3
"""Assemble the static site published to GitHub Pages.

Nothing this produces is committed. The workflow in
`.github/workflows/pages.yml` runs it into a scratch directory and then
drops the rustdoc output alongside, so no generated page can be stale --
the same reason `docs/MODULE_MAP.md` is checked rather than hand-written.

Three things happen here:

* **Module data.** `modules.js` is derived from the source tree by the
  scanner `tools/gen_module_map.py` already uses, so the counts on the
  front page and the counts in the module map come from one place and
  cannot disagree.
* **Prose pages.** `docs/GUIDE.md` and `docs/MODULE_MAP.md` become
  `guide.html` and `module-map.html` in the site's own styling, with a
  table of contents built from their headings.
* **Static files.** Everything under `site/`, plus the banner.

    python3 tools/build_site.py             # build into _site/
    python3 tools/build_site.py --out DIR   # build somewhere else
"""

from __future__ import annotations

import html
import json
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gen_module_map import AREAS, collect, public_top_levels  # noqa: E402

SITE = "site"
DOCS = "docs"
OUT = "_site"
REPO = "https://github.com/Magic-Man-us/RustPhysicsEngine"
BLOB = f"{REPO}/blob/main"

# Which markdown files become pages, and what the page is called.
PAGES = [
    ("GUIDE.md", "guide.html", "Guide",
     "A walk through the library by doing things with it."),
    ("MODULE_MAP.md", "module-map.html", "Module map",
     "Every module in the crate, with its size and summary."),
]


# --------------------------------------------------------------------------
# Module data
# --------------------------------------------------------------------------

def module_rows() -> tuple[list[dict], dict]:
    """One row per public top-level module, plus the crate totals.

    A module's figures are the sum over every file beneath it -- `cfd` is
    16,732 lines across its submodules, not the 500 in `cfd/mod.rs` -- and
    its summary is the first sentence of its own `//!` block. Counts come
    from the scanner behind `docs/MODULE_MAP.md`, so the two agree by
    construction rather than by transcription.
    """
    mods = collect()
    public = public_top_levels()
    area_of = {name: area for area, names in AREAS for name in names}

    rows = []
    for top in sorted({m.split("::")[0] for m in mods if m != "lib"} & public):
        files = [m for name, m in mods.items()
                 if name == top or name.startswith(f"{top}::")]
        summary = mods.get(top, {}).get("summary", "—").replace(r"\|", "|")
        rows.append({
            "name": top,
            "area": area_of.get(top, "Other"),
            "lines": sum(f["lines"] for f in files),
            "fns": sum(f["free"] + f["meth"] for f in files),
            "types": sum(f["types"] for f in files),
            "files": len(files),
            "summary": summary,
        })

    totals = {
        "modules": len(rows),
        # Every source file, not only those under a public module, so this
        # agrees with the count the README and the module map quote.
        "files": len(mods),
        "lines": sum(m["lines"] for m in mods.values()),
        "fns": sum(m["free"] + m["meth"] for m in mods.values()),
        "free": sum(m["free"] for m in mods.values()),
        "methods": sum(m["meth"] for m in mods.values()),
        "types": sum(m["types"] for m in mods.values()),
    }
    return rows, totals


def write_module_data(out: str) -> None:
    rows, totals = module_rows()
    areas = [a for a, _ in AREAS] + ["Other"]
    areas = [a for a in areas if any(r["area"] == a for r in rows)]
    body = (
        "// Generated by tools/build_site.py from the source tree. Do not edit.\n"
        f"window.MODULES = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.MODULE_AREAS = {json.dumps(areas, ensure_ascii=False)};\n"
        f"window.CRATE_TOTALS = {json.dumps(totals)};\n"
    )
    with open(os.path.join(out, "modules.js"), "w", encoding="utf-8") as fh:
        fh.write(body)
    return totals


# --------------------------------------------------------------------------
# Markdown
# --------------------------------------------------------------------------
#
# A converter for exactly the markdown these two files use -- headings,
# fenced code, GFM tables, lists, rules, and the four inline forms. It is
# forty lines rather than a dependency because the crate has none, and
# because the input is two files in this repository rather than arbitrary
# text from anywhere.

INLINE = re.compile(
    r"`([^`]+)`"                       # code
    r"|\*\*([^*]+)\*\*"                # bold
    r"|(?<!\*)\*([^*\n]+)\*(?!\*)"     # italic
    r"|\[([^\]]+)\]\(([^)]+)\)"        # link
)


def rewrite_href(href: str) -> str:
    """Point a repository-relative link at the right place.

    Links between the two markdown files stay inside the site; anything
    else that names a path in the repository goes to GitHub, because the
    site does not publish the source tree.
    """
    if href.startswith(("http://", "https://", "#", "mailto:")):
        return href
    target = href.split("#", 1)
    path, frag = target[0], ("#" + target[1] if len(target) > 1 else "")
    base = os.path.normpath(os.path.join(DOCS, path)) if not path.startswith(("/", "docs/")) \
        else os.path.normpath(path.lstrip("/"))
    for md, page, _t, _d in PAGES:
        if base == os.path.join(DOCS, md):
            return page + frag
    return f"{BLOB}/{base}{frag}"


def inline(text: str) -> str:
    out, pos = [], 0
    for m in INLINE.finditer(text):
        out.append(html.escape(text[pos:m.start()]))
        code, bold, ital, label, href = m.groups()
        if code is not None:
            out.append(f"<code>{html.escape(code)}</code>")
        elif bold is not None:
            out.append(f"<strong>{inline(bold)}</strong>")
        elif ital is not None:
            out.append(f"<em>{inline(ital)}</em>")
        else:
            out.append(f'<a href="{html.escape(rewrite_href(href), quote=True)}">'
                       f"{inline(label)}</a>")
        pos = m.end()
    out.append(html.escape(text[pos:]))
    return "".join(out)


def slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", re.sub(r"`|\*|\\", "", text).lower())
    return s.strip("-") or "section"


def render_markdown(md: str) -> tuple[str, list[tuple[int, str, str]]]:
    """Return the HTML body and the (level, id, text) of every heading."""
    lines = md.split("\n")
    out: list[str] = []
    toc: list[tuple[int, str, str]] = []
    seen: dict[str, int] = {}
    i = 0

    def close_para(buf: list[str]) -> None:
        if buf:
            out.append(f"<p>{inline(' '.join(buf))}</p>")
            buf.clear()

    para: list[str] = []
    while i < len(lines):
        line = lines[i]

        if line.startswith("```"):
            close_para(para)
            lang = line[3:].strip()
            i += 1
            block = []
            while i < len(lines) and not lines[i].startswith("```"):
                block.append(lines[i])
                i += 1
            i += 1
            cls = f' class="lang-{html.escape(lang, quote=True)}"' if lang else ""
            out.append(f'<div class="code"><button class="copy" type="button"'
                       f' aria-label="Copy code">Copy</button>'
                       f"<pre><code{cls}>{html.escape(chr(10).join(block))}</code></pre></div>")
            continue

        if re.match(r"^#{1,6} ", line):
            close_para(para)
            level = len(line) - len(line.lstrip("#"))
            text = line[level:].strip()
            base = slug(text)
            seen[base] = seen.get(base, 0) + 1
            ident = base if seen[base] == 1 else f"{base}-{seen[base]}"
            if level <= 3:
                toc.append((level, ident, re.sub(r"`", "", text)))
            out.append(f'<h{level} id="{ident}">{inline(text)}'
                       f'<a class="anchor" href="#{ident}" aria-label="Link to this section">#</a>'
                       f"</h{level}>")
            i += 1
            continue

        if re.match(r"^(-{3,}|\*{3,}|_{3,})\s*$", line):
            close_para(para)
            out.append("<hr>")
            i += 1
            continue

        if line.startswith("|") and i + 1 < len(lines) and re.match(
                r"^\|[\s:\-|]+\|?\s*$", lines[i + 1]):
            close_para(para)
            def cells(row: str) -> list[str]:
                return [c.strip() for c in row.strip().strip("|").split("|")]
            head = cells(line)
            align = []
            for spec in cells(lines[i + 1]):
                if spec.startswith(":") and spec.endswith(":"):
                    align.append(" style=\"text-align:center\"")
                elif spec.endswith(":"):
                    align.append(" style=\"text-align:right\"")
                else:
                    align.append("")
            i += 2
            body = []
            while i < len(lines) and lines[i].startswith("|"):
                body.append(cells(lines[i]))
                i += 1
            out.append('<div class="table-wrap"><table><thead><tr>' + "".join(
                f"<th{align[n] if n < len(align) else ''}>{inline(c)}</th>"
                for n, c in enumerate(head)) + "</tr></thead><tbody>")
            for row in body:
                out.append("<tr>" + "".join(
                    f"<td{align[n] if n < len(align) else ''}>{inline(c)}</td>"
                    for n, c in enumerate(row)) + "</tr>")
            out.append("</tbody></table></div>")
            continue

        bullet = re.match(r"^(\s*)([-*]|\d+\.)\s+(.*)$", line)
        if bullet:
            close_para(para)
            ordered = not bullet.group(2) in ("-", "*")
            tag = "ol" if ordered else "ul"
            items: list[list[str]] = []
            while i < len(lines):
                m = re.match(r"^(\s*)([-*]|\d+\.)\s+(.*)$", lines[i])
                if m and (m.group(2) not in ("-", "*")) == ordered:
                    items.append([m.group(3)])
                    i += 1
                    # A continuation line is indented and is not itself an item.
                    while (i < len(lines) and lines[i].strip()
                           and not re.match(r"^(\s*)([-*]|\d+\.)\s+", lines[i])
                           and lines[i].startswith((" ", "\t"))):
                        items[-1].append(lines[i].strip())
                        i += 1
                elif not lines[i].strip() and i + 1 < len(lines) and re.match(
                        r"^(\s*)([-*]|\d+\.)\s+", lines[i + 1]):
                    i += 1
                else:
                    break
            out.append(f"<{tag}>" + "".join(
                f"<li>{inline(' '.join(it))}</li>" for it in items) + f"</{tag}>")
            continue

        if line.startswith(">"):
            close_para(para)
            quote = []
            while i < len(lines) and lines[i].startswith(">"):
                quote.append(lines[i].lstrip(">").strip())
                i += 1
            out.append(f"<blockquote><p>{inline(' '.join(quote))}</p></blockquote>")
            continue

        if not line.strip():
            close_para(para)
            i += 1
            continue

        para.append(line.strip())
        i += 1

    close_para(para)
    return "\n".join(out), toc


# --------------------------------------------------------------------------
# Page template
# --------------------------------------------------------------------------

def shell(title: str, description: str, body: str, active: str,
          extra_head: str = "", scripts: str = "") -> str:
    nav = [("index.html#modules", "Modules", "modules"),
           ("guide.html", "Guide", "guide"),
           ("module-map.html", "Module map", "module-map"),
           ("api/rust_physics_engine/index.html", "API", "api"),
           ("index.html#python", "Python", "python")]
    links = "".join(
        '<a href="{}"{}>{}</a>'.format(href, ' class="active"' if key == active else "", label)
        for href, label, key in nav)
    return f"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<meta name="description" content="{html.escape(description, quote=True)}">
<meta property="og:title" content="{html.escape(title, quote=True)}">
<meta property="og:description" content="{html.escape(description, quote=True)}">
<meta property="og:type" content="website">
<meta property="og:image" content="https://rust-physics-engine.mimsec.com/assets/banner.svg">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="styles.css">
<script>
// Applied before first paint so a light-theme reader never sees a dark flash.
try {{ var t = localStorage.getItem('rpe-theme');
      if (t) document.documentElement.dataset.theme = t; }} catch (e) {{}}
</script>
{extra_head}</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header class="site-header">
  <div class="bar">
    <a class="wordmark" href="index.html">
      <span class="mark" aria-hidden="true"></span>
      rust_physics_engine
    </a>
    <nav class="nav">{links}</nav>
    <div class="header-actions">
      <a class="ghost" href="{REPO}">GitHub</a>
      <button class="theme" type="button" id="theme-toggle"
              aria-label="Switch between light and dark theme"></button>
    </div>
  </div>
</header>
<main id="main">
{body}
</main>
<footer class="site-footer">
  <div class="wrap">
    <div>
      <strong>rust_physics_engine</strong>
      <p>Zero-dependency physics, mathematics and engineering computation in Rust.
         MIT licensed.</p>
    </div>
    <nav>
      <a href="{REPO}">Repository</a>
      <a href="https://docs.rs/rust_physics_engine">docs.rs</a>
      <a href="https://pypi.org/project/numeria/">numeria on PyPI</a>
      <a href="{BLOB}/LICENSE">License</a>
    </nav>
  </div>
</footer>
<script src="main.js"></script>
{scripts}</body>
</html>
"""


def build_doc_pages(out: str) -> None:
    for md, page, title, description in PAGES:
        with open(os.path.join(DOCS, md), encoding="utf-8") as fh:
            source = fh.read()
        body, toc = render_markdown(source)
        # The first h1 becomes the page header, so it is not repeated in the
        # article and not listed in its own contents.
        body = re.sub(r"^<h1 .*?</h1>\n?", "", body, count=1)
        toc = [t for t in toc if t[0] > 1]
        items = "".join(
            f'<a class="lvl{lvl}" href="#{ident}">{html.escape(text)}</a>'
            for lvl, ident, text in toc)
        article = f"""<div class="doc">
  <aside class="toc" aria-label="On this page">
    <div class="toc-inner">
      <p class="toc-title">On this page</p>
      <nav>{items}</nav>
      <p class="toc-source"><a href="{BLOB}/{DOCS}/{md}">View source on GitHub</a></p>
    </div>
  </aside>
  <article class="prose">
    <p class="eyebrow">{html.escape(description)}</p>
    <h1>{html.escape(title)}</h1>
    {body}
  </article>
</div>"""
        with open(os.path.join(out, page), "w", encoding="utf-8") as fh:
            fh.write(shell(f"{title} — rust_physics_engine", description,
                           article, page.replace(".html", "")))


def main() -> int:
    if not os.path.isdir(SITE):
        print("run from the repository root", file=sys.stderr)
        return 2
    out = OUT
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]

    if os.path.isdir(out):
        shutil.rmtree(out)
    shutil.copytree(SITE, out)
    os.makedirs(os.path.join(out, "assets"), exist_ok=True)
    shutil.copy("assets/banner.svg", os.path.join(out, "assets", "banner.svg"))
    open(os.path.join(out, ".nojekyll"), "w").close()

    totals = write_module_data(out)
    build_doc_pages(out)
    print(f"built {out}: {totals['modules']} modules, "
          f"{totals['fns']:,} public functions and methods")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
