"""
A state-vector quantum circuit simulator, with density matrices and noise channels.  The representation is the whole story. An `n`-qubit pure state is a vector of `2^n` complex amplitudes, so the memory doubles with each qubit: thirty qubits is sixteen gigabytes and there is no cleverness that avoids it for a general state. That exponential is not a limitation of this implementation but the reason quantum computers are interesting, and it is why everything here is capped at a couple of dozen qubits.  Applying a one-qubit gate does *not* cost `2^n x 2^n` work. The gate acts on one tensor factor, so the amplitudes split into `2^(n-1)` independent pairs and each pair gets a two-by-two multiply: `O(2^n)` in total. Building the full unitary and multiplying would be `O(4^n)` and is offered only for small circuits, where seeing the matrix is the point.  Qubit `q` is bit `q` of the amplitude index, so `|q_2 q_1 q_0>` has index `4 q_2 + 2 q_1 + q_0`. The opposite convention is equally common and the two disagree on every multi-qubit gate, so it is stated here rather than left to be inferred.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.monte_carlo import Rng

class Circuit:
    """
A sequence of operations on a fixed number of qubits.

Rust: `quantum::circuit::Circuit`
    """
    def __init__(self, n: int) -> None: ...
    def gate(self, q: int, gate: Gate) -> Circuit: ...
    def x(self, q: int) -> Circuit: ...
    def y(self, q: int) -> Circuit: ...
    def z(self, q: int) -> Circuit: ...
    def h(self, q: int) -> Circuit: ...
    def rx(self, q: int, theta: float) -> Circuit: ...
    def ry(self, q: int, theta: float) -> Circuit: ...
    def rz(self, q: int, theta: float) -> Circuit: ...
    def phase(self, q: int, phi: float) -> Circuit: ...
    def cx(self, control: int, target: int) -> Circuit: ...
    def cz(self, control: int, target: int) -> Circuit: ...
    def cphase(self, control: int, target: int, phi: float) -> Circuit: ...
    def ccx(self, a: int, b: int, target: int) -> Circuit: ...
    def swap(self, a: int, b: int) -> Circuit: ...
    def barrier(self) -> Circuit: ...
    def append(self, other: Circuit) -> Circuit: ...
    def inverse(self) -> Circuit: ...
    def gate_count(self) -> int: ...
    def depth(self) -> int: ...
    def run(self, initial: QState) -> QState: ...
    def run_shots(self, shots: int, rng: Rng) -> list[tuple[int, int]]: ...
    def unitary_small(self) -> list[list[complex]]: ...
    def to_qasm_lite(self) -> str: ...
    def draw_ascii(self) -> str: ...
    @property
    def n(self) -> int: ...
    @property
    def ops(self) -> list[Op]: ...

class DensityMatrix:
    """
A mixed state of `n` qubits.

Rust: `quantum::circuit::DensityMatrix`
    """
    def __init__(self, n: int, rho: list[list[complex]]) -> None: ...
    @staticmethod
    def from_state(state: QState) -> DensityMatrix: ...
    @staticmethod
    def from_mixture(states: list[QState], weights: list[float]) -> DensityMatrix: ...
    def trace(self) -> complex: ...
    def purity(self) -> float: ...
    def von_neumann_entropy(self) -> float: ...
    def is_valid(self, tol: float) -> bool: ...
    def apply_gate(self, q: int, gate: Gate) -> None: ...
    def apply_channel(self, kraus: list[list[list[complex]]]) -> None: ...
    def partial_trace(self, keep: list[int]) -> DensityMatrix: ...
    @property
    def n(self) -> int: ...
    @property
    def rho(self) -> list[list[complex]]: ...

class Gate:
    """
A one-qubit gate: a two-by-two unitary.

Rust: `quantum::circuit::Gate`
    """
    def is_unitary(self, tol: float) -> bool: ...
    def dagger(self) -> Gate: ...
    @staticmethod
    def identity() -> Gate: ...
    @staticmethod
    def x() -> Gate: ...
    @staticmethod
    def y() -> Gate: ...
    @staticmethod
    def z() -> Gate: ...
    @staticmethod
    def h() -> Gate: ...
    @staticmethod
    def s() -> Gate: ...
    @staticmethod
    def sdg() -> Gate: ...
    @staticmethod
    def t() -> Gate: ...
    @staticmethod
    def tdg() -> Gate: ...
    @staticmethod
    def rx(theta: float) -> Gate: ...
    @staticmethod
    def ry(theta: float) -> Gate: ...
    @staticmethod
    def rz(theta: float) -> Gate: ...
    @staticmethod
    def phase(phi: float) -> Gate: ...
    @staticmethod
    def u3(theta: float, phi: float, lambda_: float) -> Gate: ...
    @staticmethod
    def sqrt_x() -> Gate: ...
    @property
    def matrix(self) -> list[list[complex]]: ...

class Op:
    """
One instruction in a circuit.

Rust: `quantum::circuit::Op`
    """
    ...

class QState:
    """
A pure state of `n` qubits, as `2^n` amplitudes.

Rust: `quantum::circuit::QState`
    """
    def __init__(self, n: int, amps: list[complex]) -> None: ...
    @staticmethod
    def zero(n: int) -> QState: ...
    @staticmethod
    def basis(n: int, index: int) -> QState: ...
    @staticmethod
    def from_amps(amps: list[complex]) -> QState: ...
    @staticmethod
    def plus_all(n: int) -> QState: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def norm(self) -> float: ...
    def normalize(self) -> None: ...
    def probability(self, index: int) -> float: ...
    def probabilities(self) -> list[float]: ...
    def measure_all(self, rng: Rng) -> int: ...
    def measure_qubit(self, q: int, rng: Rng) -> tuple[bool, QState]: ...
    def sample_counts(self, shots: int, rng: Rng) -> list[tuple[int, int]]: ...
    def expectation_z(self, q: int) -> float: ...
    def expectation_pauli_string(self, pauli: str) -> float: ...
    def inner(self, other: QState) -> complex: ...
    def fidelity(self, other: QState) -> float: ...
    def apply_single(self, q: int, gate: Gate) -> None: ...
    def apply_controlled(self, control: int, target: int, gate: Gate) -> None: ...
    def apply_ccx(self, a: int, b: int, target: int) -> None: ...
    def apply_swap(self, a: int, b: int) -> None: ...
    def reduced_density_matrix(self, keep: list[int]) -> list[list[complex]]: ...
    def schmidt_coefficients(self, partition: list[int]) -> list[float]: ...
    def entanglement_entropy(self, partition: list[int]) -> float: ...
    def bloch_vector(self, q: int) -> tuple[float, float, float]: ...
    @property
    def n(self) -> int: ...
    @property
    def amps(self) -> list[complex]: ...

def depolarizing_channel(p: float) -> list[list[list[complex]]]:
    """
The depolarising channel: with probability `p`, replace the qubit by the
maximally mixed state.

The one channel that treats every direction alike, so it shrinks the Bloch
vector uniformly toward the origin without rotating it.

Errors:
Returns an error unless `p` is a probability.

Rust: `quantum::circuit::depolarizing_channel`
    """
    ...

def amplitude_damping(gamma: float) -> list[list[list[complex]]]:
    """
Amplitude damping: a qubit decaying from `|1>` to `|0>` with probability
`gamma`.

Models spontaneous emission, and unlike the symmetric channels it has a
fixed point that is not the maximally mixed state: everything ends up in
the ground state. That asymmetry is why `T_1` and `T_2` are different
numbers.

Errors:
Returns an error unless `gamma` is a probability.

Rust: `quantum::circuit::amplitude_damping`
    """
    ...

def phase_damping(gamma: float) -> list[list[list[complex]]]:
    """
Phase damping: coherence lost without any energy exchange.

The off-diagonal terms shrink and the populations do not move at all, so
the Bloch vector flattens onto the `z` axis. It is the purely quantum kind
of noise -- there is no classical process it corresponds to.

Errors:
Returns an error unless `gamma` is a probability.

Rust: `quantum::circuit::phase_damping`
    """
    ...

def bit_flip(p: float) -> list[list[list[complex]]]:
    """
The bit-flip channel.

Errors:
Returns an error unless `p` is a probability.

Rust: `quantum::circuit::bit_flip`
    """
    ...

def phase_flip(p: float) -> list[list[list[complex]]]:
    """
The phase-flip channel.

Errors:
Returns an error unless `p` is a probability.

Rust: `quantum::circuit::phase_flip`
    """
    ...

def bell_state(which: int) -> QState:
    """
One of the four Bell states, indexed zero to three.

Errors:
Returns an error for an index above three.

Rust: `quantum::circuit::bell_state`
    """
    ...

def ghz(n: int) -> QState:
    """
The `n`-qubit GHZ state.

Maximally entangled and maximally fragile: losing one qubit leaves the
rest in a classical mixture with no entanglement at all, which is what
distinguishes it from the W state.

Errors:
Returns an error for fewer than two qubits or more than the cap.

Rust: `quantum::circuit::ghz`
    """
    ...

def w_state(n: int) -> QState:
    """
The `n`-qubit W state: one excitation shared equally.

The complement of GHZ. Losing a qubit leaves the others still entangled,
so the two are inequivalent under local operations -- there is no way to
turn one into the other without communication, even probabilistically.

Errors:
Returns an error for fewer than two qubits or more than the cap.

Rust: `quantum::circuit::w_state`
    """
    ...

def random_state(n: int, rng: Rng) -> QState:
    """
A Haar-random pure state.

Built from independent complex Gaussians, which is the standard trick:
normalising a Gaussian vector gives the uniform measure on the sphere, so
this really is Haar random and not merely "random looking".

Errors:
Returns an error for a bad qubit count.

Rust: `quantum::circuit::random_state`
    """
    ...

def chsh_value(state: QState, angles: tuple[float, float, float, float]) -> float:
    """
The CHSH correlation for a two-qubit state at four measurement angles.

`S = E(a, b) - E(a, b') + E(a', b) + E(a', b')`. Any local hidden variable
model obeys `|S| <= 2`; quantum mechanics reaches `2 sqrt 2` on a Bell
state, and no theory obeying no-signalling can exceed `4`. The gap between
two and `2 sqrt 2` is the whole experimental content of Bell's theorem.

Errors:
Returns an error unless the state has two qubits.

Rust: `quantum::circuit::chsh_value`
    """
    ...

def chsh_optimal_angles() -> tuple[float, float, float, float]:
    """
The angles that maximise CHSH on a Bell state, as
`(a, a', b, b')` in radians.

Rust: `quantum::circuit::chsh_optimal_angles`
    """
    ...

def quantum_teleportation_demo(theta: float, phi: float, rng: Rng) -> tuple[tuple[float, float, float], tuple[float, float, float]]:
    """
Teleports a one-qubit state and returns the input and output Bloch
vectors.

The protocol consumes one Bell pair and two classical bits, and it moves
the state exactly -- not a copy, since the sender's qubit is destroyed by
the measurement, which is what keeps no-cloning intact. Without the
classical bits the receiver holds the maximally mixed state, so nothing
travels faster than light either.

Errors:
Returns an error if the simulation fails.

Rust: `quantum::circuit::quantum_teleportation_demo`
    """
    ...

def superdense_coding_demo(bits: tuple[bool, bool]) -> tuple[bool, bool]:
    """
Superdense coding: two classical bits carried by one qubit, given a
shared Bell pair.

Returns the decoded bits, which must equal the encoded ones. The
bookkeeping is exact -- one qubit plus prior entanglement carries two
bits, and without the entanglement it carries one, which is Holevo's
bound.

Errors:
Returns an error if the simulation fails.

Rust: `quantum::circuit::superdense_coding_demo`
    """
    ...

def no_cloning_fidelity_bound() -> float:
    """
The best fidelity an approximate universal cloner can achieve: `5 / 6`.

Exact cloning is impossible because it is not linear, and the optimal
approximation is bounded by this number, which is a theorem rather than an
engineering limit.

Rust: `quantum::circuit::no_cloning_fidelity_bound`
    """
    ...

def pauli_decompose(h: list[list[complex]]) -> list[tuple[str, float]]:
    """
Decomposes a Hermitian matrix on one or two qubits into Pauli terms.

The Pauli strings form an orthogonal basis under the Hilbert-Schmidt inner
product, so each coefficient is just `tr(P H) / d` -- no linear solve
needed. That orthogonality is what makes measuring a Hamiltonian on
hardware possible at all.

Errors:
Returns an error unless the matrix is square with side two or four.

Rust: `quantum::circuit::pauli_decompose`
    """
    ...
