"""
Nonlinear resonance: the Duffing and van der Pol oscillators, parametric (Mathieu) stability, Fano interference, synchronization pulling/locking, and generic harmonic-balance machinery.  The Duffing convention throughout is x″ + δ·x′ + α·x + β·x³ = γ·cos(ωt).
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


def duffing_response_amplitude(alpha: float, beta: float, delta: float, gamma: float, omega: float) -> list[float]:
    """
Steady single-harmonic response amplitudes of the Duffing oscillator
at drive frequency ω (harmonic balance): up to three coexisting
branches, ascending.

Rust: `resonance::nonlinear::duffing_response_amplitude`
    """
    ...

def duffing_backbone(alpha: float, beta: float, amplitude: float) -> float:
    """
Backbone curve: free-vibration frequency at amplitude a,
ω = √(α + ¾βa²).

Rust: `resonance::nonlinear::duffing_backbone`
    """
    ...

def duffing_jump_frequencies(alpha: float, beta: float, delta: float, gamma: float) -> Optional[tuple[float, float]]:
    """
Jump (saddle-node) frequencies of the forced Duffing sweep: the ω
interval where three branches coexist, found by scanning the
harmonic-balance solution count. None when no bistability exists.

Rust: `resonance::nonlinear::duffing_jump_frequencies`
    """
    ...

def duffing_simulate(alpha: float, beta: float, delta: float, gamma: float, omega: float, x0: float, v0: float, t_end: float, dt: float) -> list[tuple[float, float, float]]:
    """
RK4 trajectory (t, x, v) of the forced Duffing oscillator.

Rust: `resonance::nonlinear::duffing_simulate`
    """
    ...

def duffing_poincare(alpha: float, beta: float, delta: float, gamma: float, omega: float, x0: float, v0: float, n_points: int) -> list[tuple[float, float]]:
    """
Poincaré section of the Duffing oscillator: (x, v) sampled once per
forcing period, after discarding 100 transient periods.

Rust: `resonance::nonlinear::duffing_poincare`
    """
    ...

def mathieu_stability(a: float, q: float) -> bool:
    """
Mathieu equation stability of x″ + (a − 2q·cos 2t)x = 0 by the
Floquet criterion |tr M| ≤ 2.

Rust: `resonance::nonlinear::mathieu_stability`
    """
    ...

def mathieu_stability_chart(a_range: tuple[float, float], q_range: tuple[float, float], n: int) -> list[list[bool]]:
    """
Stability chart over a (rows) × q (columns) grids of n points each.

Rust: `resonance::nonlinear::mathieu_stability_chart`
    """
    ...

def parametric_resonance_threshold(omega0: float, damping: float, n: int) -> float:
    """
Pump-amplitude threshold h_c of the n-th parametric instability
tongue for x″ + 2λx′ + ω₀²(1 + h·cos(Ωt))x = 0 with Ω = 2ω₀/n,
found by bisecting the damped Floquet spectral radius.

Panics:
Panics unless n ≥ 1 and the parameters are positive.

Rust: `resonance::nonlinear::parametric_resonance_threshold`
    """
    ...

def kapitza_pendulum_stable(l: float, g: float, a: float, omega: float) -> bool:
    """
Kapitza inverted pendulum stability: a²ω² > 2·g·l.

Rust: `resonance::nonlinear::kapitza_pendulum_stable`
    """
    ...

def van_der_pol_simulate(mu: float, omega: float, x0: float, v0: float, t_end: float, dt: float) -> list[tuple[float, float, float]]:
    """
RK4 trajectory (t, x, v) of the van der Pol oscillator
x″ − μ(1 − x²)x′ + ω²x = 0.

Rust: `resonance::nonlinear::van_der_pol_simulate`
    """
    ...

def van_der_pol_limit_cycle_amplitude(mu: float) -> float:
    """
Limit-cycle amplitude of the van der Pol oscillator (numerically
settled; → 2 as μ → 0).

Rust: `resonance::nonlinear::van_der_pol_limit_cycle_amplitude`
    """
    ...

def van_der_pol_entrainment_range(mu: float, forcing_amp: float) -> tuple[float, float]:
    """
Adler entrainment (lock-in) band of a weakly forced van der Pol
oscillator with unit natural frequency: ω ∈ 1 ± F/4 for weak
forcing F on the a = 2 limit cycle.

Rust: `resonance::nonlinear::van_der_pol_entrainment_range`
    """
    ...

def fano_lineshape(omega: float, omega0: float, gamma: float, q: float) -> float:
    """
Fano lineshape (q + ε)²/(1 + ε²), ε = 2(ω − ω₀)/γ (background → 1).

Rust: `resonance::nonlinear::fano_lineshape`
    """
    ...

def fano_fit(omega: list[float], y: list[float]) -> tuple[float, float, float, float]:
    """
Fit A·(q+ε)²/(1+ε²) to data; returns (ω₀, γ, q, A).

Panics:
Panics if the fit fails or fewer than 5 points are supplied.

Rust: `resonance::nonlinear::fano_fit`
    """
    ...

def autoresonance_threshold(alpha: float, sweep_rate: float) -> float:
    """
Autoresonance capture threshold for a swept-drive Duffing-type
oscillator: ε_c = 0.41·(dω/dt)^(3/4)/√|α_nl| (Fajans-Friedland
scaling law).

Rust: `resonance::nonlinear::autoresonance_threshold`
    """
    ...

def frequency_pulling(f0: float, q: float, coupling_detuning: float) -> float:
    """
Resonator frequency pulling by a detuned load:
f = f₀·(1 + Δ/(2Q)).

Rust: `resonance::nonlinear::frequency_pulling`
    """
    ...

def injection_locking_range(f0: float, q: float, injection_ratio: float) -> float:
    """
Adler injection-locking half-range Δf = f₀·ρ/(2Q) for injection
amplitude ratio ρ.

Rust: `resonance::nonlinear::injection_locking_range`
    """
    ...

def stochastic_resonance_snr(a: float, d: float, noise: float, omega: float) -> float:
    """
Weak-signal stochastic-resonance SNR of a bistable well
(McNamara-Wiesenfeld form): √2·(a·ΔU/D²)²·... reduced to the
standard shape SNR ∝ (a²ΔU²/D²)·e^(−ΔU/D), which is maximized at
D = ΔU/2. `omega` enters only beyond the adiabatic limit and is
ignored here.

Rust: `resonance::nonlinear::stochastic_resonance_snr`
    """
    ...

def hysteresis_loop(f_sweep: list[float], response_up: list[float], response_down: list[float]) -> float:
    """
Enclosed area of a swept-response hysteresis loop (trapezoid of
up-sweep minus down-sweep).

Panics:
Panics on mismatched lengths.

Rust: `resonance::nonlinear::hysteresis_loop`
    """
    ...

def harmonic_balance(f: Callable[[float, float, float], float], omega: float, n_harmonics: int, amplitude_guess: float) -> list[complex]:
    """
Generic harmonic balance for x″ + f(x, x′, t) = 0 with f
2π/ω-periodic in t: Newton iteration on the truncated Fourier series
x(t) = c₀ + Σ_k \\[a_k cos kωt + b_k sin kωt\\], collocated at
4·n_harmonics + 2 points. Returns coefficients c_k = a_k − j·b_k
(c₀ real) for k = 0..=n_harmonics.

Panics:
Panics if the Newton solve fails to converge.

Rust: `resonance::nonlinear::harmonic_balance`
    """
    ...

def describing_function(nonlinearity: Callable[[float], float], amplitude: float) -> complex:
    """
Sinusoidal-input describing function of a static nonlinearity:
N(A) = (b₁ + j·a₁)/A from the first Fourier component of
f(A·sin θ).

Rust: `resonance::nonlinear::describing_function`
    """
    ...

def subharmonic_response(alpha: float, beta: float, delta: float, gamma: float, omega: float) -> list[float]:
    """
Steady-state spectral amplitudes of the driven Duffing response at
\\[ω/3, ω/2, ω, 2ω, 3ω\\] — nonzero sub/superharmonic content flags
period-multiplied responses.

Rust: `resonance::nonlinear::subharmonic_response`
    """
    ...
