"""
Structural dynamics: finite-element bars and beams, modal analysis with general (consistent) mass matrices, Rayleigh damping, implicit time integration (Newmark-β, HHT-α), model reduction, response spectra, and experimental modal analysis tools.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from rust_physics_engine.linalg.matrix import Matrix

class ModalModel:
    """
Structural model M·x″ + C·x′ + K·x = F(t) with full matrices.

Rust: `resonance::structural::ModalModel`
    """
    def __init__(self, m: Matrix | Sequence[Sequence[float]], c: Matrix | Sequence[Sequence[float]], k: Matrix | Sequence[Sequence[float]]) -> None: ...
    @staticmethod
    def from_fem_1d_bar(n_elem: int, length: float, area: float, young: float, rho: float) -> ModalModel: ...
    @staticmethod
    def from_fem_beam(n_elem: int, length: float, young: float, i_area: float, rho: float, area: float) -> ModalModel: ...
    @staticmethod
    def from_lumped(masses: list[float], springs: list[tuple[int, int, float]], dampers: list[tuple[int, int, float]]) -> ModalModel: ...
    def rayleigh_damping(self, alpha: float, beta: float) -> None: ...
    def rayleigh_from_ratios(self, zeta1: float, f1: float, zeta2: float, f2: float) -> None: ...
    def modes(self) -> tuple[list[float], Matrix]: ...
    def damped_modes(self) -> list[tuple[complex, list[complex]]]: ...
    def modal_damping_ratios(self) -> list[float]: ...
    def frf(self, i: int, j: int, omega: float) -> complex: ...
    def frf_matrix(self, omega: float) -> Matrix: ...
    def newmark_beta(self, force: Callable[[float], list[float]], x0: list[float], v0: list[float], t_end: float, dt: float, beta: float, gamma: float) -> list[list[float]]: ...
    def hht_alpha(self, force: Callable[[float], list[float]], x0: list[float], v0: list[float], t_end: float, dt: float, alpha: float) -> list[list[float]]: ...
    def modal_truncation(self, n_modes: int) -> ModalModel: ...
    def guyan_reduction(self, master_dofs: list[int]) -> ModalModel: ...
    def response_spectrum(self, ground_accel: list[float], dt: float, zeta: float) -> list[tuple[float, float]]: ...
    @staticmethod
    def mac(phi1: list[float], phi2: list[float]) -> float: ...
    def campbell_diagram(self, rpm_range: tuple[float, float], n: int, orders: list[float]) -> list[tuple[float, list[float]]]: ...
    def critical_speeds(self, orders: list[float]) -> list[float]: ...
    def resonance_margins(self, excitation_freqs: list[float]) -> list[float]: ...
    @property
    def m(self) -> Matrix: ...
    @property
    def c(self) -> Matrix: ...
    @property
    def k(self) -> Matrix: ...

def experimental_modal_peak_picking(frf: list[complex], freqs: list[float]) -> list[tuple[float, float]]:
    """
Peak-picking experimental modal analysis on a receptance FRF:
(natural frequency, damping ratio) per resolved peak via half-power
bandwidths.

Rust: `resonance::structural::experimental_modal_peak_picking`
    """
    ...

def half_power_bandwidth(frf_mag: list[float], freqs: list[float], peak_idx: int) -> float:
    """
Half-power (−3 dB) bandwidth around the FRF magnitude peak at
`peak_idx`, with linear interpolation; 0 when a crossing is missing.

Rust: `resonance::structural::half_power_bandwidth`
    """
    ...

def circle_fit(frf: list[complex], freqs: list[float], window: int) -> tuple[float, float]:
    """
Kasa circle fit of an FRF arc in the Nyquist plane around a
resonance; returns (f₀, ζ) using the angular-sweep-rate maximum for
f₀ and the standard circle-fit damping formula.

Panics:
Panics if fewer than 5 points are given.

Rust: `resonance::structural::circle_fit`
    """
    ...

def operational_deflection_shape(responses: list[list[float]], omega: float, fs: float) -> list[complex]:
    """
Operational deflection shape: the complex amplitude of every
measured channel at frequency ω (single-bin correlation at fs).

Rust: `resonance::structural::operational_deflection_shape`
    """
    ...

def stochastic_subspace_identification(outputs: list[list[float]], fs: float, order: int) -> list[tuple[float, float]]:
    """
Covariance-driven stochastic subspace identification: output-only
modal frequencies and damping ratios from response channels sampled
at fs. `order` is the state dimension (≥ 2 per expected mode).

Panics:
Panics if the SVD or eigen machinery fails, or the data is shorter
than 4·order.

Rust: `resonance::structural::stochastic_subspace_identification`
    """
    ...

def shock_response_spectrum(accel: list[float], dt: float, freqs: list[float], zeta: float) -> list[float]:
    """
Shock response spectrum: peak absolute SDOF displacement response at
each requested natural frequency (Hz) for a base acceleration pulse.

Rust: `resonance::structural::shock_response_spectrum`
    """
    ...
