"""
Random matrix theory: the classical ensembles, their limiting spectral laws, and the local statistics that distinguish correlated spectra from uncorrelated ones.  The subject rests on a surprise: the eigenvalues of a large random matrix are not themselves random in any useful sense. Their *density* converges to a fixed shape that does not depend on the distribution of the entries -- Wigner's semicircle for a symmetric matrix, Marchenko-Pastur for a sample covariance -- and their *spacings* converge to a distribution that depends only on the symmetry class. Universality is what makes the subject applicable: a spectrum can be compared against these laws without knowing anything about the mechanism that produced it.  The practical payoff is a null hypothesis. Eigenvalues of independent variables repel each other, in a way that independent *points* do not, so the spacing distribution separates a spectrum with genuine level correlations from a Poisson process of unrelated levels. In finance the same statement is a filter: any eigenvalue of a sample correlation matrix that falls inside the Marchenko-Pastur band is consistent with pure noise and carries no information about the correlations being estimated.  Two conventions are fixed throughout. Ensembles are scaled so their limiting support stays put as `n` grows -- otherwise the semicircle's radius would drift and nothing would converge to compare against. And spacings are always measured on *unfolded* eigenvalues, rescaled to unit mean density, since the raw spacings of a semicircular spectrum are much tighter in the middle than at the edges and their distribution would say more about the density than about the correlations.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.linalg.matrix import Matrix
from numeria.statistics.distributions import Poisson
from numeria.monte_carlo import Rng

def goe_sample(n: int, rng: Rng) -> Matrix:
    """
A sample from the Gaussian orthogonal ensemble: a symmetric matrix whose
entries are Gaussian, independent up to the symmetry constraint.

Scaled so the spectrum fills `[-2, 2]` in the large-`n` limit: off-diagonal
entries have variance `1/n` and diagonal entries `2/n`. The factor of two
on the diagonal is not decorative -- it is what makes the distribution
invariant under orthogonal conjugation, which is the defining property of
the ensemble and the reason its spectral statistics are universal.

Panics:
Panics if `n` is zero.

Rust: `stochastic::rmt::goe_sample`
    """
    ...

def gue_sample(n: int, rng: Rng) -> tuple[Matrix, Matrix]:
    """
A sample from the Gaussian unitary ensemble, returned as
`(real part, imaginary part)` of a Hermitian matrix.

The real part is symmetric and the imaginary part antisymmetric with a
zero diagonal, which together is what "Hermitian" means for a matrix held
in two real halves. Scaled to the same `[-2, 2]` support as
`goe_sample`: each independent real degree of freedom carries variance
`1/(2n)`, so `E|H_ij|^2 = 1/n` off the diagonal.

Panics:
Panics if `n` is zero.

Rust: `stochastic::rmt::gue_sample`
    """
    ...

def ginibre_sample(n: int, rng: Rng) -> Matrix:
    """
A sample from the Ginibre ensemble: every entry independent Gaussian, with
no symmetry imposed at all.

Its eigenvalues are complex and fill the unit disc rather than an
interval, which is the point of the ensemble -- non-normality changes the
spectral picture completely.

Panics:
Panics if `n` is zero.

Rust: `stochastic::rmt::ginibre_sample`
    """
    ...

def wishart_sample(n: int, p: int, rng: Rng) -> Matrix:
    """
A sample covariance matrix built from `p` independent variables observed
`n` times, each observation standard Gaussian.

Returns `X' X / n` where `X` is `n` by `p`, so the population covariance
is the identity and every departure from it in the sample is estimation
noise. That noise is exactly what `marchenko_pastur` describes.

Panics:
Panics if either dimension is zero.

Rust: `stochastic::rmt::wishart_sample`
    """
    ...

def wigner_semicircle(x: float, r: float) -> float:
    """
Wigner's semicircle density on `[-r, r]`.

`f(x) = 2 sqrt(r^2 - x^2) / (pi r^2)`, zero outside. The limiting
eigenvalue density of a symmetric random matrix, whatever the entry
distribution, provided the entries are independent with finite variance --
the first and simplest statement of universality in the subject.

Panics:
Panics unless `r` is positive.

Rust: `stochastic::rmt::wigner_semicircle`
    """
    ...

def marchenko_pastur(x: float, ratio: float, sigma2: float) -> float:
    """
The Marchenko-Pastur density for a sample covariance matrix.

`ratio` is `p / n`, the number of variables over the number of
observations, and `sigma2` the population variance. Support is
`[sigma2 (1 -+ sqrt(ratio))^2]`; the density there is
`sqrt((b - x)(x - a)) / (2 pi ratio sigma2 x)`.

This is the shape a covariance matrix of *independent* variables takes.
The width of the band is the whole point: at `ratio = 0.5` the sample
eigenvalues spread over roughly `[0.09, 2.9]` even though every population
eigenvalue is exactly 1.

The point mass at zero when `ratio > 1` (more variables than
observations, so the matrix is singular) is not part of the density and is
not reported here.

Panics:
Panics unless `ratio` and `sigma2` are positive.

Rust: `stochastic::rmt::marchenko_pastur`
    """
    ...

def mp_edges(ratio: float, sigma2: float) -> tuple[float, float]:
    """
The two edges of the Marchenko-Pastur support,
`sigma2 (1 -+ sqrt(ratio))^2`.

Any sample eigenvalue between these is consistent with pure noise.

Panics:
Panics unless `ratio` and `sigma2` are positive.

Rust: `stochastic::rmt::mp_edges`
    """
    ...

def eigenvalue_spacing_distribution(eigs: list[float]) -> list[float]:
    """
Gaps between consecutive eigenvalues after unfolding to unit mean density.

Unfolding is not a cosmetic step. The raw gaps of a semicircular spectrum
are far tighter near zero than near the edges, so their distribution would
mostly reflect that varying density rather than the correlations between
levels. Mapping each eigenvalue through a smooth estimate of its own
cumulative count removes the density and leaves the local statistics,
which is what the surmises below describe.

The smooth estimate here is the empirical staircase itself, smoothed by
averaging over a window that grows as the square root of the sample -- the
standard compromise between following the density and following the
fluctuations one is trying to measure.

Returns `eigs.len() - 1` gaps with mean 1. An empty or single-element
input gives an empty result.

Rust: `stochastic::rmt::eigenvalue_spacing_distribution`
    """
    ...

def wigner_surmise_goe(s: float) -> float:
    """
Wigner's surmise for the orthogonal class:
`(pi/2) s exp(-pi s^2 / 4)`.

The spacing distribution of a two-by-two GOE matrix, which turns out to
approximate the large-`n` answer to within a percent. Its defining feature
is the linear vanishing at `s = 0`: eigenvalues of a real symmetric random
matrix repel, so exact degeneracies have probability zero and near ones
are rare.

Rust: `stochastic::rmt::wigner_surmise_goe`
    """
    ...

def wigner_surmise_gue(s: float) -> float:
    """
Wigner's surmise for the unitary class:
`(32 / pi^2) s^2 exp(-4 s^2 / pi)`.

The repulsion is quadratic rather than linear -- a complex Hermitian
matrix has twice as many degrees of freedom to tune away from a
degeneracy, so near-degeneracies are suppressed harder than in the
orthogonal class.

Rust: `stochastic::rmt::wigner_surmise_gue`
    """
    ...

def poisson_spacing(s: float) -> float:
    """
The spacing density of uncorrelated levels: `exp(-s)`.

A Poisson process of points has no repulsion at all, so its density is
maximal at zero. This is the null the surmises above are contrasted
against, and the contrast at small `s` is the whole diagnostic.

Rust: `stochastic::rmt::poisson_spacing`
    """
    ...

def spectral_rigidity(eigs: list[float], l: float) -> float:
    """
The spectral rigidity `Delta_3(L)`: the mean-square deviation of the
unfolded counting function from the best straight line over a window of
length `L`.

Where the spacing distribution measures correlations between *neighbours*,
rigidity measures them over a stretch of `L` levels, and it is the more
discriminating of the two. Uncorrelated levels give `L / 15`, growing
linearly; a correlated spectrum gives roughly `ln(L) / pi^2`, growing so
slowly that at `L = 20` the two differ by an order of magnitude.

Averaged over windows starting across the spectrum.

Panics:
Panics unless `l` is positive.

Rust: `stochastic::rmt::spectral_rigidity`
    """
    ...

def tracy_widom_beta1_approx(x: float) -> float:
    """
An approximation to the Tracy-Widom distribution function for the
orthogonal class, the law of the largest eigenvalue after edge scaling.

Represented as a shifted gamma matched to the first three cumulants of
`TW_1` (mean `-1.2065`, variance `1.6078`, skewness `0.2935`), which is the
standard closed-form stand-in: exact evaluation needs the Hastings-McLeod
solution of Painleve II. Accurate to a few parts in a thousand through the
body, degrading in the far tails, where the true law decays like
`exp(-|x|^3/24)` on the left and `exp(-(2/3) x^{3/2})` on the right.

The distribution matters because the largest eigenvalue does not
fluctuate on the scale of the spectrum: it sits within `n^{-2/3}` of the
edge, so a spike only a little above the Marchenko-Pastur edge is still
strong evidence of real signal.

Rust: `stochastic::rmt::tracy_widom_beta1_approx`
    """
    ...

def participation_ratio(vec: list[float]) -> float:
    """
The inverse participation ratio of a vector: `sum v_i^4 / (sum v_i^2)^2`.

A measure of how many components carry the weight. A vector concentrated
on one component scores 1; one spread evenly over `n` scores `1/n`. For
eigenvectors it separates localised states from extended ones, and a GOE
eigenvector -- uniform on the sphere -- sits at `3/n`, the extra factor
being the fourth moment of a Gaussian.

Returns zero for a zero vector.

Rust: `stochastic::rmt::participation_ratio`
    """
    ...

def level_spacing_ratio(eigs: list[float]) -> float:
    """
The mean ratio of consecutive level spacings,
`<min(s_k, s_{k+1}) / max(s_k, s_{k+1})>`.

The great virtue of this statistic is that it needs no unfolding: a ratio
of adjacent gaps is insensitive to the local density, which cancels. That
removes the one genuinely arbitrary step in spacing analysis. The limiting
values are 0.5307 for the orthogonal class, 0.5996 for the unitary, and
`2 ln 2 - 1 = 0.3863` for uncorrelated levels.

Returns zero for fewer than three eigenvalues.

Rust: `stochastic::rmt::level_spacing_ratio`
    """
    ...

def correlation_matrix_denoise_mp(corr: Matrix | Sequence[Sequence[float]], t_over_n: float) -> Matrix:
    """
Cleans a sample correlation matrix by replacing every eigenvalue inside
the Marchenko-Pastur band with their common average.

`t_over_n` is the number of observations divided by the number of
variables, so the band is set by `ratio = 1 / t_over_n`. Eigenvalues below
the upper edge are indistinguishable from the noise a correlation matrix
of independent variables would produce, and estimating each of them
separately fits that noise. Replacing them by their mean keeps the trace
-- so the cleaned matrix still has unit diagonal on average and remains a
correlation matrix -- while discarding the structure that was not there.

The eigenvalues above the edge, and their eigenvectors, are left alone.

Errors:
Returns an error if the matrix is not square and symmetric, if `t_over_n`
is not positive, or if the eigen-decomposition fails to converge.

Rust: `stochastic::rmt::correlation_matrix_denoise_mp`
    """
    ...

def symmetric_spectrum(a: Matrix | Sequence[Sequence[float]]) -> list[float]:
    """
The eigenvalues of a symmetric matrix, sorted ascending.

A convenience over `eigen_symmetric` for the spectral statistics above,
which never need the eigenvectors.

Errors:
Returns an error if the matrix is not symmetric or the solver fails.

Rust: `stochastic::rmt::symmetric_spectrum`
    """
    ...

def hermitian_spectrum(re: Matrix | Sequence[Sequence[float]], im: Matrix | Sequence[Sequence[float]]) -> list[float]:
    """
The eigenvalues of a Hermitian matrix held as `(real, imaginary)` parts.

Uses the standard real embedding: the `2n`-by-`2n` real symmetric matrix
`[[Re, -Im], [Im, Re]]` has exactly the eigenvalues of `H`, each appearing
twice. Returns the `n` distinct ones by taking every second value of the
sorted `2n`, which is what lets a real symmetric solver handle the unitary
ensemble without any complex arithmetic.

Errors:
Returns an error if the two halves disagree in shape or the solver fails.

Rust: `stochastic::rmt::hermitian_spectrum`
    """
    ...
