"""
Time series analysis: correlation structure, stationarity, ARMA models, smoothing, volatility, and change detection.  A time series differs from a sample only in that the order matters, and every tool here is a way of asking how much it matters. The autocorrelation function measures it directly; the partial autocorrelation strips out what is already explained by the lags in between; the spectral density says the same thing in the frequency domain. An ARMA model is a compact parameterisation of that structure, and its impulse-response weights are the bridge between the two views -- they generate the autocovariances, the forecast error variances, and the spectral density alike.  Stationarity is the assumption the whole apparatus rests on, so it is tested rather than assumed. The augmented Dickey-Fuller test takes a unit root as the null and looks for evidence against it; the KPSS test takes stationarity as the null and looks for evidence against *that*. They are deliberately opposed: agreeing on a rejection is much stronger evidence than either alone, and disagreement is a signal that the series is neither cleanly one nor the other.  The p-values for both come from tabulated quantiles of their non-standard null distributions, interpolated. Neither statistic is asymptotically normal or chi-squared -- a Dickey-Fuller `t`-ratio is not a `t` at all -- so a p-value computed from a standard distribution would be wrong rather than approximate. The tables are documented where they are used.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.linalg.matrix import Matrix
from numeria.monte_carlo import Rng
from numeria.statistics.inference import TestResult

class Arima:
    """
An ARIMA model: an `Arma` fitted to the `d`-th difference.

Rust: `stochastic::timeseries::Arima`
    """
    @staticmethod
    def fit(x: list[float], p: int, d: int, q: int) -> Arima: ...
    def forecast(self, h: int) -> tuple[list[float], list[float]]: ...
    @property
    def d(self) -> int: ...
    @property
    def arma(self) -> Arma: ...
    @property
    def initial(self) -> list[float]: ...

class Arma:
    """
An autoregressive moving-average model.

The process is written around its mean:
`(x_t - mu) = sum_i phi_i (x_{t-i} - mu) + e_t + sum_j theta_j e_{t-j}`,
with `e_t` white noise of variance `sigma2`. The sign convention on the
moving-average side is the additive one, matching the Box-Jenkins form.

Rust: `stochastic::timeseries::Arma`
    """
    def __init__(self, ar: list[float], ma: list[float], sigma2: float, mean: float) -> None: ...
    def p(self) -> int: ...
    def q(self) -> int: ...
    def residuals(self, x: list[float]) -> list[float]: ...
    @staticmethod
    def fit_css(x: list[float], p: int, q: int) -> Arma: ...
    @staticmethod
    def fit_hannan_rissanen(x: list[float], p: int, q: int) -> Arma: ...
    def simulate(self, n: int, rng: Rng) -> list[float]: ...
    def impulse_response(self, n: int) -> list[float]: ...
    def spectral_density(self, freqs: list[float]) -> list[float]: ...
    def roots_check(self) -> tuple[bool, bool]: ...
    def log_likelihood(self, x: list[float]) -> float: ...
    def n_params(self) -> int: ...
    def aic(self, x: list[float]) -> float: ...
    def bic(self, x: list[float]) -> float: ...
    def forecast(self, x: list[float], h: int) -> tuple[list[float], list[float]]: ...
    @property
    def ar(self) -> list[float]: ...
    @property
    def ma(self) -> list[float]: ...
    @property
    def sigma2(self) -> float: ...
    @property
    def mean(self) -> float: ...

class Garch11:
    """
A GARCH(1,1) volatility model:
`sigma_t^2 = omega + alpha r_{t-1}^2 + beta sigma_{t-1}^2`.

The single most used model in the family, because two parameters are
enough to reproduce the two features that matter: volatility clusters, and
it mean-reverts. `alpha + beta` is the persistence, and the model is
stationary only while that sum is below one.

Rust: `stochastic::timeseries::Garch11`
    """
    def __init__(self, omega: float, alpha: float, beta: float) -> None: ...
    def persistence(self) -> float: ...
    def unconditional_variance(self) -> float: ...
    def conditional_variance(self, returns: list[float]) -> list[float]: ...
    @staticmethod
    def fit(returns: list[float]) -> Garch11: ...
    def simulate(self, n: int, rng: Rng) -> list[float]: ...
    def forecast_variance(self, returns: list[float], h: int) -> list[float]: ...
    @property
    def omega(self) -> float: ...
    @property
    def alpha(self) -> float: ...
    @property
    def beta(self) -> float: ...

class HwState:
    """
The smoothing state left behind by `holt_winters`, enough to continue
the recursion or to forecast forward.

Rust: `stochastic::timeseries::HwState`
    """
    def __init__(self, level: float, trend: float, seasonal: list[float], multiplicative: bool) -> None: ...
    def forecast(self, h: int) -> list[float]: ...
    @property
    def level(self) -> float: ...
    @property
    def trend(self) -> float: ...
    @property
    def seasonal(self) -> list[float]: ...
    @property
    def multiplicative(self) -> bool: ...

class Sarima:
    """
A seasonal ARIMA model, `(p, d, q) x (P, D, Q)_s`.

Fitted by applying the seasonal difference `D` times and the ordinary
difference `d` times, then estimating the non-seasonal and seasonal
polynomials on the doubly differenced series. The seasonal part is modelled
as an ARMA in lags that are multiples of `s`.

Rust: `stochastic::timeseries::Sarima`
    """
    @staticmethod
    def fit(x: list[float], p: int, d: int, q: int, seasonal_p: int, seasonal_d: int, seasonal_q: int, s: int) -> Sarima: ...
    def forecast(self, h: int) -> list[float]: ...
    @property
    def d(self) -> int: ...
    @property
    def seasonal_d(self) -> int: ...
    @property
    def s(self) -> int: ...
    @property
    def arma(self) -> Arma: ...

class Var:
    """
A vector autoregression: each series regressed on `p` lags of every series.

Rust: `stochastic::timeseries::Var`
    """
    def k(self) -> int: ...
    def p(self) -> int: ...
    @staticmethod
    def fit(data: list[list[float]], p: int) -> Var: ...
    def forecast(self, data: list[list[float]], h: int) -> list[list[float]]: ...
    def impulse_response(self, h: int) -> list[Matrix]: ...
    def granger_matrix(self, data: list[list[float]]) -> Matrix: ...
    @property
    def coeffs(self) -> list[Matrix]: ...
    @property
    def intercept(self) -> list[float]: ...

def acf(x: list[float], max_lag: int) -> list[float]:
    """
Sample autocorrelation at lags `0..=max_lag`.

Uses the divide-by-`n` estimator rather than dividing each lag by its own
count. That biases individual lags toward zero, but it is the choice that
makes the resulting sequence positive semi-definite, which is what lets
`pacf` and the Yule-Walker equations be solved at all. The
divide-by-`n-k` version can produce a sequence no stationary process
possesses, and Durbin-Levinson then divides by a negative variance.

Element 0 is 1 by construction.

Panics:
Panics unless the series has at least two points and `max_lag < n`.

Rust: `stochastic::timeseries::acf`
    """
    ...

def pacf(x: list[float], max_lag: int) -> list[float]:
    """
Sample partial autocorrelation at lags `0..=max_lag`, by the
Durbin-Levinson recursion.

The partial autocorrelation at lag `k` is the correlation between `x_t`
and `x_{t-k}` once the intervening lags are projected out -- equivalently,
the last coefficient of the best linear predictor of order `k`. For an
AR(p) process it is exactly zero beyond lag `p`, which is what makes it
the tool for choosing `p`.

Element 0 is 1, matching `acf`.

Panics:
Panics under the same conditions as `acf`.

Rust: `stochastic::timeseries::pacf`
    """
    ...

def cross_correlation_lags(x: list[float], y: list[float], max_lag: int) -> list[float]:
    """
Cross-correlation of `x` and `y` at lags `-max_lag..=max_lag`.

Element `max_lag + k` is the correlation between `x_t` and `y_{t+k}`, so a
peak at positive `k` means `x` leads `y` by `k` steps.

Panics:
Panics unless both series have the same length, at least two points, and
`max_lag < n`.

Rust: `stochastic::timeseries::cross_correlation_lags`
    """
    ...

def ljung_box(x: list[float], lags: int) -> TestResult:
    """
The Ljung-Box portmanteau test for autocorrelation up to lag `lags`.

`Q = n(n+2) sum_{k=1}^{h} r_k^2 / (n-k)`, which is asymptotically
chi-squared on `h` degrees of freedom under the null that the series is
uncorrelated. A small p-value says the series has structure a white-noise
model would not produce.

Panics:
Panics unless `lags >= 1` and `lags < n`.

Rust: `stochastic::timeseries::ljung_box`
    """
    ...

def difference(x: list[float], d: int) -> list[float]:
    """
The `d`-th successive difference of `x`, shortening it by `d`.

Panics:
Panics if `d >= x.len()`.

Rust: `stochastic::timeseries::difference`
    """
    ...

def seasonal_difference(x: list[float], s: int) -> list[float]:
    """
The seasonal difference `x_t - x_{t-s}`, shortening the series by `s`.

Panics:
Panics unless `1 <= s < x.len()`.

Rust: `stochastic::timeseries::seasonal_difference`
    """
    ...

def undifference(diffed: list[float], initial: list[float]) -> list[float]:
    """
Rebuilds a series from its differences.

`initial` holds the first element of each successive difference, lowest
order first: `initial[j]` is `difference(x, j)[0]`, so `initial[0]` is
`x[0]`. Its length sets the differencing order being undone. Exactly
inverts `difference`.

Panics:
Panics if `initial` is empty.

Rust: `stochastic::timeseries::undifference`
    """
    ...

def adf_test(x: list[float], lags: int) -> TestResult:
    """
The augmented Dickey-Fuller test for a unit root, with a constant and no
trend.

Regresses `dy_t` on `y_{t-1}`, a constant, and `lags` lagged differences;
the statistic is the `t`-ratio on the `y_{t-1}` coefficient. The null is
that a unit root is present, so a *small* p-value is evidence the series
is stationary. `df` reports the residual degrees of freedom.

The p-value is interpolated from the module's table of Dickey-Fuller
quantiles; see the note on that table for why a `t` distribution would be
the wrong reference.

Errors:
Returns an error if the series is too short for the requested lag order or
the regression is rank deficient.

Rust: `stochastic::timeseries::adf_test`
    """
    ...

def kpss_test(x: list[float]) -> TestResult:
    """
The KPSS test for level stationarity.

The statistic is `sum_t S_t^2 / (n^2 s^2(l))`, where `S_t` is the partial
sum of deviations from the mean and `s^2(l)` is a Newey-West long-run
variance with the usual `l = floor(4 (n/100)^{1/4})` bandwidth. Here
stationarity is the *null*, so a small p-value is evidence against it --
the opposite polarity to `adf_test`, which is the point of running both.

`df` is reported as the bandwidth actually used.

Errors:
Returns an error for a series shorter than four points or one with no
variation at all.

Rust: `stochastic::timeseries::kpss_test`
    """
    ...

def auto_arima(x: list[float], max_p: int, max_d: int, max_q: int) -> Arima:
    """
Selects `(p, d, q)` by minimising AIC over a grid, choosing `d` by
differencing until an augmented Dickey-Fuller test rejects a unit root.

Differencing order is settled first and separately, because AIC cannot
compare across it: differencing changes the data the likelihood is
computed on, so the numbers are not on the same scale.

Errors:
Returns an error if no candidate model in the grid can be fitted.

Rust: `stochastic::timeseries::auto_arima`
    """
    ...

def exponential_smoothing(x: list[float], alpha: float) -> list[float]:
    """
Simple exponential smoothing: `s_t = alpha x_t + (1 - alpha) s_{t-1}`,
seeded at `x_0`.

The smoothed value is a geometrically weighted average of the whole past,
and the weights sum to one, so a constant series is reproduced exactly at
any `alpha`.

Panics:
Panics unless `x` is non-empty and `alpha` is in `[0, 1]`.

Rust: `stochastic::timeseries::exponential_smoothing`
    """
    ...

def double_exponential(x: list[float], alpha: float, beta: float) -> list[float]:
    """
Holt's linear method: a smoothed level and a smoothed slope.

Element `t` of the result is the one-step-ahead prediction of `x[t]`, made
from the state after seeing `x[t-1]` -- the same convention as
`holt_winters`. Unlike simple smoothing this tracks a linear trend
without lagging behind it.

The state is seeded one step *before* the data: the slope from the first
two points, and a level back-extrapolated so that `level + trend` equals
`x[0]`. Seeding the level at `x[0]` itself, as is often done, puts the
state half a step ahead of where the recursion expects it and leaves a
transient that takes tens of observations to decay -- on an exact straight
line, which the method should reproduce perfectly from the first step.

Panics:
Panics unless `x` has at least two points and both parameters lie in
`[0, 1]`.

Rust: `stochastic::timeseries::double_exponential`
    """
    ...

def holt_winters(x: list[float], alpha: float, beta: float, gamma: float, season_len: int, multiplicative: bool) -> tuple[list[float], HwState]:
    """
Holt-Winters triple exponential smoothing.

Tracks a level, a slope, and a set of seasonal factors, each updated by
its own smoothing constant. Returns the one-step-ahead fitted values
alongside the final state.

The seasonal factors are initialised from the first complete season and,
in the additive case, centred so they sum to zero -- otherwise the level
and the seasonal component are not separately identified and the pair can
drift apart while their sum stays right.

Panics:
Panics unless the series covers at least two full seasons, `season_len` is
at least 2, and all three parameters lie in `[0, 1]`.

Rust: `stochastic::timeseries::holt_winters`
    """
    ...

def holt_winters_optimize(x: list[float], season_len: int) -> tuple[float, float, float]:
    """
Chooses `(alpha, beta, gamma)` by minimising the one-step-ahead sum of
squared errors over a coarse grid followed by a local refinement.

A grid rather than a gradient method: the Holt-Winters error surface is
not convex in the three constants and has flat regions near the corners of
the unit cube, where a local method started badly will simply stop.

Panics:
Panics under the same conditions as `holt_winters`.

Rust: `stochastic::timeseries::holt_winters_optimize`
    """
    ...

def ewma_variance(returns: list[float], lambda_: float) -> list[float]:
    """
The RiskMetrics exponentially weighted variance,
`v_t = lambda v_{t-1} + (1 - lambda) r_{t-1}^2`.

A GARCH(1,1) with `omega = 0` and unit persistence: no mean reversion, so
the variance wanders rather than settling.

Panics:
Panics unless `returns` is non-empty and `lambda` lies in `[0, 1)`.

Rust: `stochastic::timeseries::ewma_variance`
    """
    ...

def arch_lm_test(returns: list[float], lags: int) -> TestResult:
    """
Engle's ARCH LM test for conditional heteroskedasticity.

Regresses squared returns on their own lags; the statistic `n R^2` is
asymptotically chi-squared on `lags` degrees of freedom under the null of
no ARCH effect. A small p-value says the size of a return predicts the
size of the next one, which is precisely what a GARCH model is for.

Errors:
Returns an error if the series is too short or the regression is
degenerate.

Rust: `stochastic::timeseries::arch_lm_test`
    """
    ...

def granger_causality(x: list[float], y: list[float], lags: int) -> TestResult:
    """
Tests whether `x` Granger-causes `y`: whether past `x` improves a forecast
of `y` that already uses past `y`.

An `F` test of the restricted regression of `y` on its own lags against
the unrestricted one that adds the lags of `x`. The name is a term of art
-- it is predictive precedence, not causation, and a common driver of both
series will produce it.

Errors:
Returns an error if the series differ in length, are too short, or either
regression is degenerate.

Rust: `stochastic::timeseries::granger_causality`
    """
    ...

def cointegration_engle_granger(x: list[float], y: list[float]) -> TestResult:
    """
The Engle-Granger two-step test for cointegration between `x` and `y`.

Regresses `y` on `x` with an intercept, then tests the residual for a unit
root. Rejecting means some linear combination of two individually
non-stationary series is stationary -- they share a stochastic trend.

The p-value comes from the module's Engle-Granger table rather than its
plain Dickey-Fuller one: the residual is fitted rather than observed, and the
regression has already worked to make it look stationary, so the null
distribution sits further left. Using the ordinary table here is a common
way to find cointegration that is not there.

Errors:
Returns an error if the series differ in length, are too short, or the
first-stage regression is degenerate.

Rust: `stochastic::timeseries::cointegration_engle_granger`
    """
    ...

def seasonal_decompose_stl_lite(x: list[float], period: int) -> tuple[list[float], list[float], list[float]]:
    """
Additive seasonal decomposition into `(trend, seasonal, residual)`.

The trend is a centred moving average over one full period; the seasonal
component is the average detrended value at each phase, centred to sum to
zero; the residual is whatever is left. Near the ends, where the moving
average has no window, the trend is held at the nearest value it does
have -- so the three components add back to the input exactly at every
index, which is the property that makes the decomposition usable rather
than merely indicative.

Panics:
Panics unless `period >= 2` and the series covers at least two periods.

Rust: `stochastic::timeseries::seasonal_decompose_stl_lite`
    """
    ...

def changepoint_pelt(x: list[float], penalty: float) -> list[int]:
    """
Change-in-mean detection by PELT (pruned exact linear time).

Finds the segmentation minimising the total within-segment sum of squares
plus `penalty` per changepoint. Unlike binary segmentation this is exact:
dynamic programming considers every segmentation, and the pruning step
discards only candidates that provably cannot start an optimal segment,
so the answer is the global optimum rather than a greedy approximation.

Returns the interior changepoint indices, each the first index of a new
segment, in increasing order.

Panics:
Panics if `penalty` is negative.

Rust: `stochastic::timeseries::changepoint_pelt`
    """
    ...

def changepoint_binary_segmentation(x: list[float], max_k: int) -> list[int]:
    """
Change-in-mean detection by recursive binary segmentation.

Splits at the point giving the largest reduction in sum of squares, then
recurses into both halves, stopping at `max_k` changepoints. Greedy rather
than exact -- it can miss a pair of changes whose individual effects
cancel -- but it is fast and needs no penalty to be chosen.

Returns changepoint indices in increasing order.

Rust: `stochastic::timeseries::changepoint_binary_segmentation`
    """
    ...

def cusum(x: list[float], target: float, k: float) -> tuple[list[float], list[float]]:
    """
Two-sided cumulative sum control statistics, `(upper, lower)`.

`S+_t = max(0, S+_{t-1} + (x_t - target) - k)` and the mirror image for
the lower arm. The slack `k` is what stops the statistic drifting on
ordinary noise: with `k` set to half the shift worth detecting, the
statistic stays near zero while the process is on target and climbs
roughly linearly once it is not.

Panics:
Panics if `k` is negative.

Rust: `stochastic::timeseries::cusum`
    """
    ...

def matrix_profile_lite(x: list[float], m: int) -> tuple[list[float], list[int]]:
    """
The matrix profile of `x` for subsequences of length `m`:
`(distance to the nearest other subsequence, its index)`.

Distances are z-normalised Euclidean, so a match is about shape rather
than level or amplitude. Overlapping neighbours are excluded -- a
subsequence's closest match is always the one shifted by one sample, which
says nothing -- using the usual exclusion zone of half the window.

The smallest entries locate the repeated motifs; the largest locates the
discord, the least-like-anything-else stretch.

Panics:
Panics unless `m >= 2` and the series holds at least two non-overlapping
windows.

Rust: `stochastic::timeseries::matrix_profile_lite`
    """
    ...

def sample_entropy(x: list[float], m: int, tol: float) -> float:
    """
Sample entropy: the negative log probability that two sequences matching
for `m` points go on matching for `m + 1`.

`tol` is given as a multiple of the series standard deviation. Unlike
`approximate_entropy` the self-match is excluded, which removes the bias
that otherwise makes a short series look more regular than it is.

Returns infinity when no `m+1`-length match occurs at all, which is the
honest answer -- the estimator has run out of data rather than found zero
probability.

Panics:
Panics unless `m >= 1`, `tol > 0`, and the series holds at least `m + 2`
points.

Rust: `stochastic::timeseries::sample_entropy`
    """
    ...

def approximate_entropy(x: list[float], m: int, tol: float) -> float:
    """
Approximate entropy, the older cousin of `sample_entropy`.

Includes the self-match, which guarantees the logarithm is defined but
biases the estimate toward regularity, the more so the shorter the series.
Kept because it is what a great deal of published work reports.

Panics:
Panics under the same conditions as `sample_entropy`.

Rust: `stochastic::timeseries::approximate_entropy`
    """
    ...

def permutation_entropy(x: list[float], order: int, delay: int) -> float:
    """
Permutation entropy: the Shannon entropy of the ordinal patterns of length
`order` sampled at spacing `delay`, normalised to `[0, 1]`.

Only the ranking within each window matters, so the measure is invariant
to any monotone transformation of the series and needs no tolerance
parameter. A monotone series visits one pattern and scores 0; independent
noise visits all `order!` patterns equally and scores 1.

Panics:
Panics unless `order` is between 2 and 8, `delay >= 1`, and the series is
long enough to hold at least two windows.

Rust: `stochastic::timeseries::permutation_entropy`
    """
    ...

def surrogate_test_iaaft(x: list[float], statistic: Callable[[list[float]], float], n_surrogates: int, rng: Rng) -> float:
    """
A surrogate-data test: how extreme `statistic(x)` is against the
distribution it takes on IAAFT surrogates of `x`.

The surrogates share the series' amplitude distribution and power
spectrum, hence all of its linear structure. Rejecting therefore points at
something a linear Gaussian process could not produce -- nonlinearity --
rather than merely at "not white noise", which is what a test against
shuffled data would show.

Returns the two-sided rank p-value `(1 + #{|s_i - mean| >= |s_x - mean|}) /
(1 + n)`, which is exact for finite `n` rather than asymptotic.

Panics:
Panics if `n_surrogates` is zero or the series is shorter than four points.

Rust: `stochastic::timeseries::surrogate_test_iaaft`
    """
    ...

def state_space_local_level(x: list[float]) -> tuple[list[float], float, float]:
    """
The local level model: `x_t = mu_t + e_t`, `mu_t = mu_{t-1} + n_t`.

Returns `(smoothed level, signal variance, observation variance)`. The two
variances are estimated by maximising the Gaussian likelihood from the
Kalman filter; only their ratio -- the signal-to-noise ratio, or hyper-
parameter `q` -- affects the filtered path, so it is that ratio the
optimiser searches over, with the overall scale then available in closed
form.

The model is the state-space form of simple exponential smoothing: the
steady-state Kalman gain *is* the smoothing constant, so an estimated `q`
and an estimated `alpha` carry the same information.

Errors:
Returns an error for a series shorter than five points or with no
variation.

Rust: `stochastic::timeseries::state_space_local_level`
    """
    ...
