"""
Impacts, mergers, and collision probability.  Impact geometry and speed (including the gravitational focusing that makes the impact speed at least the escape velocity, however slowly the bodies approach), perfectly inelastic merger of mass and momentum, and the energy released.  Crater scaling and the collision probability for objects sharing a volume of space follow, along with the debris-flux relations used for orbital collision risk.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.math import Vec3

class CollisionKind:
    """

Rust: `astrophysics::collisions::CollisionKind`
    """
    ...

class CollisionResult:
    """

Rust: `astrophysics::collisions::CollisionResult`
    """
    def __init__(self, kind: CollisionKind, merged_mass: float, merged_velocity: Vec3 | Sequence[float], merged_radius: float, temperature_increase: float, debris: DebrisParams) -> None: ...
    @property
    def kind(self) -> CollisionKind: ...
    @property
    def merged_mass(self) -> float: ...
    @property
    def merged_velocity(self) -> Vec3: ...
    @property
    def merged_radius(self) -> float: ...
    @property
    def temperature_increase(self) -> float: ...
    @property
    def debris(self) -> DebrisParams: ...

class DebrisParams:
    """

Rust: `astrophysics::collisions::DebrisParams`
    """
    def __init__(self, count: int, speed_factor: float, mass_fraction: float, base_temperature: float) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def speed_factor(self) -> float: ...
    @property
    def mass_fraction(self) -> float: ...
    @property
    def base_temperature(self) -> float: ...

def impact_angle(pos1: Vec3 | Sequence[float], vel1: Vec3 | Sequence[float], pos2: Vec3 | Sequence[float], vel2: Vec3 | Sequence[float]) -> float:
    """
Computes the impact angle between two colliding bodies: θ = acos(v_radial / |v_rel|).

Rust: `astrophysics::collisions::impact_angle`
    """
    ...

def impact_speed(vel1: Vec3 | Sequence[float], vel2: Vec3 | Sequence[float]) -> float:
    """
Computes the relative impact speed between two bodies: |v1 - v2|.

Rust: `astrophysics::collisions::impact_speed`
    """
    ...

def merge_velocity(m1: float, v1: Vec3 | Sequence[float], m2: float, v2: Vec3 | Sequence[float]) -> Vec3:
    """
Computes the post-merger velocity via conservation of momentum: v_cm = (m1 v1 + m2 v2) / (m1 + m2).

Rust: `astrophysics::collisions::merge_velocity`
    """
    ...

def merge_radius(r1: float, r2: float) -> float:
    """
Computes the merged body radius assuming volume conservation: r = (r1³ + r2³)^(1/3).

Rust: `astrophysics::collisions::merge_radius`
    """
    ...

def collision_energy(m1: float, v1: Vec3 | Sequence[float], m2: float, v2: Vec3 | Sequence[float]) -> float:
    """
Computes the kinetic energy available in the center-of-mass frame: KE_cm = Σ ½m_i |v_i - v_cm|².

Rust: `astrophysics::collisions::collision_energy`
    """
    ...

def escape_speed(mass: float, radius: float) -> float:
    """
Computes the surface escape speed: v_esc = √(2GM/r).

Rust: `astrophysics::collisions::escape_speed`
    """
    ...

def debris_params(kind: CollisionKind) -> DebrisParams:
    """
Returns debris generation parameters (count, speed, mass fraction, temperature) for a given collision type.

Rust: `astrophysics::collisions::debris_params`
    """
    ...

def resolve_collision(m1: float, r1: float, v1: Vec3 | Sequence[float], m2: float, r2: float, v2: Vec3 | Sequence[float], kind: CollisionKind) -> CollisionResult:
    """
Resolves a collision between two bodies, computing the merged properties and debris parameters.

Rust: `astrophysics::collisions::resolve_collision`
    """
    ...
