"""
Astronomical coordinates, low-precision ephemerides and TLE parsing.  # Four frames and what each is for  *Equatorial* coordinates -- right ascension and declination -- are fixed to the stars, or nearly so, and are what a catalogue lists. *Horizontal* coordinates -- azimuth and altitude -- are what an observer sees, and depend on where and when they are looking. *Ecliptic* coordinates are referred to the Earth's orbital plane, which is the natural frame for anything in the solar system. And the *perifocal* and inertial frames of `astrophysics::kepler` are where orbits live.  Converting between the first three is pure spherical trigonometry, and all of it is exactly invertible. Which is worth saying because the *ephemerides* here are not: they are truncated series good to a fraction of a degree, and their inverses do not exist in any useful sense.  # What "low precision" means  `sun_position_approx` is good to about a hundredth of a degree over a couple of centuries around J2000. `moon_position_approx` is good to a few tenths of a degree, because the Moon's motion has hundreds of terms of comparable size and this keeps a handful. `planet_position_low_precision` uses mean elements with linear rates and no perturbations at all, which is good to a fraction of a degree for the inner planets over a few centuries and steadily worse outward, where Jupiter and Saturn pull each other around by degrees.  None of these is suitable for an occultation, a transit timing, or anything where arcseconds matter. They are for pointing a small telescope, checking whether a planet is up, and drawing a sky map.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional


class Planet:
    """
The planets this module's low-precision ephemeris covers.

Rust: `astrophysics::coords::Planet`
    """
    ...

class TleElements:
    """
The fields a two-line element set carries.

Rust: `astrophysics::coords::TleElements`
    """
    def __init__(self, catalog_number: int, designator: str, epoch_jd: float, mean_motion_dot: float, bstar: float, inclination: float, raan: float, eccentricity: float, arg_perigee: float, mean_anomaly: float, mean_motion: float, revolution: int) -> None: ...
    @property
    def catalog_number(self) -> int: ...
    @property
    def designator(self) -> str: ...
    @property
    def epoch_jd(self) -> float: ...
    @property
    def mean_motion_dot(self) -> float: ...
    @property
    def bstar(self) -> float: ...
    @property
    def inclination(self) -> float: ...
    @property
    def raan(self) -> float: ...
    @property
    def eccentricity(self) -> float: ...
    @property
    def arg_perigee(self) -> float: ...
    @property
    def mean_anomaly(self) -> float: ...
    @property
    def mean_motion(self) -> float: ...
    @property
    def revolution(self) -> int: ...

def equatorial_to_horizontal(right_ascension: float, declination: float, latitude: float, local_sidereal_time: float) -> tuple[float, float]:
    """
Converts equatorial coordinates to horizontal, returning
`(azimuth, altitude)` in radians.

Azimuth is measured from north through east, which is the navigator's
convention; astronomers sometimes measure from south, and the two
differ by half a turn. Altitude is positive above the horizon.

The local hour angle `lst - ra` is what carries the time dependence:
it is zero when the object is due south, so an object is highest
exactly then. Everything else is one spherical triangle.

No refraction. Near the horizon the atmosphere lifts an object by
about half a degree -- more than the Sun's own diameter -- so a
computed altitude of zero is a body that has already visibly set.

Errors:
Returns an error for a non-finite input or a latitude outside
`[-pi/2, pi/2]`.

Rust: `astrophysics::coords::equatorial_to_horizontal`
    """
    ...

def horizontal_to_equatorial(azimuth: float, altitude: float, latitude: float, local_sidereal_time: float) -> tuple[float, float]:
    """
Converts horizontal coordinates back to equatorial, returning
`(right ascension, declination)`.

The exact inverse of `equatorial_to_horizontal`, which is worth
having as a separate function precisely so the pair can be checked
against each other.

Errors:
As `equatorial_to_horizontal`, with the altitude taking the place of
the declination.

Rust: `astrophysics::coords::horizontal_to_equatorial`
    """
    ...

def ecliptic_to_equatorial(ecliptic_longitude: float, ecliptic_latitude: float, obliquity: float) -> tuple[float, float]:
    """
Converts ecliptic coordinates to equatorial, returning
`(right ascension, declination)`.

A rotation by the obliquity about the vernal equinox, and nothing
more. The ecliptic frame is where the planets nearly lie -- their
latitudes are a few degrees at most -- which is why an ephemeris
computes there and converts at the end.

Errors:
Returns an error for a non-finite angle or a latitude outside
`[-pi/2, pi/2]`.

Rust: `astrophysics::coords::ecliptic_to_equatorial`
    """
    ...

def equatorial_to_ecliptic(right_ascension: float, declination: float, obliquity: float) -> tuple[float, float]:
    """
Converts equatorial coordinates to ecliptic, returning
`(longitude, latitude)`.

Errors:
As `ecliptic_to_equatorial`.

Rust: `astrophysics::coords::equatorial_to_ecliptic`
    """
    ...

def mean_obliquity(jd: float) -> float:
    """
The mean obliquity of the ecliptic at a Julian date, by the IAU 1980
polynomial.

It decreases by about 47 arcseconds a century, which over the span of
recorded astronomy is enough to matter: the tropics have moved
measurably since the term was coined.

Errors:
Returns an error for a non-finite or out-of-range Julian date.

Rust: `astrophysics::coords::mean_obliquity`
    """
    ...

def precession_approx(right_ascension: float, declination: float, jd: float) -> tuple[float, float]:
    """
Precesses equatorial coordinates from J2000 to another epoch, to first
order in the precession angles.

The equinox itself moves, at about 50 arcseconds a year, so a
catalogue position is meaningless without the epoch it belongs to.
This is the rigorous rotation truncated to its linear terms, which is
good to an arcsecond over a century and degrades quadratically beyond.

It is a coordinate change, not a motion: the star has not moved, the
grid has.

Errors:
Returns an error for a non-finite coordinate, a declination outside
`[-pi/2, pi/2]`, or an out-of-range date.

Rust: `astrophysics::coords::precession_approx`
    """
    ...

def sun_position_approx(jd: float) -> tuple[float, float, float]:
    """
The Sun's apparent geocentric position, returning
`(right ascension, declination, distance in astronomical units)`.

The low-precision series from the Astronomical Almanac: a mean
longitude, a mean anomaly, and two terms of the equation of centre.
Good to about a hundredth of a degree for a couple of centuries either
side of J2000, which is a hundredth of the Sun's own diameter.

The declination is what drives the seasons, and it reaches the
obliquity at the solstices and zero at the equinoxes -- which is what
makes those the definitions of the days rather than consequences of
them.

Errors:
Returns an error for a non-finite or out-of-range Julian date.

Rust: `astrophysics::coords::sun_position_approx`
    """
    ...

def moon_position_approx(jd: float) -> tuple[float, float, float]:
    """
The Moon's apparent geocentric position, returning
`(right ascension, declination, distance in kilometres)`.

A handful of the largest terms in longitude, latitude and distance:
the evection, the variation, the annual equation and the principal
latitude term. Good to a few tenths of a degree, which is about the
Moon's own diameter -- enough to say where it is in the sky and not
enough to predict an occultation.

The Moon is the hardest classical ephemeris there is. Its orbit is
perturbed by the Sun at the percent level, and the full theory runs to
thousands of terms; what is kept here is the first page of a long
book.

Errors:
Returns an error for a non-finite or out-of-range Julian date.

Rust: `astrophysics::coords::moon_position_approx`
    """
    ...

def planet_position_low_precision(planet: Planet, jd: float) -> tuple[float, float, float]:
    """
A planet's heliocentric position, returning
`(ecliptic longitude, ecliptic latitude, distance in AU)`.

Mean elements advanced linearly in time, Kepler's equation solved, and
the result rotated into the ecliptic. There are no mutual
perturbations at all, which is what makes this "low precision": the
inner planets come out within a fraction of a degree over a few
centuries around J2000, and Jupiter and Saturn drift by degrees over
the same span because they pull on each other and this does not know
it.

The elements are the Standish set, whose stated validity is 1800 to
2050. Outside that window the answer degrades quickly and silently,
which is a property of the data rather than of the arithmetic.

Errors:
Returns an error for a non-finite or out-of-range Julian date, or a
Kepler solve that fails.

Rust: `astrophysics::coords::planet_position_low_precision`
    """
    ...

def rise_set_times(right_ascension: float, declination: float, latitude: float, longitude: float, jd: float, standard_altitude: float) -> Optional[tuple[float, float]]:
    """
The rise and set times of a body of fixed equatorial coordinates on a
given day, as Julian dates, or `None` if it never crosses the horizon.

`standard_altitude` is the altitude counted as the horizon: zero for a
point source ignoring refraction, about -0.0145 radians (-50
arcminutes) for the Sun's upper limb with mean refraction.

`None` covers both circumpolar cases -- a body permanently up, and one
permanently down -- which are the same arithmetic: the required hour
angle has no cosine. That is the polar day and the polar night, and
which one it is can be told from the altitude at transit.

The coordinates are held fixed over the day, which is fine for a star
and an approximation for the Sun, whose declination moves by up to
0.4 degrees between rise and set near an equinox.

Errors:
Returns an error for a non-finite input, a latitude or declination out
of range, or an out-of-range date.

Rust: `astrophysics::coords::rise_set_times`
    """
    ...

def tle_parse_lite(line1: str, line2: str) -> TleElements:
    """
Parses a two-line element set into its fields.

**Parsing only.** The elements are not propagated, and they must not be
propagated by anything in this crate. A TLE's numbers are not osculating
orbital elements: they are *mean* elements in the specific sense defined
by the SGP4/SDP4 theory, with the periodic variations that theory models
already removed. Feeding them to a Kepler propagator -- including
`astrophysics::kepler::propagate_kepler` -- gives an answer
that looks reasonable and is wrong by kilometres within hours, because
the removed terms are exactly what would need adding back.

SGP4 is therefore not "a better propagator to add later"; it is the
definition of what the numbers mean. Implementing it is a substantial
piece of work with its own deep-space branch, and it is out of scope
here rather than approximated.

The exponential fields (`bstar` and the second derivative) use the
format's assumed-decimal-point convention: `12345-3` means
`0.12345e-3`.

Errors:
Returns an error for lines of the wrong length or line number, a field
that will not parse, a checksum mismatch, or an epoch out of range.

Rust: `astrophysics::coords::tle_parse_lite`
    """
    ...

OBLIQUITY_J2000: float
