"""
Gravitational radiation from a compact binary.  Quadrupole-formula results for an inspiralling binary: the emitted luminosity, the wave frequency (twice the orbital frequency), the strain amplitude at a given distance, and the time remaining to merger.  The chirp mass `ℳ = (m₁m₂)^(3/5)/(m₁+m₂)^(1/5)` is the combination that governs all of them -- it is the parameter the inspiral waveform actually determines, which is why it is measured far better than either individual mass.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.math import Vec3

def gw_luminosity(m1: float, m2: float, separation: float) -> float:
    """
Computes gravitational wave luminosity for a circular binary: L = (32/5) G⁴m₁²m₂²(m₁+m₂) / (c⁵ a⁵).

Rust: `astrophysics::gravitational_waves::gw_luminosity`
    """
    ...

def gw_frequency(m1: float, m2: float, separation: float) -> float:
    """
Computes the gravitational wave frequency (twice the orbital frequency): f_gw = (1/π)√(G(m₁+m₂)/a³).

Rust: `astrophysics::gravitational_waves::gw_frequency`
    """
    ...

def gw_strain(m1: float, m2: float, separation: float, distance_to_observer: float) -> float:
    """
Computes the dimensionless gravitational wave strain amplitude: h = 4G²m₁m₂ / (c⁴ a D).

Rust: `astrophysics::gravitational_waves::gw_strain`
    """
    ...

def inspiral_time(m1: float, m2: float, separation: float) -> float:
    """
Computes the Peters inspiral time for a circular binary: t = (5/256) c⁵ a⁴ / (G³ m₁ m₂ (m₁+m₂)).

Rust: `astrophysics::gravitational_waves::inspiral_time`
    """
    ...

def chirp_mass(m1: float, m2: float) -> float:
    """
Computes the chirp mass of a binary system: M_c = (m₁ m₂)^(3/5) / (m₁ + m₂)^(1/5).

Rust: `astrophysics::gravitational_waves::chirp_mass`
    """
    ...

def innermost_stable_circular_orbit(total_mass: float) -> float:
    """
Computes the Schwarzschild ISCO radius: r_isco = 6GM/c².

Rust: `astrophysics::gravitational_waves::innermost_stable_circular_orbit`
    """
    ...

def find_strongest_source(masses: list[float], positions: list[Vec3 | Sequence[float]]) -> Optional[tuple[int, int, float]]:
    """
Finds the pair of bodies with the highest gravitational wave luminosity, returning their indices and luminosity.

Rust: `astrophysics::gravitational_waves::find_strongest_source`
    """
    ...

def merger_energy(m1: float, m2: float) -> float:
    """
Estimates the energy radiated during merger: E = η M c², where η = m₁m₂/(m₁+m₂)².

Rust: `astrophysics::gravitational_waves::merger_energy`
    """
    ...
