"""
Lambert's problem: the orbit connecting two positions in a given time.  # The problem and why it is hard  Given where a spacecraft is, where it must be, and how long it has to get there, find the transfer orbit. Stated that way it sounds like `astrophysics::kepler::propagate_kepler` run backwards, but it is a genuinely different problem: propagation is an initial-value problem with one answer, and Lambert's is a *boundary*-value problem whose answer need not be unique.  It is not, however, a problem of existence. Within a single revolution a transfer exists for every positive flight time: making the trip faster costs more energy without limit, and the minimum-energy transfer is a particular duration rather than a floor on one. What *does* fail is a degenerate geometry -- a transfer angle of zero or exactly `pi`, where the two radii do not determine a plane and infinitely many orbits connect the points.  Only the zero-revolution solution is computed here, which is the one interplanetary trajectory design starts from. Multi-revolution transfers exist for longer flight times and are a separate search, with two branches per revolution count; they are not attempted rather than approximated.  # The universal-variable formulation  Every conic is covered by one iteration, on a variable `z` that is positive for an ellipse, negative for a hyperbola and zero for a parabola. The Stumpff functions `C(z)` and `S(z)` carry the difference, and their series expansions near zero are what keep the parabolic case from losing precision to cancellation -- the closed forms are `0/0` there.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.math import Vec3

def stumpff_c(z: float) -> float:
    """
The Stumpff function `C(z)`.

`(1 - cos sqrt(z))/z` for positive `z` and the hyperbolic analogue for
negative, both of which are `0/0` at the origin. The series
`1/2 - z/24 + z^2/720 - ...` is used near zero, where the closed forms
lose their leading digits to cancellation, and the positive branch is
evaluated as `2 sin^2(sqrt(z)/2)/z` so that it stays accurate at the
other end of the range as well.

Rust: `astrophysics::lambert::stumpff_c`
    """
    ...

def stumpff_s(z: float) -> float:
    """
The Stumpff function `S(z)`.

`(sqrt(z) - sin sqrt(z))/z^(3/2)` for positive `z`, with the series
`1/6 - z/120 + z^2/5040 - ...` near the origin for the same reason as
`stumpff_c` -- and worse, since the numerator there is a difference
of two nearly equal quantities that agree to three orders.

Rust: `astrophysics::lambert::stumpff_s`
    """
    ...

def lambert_universal(r1: Vec3 | Sequence[float], r2: Vec3 | Sequence[float], tof: float, mu: float, prograde: bool) -> tuple[Vec3, Vec3]:
    """
Solves Lambert's problem by universal variables, returning the
departure and arrival velocities.

`prograde` selects the transfer direction: true takes the short way
round in the sense of increasing right ascension, false the long way.
The two are genuinely different orbits with different flight paths and
different costs, and which one is wanted is not deducible from the
endpoints -- the transfer angle is `theta` one way and `2 pi - theta`
the other.

The iteration is bisection on `z`. Bisection rather than Newton because
the flight time is monotone in `z`, so bisection cannot fail, and the
derivative a Newton step needs is itself delicate near the parabolic
point.

Accuracy degrades as the transfer angle approaches `pi`. The
velocities are recovered as `(r2 - f r1)/g`, and near a half turn
`f` approaches one with `r2` near `-r1`, so the numerator is a
difference of nearly equal vectors. Over three thousand randomised
geometries the worst departure velocity was off by a part in 1e8, and
that case had a transfer angle of 179.99 degrees. Exactly `pi` is
refused; the approach to it is merely imprecise.

Errors:
Returns an error for a non-positive gravitational parameter or flight
time, a position at the origin, or a transfer angle of zero or exactly
`pi`, where the plane is undefined and infinitely many orbits connect
the points.

Rust: `astrophysics::lambert::lambert_universal`
    """
    ...

def porkchop_data(departures: list[tuple[float, Vec3 | Sequence[float], Vec3 | Sequence[float]]], arrivals: list[tuple[float, Vec3 | Sequence[float], Vec3 | Sequence[float]]], mu: float, prograde: bool) -> list[list[Optional[float]]]:
    """
A porkchop grid of departure characteristic energies.

Entry `[i][j]` is the departure `C3 = v_infinity^2` for leaving
`departures[i]` and arriving at `arrivals[j]`, with the flight time
taken as the difference of their epochs. `None` marks a pair with no
transfer: a non-positive flight time, a degenerate geometry, or a
duration outside what one revolution allows.

`C3` rather than delta-v because it is what a launch vehicle's
performance is quoted against: the energy left over after escaping,
which is what the upper stage must supply. The characteristic ridges
and islands of a real porkchop plot come from the two branches of the
transfer -- Type I below a half revolution and Type II above -- meeting
where the transfer angle passes `pi` and the solution degenerates.

Errors:
Returns an error for an empty grid, a non-positive gravitational
parameter, or more than a million cells.

Rust: `astrophysics::lambert::porkchop_data`
    """
    ...
