"""
Tidal forces and the Roche limit.  The tidal acceleration is the *difference* in gravitational pull across a body, so it falls as `1/r³` rather than `1/r²` -- which is why the Moon raises larger tides on Earth than the far more massive Sun does.  The Roche limit is given in both the rigid and fluid forms; the fluid limit is the larger, because a fluid body deforms and so becomes easier to pull apart. Tidal heating, the locking timescale and the tidal tensor complete the module.
"""
# @generated by bindings/python/generate.py -- do not edit.
from __future__ import annotations
from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import Any, Optional

from numeria.math import Vec3

def tidal_acceleration_magnitude(primary_mass: float, distance: float) -> float:
    """
Computes the Newtonian tidal acceleration magnitude: a_tidal = 2GM/r³.

Rust: `astrophysics::tidal::tidal_acceleration_magnitude`
    """
    ...

def tidal_acceleration_gr_corrected(primary_mass: float, distance: float, schwarzschild_radius: float) -> float:
    """
Computes tidal acceleration with a GR correction factor: a_tidal / (1 - r_s/r).

Rust: `astrophysics::tidal::tidal_acceleration_gr_corrected`
    """
    ...

def roche_limit_rigid(primary_radius: float, primary_density: float, satellite_density: float) -> float:
    """
Computes the rigid-body Roche limit: d = R_p (2 ρ_p / ρ_s)^(1/3).

Rust: `astrophysics::tidal::roche_limit_rigid`
    """
    ...

def roche_limit_fluid(primary_radius: float, primary_density: float, satellite_density: float) -> float:
    """
Computes the fluid-body Roche limit: d = 2.44 R_p (ρ_p / ρ_s)^(1/3).

Rust: `astrophysics::tidal::roche_limit_fluid`
    """
    ...

def tidal_force_ratio(primary_mass: float, body_mass: float, body_radius: float, distance: float) -> float:
    """
Computes the ratio of tidal force to self-gravity on a body's surface: (a_tidal × R_body) / (GM_body / R_body²).

Rust: `astrophysics::tidal::tidal_force_ratio`
    """
    ...

def tidal_tensor_eigenvalues(primary_mass: float, distance: float) -> tuple[float, float]:
    """
Computes the tidal tensor eigenvalues (radial, tangential): (2GM/r³, -GM/r³).

Rust: `astrophysics::tidal::tidal_tensor_eigenvalues`
    """
    ...

def roche_potential(x: float, z: float, m1: float, pos1: Vec3 | Sequence[float], m2: float, pos2: Vec3 | Sequence[float]) -> float:
    """
Computes the Roche potential in the co-rotating frame: Φ = -Gm₁/r₁ - Gm₂/r₂ - ½ω²r_com².

Rust: `astrophysics::tidal::roche_potential`
    """
    ...
